### ISSUE TITLE
导入as2.0报错,不能用

### ISSUE THREAD

**Issue by hsbyron** [YiiGuxing/TranslationPlugin#1]

**Comment by YiiGuxing** [comment]
报什么样的错啊？是不是java版本太低哦？这个是需要java8以上的版本的。

**Comment by YiiGuxing** [comment]
现在v1.2 最低要求java的版本为1.7以上才能使用，而v1.1则需要java 1.8以上。如果需要更低的java版本要求，可以下载源码自己编译。
