### ISSUE TITLE
部分地方无法翻译

### ISSUE THREAD

**Issue by kevery** [YiiGuxing/TranslationPlugin#10]
插件使用很顺手，但是发现有些地方翻译快捷键无效
![2 4injx8 vz gv_a q3h5m](https://cloud.githubusercontent.com/assets/13434356/17954003/93e5c816-6aaa-11e6-8af4-240ff9ec761d.png)
比如像这里的改进建议
是目前没有这个功能还是我的用法不对？
谢谢

**Comment by YiiGuxing** [comment]
像这样的地方是无法响应翻译的动作的，如popup,dialog等，这是IDEA限制的。其实我也想啊，但是臣妾真的做不到啊！目前就只能编辑器里响应翻译动作，以后我会尝试扩大可翻译的组件范围（应该不会太远，搞个v1.2.1之类的）。但popup,dialog等非编辑组件还是不行的。所以这些地方还是只能手动复制，然后在打开翻译对话框翻译。

**Comment by YiiGuxing** [comment]
我试着尝试了一下，run面板和even log面板上是可以响应的（只能通过快捷键），可惜的是idea上的终端面板并不鸟这些快捷键。所以，就目前来说，要扩展就比较困难了。

**Comment by YiiGuxing** [comment]
@kevery 哇哈哈哈......终于可以在快速文档面板上取词翻译了：[commit `9e3893e`](https://github.com/YiiGuxing/TranslationPlugin/commit/9e3893e51afb2ad51edd9415f1348077be80b989)

快速文档面板是指按Ctrl+Q弹出的那个面板（你上面给的图里的popup目前还是不能）：
![1](https://cloud.githubusercontent.com/assets/10737066/20630167/5371ccd6-b36a-11e6-982b-b7e5ba51dbe0.gif)

**Comment by YiiGuxing** [comment]
@kevery 现在翻译操作事件的响应范围已被扩大了很多，很多地方都可以通过快捷键翻译了（你上面给的图里的popup上也可以了）： [commit `7e9ae5a` - `4968f9c`](https://github.com/YiiGuxing/TranslationPlugin/compare/4e32a463477fe210d0dbc8c7aa9970e8914d8db4...4968f9c2a43b5764da2145f9012526b875461b69)
