### ISSUE TITLE
文档翻译 没法显示.

### ISSUE THREAD

**Issue by swebcc** [YiiGuxing/TranslationPlugin#1004]
文档翻译 没法显示.
![image](https://user-images.githubusercontent.com/33777919/160243473-6c1b726a-c151-4249-9bba-03580b5e22cc.png)

**Comment by swebcc** [comment]
![image](https://user-images.githubusercontent.com/33777919/160243520-92eeb0ab-cfa5-4e04-8f79-6654ce497006.png)

**Comment by swebcc** [comment]
![image](https://user-images.githubusercontent.com/33777919/160243544-0abcfbba-a5e2-415b-99e4-3418acd15486.png)

**Comment by YiiGuxing** [comment]
你的变量 `a` 本身并没有文档，所以它就没有东西可显示。
你变量 `a` 加上一个文档注释后再试一试。

<img width="398" alt="image" src="https://user-images.githubusercontent.com/10737066/160282298-2d17af84-ea0b-4974-815d-5cc991b4b027.png">
