### ISSUE TITLE
请教一下，IDEA插件怎么兼容到其他平台像Android Studio.

### ISSUE THREAD

**Issue by fashare2015** [YiiGuxing/TranslationPlugin#102]
您好，我刚接触IDEA插件开发，开发环境为IDEA (sdk IntelliJ IDEA Community Edition IC-141)。
试了一个demo（仅仅含有一个`action`）,打包后能在IDEA里能跑起来，但是在`Android Studio`里只能安装，按钮点击无反应（有个空指针异常，不确定是不是sdk不同导致的）。
>找了很多资料，也试了官方的建议，没起效果http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html
```xml
<depends>com.intellij.modules.lang</depends>
```
看到您的插件兼容了n多平台，望指导一下，万分感谢🙏🙏

附部分代码，demo中唯一的Action:
```java
public class Action1 extends AnAction {

    @Override
    public void actionPerformed(AnActionEvent e) {
        // TODO: insert action logic here
        Messages.showMessageDialog("Hello World !", "Information", Messages.getInformationIcon());
    }
}
```

plugin.xml
```xml
  <!-- please see http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html for description -->
  <idea-version since-build="141.0"/>

  <!-- please see http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html
       on how to target different products -->
  <depends>com.intellij.modules.lang</depends>

  <extensions defaultExtensionNs="com.intellij">
    <!-- Add your extensions here -->
  </extensions>

  <actions>
    <!-- Add your actions here -->
    <action id="aaaa" class="Action1" text="aaa" description="bbb">
      <add-to-group group-id="EditMenu" anchor="first"/>
      <keyboard-shortcut keymap="$default" first-keystroke="shift A"/>
    </action>
  </actions>
```

**Comment by YiiGuxing** [comment]
IDEA不同版本之间的API可能会有变化，并不是完全相同的。比如老一点的版本的API存在BUG，而在新的版本可能被修复了。特别是非Open API（Open API在`com.intellij.openapi`包下），非Open API并不是稳定的，可能会很容易出现变化，而Open API一般是稳定的。所以，在使用Open API时一定要小心，要在各版本之间做好测试。
如果遇到像你这样的问题，一般的处理办法是根据异常信息DEBUG，然后在自己的插件代码中修复或绕开问题，或者使用其他方法实现。
也可以针对某一些版本做兼容，例如[`cn.yiiguxing.plugin.translate.compat`](https://github.com/YiiGuxing/TranslationPlugin/tree/master/src/cn/yiiguxing/plugin/translate/compat)包中的类。

**Comment by fashare2015** [comment]
关键词`openapi `GET.我先研究一下🙏
