### ISSUE TITLE
Translate documentation无法使用

### ISSUE THREAD

**Issue by doveshelly** [YiiGuxing/TranslationPlugin#1024]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ x ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
1、右键点击java注释文档翻译，并没有显示中文，还是原封不动的显示英文
![image](https://user-images.githubusercontent.com/36104005/160313061-4c0e855c-56e9-4fe9-aacb-01e494c7b556.png)
2、单独用鼠标选择一段句子翻译是没问题的。
![image](https://user-images.githubusercontent.com/36104005/160313016-535e6790-9a4d-4edb-9a38-fcb4ed34d584.png)
### 环境 & 错误日志
- 插件版本: 3.3-203u212.patch.1
- IDE版本: IDEA 2021.2.4 
- 操作系统版本:  Mac os Monterey

**Comment by YiiGuxing** [comment]
请问插件有没有报错？这会不会是网络太太慢加载不出来？

**Comment by unclebryan719** [comment]
我显示的也是英文  和操作系统有关吗 我的操作系统是英文的
