### ISSUE TITLE
想要支持谷歌翻译

### ISSUE THREAD

**Issue by liuxing87327** [YiiGuxing/TranslationPlugin#103]
想要支持谷歌翻译

**Comment by YiiGuxing** [comment]
我也想要支持谷歌翻译啊~ :joy: :joy: :joy: 
可是谷歌翻译API是收费的，我也在找大神们的方案，都Fork了好几个了~~~ 
还有就是最近比较忙，这里的工作几乎都停了下来，连已经接近尾声的使用`Kotlin`重构的工作都停下来了。。。

**Comment by liuxing87327** [comment]
我想如果用滑词翻译的node模块本机搭建一个简单的服务，然后调用本机API 是否可行
这个chrome插件我用很久了，翻译蛮稳定的
https://github.com/Selection-Translator/translation.js

下面是我粗写的node，你应该会比我更在行
app.js

const tjs = require('translation.js')

var express = require('express');

var app = express();

app.get('/', function (req, res) {
  tjs.translate(req.query.keyword)
  .then(result => {
    console.log(result)
    res.send(result);
  })
});

app.listen(3000, function () {
  console.log('app is listening at port 3000');
});

**Comment by YiiGuxing** [comment]
@liuxing87327 你可以尝试在本地使用这个方案，并修改插件代码实现本地使用，但不适合公共的。

**Comment by milk36** [comment]
@YiiGuxing 有道云翻译API今年6月份关闭了每日免费10万字符的服务, 能否加入更多翻译API以便大家选择?

**Comment by milk36** [comment]
@YiiGuxing 自然语言翻译服务每日10万免费字符暂停提供，不过100元体验金福利暂不影响用户免费体验翻译服务.有道云翻译关闭免费翻译的服务了,能否加入更多翻译API方便大家自由选择?

**Comment by YiiGuxing** [comment]
@milk36 有这个计划。

**Comment by YiiGuxing** [comment]
@liuxing87327 @milk36 谷歌翻译的接入目前正在开发中，敬请期待!

**Comment by feisher** [comment]
@YiiGuxing 还在维护吗？其实可以考虑百度翻译啊，逻辑基本一样，改动小！每个月200万免费。基本也够用了

**Comment by hugbio** [comment]
大神，你项目的调用翻译api的代码在那里。如果要更换翻译方案应该改哪里？

**Comment by hugbio** [comment]
找了一下。https://github.com/RedGhoul/Google-Translate-API-Wrapper/blob/master/TranlateApi.java
好像这个可以。

**Comment by YiiGuxing** [comment]
@hugbio 一开使设计的时候就不支持多翻译接口更换， 代码结构上没有做扩展预留，所以要改起来就麻烦了。而新的版本目前正在开发中，对整个项目代码重构了一次，将会开始支持多翻译接口更换（第一次先新增谷歌翻译接口），目前已完成80%。想要了解更多情况，请看[`dev`](https://github.com/YiiGuxing/TranslationPlugin/tree/dev)分支。

**Comment by YiiGuxing** [comment]
@hugbio 多谢，但目前谷歌翻译接口的方案已经确定好了。

**Comment by YiiGuxing** [comment]
已完成Google翻译的接入：[`commit 8b4073c`](https://github.com/YiiGuxing/TranslationPlugin/commit/8b4073c1618afe81e548978aadab24776adfecb0)
