### ISSUE TITLE
Cosmetics: Missing version value in tab name

### ISSUE THREAD

**Issue by pahan35** [YiiGuxing/TranslationPlugin#1051]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing `[ ]` with `[x]`*

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details

After update, **What new in {0}** tab was opened.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13823215/160462605-572fb56a-5a3d-48df-b957-d730a8ab22a2.png">

### Description

1. Update the plugin from version 3.3 without restarting the IDE.
2. Check the tab name of the opened tab.

### Environment & Stack Trace
- Plugin version: 3.3-patch.1
- IDE version: WS 2022.1.5080.67
- Operating System and version: macOS Big Sur 11.6.5

**Comment by YiiGuxing** [comment]
Thanks for your feedback, are you sure the plugin version you installed is 3.3-patch.1? This problem does exist in version 3.3, but I have fixed it on version 3.3-patch.1.

![image](https://user-images.githubusercontent.com/10737066/160530217-121deb62-17c2-4b63-a938-942aba0487ca.png)
![image](https://user-images.githubusercontent.com/10737066/160530397-3219f6c5-c48a-4d66-a134-025ac240c06a.png)
![image](https://user-images.githubusercontent.com/10737066/160530436-048a408a-201b-4306-ae15-418e5bf7c768.png)

**Comment by pahan35** [comment]
> Thanks for your feedback, are you sure the plugin version you installed is 3.3-patch.1? This problem does exist in version 3.3, but I have fixed it on version 3.3-patch.1.
> 
> ![image](https://user-images.githubusercontent.com/10737066/160530217-121deb62-17c2-4b63-a938-942aba0487ca.png) ![image](https://user-images.githubusercontent.com/10737066/160530397-3219f6c5-c48a-4d66-a134-025ac240c06a.png) ![image](https://user-images.githubusercontent.com/10737066/160530436-048a408a-201b-4306-ae15-418e5bf7c768.png)

Technically, it was 3.3 since the IDE was not restarted yet.

In that case, maybe there is some problem with `What's new` triggering? It was triggered right after plugin installation but before restart.

**Comment by YiiGuxing** [comment]
So, this problem has been fixed, it only exists in v3.3, fixed in v3.3-patch.1.
