### ISSUE TITLE
ui显示错误

### ISSUE THREAD

**Issue by Zre0** [YiiGuxing/TranslationPlugin#1075]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题
![1648612224(1)](https://user-images.githubusercontent.com/51789977/160747826-672b104e-1bd2-4865-b8c4-8b12ae6f0fa1.jpg)
详情

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
Duplicate of #1025

**Comment by YiiGuxing** [comment]
在修复版本发布之前，可以临时使用这个包以解决紧急的使用需求：

[TranslationPlugin-3.3.1-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/8466059/TranslationPlugin-3.3.1-SNAPSHOT.zip)
