### ISSUE TITLE
as3.0上字体预览乱码了

### ISSUE THREAD

**Issue by Vixb1122** [YiiGuxing/TranslationPlugin#108]
![snipaste_2017-11-10_15-27-50](https://user-images.githubusercontent.com/17810492/32647445-12edc75c-c62c-11e7-8e6e-45bc387b575b.jpg)

**Comment by YiiGuxing** [comment]
@Vixb1122 如果预览的文本乱码的话，那么翻译时相应的字符也会乱码，所以建义设置一下字体。

**Comment by Vixb1122** [comment]
@YiiGuxing 换字体也没辙，貌似只有as2.3以下预览显示没问题，之后的版本就有问题了，我试了idea，rider,pycharm都是乱码。
