### ISSUE TITLE
使用有道翻译每次打开idea都要重新输入密钥

### ISSUE THREAD

**Issue by ultron-dcd** [YiiGuxing/TranslationPlugin#1098]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 3.3-203u212.patch.1
- IDE版本: IDEA 2021.2.3
- 操作系统版本:  Windows 11

**Comment by YiiGuxing** [comment]
请根据 README 中的 FAQ 尝试解决，谢谢。
