### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by wtjperi2003** [YiiGuxing/TranslationPlugin#11]
1.英文首字母不要大写
2.我的translation dialog没有文字颜色啊
3.打开dialog的时候自动聚焦到文本框里
4.添加英文单词发音的功能

**Comment by YiiGuxing** [comment]
1. 为什么啊？之前的版本就是小写的，我特意改成大写的。
2. 文字颜色只有在暗色主题上才有，亮色主题上我目前没找到合适的配色方案。。。好吧，是我太懒了。
3. 啊！是我疏忽了，以前是好的，被搞掉了。。。
4. 嗯，这个建议好，我最近也在考虑这个问题，并已经在调研如何实现了。如果不出意外的话下一个大版本应该会有。

多谢你的建议！如果有进展我会在这儿通知你的。

**Comment by kevery** [comment]
3.打开dialog的时候自动聚焦到文本框里
我也正想提这个需求，每次快捷键打开后还得用鼠标点一下，很影响用户体验，希望能尽快完善

**Comment by chenxiaolei** [comment]
Quick Documentation 的dialog 文字选择后似乎不能用, 这个能加上吗

**Comment by YiiGuxing** [comment]
@chenxiaolei 这个，并不能。这无法实现，只能把需要翻译的文本复制出来翻译。

**Comment by YiiGuxing** [comment]
@wtjperi2003 @kevery  自动聚焦已经修改完成，请下载最新包重新安装。

**Comment by YiiGuxing** [comment]
@wtjperi2003 亮色主题下载的色彩样式放到了下一版本实现，也就是v1.2.1版。如果你想体验，可以安装最新的开发版（v1.2.1-SNAPSHOT）来体验，目前暂定的色彩样式如下图所示：

![色彩样式](https://raw.githubusercontent.com/YiiGuxing/TranslationPlugin/master/images/5.png)

**Comment by kevery** [comment]
可否增加一个esc关闭查询窗口的功能方便键盘党

**Comment by YiiGuxing** [comment]
@kevery 有的，只不过对话框上只有在对话框被聚焦的时候有效。后面我再看看能不能在不被聚焦的时候有效吧。

**Comment by kevery** [comment]
连按2下esc可关闭

**Comment by YiiGuxing** [comment]
@kevery 非聚焦状态下按ESC键关闭对话框已实现（并没有打包，下一个修改打）。见：[**commit eceee33**](https://github.com/YiiGuxing/TranslationPlugin/commit/eceee338fa322a6e3e9dd93acc69de2c4560216a)

**Comment by byte-pirate** [comment]
能不能提供个功能: 把简要的翻译信息默认复制到剪切板，有时想翻译中文可能用到。

**Comment by YiiGuxing** [comment]
@byte-pirate 由于翻译的信息包含很多内容，所以这个功能不太实用。其实你可以选择对话框上的文本，再按 ctrl+c 自制的。

**Comment by byte-pirate** [comment]
我说的简要信息是是翻译中文时的英文单词
![image](https://cloud.githubusercontent.com/assets/4214963/19213014/1c8ad12e-8d93-11e6-94bf-5597f29846c7.png)

**Comment by YiiGuxing** [comment]
@byte-pirate 嗯，我明白你的意思，我说的就是这部分的内容。比如，某个词，它翻译以后可能会有名词、动词、形容词等中的几种内容，这就不好处理了。

**Comment by YiiGuxing** [comment]
哈哈，终于把英文单词朗读功能完成了。。。。详见：[`Commits: 348d2a9 - 0e6b9c1`](https://github.com/YiiGuxing/TranslationPlugin/compare/2888d1c33e0233ddf39b4d545fd4458d96b778de...0e6b9c1de5bbd23c4ef421585be12dcf2acdf8ef)
