### ISSUE TITLE
能否添加直接翻译整个类的所有注释的功能？？

### ISSUE THREAD

**Issue by pangdonghao** [YiiGuxing/TranslationPlugin#1119]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing `[ ]` with `[x]`* 

* [ x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Additional Information
插件版本：3.3-203u212.patch.1
IDE版本： IDEA 2021.2.3
操作系统版本： win10

**Comment by pangdonghao** [comment]
如果需要，可以参与此功能开发

**Comment by YiiGuxing** [comment]
1. 个人认为这功能并不是很有必要
2. 实现这个功能代价太大，需要解决的问题比较棘手

基于以上两点，所以我并没有花时间去尝试实现它。当然，如果你愿意去解决那些问题并实现它，我个人非常欢迎收到任何PR，如果实现的最终效果体验良好，我会考虑合并它的。

开发上的一些建建议：
1. 基于next分支开发
2. 看一下 #883 ，上面有提到一点这功能上的一些问题，可以作为参考
