### ISSUE TITLE
IDEA插件开发如何打成zip包

### ISSUE THREAD

**Issue by liuxianfa520** [YiiGuxing/TranslationPlugin#112]
您好，
    我fork您的项目并在本地学习idea插件开发，现在项目可以使用idea启动，但我想要打成插件包zip，使用setting->plugins->Install plugins from disk...方式安装使用。在项目打包时遇到了问题，不知如何打包插件项目。我在百度上找了一点半了也没找到相关博客。希望您可以指点一二。
谢谢！

**Comment by YiiGuxing** [comment]
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/deploying_plugin.html
要找IDEA插件开发相关的资料，还是看官方文档的好。。。。
