### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by yisier** [YiiGuxing/TranslationPlugin#1127]
选中翻译快捷键 Ctrl + Shift + X  和 IDEA 转换大小写快捷键冲突

![image](https://user-images.githubusercontent.com/26956516/161369316-f4b992b6-e44c-43c7-b7f9-6e508c7eeec6.png)

**Comment by YiiGuxing** [comment]
咦。。。大小写转换不是Ctrl+shift+u的吗？

快捷键冲突的话可以到快捷键设置里修改的

**Comment by yisier** [comment]
> 咦。。。大小写转换不是Ctrl+shift+u的吗？
> 
> 快捷键冲突的话可以到快捷键设置里修改的

1. Ctrl + Shift + X 是 keymap 为 eclipse 的快捷键。
2. 在 setting 页面 Translation 并没有设置快捷键的选项，也没有关闭快捷翻译的开关。。。。

**Comment by YiiGuxing** [comment]
你可以通过快捷键搜索，或者搜索 translate and replace 然后修改其快捷键即可
