### ISSUE TITLE
翻译时提示 签名检验失败 - 设置

### ISSUE THREAD

**Issue by jindasong** [YiiGuxing/TranslationPlugin#116]

**Comment by YiiGuxing** [comment]
设置的应用ID或应用密钥可能不正确，请确认应用ID和应用密钥是否正确。

**Comment by jindasong** [comment]
@YiiGuxing 应用秘钥保存不上，粘贴过来保存后，再次打开就没有了，webstorm版本2017.3

**Comment by YiiGuxing** [comment]
如果是MacOS，请另阅 #81
如果是Linux系统，请另阅 #115

**Comment by jindasong** [comment]
@YiiGuxing 按上面的方法可以了，感谢
