### ISSUE TITLE
有道502跪了~

### ISSUE THREAD

**Issue by Aragronsam** [YiiGuxing/TranslationPlugin#118]
之前在IDEA很好用，一切正常，今天突然就502了
![image](https://user-images.githubusercontent.com/10320179/34237218-6cbcb412-e636-11e7-8da9-8e3f763047e1.png)

**Comment by eziwen** [comment]
+1

**Comment by renshaodong** [comment]
+1

**Comment by milk36** [comment]
+1

**Comment by fxxxf** [comment]
+1
看了下有道智云，帐号没有问题。

**Comment by milk36** [comment]
ste_20171221_102936.jpg…]()

貌似是有道云Api的锅

**Comment by milk36** [comment]
应该是有道云Api的锅,下面两个地址都报错502.
http://openapi.youdao.com/api
https://openapi.youdao.com/api

**Comment by 91wangmeng** [comment]
现在翻译开始收费了啊

**Comment by YiiGuxing** [comment]
+1
唉！有道又跪了！等官方修复吧。诸君再等些时日，下一版就好多了，可以用Google翻译。

**Comment by Max-Null** [comment]
+1，顺便感谢作者

**Comment by T-Merak** [comment]
+1

**Comment by geekzhi** [comment]
+10086
