### ISSUE TITLE
【bug】安装插件后消失问题

### ISSUE THREAD

**Issue by Cyiming** [YiiGuxing/TranslationPlugin#1180]
插件安装后，关闭插件页面，再打开插件消失。

刚安装完是这样
![image](https://user-images.githubusercontent.com/45073586/162458272-61ade947-b9b7-4caf-8076-0a1a2763e437.png)
![image](https://user-images.githubusercontent.com/45073586/162458393-b3e997f0-9b38-44ec-852c-73bbbadfab4a.png)

关掉设置页面 重新打开设置-插件
插件消失 恢复到未安装状态
![image](https://user-images.githubusercontent.com/45073586/162458905-6aa21675-cdab-4e0c-b7df-aac660a43287.png)

**Comment by YiiGuxing** [comment]
这个是IDE的问题，安装后最好多等一会儿，最好不要点设置对话框的取消按钮，要点确定戓应用按钮，然后重启IDE。

**Comment by Cyiming** [comment]
> 安装后最好多等一会儿，最好不要点设置对话框的取消按钮，要点确定戓应用按钮，然后重启IDE。

确实好了 非常感谢
