### ISSUE TITLE
发音是不是定死了美音？希望能给个设置选项

### ISSUE THREAD

**Issue by flashrick** [YiiGuxing/TranslationPlugin#1217]
用有道云翻译的时候，点发音就是美音，希望能设置，英音美英可以切换

**Comment by YiiGuxing** [comment]
目前的发音只有谷歌的，它只有一个音，后续会有其他平台的TTS的，已经有相关开发计划，敬请期待！

**Comment by flashrick** [comment]
> 目前的发音只用了谷歌服务的，它只有一个音，后续会有其他平台的TTS的，已经有相关开发计划，敬请期待！

期待哈哈，有道云的tts还是相当不错的！
