### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by collbychen** [YiiGuxing/TranslationPlugin#1219]
请求Ctrl Shift O 键不要和maven编译冲突好吧，每次难受

**Comment by YiiGuxing** [comment]
可以自己定义快捷键的。

**Comment by collbychen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    how ?更改idea的快捷键吗？这个我用习惯了，改不了，插件的快捷键在哪里改，我不太清楚。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年4月12日 ***@***.***> 写道： 




可以自己定义快捷键的。

**Comment by YiiGuxing** [comment]
@collbychen 
![image](https://user-images.githubusercontent.com/10737066/162940325-1d97b2ed-27a9-4c2a-b113-15c83ed4ce25.png)

**Comment by collbychen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thanks A Lot ，之前我只是打Transla 前面几个，没出来，我以为没有。
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年4月12日 ***@***.***> 写道： 



@collbychen
