### ISSUE TITLE
Choose Translator怎么设置不让其显示在工具栏上？

### ISSUE THREAD

**Issue by rockjava** [YiiGuxing/TranslationPlugin#124]
Choose Translator怎么设置不让其显示在工具栏上？

**Comment by YiiGuxing** [comment]
![qq20180115-112216](https://user-images.githubusercontent.com/10737066/34925772-66d2f35e-f9e6-11e7-883b-9304d42e04d6.png)

还有一个是`Navigation Bar Toolbar`.
