### ISSUE TITLE
签名校验失败

### ISSUE THREAD

**Issue by Gaea-IT** [YiiGuxing/TranslationPlugin#126]
12月份的时候还能用,一月后就不能用了,提示签名校验失败,没有挂 vpn,有道智云的账号也有钱,也切换过应用翻译实例,还是不行,麻烦看一下是什么问题

**Comment by YiiGuxing** [comment]
请问使用的是哪个版本的插件？

**Comment by Gaea-IT** [comment]
我用的 mac ,看到之前的 issues,也出现了同样的问题,目前已近解决了
