### ISSUE TITLE
导航栏工具按钮太长

### ISSUE THREAD

**Issue by cn-src** [YiiGuxing/TranslationPlugin#127]
新版的导航栏工具按钮太长, 占用空间比较大.

建议方案:
将翻译方式切换放到[g/文]点击之后的对话框里
如果想体现当前翻译方式的状态, 可以放到状态栏里, 或者切换[g/文]所在按钮的图标

**Comment by YiiGuxing** [comment]
我觉得还可以接收的啊。如果接收不了可以将其去除： #124
还是先观察一下，如果不能接收的只有少数的话将不做修改。

**Comment by svran** [comment]
我也发现工具类太长了,直接留个图标可以下拉多好.或者就留 图标+Google/Youdao就好了.

**Comment by YiiGuxing** [comment]
正在考虑。。。
现在正在实现状态栏的状态展示：
![image](https://user-images.githubusercontent.com/10737066/35143802-9660517a-fd3d-11e7-8713-fd56bc83deca.png)
