### ISSUE TITLE
翻译对话框在没有焦点的状态下点击对话框外部不会使其自动关闭

### ISSUE THREAD

**Issue by Mr-hanchen** [YiiGuxing/TranslationPlugin#1273]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
框体长时间搁置后，点击代码框体并没有消失。

### 问题描述
1. 打开框体，确保显示在5min以上，并不做其他操作。
2. 点击代码显示区域后，翻译框并没有消失。
3. 当我点击代码显示区域时，翻译框应该消失，而不是还显示在idea中。
4. 重新点击翻译区域后，再点击代码显示区域框体恢复正常消失。

### 环境 & 错误日志
-->
- 插件版本：
![image](https://user-images.githubusercontent.com/58067013/163513909-d075c9e1-9aa0-4099-970d-9e6b59968475.png)

- IDE版本：
![image](https://user-images.githubusercontent.com/58067013/163513946-fde7e92a-89a0-4c58-a18b-20e22c0a1ca7.png)

- 操作系统版本：win11

- 未发生报错

此warning并不影响正常使用，目前因为没有报错信息，暂不确定是否为bug，只能提个issue以供作者测试。

**Comment by YiiGuxing** [comment]
感谢你的反馈，我已重现此事问题，其实这个问题并不需要长时间搁置才会出现，只需要让翻译框体失去焦点就会出现这个问题。
