### ISSUE TITLE
翻译替换按钮快捷键不生效

### ISSUE THREAD

**Issue by cn-src** [YiiGuxing/TranslationPlugin#128]
在我的 macbook 上, 新版和上一版, 替换的快捷键无法使用, 就像没有设置一样. 绑定其它快捷键也不行.
这太奇怪了, 在 keymap 管理里可以看到设置没问题, 但就是用不了.

**Comment by YiiGuxing** [comment]
那么在右键菜单里有翻译替换的条目吗？
![image](https://user-images.githubusercontent.com/10737066/34970971-a09e7bfe-fab2-11e7-921d-c5ffe9b266f0.png)

**Comment by cn-src** [comment]
上版有, 这版没有.

**Comment by cn-src** [comment]
看到了, 非常感谢!

**Comment by westinyang** [comment]
> 
> 
> 没有就说明当前状态下翻译替换操作不可用，所以快捷不能使用。
> 替换操作可用的状态是：当前光标周围有汉字，或者选中的文本是有汉字。

不可以翻译英文并替换为中文吗？

**Comment by YiiGuxing** [comment]
@westinyang 目前还不能
