### ISSUE TITLE
希望能优化下文档翻译的格式

### ISSUE THREAD

**Issue by chenyt01** [YiiGuxing/TranslationPlugin#1295]
形参部分翻译以后不是很直观，希望能增加缩进
还有 - 前边的参数部分有的翻译有的不翻译很奇怪，希望能增加是否翻译参数选项
![image](https://user-images.githubusercontent.com/39582535/163717721-2423cf94-af95-4daa-899c-bbf9108e5226.png)
![image](https://user-images.githubusercontent.com/39582535/163717730-2b49f815-c599-4a91-938a-1cb30f48a642.png)

**Comment by YiiGuxing** [comment]
你使用的是哪个翻译引擎的？文档翻译要格式好的话，只有使用谷歌翻译和阿里翻译才会有较好的格式，有道和百度的并不支持。

**Comment by WangJincheng4869** [comment]
的确谷歌能保持原有样式，问题是谷歌不能设置自己的账号，导致经常出现翻译频繁.....

**Comment by YiiGuxing** [comment]
> 的确谷歌能保持原有样式，问题是谷歌不能设置自己的账号，导致经常出现翻译频繁.....

@WangJincheng4869 是的，目前不能设置自己的账号，后续会有的，只是现在开发任务排得实在有点多了，一个人忙不过来，也不知道什么时候才能开发这个需求。。。。
