### ISSUE TITLE
Translation threw an uncaught PluginException.

### ISSUE THREAD

**Issue by Yves0** [YiiGuxing/TranslationPlugin#13]
Android Studio 2.1.3

` PluginException: cannot create class "cn.yiiguxing.plugin.translate.action.TranslationAction" [Plugin: cn.yiiguxing.plugin.translate]`

**Comment by YiiGuxing** [comment]
@Yves0 请问这是怎么出现的呢？我这里并不能重现该问题。

**Comment by Yves0** [comment]
安装之后重启AS就报错了，event log如下
`20:08:52 Plugin Error: Translation threw an uncaught PluginException. Disable Plugin

20:08:52 PluginException: cannot create class "cn.yiiguxing.plugin.translate.action.TranslationAction" [Plugin: cn.yiiguxing.plugin.translate]

20:08:58 PluginException: cannot create class "cn.yiiguxing.plugin.translate.action.EditorPopupMenuAction" [Plugin: cn.yiiguxing.plugin.translate]

20:09:26 PluginException: cn/yiiguxing/plugin/translate/ui/Settings : Unsupported major.minor version 52.0 [Plugin: cn.yiiguxing.plugin.translate]`

两种安装方法都是这样

**Comment by YiiGuxing** [comment]
@Yves0 这个应该是java版本的问题，你的java版本是不是低于1.7的？这个插件需要java 1.7以上的版本才行呢。

**Comment by YiiGuxing** [comment]
@Yves0 这个问题将在下一个版本修复，请留意版本更新。详情请查看: commit [`47fd2af`](https://github.com/YiiGuxing/TranslationPlugin/commit/47fd2af26e223a6c97da45659a7b5bf0e096c280).

**Comment by Yves0** [comment]
不好意思，忘记回复了。刚刚看到您的修改是降低了jdk版本，可是我的jdk是1.7啊。

**Comment by YiiGuxing** [comment]
已经上传到插件中心上的包编译还是有问题的，需要重新编译。这要放到下一个版本一起发了，如果你想先用着的话，可以把源码下载下来自己编译一个先用着（可能会有一些小问题）。
需要注意的是：
- 要用IDEA2016.2以上的版本编译，Android Studio是不能编译的。
- Java Compiler-Project bytecode version要指定为1.6。位置：preferences > Build > Compiler > Java Compiler

**Comment by Yves0** [comment]
好的，thanks
