### ISSUE TITLE
代码注释和文档翻译

### ISSUE THREAD

**Issue by cn-src** [YiiGuxing/TranslationPlugin#130]
能否增加源码上的 javadoc 的翻译，主要是因为javadoc这类一般都是嵌入了html标签，再加上注释符号的干扰，导致无法直接翻译。

或者类似这种嵌入了html标签的翻译。

😄 😄 😄

**Comment by YiiGuxing** [comment]
嗯，这个想法很好！有时间我研究研究，主要是不同的语言的文档结构一般也不一样的，这个可能有些复杂，看情况吧。
现在可以先在快速文档对话框上翻译。只有能够选择的文本，基本上都可以翻译的，右键菜单没有的话就用快捷键翻译。

**Comment by cn-src** [comment]
如果自己去实现每种不同语言的文档结构解析是挺麻烦的，我想既然 idea 的文档提示是统一的，那么能否通过这个接口或者其它方式直接拿到渲染之后的文档。
假设可以拿到那个文档的对话框，直接以翻译后的内容替换，这样可能实现要简单点。

**Comment by YiiGuxing** [comment]
是的，我就是要去找这东西，如果找到就可以实现，如果没有就算了。

**Comment by YiiGuxing** [comment]
经过一番调研（其实就是瞟了一眼），发现不同语言的文档经过IDE解析后统一返回了HTML代码，然后送到Swing的JTextPane中渲染显示。所以现在的问题变单一了，至于如何翻译HTML中文本内容而不改变其渲染效果。有一方案如下：
使用IDE内部的HTML解析器解析HTML代码，取出文本内容，逐一翻译（Googel有相应的API，有道不知道有没有）后替换，生成HTML代码再渲染。。。呃。。。表示工作量有点大啊。。。

**Comment by cn-src** [comment]
有道和谷歌都能进行网页翻译，如果能直接用就简单了，如果不能，我觉得没有必要100%原格式，只需要保留空格和换行这样的基本格式即可，然后直接全文翻译，这样就简单多了。

对于 <pre> 的内容 可以用 "(())" 这样不影响翻译的占位符替换，将这些原内容放到 List 里，翻译后再按顺序替换回来就行。

**Comment by yangxxj** [comment]
感觉v1.3.6界面比2.0.2好，2.02增加了Google翻译渠道，提示面板中的音标少了美式英式区分（不爽），字体不好看，还会乱码，多了中文发音功能（感觉多余），界面没以前那种小清新感觉了。

**Comment by YiiGuxing** [comment]
@yangxxj 为了实现多个翻译渠道的切换，肯定是要做一些取舍的，一些东西要统一一下才行，其中就包括输出页面。因为需要在输出页面添加语言的选择才会是现在这样的结果，不添加语言的选择还不行，除了有道，其他的API接口都不支持自动互译的，需要提供输出语言的。

- 『提示面板中的音标少了美式英式区分』是因为一个输入和输出的朗读只有一个接口，如果有两种发音的话朗读的时候又不能选择，所以只显示一个。
- 『字体不好看，还会乱码』这个字体是和v1.x版本的一样的，你可以在设置页面上修改为你喜欢的字体。乱码是因为当前的字体没有相应的字，也是需要通过修改字体解决的。
- 『中文发音多余』对于我们来说中文的发音确实是有点多余的，但是对于其他语言（谷歌翻译支持的语言超多的。。。）来说就不是多余的了，这个功能并不是专门为中文发音而设的，所以这个功能是必需的。

感谢您的反馈。后面我会慢慢地优化交互这方面的内容的，感谢您的支持！

**Comment by ALguojian** [comment]
可以修改默认的快捷键嘛，全部都是冲突，不想改其他的（因为经常用，都熟悉了）

**Comment by mtjmtj** [comment]
英语单词再显示个音标就完美了

**Comment by YiiGuxing** [comment]
@mtjmtj 有显示，只是谷歌翻译有的会没有给音标，这个就没有办法了。

**Comment by YiiGuxing** [comment]
另外，如果不是和本issue主题相关的，有问题请另外开issue。谢谢！

**Comment by peihu** [comment]
这个插件挺好的，我本来想给作者说下，加个音标显示的。来看看issue，结果发现有人提这个需求了。

**Comment by zhanggang807** [comment]
那这个在开发中了吗？我有一个idea，原则是简单可行，没必要做那么复杂，有时候简单的方法是最有效的方法：
第一步：获取当前文件的后缀判断注释格式（以支持多语言场景）
第二步：程序去除掉相关注释字符比如/** // /* */# ## 等，用正则去除掉HTML标签即可
第三步：翻译即可
依据简单可行原则，所以我认为没有必要保存原格式，相信大家都是看得懂的，又不是输出给别人看的，如果要输出给别人看一大把工具可供选用

**Comment by djh2717** [comment]
楼主,能否把状态栏中的翻译图标弄个设置可以隐藏其中某一个呢, 现在这个版本更新之后有一个红色的图标和一个蓝色的图标,感觉有点多余,, 要是能弄个设置隐藏图标就完美了.... 最后说一下楼主这个翻译软件真的很不错, 可以说是帮了大忙... 十分感谢!

**Comment by YiiGuxing** [comment]
@djh2717 可以在 Settings > Appearance & Behavior > Menus and Toolbars 中编辑。

**Comment by YiiGuxing** [comment]
@djh2717 这个我也不知，应该是不能的。

**Comment by djh2717** [comment]
好的，不过还是感谢您的答复 1544579459 邮箱：1544579459@qq.com 签名由 网易邮箱大师 定制 在2018年08月13日 23:31，Yii.Guxing 写道： @djh2717 这个我也不知，应该是不能的。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zonghaishang** [comment]
第一安装这个插件，被javadoc影响体验，需要这个玩意，哈哈

**Comment by djh2717** [comment]
楼主, 我最近想开发一款插件, 可以请教您一下哪里有较好的学习资料吗? 谢谢了

**Comment by YiiGuxing** [comment]
@djh2717 可以看官方的开发指南、官方开发文档、官方或第三方的开源插件源码。


另外，如果有任何问题，请新建一个issue，或者在相关的issue下评论，而不是在无关的issue下评论。谢谢！

**Comment by djh2717** [comment]
好的楼主, 十分感谢, 你有简书吗? 想请您喝杯咖啡 @YiiGuxing

**Comment by YiiGuxing** [comment]
@djh2717 谢谢，不过不必了，我也没有用简书。

**Comment by djh2717** [comment]
楼主, 我十分欣赏您, 可以加个微信交个朋友吗? 如果可以的话, 那再好不过了, @YiiGuxing

**Comment by YiiGuxing** [comment]
@djh2717 如果有需要，可以邮件联系我（邮箱在我GitHub主页），还是不要在这里讨论与主题无关的内容了。虽说我并不介意，但可能会打扰到楼上的两位兄弟。稍候我将会删除与主题无关的评论。

**Comment by djh2717** [comment]
嗯, 这是我的不对, 感谢您的回复

**Comment by sunbufu** [comment]
我有个思路，不知道是否可行：
1. 使用正则，根据 HTML 标签分组
2. 依次翻译每组词，并替换原文
3. 最后输出渲染
   
但是可能会有一个问题，需要评估下。分组后翻译是否会影响翻译的准确性。

**Comment by 1171736840** [comment]
请问这个功能完成了吗？估计有很多人需要这个功能

**Comment by YiiGuxing** [comment]
@1171736840 目前还没有时间和精力来实现这一功能。

**Comment by 1171736840** [comment]
> @1171736840 目前还没有时间和精力来实现这一功能。

好的，谢谢！

**Comment by cp19890714** [comment]
提供一个简单易行的思路：

**Comment by cp19890714** [comment]
提供一个简单易行的思路
1 提供一个单独的替换后翻译功能，设置独立的快捷键
2 用户可自己设置，需要替换的字符串集 或者 正则
3 翻译前，先根据字符串集进行替换，再翻译

这样实现起来可能是比较快的，又能解决大部分的人需求。大部分人并不需要太完美的方案。

**Comment by YiiGuxing** [comment]
@cp19890714 这样的话目前就可以使用，因为现在的版本已经支持根据正则表达式忽略内容。

**Comment by cp19890714** [comment]
> @cp19890714 这样的话目前就可以使用，因为现在的版本已经支持根据正则表达式忽略内容。

好的，多谢。
我才发现，由于我的IDEA是2016版的，导致插件一直没有更新，停留在version 1.3

**Comment by XinAnzzZ** [comment]
本来准备过来给作者提 issue，然后提个 PR实现 Javadoc 翻译，然而看完各位大佬的讨论，果断放弃，我把事情想得太简单了。。如果需要帮忙一起实现，大佬艾特我啊，愿意为插件做出微薄的贡献。

**Comment by nthpermanent** [comment]
> @cp19890714 这样的话目前就可以使用，因为现在的版本已经支持根据正则表达式忽略内容。

借楼问一下:
1.我想去掉翻译大段注释中的星号，所以我设置了正则表达式(这是我的表达式\s*\*.*)来忽略注释中的星号
2.选中一大段注释:点右键没有翻译按钮，用快捷健，没反应。
3.我猜着是因为我正则表达式命中了（因为每一行的开头都是星号）所以插件忽略这一行，不翻译。
那么，问题是怎么去实现，你所说的使用正则来实现翻译注释的功能？

**Comment by nthpermanent** [comment]
> 嗯，这个想法很好！有时间我研究研究，主要是不同的语言的文档结构一般也不一样的，这个可能有些复杂，看情况吧。
> 现在可以先在快速文档对话框上翻译。只有能够选择的文本，基本上都可以翻译的，右键菜单没有的话就用快捷键翻译。

借楼问一下:
1.我想去掉翻译大段注释中的星号，所以我设置了正则表达式(这是我的表达式\s**.*)来忽略注释中的星号
2.选中一大段注释:点右键没有翻译按钮，用快捷健，没反应。
3.我猜着是因为我正则表达式命中了（因为每一行的开头都是星号）所以插件忽略这一行，不翻译。
那么，问题是怎么去实现，你所说的使用正则来实现翻译注释的功能？

**Comment by XinAnzzZ** [comment]
> > 嗯，这个想法很好！有时间我研究研究，主要是不同的语言的文档结构一般也不一样的，这个可能有些复杂，看情况吧。
> > 现在可以先在快速文档对话框上翻译。只有能够选择的文本，基本上都可以翻译的，右键菜单没有的话就用快捷键翻译。
> 
> 借楼问一下:
> 1.我想去掉翻译大段注释中的星号，所以我设置了正则表达式(这是我的表达式\s**.*)来忽略注释中的星号
> 2.选中一大段注释:点右键没有翻译按钮，用快捷健，没反应。
> 3.我猜着是因为我正则表达式命中了（因为每一行的开头都是星号）所以插件忽略这一行，不翻译。
> 那么，问题是怎么去实现，你所说的使用正则来实现翻译注释的功能？

[/*]+，使用这个

**Comment by nthpermanent** [comment]
> > > 嗯，这个想法很好！有时间我研究研究，主要是不同的语言的文档结构一般也不一样的，这个可能有些复杂，看情况吧。
> > > 现在可以先在快速文档对话框上翻译。只有能够选择的文本，基本上都可以翻译的，右键菜单没有的话就用快捷键翻译。
> > 
> > 
> > 借楼问一下:
> > 1.我想去掉翻译大段注释中的星号，所以我设置了正则表达式(这是我的表达式\s**.*)来忽略注释中的星号
> > 2.选中一大段注释:点右键没有翻译按钮，用快捷健，没反应。
> > 3.我猜着是因为我正则表达式命中了（因为每一行的开头都是星号）所以插件忽略这一行，不翻译。
> > 那么，问题是怎么去实现，你所说的使用正则来实现翻译注释的功能？
> 
> [/*]+，使用这个
![image](https://user-images.githubusercontent.com/35824162/67547859-c9592980-f732-11e9-8c10-e33c809fb5dc.png)
全程使用有道翻译，以上面的英文为例子，我使用了你的正则表达式，效果如下
![image](https://user-images.githubusercontent.com/35824162/67547600-21dbf700-f732-11e9-81cd-8f65d296d243.png)


确实正则表达式起作用了，但是不通顺，把它挪到有道中，保留断行，发现结果一模一样
![image](https://user-images.githubusercontent.com/35824162/67547827-b5adc300-f732-11e9-8fad-3c7ad33ae624.png)

手工调一下格式，把断开的两行调成一行，很通顺了
![image](https://user-images.githubusercontent.com/35824162/67547715-68315600-f732-11e9-8d89-4587ba011752.png)

通过对比，我认为是因为每行末尾都有换行符，导致了有道将一个句子看做两个句子。
那么有没有办法能再去掉星号以后，把换行符换成空格？让本来是一个句子的别断成两行，希望各位大佬不吝赐教

**Comment by XinAnzzZ** [comment]
@nthpermanent google 翻译，正常。
![image](https://user-images.githubusercontent.com/38024683/67548724-205ffe00-f735-11e9-90f6-2cf30aded3a3.png)
![image](https://user-images.githubusercontent.com/38024683/67548734-28b83900-f735-11e9-918e-aeb31235a41e.png)

不要勾选 “使用 translation.google.com”，默认使用 traslation.google.cn，服务器在中国。

**Comment by nthpermanent** [comment]
> @nthpermanent google 翻译，正常。
> ![image](https://user-images.githubusercontent.com/38024683/67548724-205ffe00-f735-11e9-90f6-2cf30aded3a3.png)
> ![image](https://user-images.githubusercontent.com/38024683/67548734-28b83900-f735-11e9-918e-aeb31235a41e.png)
> 
> 不要勾选 “使用 translation.google.com”，默认使用 traslation.google.cn，服务器在中国。
非常感谢你的解答，不过很遗憾你的这条建议对我不起作用。我找到一句话被截断成两行的原因了，因为我勾选了插件选项中的“keep content format”，去掉就好了。
![image](https://user-images.githubusercontent.com/35824162/67549716-7c2b8680-f737-11e9-9b46-1645b5227a6e.png)

**Comment by YiiGuxing** [comment]
“**代码注释和文档翻译**”的一个代替方案，可使用**内容忽略**功能忽略掉注释和文档中的干扰内容（如Java中的 `/` 和 `*` ）。

**`Java`, `JavaScript` 等语言的内容忽略正则表达式：**

- ```regexp
  [/*]+
  ```
  > *最简单粗暴，缺点是注释和文档内容中的 `/` 和 `*` 也会被忽略掉，效果如下图所示：*
  >
  > ![1](https://user-images.githubusercontent.com/10737066/67548287-0a9e0900-f734-11e9-9ddc-143e0df63e96.png)

- ```regexp
  ((^\s*(/(/+|\*+)|(\*+(?!/))) ?)|(\s*\*+/\s*$))
  ```
  > *这个正则表达式能够保留注释和文档内容中的 `/` 和 `*`，但需要插件在v2.5.1及以上的版本才能使用（#380），效果如下图所示：*
  >
  > ![2](https://user-images.githubusercontent.com/10737066/67548304-14c00780-f734-11e9-9523-f6116e27cdc4.png)

欢迎大家补充更多更好的，或者其他语言的内容忽略正则表达式。

**Comment by nthpermanent** [comment]
@YiiGuxing 
很强👍。是否考虑在option中增加个选项“一键过滤星号”（或者别的名字）呢，毕竟这个场景太常见了，而且不是所有人都能找到这里的。 像我，这个问题困扰了好久，对正则又不熟悉，相信像这样的人不在少数。

**Comment by YiiGuxing** [comment]
@nthpermanent 不能这么做，不能做相互覆盖的事情，不是每种语言的注释都是星号。

**Comment by liangpengjie** [comment]
### Java 源码注释翻译
> 我也是前一阵过来想提 issue,发现可以使用正则，自己研究了下，分享个我现在自己用的,我的目的是为了看 Java 源码，有点缺陷，不是很完美，不过日常使用可以了，分享给有需要的同学们

```
^ +\*|(<\/?a.*?>)|[<][\w/]+[>]|(\/\*\*|\*\/)|(?<=(\n|\t)) +\*+|\/$
```
#### 效果：
![](https://i.loli.net/2019/10/29/wHfNVsgL5SIlEG9.jpg)
![](https://i.loli.net/2019/10/28/XQfSUvEg54tNxWp.jpg)
#### 功能：
- 可以翻译类注释和方法注释
- 去除注释带来的 `*`
- 去除注释里面 HTML 符号并保留标签中的内容 
- 不会删除注释里的`*`，`\` 特设符号

> `{@code String} ` 向这种格式的我觉得留下更容易理解注释内容，看起来比较清晰，所以并没有去除

#### 缺陷：
如果保留原格式，会出现上文 @nthpermanent 说的换行后翻译不准确的问题，但把全部内容连起来后觉得有些不美,应该在判断下是否是一句的结尾来是否取消换行符
> 主要原因是这个对阅读的影响并不大，并且个人的正则比较差，再继续下去，需要花费较多时间，故此放弃，如果有哪位朋友有更好的解决办法，请指教

**Comment by liangpengjie** [comment]
其实我觉得这个功能不用做这样麻烦，以这个正则为基础扩展，针对每个语言写一个正则，可以给个默认的，并且用户可以自行扩展，可以选择是否打开那个语言的，以后缀名去匹配文件 @YiiGuxing

**Comment by Leexiaobu** [comment]
我发现idea看源码的时候按ctrl+q ，就可以打开无干扰内容的源码文档，在翻译下那个就可以了

**Comment by liangpengjie** [comment]
@Leexiaobu 多谢分享，我刚试了一下，Mac 的快捷键是`F1`或者`control+J`,这样看舒服多了！

**Comment by YiiGuxing** [comment]
一个简单的实现（[v2.6.0](https://github.com/YiiGuxing/TranslationPlugin/milestone/6?closed=1) - #394）:
-----
![img](https://user-images.githubusercontent.com/10737066/69009306-16759780-098f-11ea-932a-e694bd269281.gif)

已知可用的语言有 `Java`, `Kotlin`, `Scala`, `JavaScript`, `PHP`, `Groovy` 等，可能还有其他支持的语言，反正我没有一一去试，但像 `Python` 这样的就不行了。

已经问题——获取的文档注释内容的开始会有元素的定义内容，而且无法识别并去除：
![image](https://user-images.githubusercontent.com/10737066/69009484-791b6300-0990-11ea-8fac-b5099b9909a7.png)

![image](https://user-images.githubusercontent.com/10737066/69009469-5ee18500-0990-11ea-9a97-d218dfe317b1.png)

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/compare/20a051153189dd1114c3bb8c0cf0896e6dcb14ae...2e97fe9452e8966e9d89b2e8ad80d0527ae32151

**Comment by Darling012** [comment]
作者太棒了，刚更新完尝试了下

**Comment by qiyuey** [comment]
很不错！！！
