### ISSUE TITLE
如何隐藏2.0.1状态栏图标

### ISSUE THREAD

**Issue by TGich** [YiiGuxing/TranslationPlugin#132]
[//]: 如果需要反馈一个插件错误（如一个未知原因的翻译失败问题），
[//]: 请按照http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb所述收集并在此附上收集到的错误信息。

插件做的非常好，是最好用的idea翻译插件，但是从2.0后各种工具栏状态栏图标有些突兀和违和，工具栏的图标已参考之前的issue隐藏了，请问下状态栏的图标隐藏在哪里设置，谢谢！

**Comment by YiiGuxing** [comment]
:joy: 这个是不能隐藏的，这个就没有必要隐藏了吧？:joy: :joy: :joy:

**Comment by TGich** [comment]
好吧，希望以后可以实现功能
