### ISSUE TITLE
2022.1 关不掉翻译窗口

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#1323]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/29020213/163907401-cfdcf4b8-efc9-4972-acff-2cfce9fde36d.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/29020213/163907350-936270a5-fe82-4a79-981c-c55cd4fdaeb5.png">

复现步骤

1.打开翻译窗口
2.进行翻译
3.点击复制翻译
4.点击外部无法关闭窗口
5重启才能解决

**Comment by YiiGuxing** [comment]
你是不是点击了固定窗口了？

![image](https://user-images.githubusercontent.com/10737066/163907853-3f306117-768b-4911-94b6-e0d8d5e4e46b.png)

**Comment by mdddj** [comment]
不是, 我重新启动后就没问题了, 但是后面不知道什么操作或者原因触发了不能关闭这个Popup的问题
目前为止发生了两次,开始以为是idea的问题, 上面是第二次,就产生了怀疑是不是插件的问题,所以来提了ISS

**Comment by YiiGuxing** [comment]
那你看看是不是和这个问题是一样的： #1273

**Comment by mdddj** [comment]
不是很确定,按照他的测试了没问题

**Comment by YiiGuxing** [comment]
那就只能在下个版本再看看还有没有这个问题吧，因为这部分都有修改了，从逻辑上应该不会有问题了。

**Comment by mdddj** [comment]
OK
