### ISSUE TITLE
macbook pro不响应 enter

### ISSUE THREAD

**Issue by epolar** [YiiGuxing/TranslationPlugin#133]
输入要查询的文字以后，按enter没反应，必须鼠标点击翻译按钮

**Comment by YiiGuxing** [comment]
试试这个包：
[TranslationPlugin-2.0.2-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1658254/TranslationPlugin-2.0.2-SNAPSHOT.zip)

**Comment by epolar** [comment]
这个包可以用

**Comment by YiiGuxing** [comment]
好的，谢谢反馈！

**Comment by YiiGuxing** [comment]
commit [`2ad2822`](https://github.com/YiiGuxing/TranslationPlugin/commit/2ad28224447f37109de2233d9ab9e1612fe55df8)
