### ISSUE TITLE
Use English language

### ISSUE THREAD

**Issue by mrsoftware** [YiiGuxing/TranslationPlugin#134]
Please use the English language in this plugin. we can't understand Chinese language or whatever it is .

**Comment by YiiGuxing** [comment]
See: [**TranslationBundle**](https://github.com/YiiGuxing/TranslationPlugin/blob/dev/src/main/resources/messages/TranslationBundle.properties)
Published: [**v2.0.2**](https://plugins.jetbrains.com/plugin/8579-translation/update/43053)
