### ISSUE TITLE
翻译引擎“谷歌翻译”用不了

### ISSUE THREAD

**Issue by Li-Nuo** [YiiGuxing/TranslationPlugin#1356]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
有什么提示吗？

**Comment by Li-Nuo** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Li-Nuo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 翻译引擎“谷歌翻译”用不了 (Issue #1356)





 
有什么提示吗？

**Comment by Li-Nuo** [comment]
![image](https://user-images.githubusercontent.com/93080596/164397056-79ff0bed-d88d-401f-aab7-b3f48038de05.png)

**Comment by YiiGuxing** [comment]
插件版本是多少？

**Comment by Li-Nuo** [comment]
3.3

**Comment by YiiGuxing** [comment]
此问题已修复，请升级到最新版本。

**Comment by Li-Nuo** [comment]
好滴感谢
