### ISSUE TITLE
使用Google 翻译。翻译速度比较慢。并且经常翻译出错？有人跟我一样吗？

### ISSUE THREAD

**Issue by hugbio** [YiiGuxing/TranslationPlugin#136]
有人跟我一样吗？使用Android Studio。

**Comment by YiiGuxing** [comment]
慢可能是网络问题。
出错的是什么错误？能否贴出错误信息？

**Comment by hugbio** [comment]
每次翻译都要等3-4秒时间。是否正常？出错的信息我现在无法提供给你。因为都是隔一段比较长的时间不翻译后。再次翻译出现的。后面出现时我记录一下。

**Comment by YiiGuxing** [comment]
使用Android Studio是哪个版本？有时间我看看能不能复现。

**Comment by hugbio** [comment]
Android Studio 3.0.1

**Comment by YiiGuxing** [comment]
刚刚试了一下，很快的啊。应该是你那网络环境的问题。
