### ISSUE TITLE
WebStrom 更新插件到 3.3.1 版后无法关闭更新提示弹窗

### ISSUE THREAD

**Issue by DevDengChao** [YiiGuxing/TranslationPlugin#1363]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

![image](https://user-images.githubusercontent.com/16363180/164590080-2c7a6380-0641-43ac-8f53-bc2fe4d31060.png)

今天更新 WebStrom 上的插件后, 出现了上述截图中的更新提示弹窗, 但是到处点了点都没法关闭这个弹窗. 重启 WebStrom 后恢复正常.

ps: 刚刚又更新到 3.3.1-patch1 了, 但是这一次没有出现更新提示弹窗.

### 环境 & 错误日志

```
WebStorm 2022.1
Build #WS-221.5080.193, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    name.kropp.intellij.makefile (221.5080.126)
    zielu.gittoolbox (212.8.9)
    com.intellij.swagger (221.5080.126)
    com.intellij.database (221.5080.193)
    izhangzhihao.rainbow.brackets (6.21)
    cn.yiiguxing.plugin.translate (3.3.1)
```

**Comment by YiiGuxing** [comment]
鼠标移动至窗口上，窗口右上方会有关闭按钮的，点击就可以关闭。

**Comment by DevDengChao** [comment]
下次更新的时候我试试看, 可行的话就把这个问题关闭 🤣
