### ISSUE TITLE
Android Studio版本这几天的文档翻译出错未修复

### ISSUE THREAD

**Issue by mcxinyu** [YiiGuxing/TranslationPlugin#1371]
- 插件版本: 3.3-203u212.patch.1
- IDE版本: Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 17, 2022
- 操作系统版本: Windows 11

正如题目所述，Android Studio版本并没有检查到更新，目前还是 3.3-203u212.patch.1，但目测，idea版本已经是 3.3.1-patch.1。

**Comment by YiiGuxing** [comment]
请将插件更新到最新版本

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/164865510-820921c8-60c9-49b0-8bfb-ba4fdb83bbb2.png)

如果还是没有收到更新推送，那就手动安装吧。
