### ISSUE TITLE
Translation to Japanese becomes English

### ISSUE THREAD

**Issue by CAIOS0922** [YiiGuxing/TranslationPlugin#1379]
## Problem
I've been using this plugin for some time, but a recent update (version 3.3.1) seems to prevent translation into Japanese. Specifically, even if the translation destination language is Japanese, the actual output language will be English. As far as I've tried, this problem seems to occur no matter what language you're using for translation. Also, this problem seems to occur only in Japanese and was correctly translated into other languages ​​such as Chinese.

I'm not very good at English, so I'll post the image in question below. I think it's easier to understand if you see it rather than explain it. I am trying to translate English into Japanese, but the output language is English, not Japanese.

![image](https://user-images.githubusercontent.com/56629437/164984145-0b8caa7c-e111-49cb-8ff2-1aa08a39dbba.png)

## Environment
・IntelliJ Community Edition (Build: 221.5080.210)
・Translation Plugin (Version: 3.3.1-patch.1)

**Comment by YiiGuxing** [comment]
Sorry, I released the test code to the release version, so it caused this problem. You can go back to the previous version, or use this package temporarily:
[TranslationPlugin-3.3.2-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/8550970/TranslationPlugin-3.3.2-SNAPSHOT.zip)

**Comment by CAIOS0922** [comment]
Thanks! The snapshot worked correctly. Thank you for your quick response. I love this plugin :)

**Comment by YiiGuxing** [comment]
@CAIOS0922 The [3.3.2](https://github.com/YiiGuxing/TranslationPlugin/releases/tag/v3.3.2) official version has been released.
