### ISSUE TITLE
Translate Error

### ISSUE THREAD

**Issue by de2moe** [YiiGuxing/TranslationPlugin#14]
上午11:30:35 Plugin Error: Translation threw an uncaught PluginException. Disable Plugin
上午11:30:35 PluginException: cannot create class "cn.yiiguxing.plugin.translate.action.TranslationAction" [Plugin: cn.yiiguxing.plugin.translate]
上午11:30:44 PluginException: cannot create class "cn.yiiguxing.plugin.translate.action.EditorPopupMenuAction" [Plugin: cn.yiiguxing.plugin.translate]
上午11:30:45 EmptyThrowable: Null child action in group Main Toolbar () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=TranslationAction
上午11:30:56 EmptyThrowable: Null child action in group Main Toolbar () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=TranslationAction
上午11:31:00 EmptyThrowable: Null child action in group Main Toolbar () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=TranslationAction

**Comment by YiiGuxing** [comment]
@de2moe  请问你安装的java是哪个版本的？

**Comment by YiiGuxing** [comment]
请升级你的java版本，插件需要java7以上的版本才能运行。下一个版本我把它降低到java6上吧。

**Comment by de2moe** [comment]
感谢你的回答，这个错误出现在我的环境：Java 7 Update 79 & Android Studio 2.1.3

**Comment by de2moe** [comment]
我是 Java SE Development Kit 7u79 For Mac

**Comment by YiiGuxing** [comment]
@de2moe 这个问题将在下一个版本修复，请留意版本更新。详情请查看: commit [`47fd2af`](https://github.com/YiiGuxing/TranslationPlugin/commit/47fd2af26e223a6c97da45659a7b5bf0e096c280).
