### ISSUE TITLE
2.0.1快捷键变更？？？

### ISSUE THREAD

**Issue by yedajiang44** [YiiGuxing/TranslationPlugin#140]
Alt+R、Alt+1、Alt+2、Alt+3这几个快捷键取消了吗还是怎么回事？今天更新了之后就没了。。。

**Comment by YiiGuxing** [comment]
http://yiiguxing.github.io/TranslationPlugin/start.html#faq-km

**Comment by yedajiang44** [comment]
@YiiGuxing 那可否问下原本Alt+R的功能还在吗？

**Comment by yedajiang44** [comment]
@YiiGuxing 找到了ctrl+shift+x
