### ISSUE TITLE
可以添加英语音标吗

### ISSUE THREAD

**Issue by valord577** [YiiGuxing/TranslationPlugin#141]
[//]: 如果需要反馈一个插件错误（如一个未知原因的翻译失败问题），
[//]: 请按照http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb所述收集并在此附上收集到的错误信息。

正文
可以添加英语的英标吗
最好  美式 英式  的英标都加一下

**Comment by YiiGuxing** [comment]
google翻译有的有英标，有的没有。
有道的话一般单词都有英标，英标好像是英式的。
