### ISSUE TITLE
Translation to Chines becomes unknow language

### ISSUE THREAD

**Issue by XiangxiangLiu** [YiiGuxing/TranslationPlugin#1416]
### Problem
I've been using this plugin for some time, but a recent update (version 3.3.1) seems to prevent translation into Chinese，Also，I don't how to set target Languague。
![image](https://user-images.githubusercontent.com/18486663/165989220-ba486e2e-b570-4888-ab94-42b7f4054885.png)
![image](https://user-images.githubusercontent.com/18486663/165989851-44da7827-7f83-426d-9d83-52842034d0a6.png)

### Environment
IntelliJ IDEA 2022.1 (Ultimate Edition)
TranslationPlugin(3.3.1-patch.1)

**Comment by YiiGuxing** [comment]
请设置主要语言为“中文”

**Comment by XiangxiangLiu** [comment]
已设置
![image](https://user-images.githubusercontent.com/18486663/166109417-3d248de2-7671-4bdb-ad0d-9e39aa9ab41b.png)
