### ISSUE TITLE
相当的棒, 不知道有没有考虑弄个Eclipse版出来呢?

### ISSUE THREAD

**Issue by wuwz** [YiiGuxing/TranslationPlugin#145]
之前一直用idea, 用你这插件用上瘾了, 现在由于一些特殊原因, 冷不丁的切换到eclipse, 好不习惯

**Comment by wuwz** [comment]
谢谢, 建议弄一个分支出来吧

**Comment by YiiGuxing** [comment]
代码就在这里：https://gitee.com/tinkling/Tinkling-Eclipse-Plug-in
也不知道还能用不，你可以试试，如果不能用可以自己动手修改代码。现在让我回过头去使用eclipse，已经完全不会用了。。。

**Comment by YiiGuxing** [comment]
[cn.tinkling_1.1.0.v201411241411.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1822431/cn.tinkling_1.1.0.v201411241411.zip)
这是安装包，解压到`eclipse-workspace`目录下，重启eclipse，然后点工具栏上的Window -> Show View -> Other -> Tinkling -> 有道词典。

**Comment by wuwz** [comment]
谢谢
