### ISSUE TITLE
替换和格式

### ISSUE THREAD

**Issue by grusirna** [YiiGuxing/TranslationPlugin#146]
1. 选中一大段英文（代码注释），提供一个翻译替换的快捷键会更方便。
2. 原文合并翻译保证了翻译的准确性，但失去了原文的层次结构。
目前翻译格式有一个问题，对选中的一整大段英文（按照缩略+回车组织）采用合并输送给google翻译，  生成的译文内容没问题。但出现另外一个问题，生成的译文是没有格式的，原先的英文格式不在了(回车，缩进)。

**Comment by YiiGuxing** [comment]
1. 翻译替换目前只支持向英文翻译
2. 翻译替换目前只适用于字符量少的字符串，适用场景为命名变量、方法名、类名。。。

**Comment by YiiGuxing** [comment]
后续可能会提供一个专门用于翻译长文本的功能，到时候才考虑是否取消上述限制。
所以现在先关闭此问题，如果你有任何问题可以重新打开。
