### ISSUE TITLE
请问下作者，你这个插件如何上传到AndroidStudio中，并且在AndroidStudio中搜索到的呢

### ISSUE THREAD

**Issue by 15189611** [YiiGuxing/TranslationPlugin#147]
请问下作者，你这个插件如何上传到AndroidStudio中，并且在AndroidStudio中搜索到的呢，谢谢，

**Comment by YiiGuxing** [comment]
将插件发布到[JetBrains插件仓库](https://plugins.jetbrains.com/)里即可。

**Comment by 15189611** [comment]
不是很懂·，请问下有详细的教程？谢谢···

**Comment by YiiGuxing** [comment]
https://plugins.jetbrains.com/plugin/add/intellij
