### ISSUE TITLE
无声音 Translation threw an uncaught NoClassDefFoundError

### ISSUE THREAD

**Issue by junquanvip** [YiiGuxing/TranslationPlugin#149]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
请提供详细的错误信息，谢谢

**Comment by YiiGuxing** [comment]
请提供一下红框里的内容，谢谢：
![1](https://user-images.githubusercontent.com/10737066/38465710-d1306f86-3b51-11e8-92b2-611959fea295.png)

**Comment by junquanvip** [comment]
我重复安装了一下就好了，打扰了
