### ISSUE TITLE
字体大小调整, 隐藏原文 和译文换行 * 忽略

### ISSUE THREAD

**Issue by liuzhihangs** [YiiGuxing/TranslationPlugin#150]
设置不显示英文或者可以调整显示的大小,显示框. 并且翻译是否应该有换行

**Comment by YiiGuxing** [comment]
1. 由于需要更变语言和语音朗读，所以不能完全去掉输入文本，倒是可考虑是否加个折叠选项；
2. 调整界面大小我先试试；
3. 关于“翻译是否应该有换行”这个另有计划。

**Comment by liuzhihangs** [comment]
谢谢,  主要使用场景是在看源码的时候对注释段落进行翻译, 因为带有 * 和换行 以及字体大小无法调整, 进行整段翻译的时候显示比较乱.

**Comment by liuzhihangs** [comment]
@YiiGuxing  谢谢, 主要使用场景是在看源码的时候对注释段落进行翻译, 因为带有 * 和换行 以及字体大小无法调整, 进行整段翻译的时候显示比较乱

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/projects/1

**Comment by YiiGuxing** [comment]
关于字体大小的自定义调整，我并不推荐这样做，因为这样可能会影响界面的美观。如果确实需要调整的话，可以调整IDE整体界面的字体大小，插件字体会自适应（只向上适应）：
![1](https://user-images.githubusercontent.com/10737066/39034994-06fb56f0-44ab-11e8-97d1-c19c303a8e6d.png)

而关于其他的建议，已有相应的计划，但不会在近期实现。

**Comment by YiiGuxing** [comment]
@liuzhihangs 关于忽略翻译内容，在新版本[v2.1.0](https://github.com/YiiGuxing/TranslationPlugin/releases/tag/v2.1.0)中已加入相关配置选项：
![image](https://user-images.githubusercontent.com/10737066/43373798-993eb4d0-93de-11e8-9908-a8753caa3670.png)
默认为空（也就不是忽略任何内容），需要自行配置。
