### ISSUE TITLE
希望增加Google.com接口

### ISSUE THREAD

**Issue by Jav4Boy** [YiiGuxing/TranslationPlugin#151]
所在环境无法使用google.cn

**Comment by Jav4Boy** [comment]
希望可以增加Google.com接口.
并且提供cn/com切换功能.
谢谢!

**Comment by YiiGuxing** [comment]
![1](https://user-images.githubusercontent.com/10737066/39035169-a8412d0a-44ab-11e8-8c27-13c38fe57d7f.png)

**Comment by Jav4Boy** [comment]
thanks~
