### ISSUE TITLE
希望增加 任意语言之间的翻译替换

### ISSUE THREAD

**Issue by pilipalala** [YiiGuxing/TranslationPlugin#152]
希望增加 任意语言之间的翻译替换

**Comment by YiiGuxing** [comment]
目前的翻译替换功能的适用场景只有代码变量命名，不适用于其他地方。

**Comment by YiiGuxing** [comment]
近期还不会考虑增加这个需求，所以先关闭这个issue了。
https://github.com/YiiGuxing/TranslationPlugin/projects/1#card-8939849
