### ISSUE TITLE
作者你好,第三方插件替换文档,翻译失效

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#1522]
作者你好,我写了一个插件,替换了`dart`语言的官方文档后,有用户反馈说翻译不起作用了

下面放上插件的部分代码, 大佬有空帮忙看看解决一下吗

代码文件: https://github.com/mdddj/dd_flutter_idea_plugin/blob/master/src/main/kotlin/shop/itbug/fluttercheckversionx/document/DartDocumentExt.kt

截图:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/29020213/169434023-afafa026-9d60-432b-9ec5-48189be46cd4.png">

**Comment by YiiGuxing** [comment]
原因可能是出来在这里：
[`<lang.documentationProvider implementationClass="shop.itbug.fluttercheckversionx.document.DartDocumentExt" language="Dart" order="first" />`](https://github.com/mdddj/dd_flutter_idea_plugin/blob/973a0e7dfbb9c4403d0b7513be91c63e6c7296f2/src/main/resources/META-INF/plugin.xml#L78)

两个插件都使用了相同的`order`: `order="first"`，两者相冲突，只会有一个获取`first`优先权，没有获得`first`优先权的就会失效。
这个问题貌似无解，平台设计的问题。。。

**Comment by mdddj** [comment]
@YiiGuxing  好的,谢谢. 那没办法了...
