### ISSUE TITLE
开放翻译的api

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#1525]
我是昨天提问的那个 https://github.com/YiiGuxing/TranslationPlugin/issues/1522

请问一下,第三方idea插件可以依赖这个包,然后调用TranslationPlugin的开放翻译api吗?  
是否有相关文档查看?谢谢

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/29020213/169628513-93de47b7-56bf-4ce1-9527-66c1ab9a4b1e.png">

**Comment by YiiGuxing** [comment]
@mdddj 
目前没有开放api相关的计划，不过这个问题好像也不是没有解决办法，我看了一下源代码：
```
com.intellij.openapi.extensions.LoadingOrder
```
你那边可以将`order`的值指定为这样的形式：`order="first, after XXX"`，其中`XXX`是一个ID，这样就可以指定其相对的加载顺序了，你可以研究一下，这个方式是否有效（在跨插件的情况下，我看代码文档应该是可以的），如果有效，我可以在下一个版本为你的插件在我的文档拓展提供这么一个ID，你那边引用一下这个ID，确保你的文档拓展在我的之后加载就可以了。

**Comment by mdddj** [comment]
@YiiGuxing 好的,谢谢, 有空我研究一下用法
