### ISSUE TITLE
选择后自动弹出翻译的结果

### ISSUE THREAD

**Issue by wuzhen0808** [YiiGuxing/TranslationPlugin#1527]
目前，选择一个单词后，需要右键点击，弹出上下文菜单后，再点击菜单，才能显示翻译结果，这样很麻烦；
希望增加功能：选择单词后，自动弹出翻译结果；
就像FireFox中的插件：Simple Translate ；

**Comment by JiuyeXD** [comment]
个人建议修改快捷键 File -> Settings -> Keymap -> Plugins -> Translation 中修改
![image](https://user-images.githubusercontent.com/44766833/170408594-1affd3d6-d191-492f-8a5d-8a92fbee2978.png)

**Comment by YiiGuxing** [comment]
可以通过鼠标快捷键实现。
