### ISSUE TITLE
翻译文档失败: 未知错误

### ISSUE THREAD

**Issue by sepmonkey** [YiiGuxing/TranslationPlugin#1531]
## 问题详情
翻译文档失败: 未知错误

### 问题描述
使用Translate能够得到翻译结果
使用Translate documentation功能, 一直提示“翻译文档失败: 未知错误”

### 环境 
- 插件版本: 3.3-203u212.patch.1
- IDE版本:  IDEA 2021.1.3
- 操作系统版本:  Windows 7/Windows 10

**Comment by YiiGuxing** [comment]
更新插件到最新版本就可以了。
