### ISSUE TITLE
无法保存百度翻译应用程序的密钥

### ISSUE THREAD

**Issue by kentelove** [YiiGuxing/TranslationPlugin#1534]
## 问题详情
无法保存百度翻译应用程序的密钥。
设置完成以后，当次启动有效，可以正常使用。
当idea关闭，再次启动后，需要重新设置密钥。
### 环境 & 错误日志
- 插件版本: 3.3.2-203u212
- IDE版本: IDEA 2021.1.3 
- 操作系统版本: Windows 7

**Comment by YiiGuxing** [comment]
https://yiiguxing.github.io/TranslationPlugin/start.html#faq

**Comment by zhangzhen123** [comment]
这个问题有解决吗
