### ISSUE TITLE
关于获取发音的问题

### ISSUE THREAD

**Issue by jerome-233** [YiiGuxing/TranslationPlugin#157]
安装的最新版本, 用百度和有道接口都没办法获取到发音.
发现`pycharm`通知栏会显示正在下载安装`TTS`..但是下载会失败...错误显示:
`java.net.SocketTimeoutException: connect timed out`
所以想请问一下作者您, 好确认一下是插件本身的问题, 还是我这边因为Gfw墙等网络环境造成的问题.....

**Comment by YiiGuxing** [comment]
TTS使用的是谷歌的TTS.根据你给出的信息来看是网络的问题，请检查一下你的网络环境。
