### ISSUE TITLE
出现翻译失败

### ISSUE THREAD

**Issue by 1050190942** [YiiGuxing/TranslationPlugin#1570]
服务当前已关闭，请前往管理控制台开启服务
出现这中情况怎么去解决他呢

**Comment by YiiGuxing** [comment]
请问你使用的版本是哪个？
还有请提供一下错误的截图。

**Comment by N-show** [comment]
> 你使用的版本是哪个？ 还有请提供一下错误的截图。

<img width="271" alt="截屏2022-06-21 15 13 11" src="https://user-images.githubusercontent.com/10193628/174738670-558d32d8-59ed-4758-9371-9d0ccdd47c6b.png">
