### ISSUE TITLE
新版的Rider 文档翻译不起作用

### ISSUE THREAD

**Issue by geeksmy** [YiiGuxing/TranslationPlugin#1578]
新版的Rider 文档翻译不起作用
版本: 2022.1.1
环境: MacBook Pro M1
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/56111765/172090400-12e676bd-741b-499b-8c12-c25fb61055fd.png">

**Comment by YiiGuxing** [comment]
由于 Rider 的文档系统与IDEA平台存在一定的差异，导致光标悬浮文档窗口的文档翻译不能正常工作，可以暂时通过快速查看文档的快捷键 `Control + J` 查看翻译的文档。

**Comment by YiiGuxing** [comment]
设置页面的文档翻译开关在 Rider 上已经去除掉了，可以在暂时在这里进行打开或关闭：
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/56111765/172090400-12e676bd-741b-499b-8c12-c25fb61055fd.png">

**Comment by geeksmy** [comment]
在这里使用这个按钮来进行文档翻译, 完全没有作用

**Comment by YiiGuxing** [comment]
> 在这里使用这个按钮来进行文档翻译, 完全没有作用

@geeksmy  是的，所以暂时要通过快速查看文档的快捷键 `Control + J` 查看翻译的文档。
