### ISSUE TITLE
英文代码文档出现部分中文时中英互译不生效

### ISSUE THREAD

**Issue by lmmarisej** [YiiGuxing/TranslationPlugin#1584]
### 问题描述
在存在少量的汉字时，可以将英文文档进行翻译。
<img width="761" alt="image" src="https://user-images.githubusercontent.com/90127719/172317038-d6bc5764-91bb-4dec-a02d-d1aa0dd5f3a1.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/90127719/172317000-2d7c4b4c-89fd-449f-868c-d65e2afec843.png">

**当出现一定数量的汉字时，将不会进行翻译。**
<img width="783" alt="image" src="https://user-images.githubusercontent.com/90127719/172317143-8a5773a2-1fa8-46f5-b36c-c0cdb2bf9540.png">

**Comment by YiiGuxing** [comment]
插件本地无法判断输入是什么放言的，所以只能让翻译服务自己判断，这是翻译服务的行为。
