### ISSUE TITLE
IDEA设置Proxy

### ISSUE THREAD

**Issue by Jav4Boy** [YiiGuxing/TranslationPlugin#159]
设置Proxy后会出现错误
win10/idea2018.1/ShadowsocksR-win-4.9.0
设置选项
![1](https://user-images.githubusercontent.com/37819737/39673633-8028e35c-5172-11e8-8989-c69f30ace0a2.jpg)
错误提示
![2](https://user-images.githubusercontent.com/37819737/39673634-85381228-5172-11e8-95b6-a12cdd2801b0.jpg)

**Comment by Jav4Boy** [comment]
补充一下
如果使用`Auto-detect proxy settings`这个选项就不会出现错误

**Comment by YiiGuxing** [comment]
代理配置与插件无直接关系，如果代理无效可能是代理配置问题。另外，插件内使用的是HTTP请求，且国内默认使用谷歌中国的API，无需代理就可以直接使用的，如果你想使用谷歌原API，可在插件配置页设置。

**Comment by Jav4Boy** [comment]
代理配置没有问题,使用IDEA设置里测试连接测试过.
不过我现在用自动检测代理设置这一选项没有问题.
感谢回复

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/39680929-a8c8c866-51d8-11e8-8179-7ab3e107c2a9.png)

你可以使用“https://translate.google.cn/translate_a/single” 测试。我这边是可以的。

**Comment by Jav4Boy** [comment]
我测试了一下 会出现403错误
使用的是"https://translate.google.cn/translate_a/single"这个网址
![error](https://user-images.githubusercontent.com/37819737/39681034-91aa1a62-51d9-11e8-9b0b-933cfece277d.jpg)

**Comment by YiiGuxing** [comment]
403说明是可以访问的，Read timed out才是无法访问。

**Comment by Jav4Boy** [comment]
👍 谢谢 可以使用
