### ISSUE TITLE
添加单词的词性，名词，形容词等

### ISSUE THREAD

**Issue by wumeixinjiazu** [YiiGuxing/TranslationPlugin#1594]
### 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) ，但仍然没有找到想要的功能。
* [ ] 我已经搜索过与我要提交的功能需求相匹配的问题，但没有找到。

**Comment by YiiGuxing** [comment]
这部分 谷歌、有道 是已经有的，百度的没有，如果需要，请更换翻译引擎。
