### ISSUE TITLE
文档翻译无效

### ISSUE THREAD

**Issue by gzyangfan** [YiiGuxing/TranslationPlugin#1595]
## 问题详情
文档翻译功能不生效，点击图标与快捷键均不生效。
其余功能正常。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
请提供 插件版本、IDE版本等信息，谢谢。

**Comment by gzyangfan** [comment]
插件版本为 3.2.2
IDE版本为 2022.1.2 (Rider)

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月10日 11:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [YiiGuxing/TranslationPlugin] 文档翻译无效 (Issue #1595)


请提供 插件版本、IDE版本等信息，谢谢。

―

**Comment by YiiGuxing** [comment]
Duplicate of #1578.
