### ISSUE TITLE
导入 Translation 要 Checking plugin dependencies

### ISSUE THREAD

**Issue by grehung** [YiiGuxing/TranslationPlugin#1630]
(不知怎么，能流畅访问谷歌，在IDEA里装个插件都加载不出来...)
去官网在线下载了需要的插件，其他插件导入都很顺利，到Translation导入，就要Checking plugin dependencies。教教我咋解决：能流畅访问谷歌，在IDEA里装个插件都加载不出来...

**Comment by YiiGuxing** [comment]
安装插件的时候和能不能访问谷歌是没有关系的，它需要的是能访问jetbrains的服务器，这也是个网络问题，所以请确保你的网络环境能访问jetbrains的网络。
