### ISSUE TITLE
[Feature Request] 希望下一版本能提供设置翻译字体的大小的特性

### ISSUE THREAD

**Issue by pexcn** [YiiGuxing/TranslationPlugin#164]
字体太大了，可能是因为屏幕分辨率太小？(1366 * 768)

![1](https://user-images.githubusercontent.com/4590439/40364473-fed5b2e0-5e04-11e8-8ba4-e168ef3fe8fe.png)
![2](https://user-images.githubusercontent.com/4590439/40364440-f3df46f8-5e04-11e8-9f90-159bf81f3154.png)

**Comment by YiiGuxing** [comment]
是的，我猜测你调整了IDE的基础字体的大小，那会影响插件的字体大小，因为插件的字体大小是基于IDE的基础字体的大小的：
![1](https://user-images.githubusercontent.com/10737066/40372854-26819206-5e18-11e8-8ee3-751ab5cc775f.png)

或许你也可以尝试将原文折叠：

![2](https://user-images.githubusercontent.com/10737066/40373051-a0c0c60e-5e18-11e8-9eaf-63cb270014e0.png)

**Comment by pexcn** [comment]
@YiiGuxing 是的，IDE 的默认字体大小好像是 12, 在 1366 * 768 分辨率的屏幕下显示得太小了，我调整到了 14, 刚刚好。但是翻译字体看起来不像是 14.

**Comment by YiiGuxing** [comment]
插件的默认字体大小为14，但由于基础字体大小从12调到14了，所以插件的字体被自动调大了，大概是18，而翻译的原文和译文的默认大小是18，那被自动调整后就更大了。所以建议不要调整IDE默认字体大小：
![1](https://user-images.githubusercontent.com/10737066/40398095-cb72990e-5e68-11e8-985b-8f90ba09c866.png)

**Comment by pexcn** [comment]
IDE 的默认字体大小在 1366 * 768 分辨率的屏幕下显示得太小了

**Comment by YiiGuxing** [comment]
那你只能将原文折叠了，这样能腾一些空间来。主要是界面上很多文字字体大小都不一样，这就不好处理了。
