### ISSUE TITLE
google翻译失败

### ISSUE THREAD

**Issue by zhangchunxing** [YiiGuxing/TranslationPlugin#165]
## 谷歌翻译失败

- 选择谷歌翻译
- 网络连接超时，请选择网络
- 谷歌翻译不需要代理吧.

## Environment & Stack Trace
- Plugin version: 2.0.3
- IDE version: 2018.1.3
- Operating System and version: win7

**Comment by YiiGuxing** [comment]
我这边是可以翻译的啊。
谷歌翻译并不需要代理，除非你勾选了“使用translate.google.com”的选项。

**Comment by zhangchunxing** [comment]
是的，的确勾选了该选项，现在可以了。
