### ISSUE TITLE
翻译对话框图标不显示

### ISSUE THREAD

**Issue by xiaowine** [YiiGuxing/TranslationPlugin#1667]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本:  3.3.2
- IDE版本: DEA 2022.2 EAP 
- 操作系统版本: Windows 10 

### 启用新的UI后，翻译对话框图标不会显示在操作栏上
是需要什么额外操作还是插件需要改动
![image](https://user-images.githubusercontent.com/68009112/175955942-489737bc-5790-4515-ae67-4b77595cd571.png)

**Comment by YiiGuxing** [comment]
目前还未适配新UI

**Comment by xiaowine** [comment]
> 目前还未适配新UI

请尽快适配
