### ISSUE TITLE
建议翻译结果能否保留注释的格式，这样看起来清爽干净

### ISSUE THREAD

**Issue by sqj8899** [YiiGuxing/TranslationPlugin#169]
/**
                   * Return the ParameterNameDiscoverer to use for resolving method parameter
                   * names if needed.
*/
比如上面这样一个例句，能否建议翻译出来的结果也是这样的格式，现在结果没有排版看起来挺杂的

**Comment by YiiGuxing** [comment]
在新版本[v2.1.0](https://github.com/YiiGuxing/TranslationPlugin/releases/tag/v2.1.0)中已加入保留原文格式的功能，但是是在另外一个新的单独的窗口中：
![image](https://user-images.githubusercontent.com/10737066/43373249-ffa56e70-93da-11e8-8a2d-bf79b9ad713a.png)
![image](https://user-images.githubusercontent.com/10737066/43373267-24ae5f1a-93db-11e8-8973-8353fce562e4.png)

至于原来的两个界面，我后面先试试效果，如果在排版上能接受的话就加一个配置选项吧。

**Comment by YiiGuxing** [comment]
see: commit [`ef25928`](https://github.com/YiiGuxing/TranslationPlugin/commit/ef259281466f6f054d9a42b18cafc08cec9c012c)
