### ISSUE TITLE
添加翻译引擎：华为翻译

### ISSUE THREAD

**Issue by MiracleShadow** [YiiGuxing/TranslationPlugin#1695]
### 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) ，但仍然没有找到想要的功能。
* [x] 我已经搜索过与我要提交的功能需求相匹配的问题，但没有找到。

### 问题描述

希望添加华为翻译可选项
https://translate.huawei.com/

**Comment by artillerymans** [comment]
https://www.deepl.com/translator  这个 DeepL翻译可以添加么

**Comment by YiiGuxing** [comment]
@MiracleShadow 华为翻译可能不会默认集成，在4.0版本之后计划支持插件二次扩展，那时候可以考虑一下。
