### ISSUE TITLE
能否根据光标所在位置，自动提取camel case中当前单词进行取词？

### ISSUE THREAD

**Issue by cycorey** [YiiGuxing/TranslationPlugin#17]
例如： sparkSession
如果光标在a上，自动取spark
如果光标在i上，自动取session。
此外，可以增加一个action，取整个sparkSession。

谢谢:)

**Comment by YiiGuxing** [comment]
其实自动取词已经实现，将在下一版本可用，不过只取整句的，这要感谢你的建议，我会试着添加可自动选单个词的，我就没想到这个。。。  [Change Log](../blob/master/CHANGELOG.md)
