### ISSUE TITLE
网络连接超时，请检查网络连接

### ISSUE THREAD

**Issue by dinggenfeng** [YiiGuxing/TranslationPlugin#171]
1. 选的 google 翻译
![trs_fail_1](https://user-images.githubusercontent.com/25331862/41267837-c230ebda-6e2f-11e8-9ffc-87fdf648d768.png)

2. https://translate.google.cn 可以访问
![trs_fail_2](https://user-images.githubusercontent.com/25331862/41267852-d0a40d46-6e2f-11e8-80d9-9eb6f09242fc.png)

3. File | Settings | Appearance & Behavior | System Settings | HTTP Proxy 选择 No Proxy
![trs_fail_3](https://user-images.githubusercontent.com/25331862/41267874-e3b39938-6e2f-11e8-80d0-3c7435a8b1ee.png)

4. 报: 网络连接超时，请检查网络连接
![trs_fail_0](https://user-images.githubusercontent.com/25331862/41267877-e6ed5198-6e2f-11e8-9ce4-a008da52b925.png)

**Comment by dinggenfeng** [comment]
换成有道，依然还是失败，不应该啊....  报错日志在哪里查看呢？

![trs_fail_4](https://user-images.githubusercontent.com/25331862/41267969-8223a11c-6e30-11e8-8787-350973ac07a5.png)

**Comment by YiiGuxing** [comment]
你贴一下详细信息我看下。

**Comment by dinggenfeng** [comment]
详细的信息指的是日志吗？

**Comment by YiiGuxing** [comment]
是的

**Comment by YiiGuxing** [comment]
你可以尝试随便添加一代理，然后将`translate.google.cn`忽略，最后使用`http://translate.google.cn/translate_a/single`测试，看看能不能访问成功。如下图，如果提示“Problem with connection: Status: 403”即是访问成功。如果还是连接超时的话就是你IDE的问题了。
![image](https://user-images.githubusercontent.com/10737066/41268283-eb52ad58-6e31-11e8-81dd-833e7b0ac792.png)
