### ISSUE TITLE
希望能在翻譯日文時也像中文英文一樣有附加說明

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#175]
希望能在翻譯日文時也像中文英文一樣有附加說明

> 翻譯來源為 中文 英文時

![2018-06-29-08-24-37-2](https://user-images.githubusercontent.com/167966/42066908-0533d296-7b76-11e8-8e01-83432f49c4b5.png)

> 但是翻譯來源為日文時 就沒有附加說明

![2018-06-29-08-25-25-3](https://user-images.githubusercontent.com/167966/42066909-055fb384-7b76-11e8-9428-16db09d60ba1.png)

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/42068228-52a16b86-7b7d-11e8-96cc-ba434a04fe43.png)

**Comment by bluelovers** [comment]
hmm 看樣子 是剛好我試的字 都沒有
