### ISSUE TITLE
进行文档注释时，在使用jsoup输出翻译后文档html之前，将prettyformat设为false

### ISSUE THREAD

**Issue by DragonKnightOfBreeze** [YiiGuxing/TranslationPlugin#1762]
### 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [X] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) ，但仍然没有找到想要的功能。
* [X] 我已经搜索过与我要提交的功能需求相匹配的问题，但没有找到。

### 问题描述

没有设置`translatedDocumentation.outputSettings().prettyPrint(false)`导致翻译后文档注释的definition片段中可能出现不期望的换行

![image](https://user-images.githubusercontent.com/34092666/178291057-205302b9-3468-476b-b7d9-9071a3783d22.png)

### 建议的解决方案

将prettyformat设为false

**Comment by YiiGuxing** [comment]
感谢你的建议，不过你能提供一下`prettyformat`在不同值的差异截图吗？感谢

**Comment by DragonKnightOfBreeze** [comment]
经测试jsoup使用prettyformat=true，pre标签中会出现意外的换行（从而导致文档definiition部分出现意外的换行）


![1657551713890](https://user-images.githubusercontent.com/34092666/178397762-595d7e0a-6729-4f53-aba6-598d750bd961.gif)
