### ISSUE TITLE
2.1.0版本UI出现乱码

### ISSUE THREAD

**Issue by Num426** [YiiGuxing/TranslationPlugin#179]
![issue.png](https://i.loli.net/2018/07/30/5b5e722ce8608.png)

IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by YiiGuxing** [comment]
请检查这里的字体设置，你是不是修改了这个设置，如果是，将其修改为支持中文的字体就行了：
![image](https://user-images.githubusercontent.com/10737066/43375962-ba9849f0-93ea-11e8-92e8-472d79dd7d04.png)

**Comment by Num426** [comment]
看了一下，我目前用的字体是Consolas，改为微软雅黑后问题解决。
但奇怪的是其他地方的中文并未出现这种问题，不是很懂有什么区别😂

**Comment by DoneMr** [comment]
兄弟，你这个解决方式的图片访问不到了

**Comment by YiiGuxing** [comment]
@DoneMr Settings->Appearance & Behavior->Appearance->修改默认字体（需要支持中文的字体）
