### ISSUE TITLE
请问一下，快捷键是否可以自定义？

### ISSUE THREAD

**Issue by Xiecai** [YiiGuxing/TranslationPlugin#180]
目前用 IntelliJ IDEA 2018.2 x64 发现快捷键 Ctrl+Shift+Y 与 Ctrl+Shift+X 并不可用(冲突)。原版本的Alt 1 很好用，可惜也冲突了。是否可自定义一下快捷键？

**Comment by Vixb1122** [comment]
可以自定义的，在设置 - Keymap 里面搜索Translation
![image](https://user-images.githubusercontent.com/17810492/43376799-51038df6-93ef-11e8-9e2f-fe6fe658b767.png)

**Comment by Xiecai** [comment]
谢谢

**Comment by YiiGuxing** [comment]
我都是用鼠标点的，我自己定的快捷键我自己都记不住。。。:joy::joy::joy:

**Comment by Xiecai** [comment]
我给换成 Ctrl+Shift+Y -> Alt + E ，Ctrl+Shift+X -> Alt + D 了。不用快捷键不舒服~
