### ISSUE TITLE
2022.2 新版UI导航栏过高

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#1803]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/29020213/181150635-70df7fb0-e520-43a8-9238-be23647ce971.png">

如图, 顶部区域多出一块空白区域

**Comment by YiiGuxing** [comment]
请问插件和IDE的版本分别是多少？

**Comment by mdddj** [comment]
idea

```bash
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to 欣 孟
Subscription is active until March 19, 2023.
For educational use only.
Runtime version: 17.0.3+7-b469.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 12000M
Cores: 8
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    actionSystem.secondKeystrokeTimeout=2000uiui
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    org.swiftformat.plugin (1.0.1)
    com.tao.getx (3.2.6)
    com.markskelton.one-dark-theme (5.6.0)
    com.github.beansoft.devkit.helper (2022.1.0)
    Dart (222.3345.108)
    io.flutter (69.0.5)
    com.localizely.flutter-intl (1.17.3-2020.3)
    cn.yiiguxing.plugin.translate (3.3.4)

Kotlin: 222-1.7.10-release-334-IJ3345.118
```

tr
3.3.4

要开启新UI
<img width="786" alt="image" src="https://user-images.githubusercontent.com/29020213/181397616-c5422a70-160b-415b-a00e-d491eed2054b.png">

**Comment by YiiGuxing** [comment]
我这边在Windows上是没什么问题的，也不知道是不是只在MacOS上才会出现，手上也没有MacOS调式。。。。请问其他IDE也会出现吗？比如WebStom。

**Comment by YiiGuxing** [comment]
我这边在Windows上是没什么问题的，也不知道是不是只在MacOS上才会出现，手上也没有MacOS调式。。。。请问其他IDE也会出现吗？比如WebStom。

**Comment by mdddj** [comment]
> 我这边在Windows上是没什么问题的，也不知道是不是只在MacOS上才会出现，手上也没有MacOS调式。。。。请问其他IDE也会出现吗？比如WebStom。

webstore 也一样,顶部多处空白区域
<img width="678" alt="image" src="https://user-images.githubusercontent.com/29020213/181402346-b0c38d3a-b4a6-4931-88f5-da5fa062f7f5.png">

**Comment by LiDongYang743** [comment]
电脑 windos 
idea 2022.2  使用新版本的UI发现一个问题，导致体验非常差劲，当运行的文件名称过长时，由于插件会导致右边的最小化、缩放、关闭这几个按钮贴合在一起。
![image](https://user-images.githubusercontent.com/59534637/181562783-b8636f9b-6f83-4eb5-9262-fd71ac9d05e0.png)

**Comment by mdddj** [comment]
> 电脑 windos idea 2022.2 使用新版本的UI发现一个问题，导致体验非常差劲，当运行的文件名称过长时，由于插件会导致右边的最小化、缩放、关闭这几个按钮贴合在一起。 ![image](https://user-images.githubusercontent.com/59534637/181562783-b8636f9b-6f83-4eb5-9262-fd71ac9d05e0.png)

jb的锅

**Comment by YiiGuxing** [comment]
> 电脑 windos idea 2022.2 使用新版本的UI发现一个问题，导致体验非常差劲，当运行的文件名称过长时，由于插件会导致右边的最小化、缩放、关闭这几个按钮贴合在一起。 ![image](https://user-images.githubusercontent.com/59534637/181562783-b8636f9b-6f83-4eb5-9262-fd71ac9d05e0.png)

@LiDongYang743 这和插件没有关系，IDE的行为就是这个样子的，不知道是不是有问题，或许正常行为就是这个样子的。

**Comment by LiDongYang743** [comment]
了解，感谢，这个应该需要jb去修复，按钮太小了，用着很不习惯

**Comment by LiJiaDong0922** [comment]
![image](https://user-images.githubusercontent.com/49577616/191398625-07b0b96a-a2d1-4074-9131-d4e2e0383d0b.png)
我也遇到这问题，
  电脑mac m1
  idea版本2022.2.2，开启了新UI，并且窗口鼠标放在最上方空白那块是拖动不了的
