### ISSUE TITLE
希望能將一般常用語言往上排序

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#181]
例如 
中文 英文 日文 這幾個常見的排在列表前的上方
或者可以自訂排序 / 記憶最近選擇的語言 之類

----

另外 不知道能不能支援 二次翻譯功能

也就是 翻譯出來的 結果 在翻譯一次(預設則為 原翻譯語言)
像 https://www.excite.co.jp/world/chinese/ 這個網站一樣感覺

變成總共顯示 目前文字 > 翻譯結果 > 再翻譯結果 總共三項

----

或者支援 同時翻譯 兩種目標語言

----

![2018-07-30-19-51-01-3](https://user-images.githubusercontent.com/167966/43395789-f15462ac-9431-11e8-8ec1-23f935e15be0.png)

這個頁面希望能有 回到上一次翻譯的 按鈕(雖然現在能透過 按下列表來選擇回去)
不過如果多個 向前的箭頭 感覺比較直觀

----

![2018-07-30-19-57-34-4](https://user-images.githubusercontent.com/167966/43396052-e33f9190-9432-11e8-8c79-7441084fff88.png)

另外希望所有出現的文字都能複製(例如 圖片中 紅框部分的文字 目前沒有複製功能)

**Comment by YiiGuxing** [comment]
非常感谢你的建议，我会酌情处理的。
1. 常用语言优先排序，这个可以有。
2. 音标复制，这个也可以有。
3. 上一次翻译按钮，这个只会在最后两个记录之间切换，感觉意义并不大，而且在页面布局上不好放置这个按钮。所以这个暂不实现。
4. 再翻译这个功能暂不考虑实现。在v2.1.0的版本有相似的功能（点击切换按钮后会反向翻译）：
![image](https://user-images.githubusercontent.com/10737066/43400169-94b702d0-943f-11e8-8186-aec430713483.png)


另外请问你所在的地区是日本吗？建议你将自己的母语设置为插件的主要语言：
![image](https://user-images.githubusercontent.com/10737066/43400497-71f1038a-9440-11e8-89ae-5ac93d298363.png)
插件没有自动将主要语言设置为你所在地区的当地语言吗？（如果没有的话我想这应该是个BUG）

**Comment by bluelovers** [comment]
@YiiGuxing 插件是中文的沒錯 這點沒有 BUG

只是會有經常需要改變翻譯來源 及 目標語言 的需求

---

不過如果點擊 圖片中上方的藍色按鈕 翻譯所選擇的語言就會變成 世界語

![2018-07-31-07-41-41-3](https://user-images.githubusercontent.com/167966/43429310-4d894f7a-9495-11e8-8f8c-bdb8687d8bd7.png)

---

另外 好奇一下 圖片中的藍色按鈕是做什麼的?

因為似乎點擊時 沒有任何變化以及反應

![2018-07-31-07-47-12-4](https://user-images.githubusercontent.com/167966/43429460-293ab9b4-9496-11e8-8339-bbd723252865.png)

**Comment by YiiGuxing** [comment]
see: commit [`53a2b30`](https://github.com/YiiGuxing/TranslationPlugin/commit/53a2b302344a7634ff5d5aab19b0914620207da8), [`f8baad1`](https://github.com/YiiGuxing/TranslationPlugin/commit/f8baad15455cd7915d686d43df6143768a918cb4)
