### ISSUE TITLE
Show Instant Transaction Dialog打开后，有一个按钮显示的是乱码

### ISSUE THREAD

**Issue by zzk0803** [YiiGuxing/TranslationPlugin#183]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)
PluginVersion：2.1
IDE：IDEA 2018.2
如题

**Comment by YiiGuxing** [comment]
另见： #197
