### ISSUE TITLE
android studio 2.3.3版本装不上最新的2.1.0版本的插件

### ISSUE THREAD

**Issue by qweenhool** [YiiGuxing/TranslationPlugin#184]
你好，插件很好用，感谢你的付出，但是android studio 2.3.3版本就装不上最新的2.1.0版本的插件了，提示不兼容，是否只有升级AS版本这一条路呢？

**Comment by YiiGuxing** [comment]
新版本只能在AS 3.0及以上版本安装，AS 3.0以下的版本只能安装老版本的插件。
