### ISSUE TITLE
(其他) 简繁转换小插件

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#185]
用 liveplugin 弄了個簡繁轉換的插件
https://gist.github.com/bluelovers/cfa87b159025ec2f3cb8a6d7c3548959

由於轉換表仍然還在更新 以及 除錯中
所以沒做成獨立插件

雖然這與 翻譯插件 是不同東西
但我想有些人可能也會需要用到這個

**Comment by YiiGuxing** [comment]
建议做成独立的插件，这样使用起来就方便多了。至于转换表可以慢慢更新的。

**Comment by bluelovers** [comment]
更新頻率最近有點高
https://github.com/bluelovers/cjk-convert/commits/master/build/zh/convert

等穩定一點之後 在弄成獨立插件XD

**Comment by bluelovers** [comment]
@YiiGuxing 想借問一下 你知道 要如何 讓 搜尋 的輸入框 也支援 右鍵選單嗎?

**Comment by YiiGuxing** [comment]
是右键菜单吗？如果是，可以试试`setComponentPopupMenu`

**Comment by bluelovers** [comment]
看起來這各作法 還須要先取得搜尋框的物件才行QQ
(覺得idea的搜尋框不能無腦右鍵真是煩人XD)

話說 獨立插件已經參考了你的代碼做出來了
https://github.com/bluelovers/idea-cjk-conv
