### ISSUE TITLE
在 idea 182.3911.36 編輯器內右鍵選單消失

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#188]
## Description

在 idea 182.3911.36 編輯器內右鍵選單消失

![2018-08-12-00-34-29-13](https://user-images.githubusercontent.com/167966/43993955-82f30c2e-9dc7-11e8-9952-8a419d2373e4.png)

------

但是 工具列 圖示 依然存在

rename 內 似乎 `翻譯並取代` 這個選項消失

![2018-08-12-00-36-37-14](https://user-images.githubusercontent.com/167966/43993977-e48bc782-9dc7-11e8-8136-368c88a7d25b.png)

run 的 output 內依然存在

![2018-08-12-00-38-38-16](https://user-images.githubusercontent.com/167966/43993993-1f2f5a8e-9dc8-11e8-961f-cbec2e096226.png)

> 其他我已經想不起來有那裡可以檢查了

---

另外就是 上次增加的功能 是不是沒有推送到 plugins.jetbrains
還是只是還在審核?

## Environment & Stack Trace
- Plugin version: 2.1.0
- IDE version: 182.3911.36
- Operating System and version: windows 10
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
1. 请确保光标左右两侧的任何一侧或者选择的文本存在有效字符（中文、英文等字符）
2. 请确保插件的编辑器右键菜单项没有被删除

另外，新内容并未发布。

**Comment by bluelovers** [comment]
hmm 看樣子 是發生了不知道什麼狀況 導致選單被更改

reset toolbar and menu 之後 就看見了
