### ISSUE TITLE
翻译文档 功能在Android studio 上不可用，IDEA就可以。同为 M1 mac上。

### ISSUE THREAD

**Issue by can-eat-a-fish** [YiiGuxing/TranslationPlugin#1881]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing `[ ]` with `[x]`*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version: 

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.xiuyukeji.plugin.translation (1.0.3), com.robohorse.robopojogenerator (2.3.6), GsonFormatPlus (1.6.1), com.huangmb.idea (1.1), org.intellij.plugins.markdown (212.5457.16), Dart (212.5744), com.thoughtworks.gauge (212.4746.52), io.flutter (68.1.2), cn.yiiguxing.plugin.translate (3.3-203u212.patch.1)

**Comment by YiiGuxing** [comment]
1. 情将插件升级到最新版本
2. 检查文档翻译选项是否已打开，如未打开请打开该选项

**Comment by can-eat-a-fish** [comment]
1、是的已经将插件更新到最新了，并且 Android Studio 也更新了。
2、文档翻译选项是打开的状态


我还 IDEA 和 Android Studio 所有的设置选项一起检查了一下，都是一样的。

&nbsp;Android Studio 的文档翻译功能还是不行

一直提示这个，IDEA就没这个问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 晚上8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 翻译文档 功能在Android studio 上不可用，IDEA就可以。同为 M1 mac上。 (Issue #1881)





  
情将插件升级到最新版本
 
检查文档翻译选项是否已打开，如未打开请打开该选项

**Comment by YiiGuxing** [comment]
那进行文档翻译的时候有IDE有什么提示吗？或者有报错吗？

**Comment by can-eat-a-fish** [comment]
我尝试卸载后，在安装，突然就好了，感谢🙏。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月17日(星期三) 晚上7:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 翻译文档 功能在Android studio 上不可用，IDEA就可以。同为 M1 mac上。 (Issue #1881)





 
那进行文档翻译的时候有IDE有什么提示吗？或者有报错吗？
