### ISSUE TITLE
请问是否考虑过做一个桌面版的类似工具，目前的桌面翻译工具都太low了，这个插件已经接近完美了

### ISSUE THREAD

**Issue by Autumn-one** [YiiGuxing/TranslationPlugin#1896]
### 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) ，但仍然没有找到想要的功能。
* [ ] 我已经搜索过与我要提交的功能需求相匹配的问题，但没有找到。

**Comment by YiiGuxing** [comment]
并没有这方面考虑。。。
