### ISSUE TITLE
当goland使用ssh来链接开发时，插件无法打开

### ISSUE THREAD

**Issue by misstt123** [YiiGuxing/TranslationPlugin#1897]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing `[ ]` with `[x]`*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
请在本地端安装和和使用插件
