### ISSUE TITLE
自动检查语言不正确

### ISSUE THREAD

**Issue by zonghaishang** [YiiGuxing/TranslationPlugin#191]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
点击插件右上方红色按钮
![image](https://user-images.githubusercontent.com/15549777/44339319-7c851d80-a4b3-11e8-8edc-d3141817e2af.png)

- What happened.
![image](https://user-images.githubusercontent.com/15549777/44339298-6b3c1100-a4b3-11e8-94e8-5af76ad38040.png)
- What you think the correct behavior should be.
期望自动英文到中文

## Environment & Stack Trace
- Plugin version: 3.0.0.181
- IDE version:
![image](https://user-images.githubusercontent.com/15549777/44339357-a2aabd80-a4b3-11e8-832b-0bd67eee8fc5.png)

- Operating System and version:
![image](https://user-images.githubusercontent.com/15549777/44339366-ab9b8f00-a4b3-11e8-8902-7b0de74fbb8d.png)

- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
这里并不会做语言检测，需要手动设置。
