### ISSUE TITLE
翻译文档时内容长度超出限制，已跳过翻译。

### ISSUE THREAD

**Issue by Xxpain** [YiiGuxing/TranslationPlugin#1950]
### 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) ，但仍然没有找到想要的功能。
* [x] 我已经搜索过与我要提交的功能需求相匹配的问题，但没有找到。

### 问题描述

![image](https://user-images.githubusercontent.com/44777634/188368335-6e057af1-5386-4a9a-8289-d5b175e8fb22.png)
翻译一些类时文字过多可能会有这个限制。

### 建议的解决方案

希望可以放开该限制的配置或者有个设置翻译字数max的设置选项

**Comment by YiiGuxing** [comment]
这个限制阈值不是插件定的，是翻译服务商定的，字符数量超过这个阈值就无法翻译，所以插件对这个值的配置是无意义的。

**Comment by lieyanqzu** [comment]
> 这个限制阈值不是插件定的，是翻译服务商定的，字符数量超过这个阈值就无法翻译，所以插件对这个值的配置是无意义的。

能不能考虑通过断行来多次翻译呢？

**Comment by YiiGuxing** [comment]
目前没有这方面的考虑
