### ISSUE TITLE
2.1.1版本无法发音

### ISSUE THREAD

**Issue by fuqile** [YiiGuxing/TranslationPlugin#196]
## Description
当我点击两个发音按钮时，idea底部出现如下进度框，看样子像是网络连接无法问题，本机网络ok
（测试使用百度翻译和有道翻译都存在该问题）
![image](https://user-images.githubusercontent.com/8953582/44920311-2f862e80-ad72-11e8-90b9-79e39f4f34dd.png)
![image](https://user-images.githubusercontent.com/8953582/44920250-02d21700-ad72-11e8-96b2-3e826e674586.png)

## Environment & Stack Trace
- Plugin version:2.1.1
- IDE version:2018.2.2
- Operating System and version:MacOS 10.13.6
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
见： #166

**Comment by fuqile** [comment]
我和#166有点不一样
* 网络OK的，没有配置代理
![image](https://user-images.githubusercontent.com/8953582/44943366-cd700c80-adf7-11e8-87c7-573b0a35a641.png)
* 我不是没法翻译，可以翻译，但是无法读音
* 之前都是好的，一直保持着plugins和idea都是最新版本，不知是否是版本升级导致

**Comment by YiiGuxing** [comment]
TTS用的是谷歌的API，还是网络的问题，这就基本和插件无关了，除非报错。这类问题大多是网络环境的问题。你看看你是不是点了使用google.com的那个选项了，如果没选，那我也办法了，因为网络的问题因素太多了。

**Comment by fuqile** [comment]
嗯，在下拉框选择google翻译，在里面去掉use translate.google.com选项就好了
