### ISSUE TITLE
有道翻译配置为英文时无法查询

### ISSUE THREAD

**Issue by fuqile** [YiiGuxing/TranslationPlugin#197]
## Description
* 当选择有道翻译，并且主要语言设置为英文的时候（虽然基本都是使用的中文），存在如下问题
* 百度翻译不存在该问题

![image](https://user-images.githubusercontent.com/8953582/44920592-f00c1200-ad72-11e8-94e2-7f418110e7b7.png)
![image](https://user-images.githubusercontent.com/8953582/44920607-fa2e1080-ad72-11e8-9154-9a32a09c2d95.png)

## Environment & Stack Trace
- Plugin version:2.1.1
- IDE version:2018.2.2
- Operating System and version:MacOS 10.13.6
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
这是有道的问题，它应该是不支持同语言之间的翻译。
