### ISSUE TITLE
为什么会有两个图标

### ISSUE THREAD

**Issue by huclengyue** [YiiGuxing/TranslationPlugin#199]
为什么会出现两个图标在导航栏，
一个红色一个蓝色
![095503.png](https://i.loli.net/2018/09/05/5b8f37d10c190.png)

**Comment by YiiGuxing** [comment]
功能不一样啊。。。

**Comment by YolineWu** [comment]
> 功能不一样啊。。。

我更新之后也挺纳闷的，为什么会有两个图标！你说功能不同，是什么功能不同，是不是应该说明一下，比如把鼠标放到图标上出现的提示说明一下

**Comment by dinggenfeng** [comment]
感觉用起来都一样啊，有办法隐藏一个吗

**Comment by YiiGuxing** [comment]
@dinggenfeng 可以的：
![image](https://user-images.githubusercontent.com/10737066/56478663-96b04900-64e3-11e9-9abf-2e228a4f49b5.png)

**Comment by appdev** [comment]
升级到AS 3.6 版本,这个方法不能给去掉了

**Comment by YiiGuxing** [comment]
@appdev 这个是AS的BUG。。。
