### ISSUE TITLE
AS2.0 导入两个插件都报错，请解决。

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [YiiGuxing/TranslationPlugin#2]

**Comment by YiiGuxing** [comment]
@houzixiashanxiedaima 请问报什么样的错误？

**Comment by houzixiashanxiedaima** [comment]
houzixiashanxiedaima@foxmail.com
 
发件人： Yii.Guxing
发送时间： 2016-07-08 12:57
收件人： YiiGuxing/TranslationPlugin
抄送： houzixiashanxiedaima; Mention
主题： Re: [YiiGuxing/TranslationPlugin] AS2.0 导入两个插件都报错，请解决。 (#2)
@houzixiashanxiedaima 请问报什么样的错误？

**Comment by YiiGuxing** [comment]
#1
