### ISSUE TITLE
在PHPstorm中朗读功能报错

### ISSUE THREAD

**Issue by rynoway** [YiiGuxing/TranslationPlugin#20]
错误信息：NoClassDefFoundError: javazoom/spi/mpeg/sampled/file/MpegAudioFileReader

**Comment by YiiGuxing** [comment]
@rynoway 请问你的PhpStorm版本号是什么？我这边是可以正常使用。

**Comment by YiiGuxing** [comment]
无法重现

**Comment by YiiGuxing** [comment]
@rynoway 你看看是不是也是这种情况： #24
