### ISSUE TITLE
翻译和Suffix一起的驼峰词会导致翻译失败

### ISSUE THREAD

**Issue by GuanLiPeng** [YiiGuxing/TranslationPlugin#2007]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
单独翻译suffix，效果正常。翻译和suffix一起的驼峰词，会翻译失败，并且经过尝试，有以下几种情况：
1. fileSuffix, File_Suffix, FileSuffix, logFileSuffix, aSuffix [翻译结果："翻译失败: 未知错误"]
2. filesuffix, folderSuffix, logfileSuffix, asuffix [翻译结果："文件后缀"]
3. fileSuffex[翻译结果："文件后缀"]
4. Suffix, suffix, suffex[翻译结果："后缀"]
总结下来就是，当suffix和某些词组成驼峰词时，会有未知错误的情况（例：fileSuffix, logFileSuffix, aSuffix），但是有些驼峰词又不会产生错误（例：logfileSuffix, 错误拼写的fileSuffex, 驼峰格式错误的filesuffix）
我重启Android Studio后，这种现象依然存在

### 环境 & 错误日志
- 插件版本: 3.1.2-201u202
- IDE版本: Android Studio 4.1.3
- 操作系统版本: Windows 10
- 无错误日志和崩溃日志

**Comment by YiiGuxing** [comment]
请问你用的是什么翻译引擎？

**Comment by GuanLiPeng** [comment]
没有对翻译引擎进行额外的设置，应该是使用的默认的
