### ISSUE TITLE
shortcut key custom

### ISSUE THREAD

**Issue by wangshaolei** [YiiGuxing/TranslationPlugin#202]
## Description
how do shortcut key custom

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
Settings > Keymap > Plug-ins > Translation

**Comment by wangshaolei** [comment]
thanks
