### ISSUE TITLE
添加对python基础词汇的翻译及其他

### ISSUE THREAD

**Issue by lhuafmaof** [YiiGuxing/TranslationPlugin#2024]
作者好，感谢辛苦付出！这东西真的好！
简单说下需求：
一、背景：
有翻译需求的，都是英语基础不太好或者对于python不太熟悉的人，编程小白比较多。（在下正是此类人，哈哈）

二、需求细分

- 1、因为函数众多，难于记忆。需要对python的知识查询，例如“lines”，我英语再差也知道是线条的意思。但其实我想知道的是这个单词在python中的语义。需要告诉我，lines是个函数，大致的功能。可能更好的举例是“str“，告诉我是个转换函数，一般用来把数值转换为字符串。如果这点能解决，其实省去的是用户Google和查询函数表的时间，很多时候就是想不起来。用翻译正合适。
- 2、编程基础词汇二次记忆，我看目前已经做了词汇收集，等于路只走了一半。
- 3、基于业务查询，这里才是解决英语不好的问题。某个数据名称不认识，不知道是业务中的那个实体。这点当前已经解决的很好了，不赘述。

三、建议的解决方案（我只是一个产品狗，考虑不周请见谅）
- 1、上述需求2，建议先做个python基础词汇的单词本，支持导入词典软件（金山、百度、有道等）（以xml形式），目前这一块还是空白。后期可以根据统计数据更新输出。可以放个链接在官网，应该可以帮住导流。具体情况如下：

-有道的单词本导入界面 
![image](https://user-images.githubusercontent.com/33141484/192125750-5c708eb3-bdc1-4763-b360-cf9f713126db.png)
![image](https://user-images.githubusercontent.com/33141484/192125791-92674a0f-3b68-4669-9919-dbdc62261fd2.png)
-导入文件数据格式
![image](https://user-images.githubusercontent.com/33141484/192125826-71da8f0c-3296-40e2-9590-ad0fa6e74889.png)
-导入文件（文件无法上传，可能要麻烦作者下载下）
- 这块来源，直接找网上的基础词汇表即可，其他编程语言也可以考虑出。

- 2、针对需求1，建议在翻译界面添加个字段“编程常见含义”，类似下图
![image](https://user-images.githubusercontent.com/33141484/192126040-f99f9a69-11f6-4c1d-8ce6-080b9323b37d.png)

后端考虑多种编程语言，可以根据编程语言分别维护一张语义表，就单词、常见含义两列。业务逻辑，就完全匹配就好。

最后，因为没有数据支撑，考虑难免不周。只是从个人的角度盲猜，需求1、2两点还是值得做的。

**Comment by YiiGuxing** [comment]
感谢您提的需求建议，以下是我分别对您所提出的需求的回复：
1. 本插件要解决的根本需求就只是翻译这一需求，其他功能都是围绕它展开的，而您所提的需求1其实已经超出了本插件所考虑的需求范围之外了。而事实上您所需要的功能IDE本身就已经具备了的，那就是代码文档，代码文档本身就是对代码进行了说明，解释代码的功能、用法等，并不需要额外的插件来提供。当然，如果代码文档是英文的，在绝大多数情况下，本插件是可以将其翻译成您所需要的语言并展示的。
2. 插件的单词本目前是可以进行导入和导出的，只是目前并不能导入其他第三方词典应用的数据：
    ![img](https://user-images.githubusercontent.com/10737066/192146755-fde67179-d226-4421-b8c8-b5be88c78377.gif)

3. 需求3同样也是超出了本插件所考虑的需求范围之外，同样的，它也在代码文档中也得到解决了的。
