### ISSUE TITLE
发音的时候，能否延迟0.5秒，总有前半句听不到/听不清

### ISSUE THREAD

**Issue by TankCoder** [YiiGuxing/TranslationPlugin#2025]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
选中单词后，进行发音，单词的前半部分大概0.5s的读音是听不到或者声音太小听不清的，能否不要做声音渐进的效果，延迟0.5s再进行正常的发音。

拿中文举例，比如读“路由器”三个字， 实际听到的是 “由器”  ，英文就更听不懂了，有点离谱。

相关问题： 
https://github.com/YiiGuxing/TranslationPlugin/issues/937
### 环境 & 错误日志
- 插件版本: 3.3.5 
- IDE版本: IDEA 2022.2.1 
- 操作系统版本: win10

**Comment by YiiGuxing** [comment]
服务商返回的音频内容就是这个样子的，我再怎么延迟也是一样的，我是没办法了这个。。。

**Comment by TankCoder** [comment]
> 

你看这样行不行，天马行空想一下，做个发音前缀词的文本框，默认是“发音”两个字，在【请求发音的接口】里边加上这个前缀，这样子，至少我就能听到英文的发音了。。。

![image](https://user-images.githubusercontent.com/111105563/192273737-4f0c94dc-441a-45ff-be70-7d1cc737104f.png)

**Comment by YiiGuxing** [comment]
。。。。 这肯定是不行的，后面会添加多个TTS引擎，到时候不爽就换TTS引擎吧。。。

**Comment by TankCoder** [comment]
> 。。。。 这肯定是不行的，后面会添加多个TTS引擎，到时候不爽就换TTS引擎吧。。。

哈哈哈  那索性我每次听发音的时候，自己多敲几个字符 ^_^
