### ISSUE TITLE
翻译后无法听阅读语音，总是报链接超时

### ISSUE THREAD

**Issue by Viking-soft** [YiiGuxing/TranslationPlugin#203]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)
TTS Error

java.net.SocketTimeoutException: connect timed out

**Comment by YiiGuxing** [comment]
请另阅： #196
