### ISSUE TITLE
翻译ttk错误

### ISSUE THREAD

**Issue by PerCheung** [YiiGuxing/TranslationPlugin#2054]
### 📝 问题描述

谷歌翻译失效，是谷歌翻译停掉了？

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Licensed to Zhejiang University / Xinyu Liu
订阅有效期至 2023年5月23日。
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16
Non-Bundled Plugins:
    some.awesome (1.14)
    net.vektah.codeglance2 (1.5.5)
    lermitage.intellij.extratci (1.23.0.201)
    com.vermouthx.xcode-theme (1.5.0)
    com.tabnine.TabNine (0.7.25)
    com.intellij.zh (222.202)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.14.0)
    com.mallowigi (73.0.0)
    org.jetbrains.plugins.vue (222.4167.35)
    com.sjhy.plugin.easycode (1.2.6-java.RELEASE)
    izhangzhihao.rainbow.brackets (6.26)
    com.baomidou.plugin.idea.mybatisx (1.5.4)
    cn.yiiguxing.plugin.translate (3.3.5)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

**Comment by xiaobo1997** [comment]
tips:TKK: 更新 TKK 失败，请检查网络连接   
按理说不应该,代理都正常连接的

**Comment by SACMaker** [comment]
我也是,好多人都出现了这个情况

**Comment by xueyazhen** [comment]
我也是

**Comment by yangxing19930210** [comment]
暂时换成可百度

**Comment by li-mubiao** [comment]
同样遇到这个问题

**Comment by YiiGuxing** [comment]
Duplicate of #2051

**Comment by PerCheung** [comment]
我记得以前用谷歌浏览器自带的翻译都不需要用代理，现在试了一下，谷歌浏览器自带的翻译也用不了了，但是进谷歌翻译网页翻译还是能用的，是谷歌本身变了吗？你那边现在还能无代理使用谷歌的页面英翻中吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 翻译ttk错误 (Issue #2054)





 
tips:TKK: 更新 TKK 失败，请检查网络连接
 按理说不应该,代理都正常连接的

**Comment by PerCheung** [comment]
https://translate.googleapis.com 看一下是不是这个不给中国用了，而且代理也不让用，我看都被谷歌浏览器拦截了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 翻译ttk错误 (Issue #2054)





 
tips:TKK: 更新 TKK 失败，请检查网络连接
 按理说不应该,代理都正常连接的

**Comment by YiiGuxing** [comment]
咱们国内的网络环境这么复杂，不是说以前能用，以后就都可以用的，这点觉悟还是要有嘀~

**Comment by YiiGuxing** [comment]
还有说是有梯子是可以使用的，但要选对梯子，还要会配置。

**Comment by PerCheung** [comment]
解决方案：ping update.googleapis.com后，或许ip地址(update.googleapis.com)，修改C:\Windows\System32\drivers\etc\hosts文件，指定ip(update.googleapis.com) translate.googleapis.com，cmd执行ipconfig /flushdns，刷新DNS，即可不翻墙正常访问谷歌翻译。
