### ISSUE TITLE
顯示上的 BUG

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#207]
![2018-09-20-02-41-15-2](https://user-images.githubusercontent.com/167966/45774139-cf9eeb80-bc7e-11e8-8ae9-29a4e8c3cedf.png)

![2018-09-20-02-41-39-3](https://user-images.githubusercontent.com/167966/45774143-d299dc00-bc7e-11e8-8003-897d4244985d.png)

翻譯顯示區無法完整顯示
![2018-09-20-02-41-59-4](https://user-images.githubusercontent.com/167966/45774148-d594cc80-bc7e-11e8-98fb-12369870ee84.png)

**Comment by YiiGuxing** [comment]
气泡是需要在一个Window上才能显示的，如果一个Window尺寸太小以至于气泡无法完整显示，这是应该正常的现象，因为这时候我不能把气泡放在其他Window上显示。所以我并不认为这是一个BUG，另外，Rename窗口是可以修改尺寸的：
![image](https://user-images.githubusercontent.com/10737066/45792782-e286df80-bcc1-11e8-9847-dc882813bfe9.png)

我会为这种情况优化一下的，但不会作为一个BUG处理。

**Comment by YiiGuxing** [comment]
在气泡显示之前，气泡的大小是未知的，因此也就无从优化了。
