### ISSUE TITLE
Replace and insert translation doesn't work al all

### ISSUE THREAD

**Issue by LoSuCuBus** [YiiGuxing/TranslationPlugin#208]
Hi,
thanks for your fantastic job .
Your plugin works well with no crash and is very useful. 
Translation works fine using the context menu or the CTRL+X shortcut, but "Replace and insert translation" doesn't work at all: no entry for that in the context menu, and the CTRL+Y shortcut does nothing.

Tried to change keymap with no success.
Tried to invert CTRL+X and CTRL+Y shortcuts: only "translate" is working

Environment:
- Plugin version: 2.1.1
- PHPStorm 2018.2.3
- Operating System and version: Windows 10 x64 Rs5 (lastest at the moment)

**Comment by YiiGuxing** [comment]
"Replace and insert translation" only works to non-Latin words, only translate to English.

**Comment by LoSuCuBus** [comment]
Oh, I see. 
Is it possible to add this functionnality to other languages ? 
Because I'm a french guy and I often use your plugin to translate from english to french and reverse. 
It could be a great help for me.
Many thanks for that

**Comment by YiiGuxing** [comment]
Not yet, but I will consider implementing it later, I just need some time. If you need a reverse translation, you can try to use this:
![image](https://user-images.githubusercontent.com/10737066/45819142-358a8200-bd16-11e8-9ffa-95c18deb3a1f.png)

**Comment by YiiGuxing** [comment]
Feel free to re-open it or raise a new one if you have any issue.
