### ISSUE TITLE
支持网络代理

### ISSUE THREAD

**Issue by leexusky** [YiiGuxing/TranslationPlugin#21]
你好，我用公司的网络无法做查询，怀疑是因为公司的网络需要代理设置。在IDEA中已经设置的代理仍然不起作用。
请问是否没有网络代理这部分功能？后续能否添加？

**Comment by YiiGuxing** [comment]
@leexusky 目前并不支持网络代理，有时间我加上吧。

**Comment by leexusky** [comment]
多谢多谢~这个需求在很多公司还是有的

**Comment by YiiGuxing** [comment]
@leexusky 网络代理已经实现，详见: [`commit 460c5d3(Http请求优化，支持代理)`](https://github.com/YiiGuxing/TranslationPlugin/commit/460c5d3f59925fc722472aed04c8b5018ecb7291)。但是并没有打包，如果你需要包的话，可以自己下载代码编译一个，代码在[`v1.3分支`](https://github.com/YiiGuxing/TranslationPlugin/tree/v1.3)。

**Comment by YiiGuxing** [comment]
@leexusky 支持网络代理的新版本v1.3.1已经正式发布，你可以更新试一下。

**Comment by leexusky** [comment]
经测试可用，感谢~~
