### ISSUE TITLE
谷歌翻译 .com域名 国内连接不上了

### ISSUE THREAD

**Issue by daocr** [YiiGuxing/TranslationPlugin#210]
https://translate.google.com/  这个域名，国内已经连接不上了，需要使用 https://translate.google.cn/ 这个域名才可以~

**Comment by YiiGuxing** [comment]
请在设置里取消勾选“使用translatte.google.com”.

**Comment by daocr** [comment]
我取消勾选后，还是不行~ 提示 google translate  network error

**Comment by YiiGuxing** [comment]
见： #166
