### ISSUE TITLE
谷歌翻译网络错误的解决办法

### ISSUE THREAD

**Issue by YiiGuxing** [YiiGuxing/TranslationPlugin#2115]
> _感谢 @zhangkaiqiu 在 https://github.com/YiiGuxing/TranslationPlugin/issues/2051#issuecomment-1261880391 中提供的解决办法！_

## 问题原因
疑是谷歌关停了国内的翻译服务，导致相关网站和API无法使用。

## 解决办法
可以通过修改 hosts 文件以暂时解决此问题，恢复谷歌翻译和语音朗读功能的正常使用：

### 1. 复制以下内容
```
203.208.40.66  translate.googleapis.com
``` 

### 2. 修改 hosts 文件
hosts 文件位置：
- Windows：`C:\Windows\System32\drivers\etc\hosts`
- Linux/Mac OS：`/etc/hosts`

修改方法——将第1步复制的内容追加到 hosts 文件的末尾：
- Windows：使用记事本编辑（记事本程序须以管理员身份运行）
- Linux/Mac OS：`sudo vi /etc/hosts`

### 3. 刷新 DNS
一般情况下修改 hosts 文件后会直接生效，如未生效可尝试下面的办法刷新 DNS：
- Windows：在 CMD 窗口执行 `ipconfig /flushdns` 命令
- Linux：在终端执行 `sudo nscd restart` 命令
- Mac OS：在终端执行 `sudo killall -HUP mDNSResponder` 命令

> Tips： 上述方法仍无效可以尝试重启机器。

**Comment by xsdream** [comment]
perfect！

**Comment by yuan9Java** [comment]
good！

**Comment by ronghaoZhang0228** [comment]
6666

**Comment by blueair5** [comment]
nice , 重启解决

**Comment by haoww** [comment]
大佬👍

**Comment by vaspike** [comment]
完美

**Comment by 960208781** [comment]
very nice 👍👍

**Comment by LannYuu** [comment]
2022-10-09 15:54:17 有效 👍👍

**Comment by shenhuxi92** [comment]
补充一下，如果设置了代理，但是还是无法使用，比如V2rayN，需要在路由规则那里将 translate.googleapis.com 设置为通过代理进行连接，目前V2rayN的默认路由规则中该网址是直连的，没有通过代理。

**Comment by blueair5** [comment]
在前几天第一次设置 hosts 文件后，还是可以用的，但是现在必须走代理了，不走代理会报 TKK 错误。

**Comment by YiiGuxing** [comment]
> 在前几天第一次设置 hosts 文件后，还是可以用的，但是现在必须走代理了，不走代理会报 TKK 错误。

@blueair5 还可以用的啊

**Comment by blueair5** [comment]
> > 在前几天第一次设置 hosts 文件后，还是可以用的，但是现在必须走代理了，不走代理会报 TKK 错误。
> 
> @blueair5 还可以用的啊

我的不知道为什么，不能用了，走代理才行。第一次配置以后能用，后面就不行了。:cry:

**Comment by caiqichang** [comment]
知乎上找的

上海/电信：
180.163.150.34
180.163.151.34
180.163.151.162
180.163.150.162
180.163.150.33

上海/移动：
120.253.253.226
120.253.253.98
120.253.250.226
120.253.255.162
120.253.253.34
120.253.255.98
120.253.253.162
120.253.255.34

上海/Google数据中心/电信：
203.208.40.98
203.208.41.98
203.208.41.66
203.208.41.34
203.208.40.66
203.208.41.97
203.208.40.97
203.208.40.65
203.208.40.34

北京/电信：
220.181.174.226
220.181.174.34
220.181.174.98
220.181.174.162
220.181.174.33
203.208.50.162

北京/Google数据中心/电信：
203.208.43.66
203.208.39.194
203.208.50.66
203.208.43.98
203.208.50.34
203.208.39.226

北京/联通：
114.250.64.34
114.250.70.34
114.250.63.34
114.250.66.34
114.250.65.34

广州/电信：
113.108.239.226
58.63.233.98
113.108.239.162

广州/移动：
120.241.147.162
120.232.181.162

广州/联通：
58.254.137.226

**Comment by lizwwww** [comment]
good！👍🏻

**Comment by chujiu** [comment]
nice

**Comment by YiiGuxing** [comment]
> ![image](https://user-images.githubusercontent.com/31870384/196578068-f846b6bc-305b-46eb-920e-58221d401e41.png)今天遇到了新的问题，不知道是什么原因。可以翻译，但是不能朗读

奇怪了，我这可以的啊。你那是不是有毒哦？

**Comment by Vicent9920** [comment]
有道翻译不充钱用不了，谷歌翻译设置IP也不行，还是用百度了。。。。。。。

**Comment by LsG217** [comment]
> > ![图片](https://user-images.githubusercontent.com/31870384/196578068-f846b6bc-305b-46eb-920e-58221d401e41.png)遇到今天的新问题，不知道是什么原因。可以翻译，但是不能朗读
> 
> 算了，我的啊。

我也出现了这个情况  不知道咋回事

**Comment by YiiGuxing** [comment]
> > > ![图片](https://user-images.githubusercontent.com/31870384/196578068-f846b6bc-305b-46eb-920e-58221d401e41.png)遇到今天的新问题，不知道是什么原因。可以翻译，但是不能朗读
> > 
> > 算了，我的啊。
> 
> 我也出现了这个情况  不知道咋回事

换个IP试试呢？

**Comment by YiiGuxing** [comment]
使用这个方法还是有很大的概率出现翻译失败的情况啊，朋友们。TTS 不支持的语言也是属于这种情况。

**Comment by xsdream** [comment]
> 使用这个方法还是有很大的概率出现翻译失败的情况啊，朋友们。TTS 不支持的语言也是属于这种情况。
之前稳定的，前天开始这样的

**Comment by LsG217** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/31870384/196578068-f846b6bc-305b-46eb-920e-58221d401e41.png)遇到今天的新问题，不知道是什么原因。可以翻译，但是不能朗读
> > > 
> > > 
> > > 算了，我的啊。
> > 
> > 
> > 我自己也出现了
> 
> @LsG217换个IP试试呢？

![image](https://user-images.githubusercontent.com/112554366/197329695-49218ed1-fcb7-4ec2-8c35-900f4e4a3107.png)
换ip就是这样  为啥有梯子也还是会出现翻译失败

**Comment by YiiGuxing** [comment]
朋友们，现在貌似彻底无法使用了，修改Hosts现在都返回NotFound了，应该已经是彻底停掉了。所以大家要么就得使用梯子，要么使用其他的翻译引擎了。至于TTS，我看看国内的有没有可以免费使用的。

**Comment by Frozen-Knife** [comment]
用了梯子全局代理 也没戏了

**Comment by YiiGuxing** [comment]
> 用了梯子全局代理 也没戏了

@Frozen-Knife 梯子是可以的，配置的问题。

**Comment by YiiGuxing** [comment]
找到了一个可用的IP，但不知道它能坚持多久：
```
172.253.124.90 translate.googleapis.com
```

**Comment by vaspike** [comment]
> 找到了一个可用的IP，但不知道它能坚持多久：
> 
> ```
> 172.253.124.90 translate.googleapis.com
> ```

是可以用的,谢谢~

**Comment by yifachen521** [comment]
> 找到了可用的 IP，但不知道能有多坚持：
> 
> ```
> 172.253.124.90 translate.googleapis.com
> ```

可以用，泪目

**Comment by YiiGuxing** [comment]
新开了一个帖子：#2315 ，以后会在上面维护更新可以使用的IP，欢迎大家去点赞/吐槽/讨论。
