### ISSUE TITLE
ctrl+shift+x 无效 

### ISSUE THREAD

**Issue by mzzsfy** [YiiGuxing/TranslationPlugin#212]
手误全选一个文档,(约7k),
按下ctrl+shift+x,
插件报错,然后插件ctrl+shift+失效,
更换快捷键仍然不能生效,
卸载插件并重新安装,
仍然无效

Translation : 2.1.1
idea : IntelliJ IDEA 2017.3.4
win7系统

**Comment by YiiGuxing** [comment]
另外，替换操作可用的状态是：当前光标周围有汉字，或者选中的文本是有汉字。

**Comment by mzzsfy** [comment]
我已经这样做了,但是仍然无效,另外ctrl+shift+y功能可以正常使用

**Comment by mzzsfy** [comment]
另外:当我按下ctrl+shift+X时,"C:\Users{YOUR_USER_NAME}\{YOUR_IDE_DIR}\config\options\yiiguxing.translation.xml"中histories节点内容会改变.说明按下组合键仍然触发插件?

**Comment by YiiGuxing** [comment]
试一下在中文上使用，要有中文字条才能用的

**Comment by mzzsfy** [comment]
感谢,再次重装插件后恢复正常了
