### ISSUE TITLE
建议增加腾讯翻译的配置项

### ISSUE THREAD

**Issue by BraveHL** [YiiGuxing/TranslationPlugin#2136]
### 需求/建议描述

建议增加腾讯翻译的配置项，主要是谷歌现在也被关了，虽然有别的技巧来绕过，但相信也不是长久之计，还是老老实实把国内的都用起来，我觉得更好

### 建议的解决方案

建议增加腾讯翻译的配置项，他也有免费服务，每月500万字符免费额度

**Comment by BraveHL** [comment]
主要是谷歌现在也被关了，虽然有别的技巧来绕过，但相信也不是长久之计，还是老老实实把国内的都用起来，我觉得更好

**Comment by BraveHL** [comment]
翻译工具，百家争鸣，相信对用户来说更有利，哪怕此刻腾讯翻译用的人少

**Comment by YiiGuxing** [comment]
这个之前就已经有朋友提交过PR了的，只是评估过后还是移除了，具体的原因请另参阅 #768
