### ISSUE TITLE
集成微软翻译引擎

### ISSUE THREAD

**Issue by FoundAdd** [YiiGuxing/TranslationPlugin#2157]
### 需求/建议描述

谷歌翻译目前虽然可以通过修改host文件使用api，但是随时可能会再次被墙。

### 建议的解决方案

是否可以增加必应翻译等其他更多的引擎用于替代呢

**Comment by YiiGuxing** [comment]
有计划的，有太多的计划了🙃

**Comment by 3473664996** [comment]
> 有计划的，有太多的计划了🙃

有计划就会 Google 翻译越来越 难访问了

**Comment by chanjie** [comment]
> 有计划的，有太多的计划了🙃

赶紧加上必应，谷歌太验证的，国内的都是收费的

**Comment by YiiGuxing** [comment]
> > 有计划的，有太多的计划了🙃
> 
> 赶紧加上必应，谷歌太验证的，国内的都是收费的

大哥！我现在最需要的就是时间啊！！！

**Comment by starSmallDream** [comment]
期待

**Comment by starSmallDream** [comment]
感觉必应都比百度翻译强，是指翻译后的内容和语义性

**Comment by wilinz** [comment]
我已添加Edge web翻译引擎，晚点我提个pr

**Comment by YiiGuxing** [comment]
> 我已添加Edge web翻译引擎，晚点我提个pr

@wilinz  啊~我已经在实现这个功能了。。。
![image](https://user-images.githubusercontent.com/10737066/203112573-cdb7882c-2491-4bf4-9d3f-5d1fb3c0e2c9.png)

**Comment by wilinz** [comment]
我就写了几个小时

**Comment by wilinz** [comment]
要不你看看代码，是不是和你添加的是同一个翻译引擎

**Comment by YiiGuxing** [comment]
@wilinz 
是同一个的： https://github.com/YiiGuxing/TranslationPlugin/tree/v3.4/dev/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/microsoft
只不过我没想到它的token是JWT的，我对token的过期时间没有正确地处理，感谢你的PR，至少它没有完全浪费掉，它修正了我对token过期时间的处理，哈哈😁😁😁

**Comment by wilinz** [comment]
@YiiGuxing 好的

**Comment by YiiGuxing** [comment]
> @YiiGuxing 还有要不要把微软翻译作为默认引擎

已设为默认的了

**Comment by wilinz** [comment]
嗯好

**Comment by xkcyy** [comment]
> > @YiiGuxing 还有要不要把微软翻译作为默认引擎
> 
> 已设为默认的了

![image](https://user-images.githubusercontent.com/18730742/203578015-f3081a00-20b6-4cfe-9c76-b6c26abf9425.png)
我这里翻译显示的是英文，不能切换到中文

**Comment by YiiGuxing** [comment]
> > > @YiiGuxing 还有要不要把微软翻译作为默认引擎
> > 
> > 已设为默认的了
> 
> ![image](https://user-images.githubusercontent.com/18730742/203578015-f3081a00-20b6-4cfe-9c76-b6c26abf9425.png)
> 我这里翻译显示的是英文，不能切换到中文

还没有写完呢。。。

**Comment by YiiGuxing** [comment]
commits: https://github.com/YiiGuxing/TranslationPlugin/compare/f38b621...b1c7733

**Comment by wilinz** [comment]
> 兄弟们，终于开发好了: [f38b621...b1c7733](https://github.com/YiiGuxing/TranslationPlugin/compare/f38b621...b1c7733) ，希望它能一直用。 微软翻译一次可以翻译50000字符，对于大文档翻译真的太好用了。。。

啥时候发版

**Comment by YiiGuxing** [comment]
> > 兄弟们，终于开发好了: [f38b621...b1c7733](https://github.com/YiiGuxing/TranslationPlugin/compare/f38b621...b1c7733) ，希望它能一直用。 微软翻译一次可以翻译50000字符，对于大文档翻译真的太好用了。。。
> 
> 啥时候发版

快了，还在处理一些边边角角
