### ISSUE TITLE
支持用户自定义谷歌翻译Host设置

### ISSUE THREAD

**Issue by caiqichang** [YiiGuxing/TranslationPlugin#2165]
### 需求/建议描述

支持用户自定义谷歌翻译Host设置，方便没有梯子，不会改host的用户

### 建议的解决方案

原来的请求
```
GET https://translate.googleapis.com/translate_a/single...(省略)
```
用户自定义Host (例如：203.208.39.194)后的请求
```
GET https://203.208.39.194/translate_a/single...(省略)
Host: translate.googleapis.com
```

也就是用用户自定义的IP替换原来的域名，增加请求头`Host:  translate.googleapis.com`，还需要忽略SSL域名校验

**Comment by YiiGuxing** [comment]
此方式并不可行，得到的响会是404。

**Comment by caiqichang** [comment]
@YiiGuxing 不知道是否和tk参数有关，不带tk是可行的
![QQ截图20221010231137](https://user-images.githubusercontent.com/20108732/194898809-427830f3-d1a0-42ce-b6d4-232f0e43e045.jpg)
