### ISSUE TITLE
Question: Can this be used as engine for Android Studio Translation Editor?

### ISSUE THREAD

**Issue by paulvi** [YiiGuxing/TranslationPlugin#218]
Can this be used as engine for Android Studio Translation Editor?
https://developer.android.google.cn/studio/write/translations-editor

**Comment by YiiGuxing** [comment]
No, because the Translations Editor does not provide any extension points. However, in subsequent versions it is possible to use the "Translate and Replace" action to translate.

**Comment by YiiGuxing** [comment]
commit: https://github.com/YiiGuxing/TranslationPlugin/commit/de14e4a3f07a35eaf77987835d50ba28ea8db593

![img](https://user-images.githubusercontent.com/10737066/51752144-b48f2d00-20f1-11e9-954d-0a15121619dc.gif)

Please follow issue #229 about choosing a language.
