### ISSUE TITLE
有时候音标显示不出来

### ISSUE THREAD

**Issue by sdandroid** [YiiGuxing/TranslationPlugin#22]
![_004](https://cloud.githubusercontent.com/assets/1787737/20085634/64aebbd0-a5a5-11e6-93da-eb51a3e79e37.png)

**Comment by YiiGuxing** [comment]
@sdandroid 你是指音标上的那两个方块吗？这个是字体问题，请问你用的是什么系统？

**Comment by sdandroid** [comment]
@YiiGuxing  debian 界面用的是微软雅黑，但不是每次都这样。

**Comment by YiiGuxing** [comment]
那这应该就是系统字体的问题了，我指定的就是微软雅黑字体，如果没有这个字体的话会用默认字体的，在Mac上就是这样，在Mac和windows上是没问题的。。。

**Comment by sdandroid** [comment]
不是每次都有问题，我用的是 IDEA EAP 不知道和版本有没有关系，我自己再看看。

**Comment by sdandroid** [comment]
知道问题了，我系统装的是 Microsoft YaHei UI 。

**Comment by NatsuSai** [comment]
能够说一下解决过程么，同样的问题，用的是IntelliJ IDEA

**Comment by sdandroid** [comment]
@YiiGuxing @NatsuSai  今天刚好弄了下，StyleConstants.setFontFamily(ATTR_EXPLAIN, "Source Code Pro"); 这个设置成为微软雅黑就有问题，但是在插件开发模式没问题，把音标设置成其他的字体就好了，应该是系统环境问题。

**Comment by YiiGuxing** [comment]
@sdandroid @NatsuSai 这个是和系统的字体环境有关的，可以尝试在系统里安装Microsoft YaHei字体（插件在代码上默认指定的字体），有时间我再看看能不能从代码上解决一下吧，自己打包太坑了。
