### ISSUE TITLE
linux 发行版 乱码问题  In the deepin distribution, there will be Chinese garbled code to solve!

### ISSUE THREAD

**Issue by fwq418233640** [YiiGuxing/TranslationPlugin#220]
在 deepin 发行版中  会出现中文乱码 求解决！

In the deepin distribution, there will be Chinese garbled code to solve!

**Comment by YiiGuxing** [comment]
see: [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq)
see: #179
