### ISSUE TITLE
Keep the last selected language

### ISSUE THREAD

**Issue by ivolkoff** [YiiGuxing/TranslationPlugin#2205]
### Feature/Enhancement Description

When clicking on the translation, I want the last selected language to be saved, and not the default

### Proposed Solution

Keep the last selected language

**Comment by YiiGuxing** [comment]
This feature already exists, you can find the configuration options you want by searching for "last used language" in the settings dialog:

![image](https://user-images.githubusercontent.com/10737066/195482623-7561b436-c786-4385-bc08-b0cdd9682952.png)

**Comment by ivolkoff** [comment]
thanks a lot, it's amazing
