### ISSUE TITLE
linux 中文乱码问题

### ISSUE THREAD

**Issue by fwq418233640** [YiiGuxing/TranslationPlugin#221]
## Description
![Uploading image.png…]()
deepin 发行版本中，在 IDEA中使用  会出现这个问题

## Environment & Stack Trace
- Plugin version:2.2
- IDE version:2018.2
- Operating System and version:deepin 15.8

**Comment by YiiGuxing** [comment]
#220 ?
没弄好？
是哪个地方乱码？你发的图片看不到。

**Comment by YiiGuxing** [comment]
这应该要设置主要字体：
![image](https://user-images.githubusercontent.com/10737066/48683708-69d0d080-ebe9-11e8-8404-04a3f341bab2.png)

那在设置页面的中文也是乱码的吗？

**Comment by fwq418233640** [comment]
请问，这个是在哪里设置的？

**Comment by fwq418233640** [comment]
![image](https://github.com/fwq418233640/books/blob/master/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20181119143122.png)

似乎这里也是乱码。。。

**Comment by YiiGuxing** [comment]
请另阅： #179

**Comment by fwq418233640** [comment]
似乎更换了微软雅黑解决了一部分问题，但还有一些问题。。
请看下面这张图
![image](https://github.com/fwq418233640/books/blob/master/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20181119145337.png)

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/43375962-ba9849f0-93ea-11e8-92e8-472d79dd7d04.png)
这里的字体也换一下试试

**Comment by fwq418233640** [comment]
非常感谢，基本上解决了  还有一小部分问题，但并不影响使用。另外 我在idea 的 idea.vmoptions 文件 和idea64.vmoptions 又加入了-Dfile.encoding=UTF-8 参数，重启了一下idea
