### ISSUE TITLE
词组翻译加入中划线的格式

### ISSUE THREAD

**Issue by SvenZhao** [YiiGuxing/TranslationPlugin#223]
词组翻译能否加上中划线的格式 或者可配置显示格式
举例：
“随机名称”=》random-name

现在只有下面四种格式
randomName RandomName random_name random name

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/51510764-63edaa80-1e39-11e9-8d8e-f86fd5023765.png)

**Comment by SvenZhao** [comment]
nice  cool!!
