### ISSUE TITLE
网络配置功能

### ISSUE THREAD

**Issue by FeiTlng** [YiiGuxing/TranslationPlugin#2235]
### 需求/建议描述

能否增加网络配置功能

### 建议的解决方案

类似本次谷歌事件，能否考虑新增网络配置的功能，单独对每个引擎设置走不同的网络呢？

**Comment by YiiGuxing** [comment]
是有考虑过，但是本次谷歌事件实在是太特殊了，它并不是修改到其他节点（如：香港、日本等）就可以了，它是所有节点都不能无梯子访问。就只能通过梯子或修改Hosts这样绕过访问，虽然可通过技术手段在插件上添加相关配置的功能来实现和修改Hosts一样的效果，但是呢，在插件中配置和在系统中配置，都一样是需要配置，所以我认为没有必要在插件上实现这个功能，增加插件的负担。
