### ISSUE TITLE
我想翻译的时候自动忽略注释部分...

### ISSUE THREAD

**Issue by shihp** [YiiGuxing/TranslationPlugin#226]
## 我想翻译的时候自动忽略注释部分
比如: //
或者 /** 

看到可以用正则忽略掉.但是试了几次都没有成功(类似于那位大哥的问题 #130)

## Environment & Stack Trace
- Plugin version: 2.2
- IDE version: IntelliJ IDEA 2018.3.1 (Ultimate Edition)
- Operating System and version: mac 10.14
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
是不是你的正则表达式不正确？
![image](https://user-images.githubusercontent.com/10737066/50414230-513e8080-084f-11e9-88d6-6e51e42342bf.png)
![image](https://user-images.githubusercontent.com/10737066/50414241-661b1400-084f-11e9-8c55-c7d6cb339828.png)
![image](https://user-images.githubusercontent.com/10737066/50414248-716e3f80-084f-11e9-807e-afa8bdc7d524.png)

**Comment by YiiGuxing** [comment]
翻译替换操作并不会忽略任何内容
