### ISSUE TITLE
The translate and replace would be nice to allow to chose the language

### ISSUE THREAD

**Issue by BadChoice** [YiiGuxing/TranslationPlugin#229]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
Select text and do translate and replace

- What happened.
It translated to my computer language

- What you think the correct behavior should be.
It should ask the language to translate to

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/52547291-a3d4fb80-2e01-11e9-896a-b50fb4cf71ff.png)
