### ISSUE TITLE
谷歌翻译文档失败: Not Found

### ISSUE THREAD

**Issue by zhangzhiyong-ay** [YiiGuxing/TranslationPlugin#2296]
### 📝 问题描述

使用谷歌插件翻译提示 翻译文档失败: Not Found
![image](https://user-images.githubusercontent.com/33783172/197345924-e4568e18-dd02-4ad0-b2cc-8667b9b11255.png)

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to cat method
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 16
Non-Bundled Plugins:
    com.intellij.zh (222.202)
    ink.organics.pojo2json (1.2.5)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    String Manipulation (9.5.1)
    MavenRunHelper (4.21.222.2964.0)
    cn.cloud.auto.restful.tool (1.4.5)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    zielu.gittoolbox (212.9.9)
    com.obroom.plugin.toolset (2022.9.1)
    JRebelPlugin (2022.4.0)
    jr-mp-ide-idea (0.0.5)
    MyBatisLog (2022.7.9)
    com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (3.1.1)
    cn.yiiguxing.plugin.translate (3.3.5)

Kotlin: 222-1.7.20-release-201-IJ4167.29
```

**Comment by YiiGuxing** [comment]
谷歌已经关停了中国大陆的翻译服务，所以插件中的谷歌翻译引擎也不可用了。语音朗读也是基于谷歌翻译服务的，所以也不可用。如果您有梯子，您可以通过梯子正常使用，如果没有，则只能使用其他翻译引擎了。

**Comment by MineYuanlu** [comment]
> 谷歌已经关停了中国大陆的翻译服务，所以插件中的谷歌翻译引擎也不可用了。语音朗读也是基于谷歌翻译服务的，所以也不可用。如果您有梯子，您可以通过梯子正常使用，如果没有，则只能使用其他翻译引擎了。

我有梯子也用不了，怎么配置梯子呀？系统代理不行吗

**Comment by wangxing-wq** [comment]
> > 谷歌已经关停了中国大陆的翻译服务，所以插件中的谷歌翻译引擎也不可用了。语音朗读也是基于谷歌翻译服务的，所以也不可用。如果您有梯子，您可以通过梯子正常使用，如果没有，则只能使用其他翻译引擎了。
> 
> 我有梯子也用不了，怎么配置梯子呀？系统代理不行吗

我也是这个情况,我自己开梯子网页可以,也Ping的通,但是插件用不了

**Comment by LsG217** [comment]
> > > 谷歌已经关停了中国大陆的翻译服务，所以插件中的谷歌翻译引擎也不可用了。语音朗读也是基于谷歌翻译服务的，所以也不可用。如果您有梯子，您可以通过梯子正常使用，如果没有，则只能使用其他翻译引擎了。
> > 
> > 
> > 我有梯子也用不了，怎么配置梯子呀？系统代理不行吗
> 
> 我也是这个情况,我自己开梯子网页可以,也Ping的通,但是插件用不了

我也想知道，怎么设置都不对，都提示网络链接失败

**Comment by wangxing-wq** [comment]
> 谷歌已经关停了中国大陆的翻译服务，所以插件中的谷歌翻译引擎也不可用了。语音朗读也是基于谷歌翻译服务的，所以也不可用。如果您有梯子，您可以通过梯子正常使用，如果没有，则只能使用其他翻译引擎了。

老哥能看下用梯子也没用的问题吗

**Comment by YiiGuxing** [comment]
梯子没有作用的问题，第一，如果你之前修改了Hosts，那要先把之前添加的Hosts内容删除掉。第二，那就是你梯子的配置问题了，梯子客户端一般是有路由规则的，一些网址（比如国内的）它是不走梯子的，有些才回走，这就是那个规则定的，很有可能是translate.googleapis.com这个地址在规则里它是不走梯子的，所以无效，可以到 #2051 里看看。

**Comment by zhangzhiyong-ay** [comment]
我梯子可用正常访问google翻译，translate.googleapis.com地址也走梯子，IDEA插件翻译出错。可用在idea设置-HTTP代理中，手动设置主机名、端口号为梯子地址后，可用正常使用翻译插件。
![image](https://user-images.githubusercontent.com/33783172/197383387-e92423e8-4a16-41c4-a49c-75afe1fff534.png)

**Comment by wangxing-wq** [comment]
> 梯子没有作用的问题，第一，如果你之前修改了Hosts，那要先把之前添加的Hosts内容删除掉。第二，那就是你梯子的配置问题了，梯子客户端一般是有路由规则的，一些网址（比如国内的）它是不走梯子的，有些才会走，这就是那个规则定的，很有可能是translate.googleapis.com这个地址在规则里它是不走梯子的，所以无效，你需要去修改那个规则，或者让IDE上的网络请求都走梯子，可以到 #2051 里看看。

okok,可以了

**Comment by Sakura0122** [comment]
> 我的梯子可以访问google，translate.googleapis.com梯子，IDEA插件也正常显示地址。可用idea插件在HTTP代理中，手动设置主机使用翻译名，端口设置为梯子地址后，可以正常使用翻译名。 ![图片](https://user-images.githubusercontent.com/33783172/197383387-e92423e8-4a16-41c4-a49c-75afe1fff534.png)

怎么查看梯子使用的端口号呢 我这个梯子貌似没有显示

**Comment by YiiGuxing** [comment]
> 怎么查看梯子使用的端口号呢 我这个梯子貌似没有显示

@Sakura0122 不同的客户端一般都不同，所以你可以根据你所使用的客户端查一下。

**Comment by zhangzhiyong-ay** [comment]
> > 我的梯子可以访问google，translate.googleapis.com梯子，IDEA插件也正常地址。可以在HTTP中的idea，手动设置主机使用翻译名，设置为代理梯子地址后，可以正常使用翻译名。![图片](https://user-images.githubusercontent.com/33783172/197383387-e92423e8-4a16-41c4-a49c-75afe1fff534.png)
> 
> 怎么查看梯子的表情没有显示号呢

windows试试，正常打开梯子软件后，打开IE浏览器，internet选项-连接-局域网设置，代理服务器如果勾选的话，那应该就是代理的端口。仅供参考。
![image](https://user-images.githubusercontent.com/33783172/197383707-bbb94539-ed52-407e-9d5b-933346234f90.png)

**Comment by Sakura0122** [comment]
> > > 我的梯子可以访问google，translate.googleapis.com梯子，IDEA插件也正常地址。可以在HTTP中的idea，手动设置主机使用翻译名，设置为代理梯子地址后，可以正常使用翻译名。![图片](https://user-images.githubusercontent.com/33783172/197383387-e92423e8-4a16-41c4-a49c-75afe1fff534.png)
> > 
> > 
> > 怎么查看梯子的表情没有显示号呢
> 
> windows试试，正常打开梯子软件后，打开IE浏览器，internet选项-连接-局域网设置，代理服务器如果勾选的话，那应该就是代理的端口。仅供参考。 ![image](https://user-images.githubusercontent.com/33783172/197383707-bbb94539-ed52-407e-9d5b-933346234f90.png)

非常感谢 可以正常使用了

**Comment by YiiGuxing** [comment]
修改Hosts方式又找到了一个可用的IP：
```
172.253.124.90 translate.googleapis.com
```
由于这个IP是美国谷歌云的，所以不知道它能坚持多久。

**Comment by yzy-1995** [comment]
我的建议还是搭建梯子更好

**Comment by YiiGuxing** [comment]
谷歌翻译无法使用的问题目前在3.4.0版本中已有了替代方案，下一步的工作目标是TTS的代替方案。

**Comment by wk849411933** [comment]
> 谷歌翻译无法使用的问题目前在3.4.0版本中已有了替代方案，下一步的工作目标是TTS的代替方案。



> 谷歌翻译无法使用的问题目前在3.4.0版本中已有了替代方案，下一步的工作目标是TTS的代替方案。

请问谷歌翻译在3.4.0的替代方案是什么？

**Comment by beike6688** [comment]
如果使用手动代理配置也是有缺点的，就是所有流量都会走代理，这样会浪费比必要的流量，只要写一个PAC脚本就可以轻松解决这个问题，只有使用谷歌翻译时才走代理。脚本如下，亲测有效。

`function FindProxyForURL(url, host) {
    var proxy_domains = [
        "translate.googleapis.com"
    ];

    function isInProxyDomains(host) {
        for (var i = 0; i < proxy_domains.length; i++) {
            if (dnsDomainIs(host, proxy_domains[i])) {
                return true;
            }
        }
        return false;
    }

    if (isPlainHostName(host) || isInNet(host, "192.168.0.0", "255.255.0.0") || isInNet(host, "127.0.0.0", "255.0.0.0") || isInNet(host, "10.0.0.0", "255.0.0.0") || isInNet(host, "172.16.0.0", "255.240.0.0")) {
        return "DIRECT";
    }

    if (isInProxyDomains(host)) {
        return "PROXY 127.0.0.1:7890";
    }

    return "DIRECT";
}`


把上面设置的好的文件放到一个可以通过http服务能够访问到的地方就行，不管是网络上还是本地web服务器都行，只要保证读取到的是上面这段代码就行，不要有其他的内容。

然后IDEA的HTTP代理设置页面选择-》 自动检测代理设置 -》 自动代理配置URL 打勾，地址填写你的上面这段PAC脚本所在的地址。注意最好使用http协议，如果使用https的最好是有证书的，不然可能会影响正常使用，在window10的系统代理里就是这样，没有证书的https链接设置了无效。
