### ISSUE TITLE
翻译文档功能与ide外部文档显示功能冲突，应该显示中文，却被翻译成英文

### ISSUE THREAD

**Issue by tanxianbo** [YiiGuxing/TranslationPlugin#2299]
### 需求/建议描述

![image](https://user-images.githubusercontent.com/17635963/197382276-b230ec93-2562-41b9-be8a-24a340b61500.png)
![image](https://user-images.githubusercontent.com/17635963/197382541-3c7f30d6-e6d8-4b41-8ece-b7aabcce73de.png)
![image](https://user-images.githubusercontent.com/17635963/197382353-02138963-b678-4de4-b730-da6697c6408f.png)

翻译文档功能与ide外部文档显示功能冲突，应该显示中文，却被翻译成英文

### 建议的解决方案

解决冲突，或者增加不翻译中文选项

**Comment by tanxianbo** [comment]
**JDK_API_1_6_zh_CN.zip**
链接：https://pan.baidu.com/s/1JeKjrSABOVVgOvFVsV5iZg 
提取码：adxr

**Comment by tanxianbo** [comment]
上图使用的是有道翻译

**Comment by YiiGuxing** [comment]
🤣你应该使用的是有道翻译吧？文档翻译是不管原来是什么语言的，都翻译成指定的主要语言（国内默认为中文），但是呢，有道是我不管你要翻译到什么语言，只要你的输入不是英文，我都给你翻译中文，所以我控制不了它啊。。。

**Comment by tanxianbo** [comment]
**能否加个选项能控制文档包含一些字符就不翻译？比如下图这个功能，不知是不是我使用不对，没有效果**

![image](https://user-images.githubusercontent.com/17635963/197383495-4e80f222-d682-4edb-b842-251cf520e8a3.png)

**Comment by YiiGuxing** [comment]
😅这个不行，这个对文档翻译是无效的，唯一的办法是不默认开文档翻译，要使用的时候再开，而且默认开文档翻译是很消耗使用量的，你的翻译量会消耗大，费钱😑，所以用有道的话不建议开。。。

**Comment by tanxianbo** [comment]
源码里的文档没有外部文档详细和可读性好，陌生API偶尔用到要看下，现在使用就是切换一下，给文档翻译也加个“忽略正则”就更好了。
有道翻译有音标，翻译内容比较详细，有助于学英语。至于消耗大，见仁见智。

**Comment by YiiGuxing** [comment]
“忽略正则”是把匹配的内容删除掉，而不是忽略不翻译，由于翻译提供商的限制，是做不了这一点的。而且文档翻译和一般翻译是不一样的，不能混为一谈的。

**Comment by tanxianbo** [comment]
梦想还是要有，万一实现了呢😅

**Comment by YiiGuxing** [comment]
😆

**Comment by YiiGuxing** [comment]
目前就只能先这样了，下个版本文档翻译的开启和关闭方式会有所优化，添加一个只针对单个文档的翻译的功能，而不是像现在这样一开全开，一关全关的了。
