### ISSUE TITLE
Key name, Key value?

### ISSUE THREAD

**Issue by jp1017** [YiiGuxing/TranslationPlugin#23]
而网站上是给出的是

```
API key:
keyfrom:
```

刚测试了下，key value 对应 API key, 还望修改下啊，否则第一眼还有些疑惑 :smile:

**Comment by YiiGuxing** [comment]
嗯，从界面上确实不能第一眼看出哪个对应哪个，不直观。

**Comment by liuzheng9110** [comment]
已经换了 key 还是提示请求频繁？？？ @YiiGuxing

**Comment by jp1017** [comment]
@liuzheng9110 我这里正常啊 :smile: 再重新生成一个试试。。。

**Comment by YiiGuxing** [comment]
@liuzheng9110 你看看设置里面，是不是被修改为默认的了？有一版升级后会重置为默认的。
