### ISSUE TITLE
建议：添加单词本功能

### ISSUE THREAD

**Issue by bayllech** [YiiGuxing/TranslationPlugin#230]
想把查询过的单词放入到生词本里，方便浏览记忆，当然，账号信息肯定要记录的
如果可行：
    1.最方便的就是在卡片上增加按钮
    2.实在不行，从查询记录里导入是否可以
[类似此项目实现的添加单词到有道单词本：](https://github.com/TerryX-Lee/AlfredWorkflow_YoudaoTranslate)

**Comment by YiiGuxing** [comment]
有道并未供相关API

**Comment by bayllech** [comment]
确实没有API，我看了下这个人的实现，是直接模拟网页请求添加的生词

Referer: http://dict.youdao.com/wordbook/wordlist?action=add
{
                'word': word,
                'phonetic': soundmark,
                'desc': explains,
                'tags': ''
            }

**Comment by lixi0912** [comment]
建议先在插件内部增加单词本、以及导出单词本的功能(每行一个词，释义作为可选导出)

**Comment by YiiGuxing** [comment]
初步的计划是在本地保存单词本数据，不会提交到有道的云端，因为并不是每个人都会使用有道的。这样一来数据的共享范围就限制在本机了，但这也是无奈之举。

**Comment by 1992YoungHong** [comment]
有道词典windows版本可以导入导出xml文件，作者可以根据有道的格式来记录，这样方便了我们手动导入到有道词典中，非常感谢。

PS：插件非常好用，再次谢谢作者的开发。

**Comment by lixi0912** [comment]
用 json 格式导出可能更通用一些

**Comment by YiiGuxing** [comment]
:construction:  : https://github.com/YiiGuxing/TranslationPlugin/compare/0d1cc501c2208dd34f7d2b9ea57bec03688ee784...dev

**Comment by Darling012** [comment]
期待单词本功能
