### ISSUE TITLE
安装Translation插件之后，IDEA每次启动都会一直卡在启动界面

### ISSUE THREAD

**Issue by Zhou-Jianhao** [YiiGuxing/TranslationPlugin#2302]
### 📝 问题描述

如题，安装Translation插件之后如果退出IDEA，下次打开时就一直卡在IDEA中间的那个启动海报页面，不会显示其他任何东西，也不报错。
强行卸载或者禁用Translation插件之后重启IDEA就可以很快正常启动。

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
```

**Comment by Zhou-Jianhao** [comment]
> 这是一个IDE的BUG，应该是和其他已经按装过的插件冲突了，能否提供一下IDE的日志？需要发生启动异常之后的日志，日志文件：主菜单 -> Help -> Show Log in Explorer -> idea.log

主菜单连help都显示不了了，这样看不到log，我装的其他插件清单如下：
Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    org.intellij.RegexpTester (1.0.8)
    com.intellij.zh (222.202)
    com.intellij.plugins.watcher (222.4345.14)
    com.intellij.plugins.macoskeymap (222.4345.14)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    Key Promoter X (2022.3)
    org.sonarlint.idea (7.1.1.54565)
    intellij.prettierJS (222.4345.14)
    CheckStyle-IDEA (5.71.1)
    com.microsoft.tooling.msservices.intellij.azure (3.69.0-2022.2)
    cn.yiiguxing.plugin.translate (3.3.5)

**Comment by YiiGuxing** [comment]
😅你可以先在正常的时候从菜单那打开日志目录，再复现问题不就可以得到日志了嘛？哈哈，不过现在已经不用了，我已经知道是和哪个插件冲突了，是这个：com.microsoft.tooling.msservices.intellij.azure，但这个确实是IDE的Bug，我没有办，你只能安装其中的一个了。。。。抱歉

**Comment by Zhou-Jianhao** [comment]
> 😅你可以先在正常的时候从菜单那打开日志目录，再复现问题不就可以得到日志了嘛？哈哈，不过现在已经不用了，我已经知道是和哪个插件冲突了，是这个：com.microsoft.tooling.msservices.intellij.azure，但这个确实是IDE的Bug，我没有办，你只能安装其中的一个了。。。。抱歉

好的，没事，找到原因就可以，感谢大佬🙏
