### ISSUE TITLE
建议加个IP代理的选项

### ISSUE THREAD

**Issue by xdr630** [YiiGuxing/TranslationPlugin#2316]
### 需求/建议描述

建议加个IP代理的选项，国内现在谷歌翻译不能用了，频繁改IP太麻烦了，每隔一段时间都要找hosts文件然后修改有用的IP，如果能在插件那里加个代理的选项，就不用每次打开 hosts 文件了了

### 建议的解决方案

建议加个IP代理的选项，国内现在谷歌翻译不能用了，频繁改IP太麻烦了，每隔一段时间都要找hosts文件然后修改有用的IP，如果能在插件那里加个代理的选项，就不用每次打开 hosts 文件了了

**Comment by YiiGuxing** [comment]
Duplicate of #2165 #2235
