### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by xzq52110** [YiiGuxing/TranslationPlugin#2320]
### 需求/建议描述

希望在idea中选中对应的单词或者句子就在翻译栏中给出翻译结果，不需要其他操作

### 建议的解决方案

谷歌浏览器中有一个插件叫做梦想划词翻译功能可参考

**Comment by YiiGuxing** [comment]
嗯~~~~这个还有待调研，在编辑器里最主要的还是要写代码，如果频繁弹窗的话会影响到我们编码的速度的，又没有一个好的固定的地方显示。。。。或者在阅读模式下可以尝试一下。

**Comment by xzq52110** [comment]
也是的 主要功能还是编码 现在的功能已经很好了 节省了我不少时间 感谢您的回复！发自我的荣耀手机-------- 原始邮件 --------发件人： "Yii.Guxing" ***@***.***>日期： 2022年10月25日周二 22:08收件人： YiiGuxing/TranslationPlugin ***@***.***>抄送： xzq52110 ***@***.***>, Author ***@***.***>主    题： Re: [YiiGuxing/TranslationPlugin] 功能优化 (Issue #2320)

嗯~~~~这个还有待调研，在编辑器里最主要的还是要写代码，如果频繁弹窗的话会影响到我们编码的速度的，又没有一个好的固定的地方显示。。。。或者在阅读模式下可以尝试一下。
