### ISSUE TITLE
 I'd like to be able to adjust the font size in the settings

### ISSUE THREAD

**Issue by mulder3062** [YiiGuxing/TranslationPlugin#235]
## Description
The font in the popup window is too big for the editor's font.
Is there any way to control it?
If not, I'd like to be able to adjust the font size in the settings.

## Environment & Stack Trace
- Plugin version: v2.2
- IDE version: Intellij IDEA 2018
- Operating System and version: Mac Mojave
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
Plug-in font size is controlled by global font size:
![image](https://user-images.githubusercontent.com/10737066/51810023-2cbb4580-22e0-11e9-9f34-a4391fa2640f.png)

**Comment by mulder3062** [comment]
Thank you for guide :)
