### ISSUE TITLE
翻译替换的目标语言只有英文么？？

### ISSUE THREAD

**Issue by pp126** [YiiGuxing/TranslationPlugin#236]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
请参阅: #225, #229

**Comment by YiiGuxing** [comment]
请关注 #229 以了解开发进度。

**Comment by pp126** [comment]
好的，好的！感谢大佬
