### ISSUE TITLE
建议添加腾讯翻译君

### ISSUE THREAD

**Issue by etgyd** [YiiGuxing/TranslationPlugin#2360]
### 需求/建议描述

国内能用的翻译也就有道和百度，一个月的免费额度都是100万，如果用得多很容易会超额度的，腾讯翻译君的付费版每月的前 500 万字符免费，比起来额度多了很多。希望作者能采纳！

### 建议的解决方案

添加腾讯翻译君的api使用

### 附加信息

[腾讯云机器翻译服务定价文档](https://curl.qcloud.com/JAXtzpXl)  ，
api文档 ：https://cloud.tencent.com/document/product/551/15612

**Comment by YiiGuxing** [comment]
腾讯翻译君应该是会添加的，但不是现在，也不会是默认集成，而是以插件的方式添加进来，这个还需要一段时间。

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/issues/768#issuecomment-902448093
