### ISSUE TITLE
能否添加一个微软翻译的功能

### ISSUE THREAD

**Issue by chinna-1** [YiiGuxing/TranslationPlugin#2371]
### 需求/建议描述

已知微软的翻译接口，奈何不会写kotlin语言

相关接口

###获取授权凭证###
GET https://edge.microsoft.com/translate/auth

###翻译接口###
POST https://api.cognitive.microsofttranslator.com/translate?from=en&to=zh-CHS&api-version=3.0&includeSentenceLength=true

### 建议的解决方案

![image](https://user-images.githubusercontent.com/39046598/198921261-3bb9ec7f-e27b-4ce9-854f-2a7145fcb6df.png)

**Comment by YiiGuxing** [comment]
这个是要加的，可能是在下个版本。

感谢提供的相关API，请问这些API你是从哪里获得的，有没有文档？，除了翻译的，有没有语音合成的API？

**Comment by chinna-1** [comment]
> 

这两个api是通过抓包Microsoft Edge浏览器提供的翻译服务拿到的，暂时没有语言合成的，不过微软官方提供了免费的文本翻译和语言翻译服务，需要注册账号申请免费试用，每个月大概免费200w字符，但是注册账号有点繁琐，需要添加银行卡信息

**Comment by YiiGuxing** [comment]
微软官方翻译服务这个注册账号门槛太高了，还要有梯子才行，所以不考虑了。虽然有其他方案，但也比较复杂的，你提供的这个就很简单方便，但可惜没有语音合成的，我后面再研究一下。感谢提供的方案！

**Comment by kuke2733** [comment]
http://fanyi.youdao.com/translate?&doctype=json&type=AUTO&i=translation
![image](https://user-images.githubusercontent.com/107527937/199380146-50147963-78ef-4971-a0dc-1465eb833b97.png)
再给你提供一个有道的免费翻译接口  没有文档   只有这个

**Comment by YiiGuxing** [comment]
合并至 #2157
