### ISSUE TITLE
更新tkk失败，请检查网络连接

### ISSUE THREAD

**Issue by qiu6230135** [YiiGuxing/TranslationPlugin#2382]
### 📝 Issue Description

翻译时更新tkk失败，请检查网络连接，网上各种搜索，依然无法解决

### 🏷 Plugin Version

v3.3.5

### 🔁 Translation Engine(s)

Google Translate

### 💻 IDE and Operating Environment

```plain text
win10  系统， android studio 软件
```

**Comment by zhoujuanjuan** [comment]
google 翻译现在退出国内，访问不了导致的，求配置有道翻译方式

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/discussions/2315
