### ISSUE TITLE
使用Google Translation作为翻译引擎进行翻译时，报错Bad Request

### ISSUE THREAD

**Issue by Deathef** [YiiGuxing/TranslationPlugin#2394]
### 📝 问题描述

1. 选中文字进行翻译时，报错Bad Request
2. 在IDE中测试了与translate.google.com的网络连接是正常的

屏幕截图：
![google翻译引擎的问题](https://user-images.githubusercontent.com/32616338/199649065-77b44f53-120b-4599-9c56-e6331f8828df.gif)

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022

You have a perpetual fallback license for this version.
Subscription is active until July 1, 2023.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.45-amd64-desktop
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 12
Registry:
    ide.experimental.ui.inter.font=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.murphysec.intellij.Plugin (3.0.2)
    ro.florinpatan.gopher (2021.1)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    org.sonarlint.idea (7.1.1.54565)
    Pythonid (222.4345.14)
    zielu.gittoolbox (212.9.9)
    cn.yiiguxing.plugin.translate (3.3.5)
    izhangzhihao.rainbow.brackets (6.26)
    MavenRunHelper (4.23.222.2964.0)

Kotlin: 222-1.7.20-release-201-IJ4167.29
Current Desktop: Deepin
```

**Comment by Deathef** [comment]
> 并不能重现这个问题，会不会是你梯子的问题？使用这里的IP试试：[#2315 (comment)](https://github.com/YiiGuxing/TranslationPlugin/discussions/2315#discussioncomment-3949785)

和梯子的关系不大吧，在浏览器都可以访问Google翻译，Gmail什么的都可以正常使用。
![1667527448699](https://user-images.githubusercontent.com/32616338/199869381-08d999e6-a10f-4d30-8ba9-6051f6a00117.jpg)
配了本地Host也不行，还是Bad Request。
需要我提供什么相关的log吗？

**Comment by YiiGuxing** [comment]
那就麻烦你提供一下idea的日志文件嘛，我看下日志，看看到底是怎么回事。

**Comment by Deathef** [comment]
@YiiGuxing 上周无确实怎么访问都是Bad Request，今早上班测了一下，只出现了一次Timeout，后面就正常了
