### ISSUE TITLE
Action命名

### ISSUE THREAD

**Issue by DanteAndroid** [YiiGuxing/TranslationPlugin#24]
>TranslationPlugin有四个操作动作，它们分别是：Translation, Translate, Translate(Inclusive) 和 Translate(Exclusive). 

这命名真感人。。我想自定义keymap很容易搞混。。建议改成具体点含义的Action，比如'Translation bar', 'Translate(Full)', 'Translate(Single)'等等。。（不过好像Inclusive这个词很准确，可惜我不认识:P）

**Comment by DanteAndroid** [comment]
另外，我导入jar时，除了主体以外，都无法导入。因此播放单词发音时，出现了
![image](https://cloud.githubusercontent.com/assets/10005563/20131612/8979dfd6-a699-11e6-968d-f4210ee800b1.png)

**Comment by YiiGuxing** [comment]
嘿，其实这命名我可费了很大劲的，但终于还是不知道怎么命名才好，没办法，Inclusive和Exclusive我还是从android代码上弄过来的。。。其实我到现在我也分不清，汗~~~  
还有，如果再改的话，以前设置的快捷键就无效了，这样会不会被打？

**Comment by YiiGuxing** [comment]
@DanteAndroid 关于单词发音报错，你能不能提供你的系统和IDEA环境信息？因为我这边是能正常使用的。

**Comment by YiiGuxing** [comment]
@DanteAndroid 关于Action命名，我准备不改了，其实分不清的话是可以用鼠标指针停在Action项上一小会儿，就会有中文提示的：
![截图](https://cloud.githubusercontent.com/assets/10737066/20138480/8e2f930a-a6bb-11e6-84ca-018dd82a0023.png)

**Comment by DanteAndroid** [comment]
系统是10.10.3，AS 2.2.2。
Plugin只成功导入本体。

**Comment by YiiGuxing** [comment]
@DanteAndroid  那就奇怪了，我这边在AS 2.2.2上也是没问题的啊。要不你先卸载，然后直接在AS里搜索安装试试，不自己下载插件包。还有你是不是下载了zip包，解压后才导入AS里的哦？

**Comment by DanteAndroid** [comment]
晕。我确实是导入的jar包啊。2L的图片也显示是这样的啊。。我习惯性地看到zip就想解压了。换成zip好了。谢谢

**Comment by YiiGuxing** [comment]
哈哈，还好我想到了。其实用IDE上的插件中心搜索安装更方便

**Comment by DanteAndroid** [comment]
因为上次装过一款插件、叫ECTranslation，他是没有zip包的，所以我直接就下zip了。
