### ISSUE TITLE
无法使用朗读功能

### ISSUE THREAD

**Issue by Fission21** [YiiGuxing/TranslationPlugin#2412]
### 📝 问题描述

1，ctrl + shift + y 打开翻页界面
2，点击朗读
3，编译器右下角报错
![image](https://user-images.githubusercontent.com/80576421/200233741-3dc52636-08da-4584-9a66-6c62a9ac3a14.png)

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
Windows 11 专业版 22H2  
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
```

**Comment by Fission21** [comment]
关于Google翻译的问题。

根据这篇内容：https://github.com/YiiGuxing/TranslationPlugin/discussions/2315
我修改了本机host，并且找了一个可以在cmd ping通过的地址，写进host里，改完刷新了本机dns，但是idea里还是不能用，Google的翻译。

**Comment by YiiGuxing** [comment]
网络问题，都检查一下可能出现问题的环节吧。

**Comment by YiiGuxing** [comment]
我这边这个IP是可使用的：142.250.4.90
