### ISSUE TITLE
建议：查询长词点击分词直达结果

### ISSUE THREAD

**Issue by lixi0912** [YiiGuxing/TranslationPlugin#242]
建议
* 查询某个长词或者词组，点击弹窗里的分词，可以直达搜索结果(现在只能右键翻译)
* 点击搜索结果的词汇，直接改变当前弹窗的内容，不要跳到搜索窗口(在弹窗上加个搜索窗口的入口按钮)

**Comment by YiiGuxing** [comment]
1. 目前可点击直达搜索结果的只有谷歌翻译的字典部分，至于原文和译文部分，右键翻译已足够了（也不见有道的客户端有这样的功能呀）。虽说那样会方便一点，但其实也是并非非要不可。即使要实现，那也是先在有道翻译的释义部分实现（1.x版本就实现了的，在2.x版本上由于数据结构的问题暂时去掉了）。
2. 这不好，气泡弹窗上的内容是对气泡弹窗在编辑器里所指向的内容的翻译，因此，气泡弹窗里并不适合显示其他的翻译内容，只好在新对话框显示。
