### ISSUE TITLE
请问在哪里设置不要把中文翻译成英文

### ISSUE THREAD

**Issue by wmmhnsz** [YiiGuxing/TranslationPlugin#2425]
### 📝 问题描述

只想把英文翻译成中文，不想把中文翻译成中文，请问在哪里可以设置

### 🏷 插件版本

3.3.5+203u212

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
IDEA 2020.3
```

**Comment by YiiGuxing** [comment]
还请您清晰地描述您的问题，必要的话可以提供一些截图来帮助您解释您的问题。您是在什么情况下出现中文翻译成中文的情况？

另外，这不是一个BUG，如果您只是想提问的话，请通过GitHub Discussions提问，这里是**报告错误或异常行为**，在您提交一个报告之前还请您选择一个正确的选项：
![image](https://user-images.githubusercontent.com/10737066/200738227-6c464ded-ad75-4975-b377-ca8d6a09432a.png)

感谢您的配合与支持！

**Comment by wmmhnsz** [comment]
> 还请您清楚地描述您遇到的问题，您可以提供一些截图来帮助解释您出现的问题。是在什么情况下将中文翻译成中文的？
> 
> 另外，这不是一个错误，如果您只是想的话，请通过 GitHub Discussions 提问，这里是**报告错误或行为**，在您正确提交报告之前还请您选择一个异常的选项： ![图片](https://user-images.githubusercontent.com/10737066/200738227-6c464ded-ad75-4975-b377-ca8d6a09432a.png)
> 
> 感谢您的配合与支持！

明白了，先关掉吧，切换成google翻译就没问题了
