### ISSUE TITLE
IntelliJ2018.3.3X64 有道翻译 音标乱码

### ISSUE THREAD

**Issue by futurename** [YiiGuxing/TranslationPlugin#244]
有道翻译的音标不能正确显示，但是鼠标点击后能显示出来。

请问是我的设置问题吗？

![20190221143351.jpg](https://images.zenhubusercontent.com/5c6ef3241cdb705a99b2ed1f/70b73334-3285-4ddb-b43c-a0dee4e02993)

**Comment by YiiGuxing** [comment]
请查阅: [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq)
