### ISSUE TITLE
无法记住要翻译到的语言

### ISSUE THREAD

**Issue by Ljqiii** [YiiGuxing/TranslationPlugin#246]
## Description
Please describe the problem in detail. Be sure to include:
无法记住要翻译到的语言,每次都是从English翻译到English.用的Google翻译

## Environment & Stack Trace
- Plugin version:2.3.2
- IDE version: IDEA 2018.3.5
- Operating System and version: Ubuntu 18.04
- Stack Trace (for crash):
不是翻译错误,没有copy to clipboard 选项

**Comment by Ljqiii** [comment]
抱歉,没看设置,我以为直接能记住要翻译成的语言#170

**Comment by YiiGuxing** [comment]
记住上次使用的语言需要开启选项：
![image](https://user-images.githubusercontent.com/10737066/53534924-be1a1380-3b3b-11e9-8ef7-04da321ba69f.png)

而且是手动选择的语言才会被记住，自动选的不会。

**Comment by Ljqiii** [comment]
能不能加一个设置,不显示右上角的两个翻译图标

**Comment by YiiGuxing** [comment]
你可以在设置里将其删掉：
![image](https://user-images.githubusercontent.com/10737066/53535070-5a441a80-3b3c-11e9-862e-e86c5bb958c6.png)
