### ISSUE TITLE
建议使用谷歌翻译国内镜像

### ISSUE THREAD

**Issue by Jontyshaw** [YiiGuxing/TranslationPlugin#2463]
### 需求/建议描述

最近谷歌翻译退出中国，无法直接使用。可以考虑使用谷歌翻译国内镜像

### 建议的解决方案

建议参照copytranslator类似解决方案https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.2.3。
参照链接：https://www.haah.net/archives/7885.html
https://copytranslator.gitee.io/guide/questions.html#%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E9%80%80%E5%87%BA%E4%B8%AD%E5%9B%BD%E5%B8%82%E5%9C%BA%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by YiiGuxing** [comment]
感谢提供的解决方案，不过我还是决定不实现，我的理由是：这类CDN的路子并不是很正（不是指技术哈，你懂的），其可靠性并没有什么保障，鬼知道哪天也就挂了。后面接入Bing翻译，就有了更好的代替谷歌翻译的方案了。如果非要使用谷歌翻译，那用户就自己动手添加Hosts或者挂梯子就行了。

**Comment by noenif** [comment]
老哥bing 是爬虫爬的调用接口吗

**Comment by YiiGuxing** [comment]
> 老哥bing 是爬虫爬的调用接口吗

不是
