### ISSUE TITLE
推荐添加支持在 （提示方法注释）窗口支持翻译

### ISSUE THREAD

**Issue by HKMV** [YiiGuxing/TranslationPlugin#247]
推荐添加支持在 （提示方法注释）窗口支持翻译

![image](https://user-images.githubusercontent.com/26456469/53926345-12823d80-40be-11e9-8c5c-78ea0309aca0.png)

就是鼠标 移到 类、方法、属性等，上面弹出的提示框，希望能支持选中注释文字后，支持翻译。

选谢过大佬了，thanks

**Comment by YiiGuxing** [comment]
是支持的，这类提示框只能在选择文本后通快捷键翻译，不能通过右键菜单翻译。

**Comment by HKMV** [comment]
> 是支持的，这类提示框只能在选择文本后通快捷键翻译，不能通过右键菜单翻译。

谢谢您,get了

**Comment by YiiGuxing** [comment]
不用客气
