### ISSUE TITLE
相当不错，高逼格的插件

### ISSUE THREAD

**Issue by tianzhijiexian** [YiiGuxing/TranslationPlugin#25]
特别喜欢导航栏上的按钮，轻量，方便。

![image](https://cloud.githubusercontent.com/assets/9552155/20163788/36494710-a73a-11e6-87b9-533bab5e0697.png)

就是想问下，能否让气泡里面的单词可以点击跳转？

**Comment by YiiGuxing** [comment]
以后可以考虑加上，现在只能在气泡里选择单词然后点击鼠标右键，点查询跳转
