### ISSUE TITLE
建议翻译窗口大小可调

### ISSUE THREAD

**Issue by ygnzh** [YiiGuxing/TranslationPlugin#251]
首先感谢分享！
切入正题：由于插件的窗口(win快捷键为Ctrl+Shift+Y呼出)较小且不能调整大小，翻译大段文本时（比如javadoc），翻译结果换行频繁影响阅读速度。建议支持翻译窗口大小可以调整。

**Comment by linux-lpx** [comment]
附议！
确实是窗口太小，很影响大段文字的阅读

**Comment by giveup** [comment]
默认窗口过大，小屏幕设备较为影响使用。
![image](https://user-images.githubusercontent.com/2897585/60853219-a2332680-a22d-11e9-85d0-14fb35a2bfd3.png)
上图已经占用了2/3的屏幕高度。

只是简单查询单词，不需要太过详细的结果。建议UI参考IDEA默认的提示框，
单行显示结果，如果有需要，再打开链接查看即可。
![image](https://user-images.githubusercontent.com/2897585/60853242-ba0aaa80-a22d-11e9-8cb7-8614c8ae112c.png)

**Comment by YiiGuxing** [comment]
@giveup 我怀疑你的IED是不是修改了默认字体大小，默认字体改大后，界面尺寸也会相适应地变大。

**Comment by giveup** [comment]
Font的设置是12.应该不会吧。ide里面看代码都是正常大小的。
