### ISSUE TITLE
Translate Text Component 无效

### ISSUE THREAD

**Issue by a523** [YiiGuxing/TranslationPlugin#253]
## Description
我想翻译一些语法提示信息，看了文档是：

> Translate Text Component
> 翻译一些文本组件（如快速文档、提示气泡、输入框……）中选中的文本，不支持自动取词。默认快捷键:
> 
> Windows - Ctrl + Shift + O
> Mac OS - Control + Meta + I
> 
我是windows系统， 按下Ctrl + Shift + O快捷键无效，  去WS快捷键设置里面找也没有发现
Translate Text Component 选项。
因为我无法把ide提示框里面的文字拷贝出来放到其他翻译工具里面去翻译，这个需求对我来说还挺重要的，相信很多人也跟我一样， 请帮我一下。
## Environment & Stack Trace
- Plugin version: 3.8.0.2
- IDE version: Webstrom 2019.1
- Operating System and version: windos10
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
该功能已无法在2019.1之后的版使用了，由于是IDE内部的原因，目前还无法解决。

**Comment by YiiGuxing** [comment]
如需跟进后续情况，请关注https://youtrack.jetbrains.com/issue/IDEA-210591
