### ISSUE TITLE
为什么翻译替换规则改了?

### ISSUE THREAD

**Issue by T-Merak** [YiiGuxing/TranslationPlugin#254]
最新版本 2.3.2 为什么翻译替换规则和以前不一样了?以前输入双引号然后在双引号里面输入中文在直接翻译替换会直接吧双引号里面的中文替换掉 双引号还在 
但是现在最新的版本会直接双引号也一起替换?

而且以前英文接着中文的时候 直接快捷键取词翻译会直接取中文部分忽视英文部分 然后替换的时候也是无视英文部分的 为什么现在又不行了?

**Comment by YiiGuxing** [comment]
因为以前是只能从非英文翻译替换为英文，而现在是任何语言都能翻译替换了。

**Comment by T-Merak** [comment]
> 因为以前是只能从非英文翻译替换为英文，而现在是任何语言都能翻译替换了。

那怎么办呢?赶紧这样很不方便啊?实在不行的话能不能提供一个以前的版本给我?我真的不习惯这样的...赶紧各种不顺畅

**Comment by YiiGuxing** [comment]
可以从release中下载老的版本

**Comment by T-Merak** [comment]
> 可以从release中下载老的版本

找到老版本了  不过还是建议可以在替换的时候判断一下 只是截取相同语言的部分 不同语言的部分就不用截取和替换了 感觉那样会更好

**Comment by YiiGuxing** [comment]
本地是很难判断有哪些语言的。
