### ISSUE TITLE
IDEA 2019.1警告建议消息无法选择翻译

### ISSUE THREAD

**Issue by xiaonanhailili** [YiiGuxing/TranslationPlugin#256]
![image](https://user-images.githubusercontent.com/13197336/55845293-e30a9900-5b73-11e9-9684-b235a7243b96.png)
![image](https://user-images.githubusercontent.com/13197336/55845327-fcabe080-5b73-11e9-86bf-daf1d52e7e4c.png)

像第二张图那样的消息，选中后进行翻译
上个版本似乎都可以，前两天更新之后就出现按了crtl+Y无反应，类似于这个消息框失去焦点后消失的状况

**Comment by YiiGuxing** [comment]
#253
