### ISSUE TITLE
DataGrip上安装后重新查看显示未安装

### ISSUE THREAD

**Issue by RaiseSunner** [YiiGuxing/TranslationPlugin#2560]
### 📝 问题描述

Jetbrains正版全家桶用户，在DataGrip仓库在线安装，进度条结束显示installed，但是没提示restart，也找不到translation插件。于是手动重启DataGrip打开后或在设置界面切换tab再切换回去时显示未安装，离线安装问题现象一致，在IDEA、Goland、Pycharm Professional、PhpStorm上正常

### 🏷 插件版本

3.3.5

### 🔁 翻译引擎

阿里翻译

### 💻 IDE及运行环境

```plain text
IDE版本: DataGrip 2022.2.5
操作系统版本: macOS13.0.1(Ventura)

处理器： 8 × Intel® Core™ i9-9880H
内存： 64 GiB 内存
图形处理器： AMD Radeon Pro 5500M 4 GB
```

**Comment by YiiGuxing** [comment]
这是一个IDE的BUG，你在安装完成之后不要急着重启，要先点一下Apply按钮，再进行其他操作就可以了，如果Apply按钮不可点击，就行切换一下 marketplace 和 installed 会签页就应该可以点击了。
