### ISSUE TITLE
ctrl shift o androidstudio无响应

### ISSUE THREAD

**Issue by DarrenWorks** [YiiGuxing/TranslationPlugin#257]
使用快捷键ctrl shift o打开翻译窗口后androidstudio只有顶部标题栏可用，其他位置鼠标被遮盖且均不可点击，只能选择结束进程，不知是否与其他插件冲突所致。

完整plugin列表
![image](https://user-images.githubusercontent.com/15689725/56073261-68d84f80-5dd3-11e9-8195-82d69b09911a.png)
![image](https://user-images.githubusercontent.com/15689725/56073273-87d6e180-5dd3-11e9-9222-c21720679358.png)
![image](https://user-images.githubusercontent.com/15689725/56073276-8f968600-5dd3-11e9-9b72-69b7d781c921.png)

**Comment by YiiGuxing** [comment]
请问插件和as的版本分别是多少？

**Comment by DarrenWorks** [comment]
> 请问插件和as的版本分别是多少？

`translation2.3.2`

```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by YiiGuxing** [comment]
这种情况是必现的吗？我这边试了一下并没有什么问题。

**Comment by DarrenWorks** [comment]
> 这种情况是必现的吗？我这边试了一下并没有什么问题。如果是必现的，如何重现？

我这里只要是用快捷键打开就必定复现，点击图标是没有问题的

**Comment by DarrenWorks** [comment]
> > 这种情况是必现的吗？我这边试了一下并没有什么问题。如果是必现的，如何重现？
> 
> 我这里只要是用快捷键打开就必定复现，点击图标是没有问题的

很像是被一个看不到的view抢了焦点，也可能不是这个插件的问题吧

**Comment by YiiGuxing** [comment]
点击工具栏的的打开翻译对话框的图标（不是鼠标右键菜单的图标）是好的哈？你试试执行一下以下的操作：
File -> Invalidate/Restart -> Invalidate and Restart

再不行重新安装一下插件试试。

主要是我这里不能重现，这比较尴尬。。。

**Comment by DarrenWorks** [comment]
> 点击工具栏的的打开翻译对话框的图标（不是鼠标右键菜单的图标）是好的哈？你试试执行一下以下的操作：
> File -> Invalidate/Restart -> Invalidate and Restart
> 
> 再不行重新安装一下插件试试。
> 
> 主要是我这里不能重现，这比较尴尬。。。

最近好像不再复现这个问题了，仅有一次复现是在光标在gai该处时，但仍是大概率不复现，大概是我电脑中某些环境导致的吧，这个问题大概可以close了。。。
![image](https://user-images.githubusercontent.com/15689725/56628714-68667100-667d-11e9-8594-694838be4d99.png)
