### ISSUE TITLE
某次更新后就无法使用发音服务了，每次都是 tts超时

### ISSUE THREAD

**Issue by yonxao** [YiiGuxing/TranslationPlugin#2594]
### 📝 问题描述

选择单词，点击翻译，可以翻译出来，点击发音，就提示 tts 超时

### 🏷 插件版本

3.4.0

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
idea 最新版
```

**Comment by YiiGuxing** [comment]
#2315

**Comment by yonxao** [comment]
您好，您的邮件永潇已经收到。如有需要，待他查看后会尽早回复您。--------------------------------------------本邮件为自动回复邮件，不用回复，谢谢。
