### ISSUE TITLE
公司把有道翻译屏蔽了，翻译时ServiceUnavailable，这个插件是不是就用不了了。。。。

### ISSUE THREAD

**Issue by yumi0629** [YiiGuxing/TranslationPlugin#26]
公司把有道翻译屏蔽了，翻译时ServiceUnavailable，这个插件是不是就用不了了。。。。

**Comment by YiiGuxing** [comment]
这个插件是支持网络代理的，如果用网络代理可以访问有道翻译的话就能用，网络代理还是不能访问就真没办法了，毕竟这个不是离线的。你可以到这里看看： #21 ，网络代理设置如下图：
![http](https://cloud.githubusercontent.com/assets/10737066/20170329/c5610650-a766-11e6-87d5-a6e4931a9a10.png)
