### ISSUE TITLE
建议可以增加遇到/****/类的注解可以直接翻译成中文,如果可以直接替换成中文

### ISSUE THREAD

**Issue by huicunjun** [YiiGuxing/TranslationPlugin#261]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
Merge to #130
[project-card-8394310](https://github.com/YiiGuxing/TranslationPlugin/projects/1#card-8394310)
