### ISSUE TITLE
检查

### ISSUE THREAD

**Issue by qweenhool** [YiiGuxing/TranslationPlugin#262]
好多常用的单词明明是英语，会自动检测成法语，比如whitespace，请问一下是我没设置对么？

**Comment by YiiGuxing** [comment]
这是翻译服务的问题，本地判断语言比较困难的，所以并没有做本地判断语言，是送到翻译服务让翻译服务判断的。你用的是有道的吧？谷歌翻译的判断是正确的。

**Comment by qweenhool** [comment]
的确是有道翻译，谷歌翻译又有点简单。
