### ISSUE TITLE
关于DiaglogWrapper的问题

### ISSUE THREAD

**Issue by FlyingPigQAQ** [YiiGuxing/TranslationPlugin#264]
@YiiGuxing 您好，我最近也在尝试开发idea插件，有一个问题想请咨询下您，就是我的form继承了DiaglogWrapper后，使用Action调用是没问题，但是整个UI是阻塞的。我看您的翻译插件，在翻译的同时还可以操作IDE的其他功能，这个是怎么做到的呢

**Comment by YiiGuxing** [comment]
设置其为非模态窗口即可

**Comment by FlyingPigQAQ** [comment]
好的，可以了，谢谢！
