### ISSUE TITLE
朗读报错 TTS Error SocketException: Connection reset

### ISSUE THREAD

**Issue by atliwen** [YiiGuxing/TranslationPlugin#267]
朗读报错 TTS Error SocketException: Connection reset

**Comment by YiiGuxing** [comment]
可能是网络问题，请检查一下网络环境。

**Comment by YiiGuxing** [comment]
也检查一下代理设置，IDE内的代理有时候会有问题。

**Comment by atliwen** [comment]
> 可能是网络问题，请检查一下网络环境。

非常感谢提供这么好的插件   能提供一下调用的URL地址吗 公司网络 可能真是有的被屏蔽了。

**Comment by YiiGuxing** [comment]
试一下在这上面使用TTS（插件内使用的同一API）：https://translate.google.cn/

**Comment by atliwen** [comment]
我知道了，看源码是使用的谷歌进行朗读的。 公司谷歌翻译等都被屏蔽了。  谢谢啦！ 是否可以添加百度的朗读功能（如果百度提供该功能）？  使用这个插件的人大多数都是英文水平不高的，如果能变翻译 边学这么读。这样也能提高一点英语水平了。

**Comment by YiiGuxing** [comment]
其他的TTS引擎的集成目前还未有相应的计划，以后会有的，只不过不知道要等到什么时候了，个人精力有限。
