### ISSUE TITLE
idea2019.1提示内容不能使用快捷键翻译

### ISSUE THREAD

**Issue by caowenhui** [YiiGuxing/TranslationPlugin#268]
![image](https://user-images.githubusercontent.com/40911247/58377661-40d63180-7fb8-11e9-8eab-21cf98f10b9f.png)
不能使用ctrl+shift+y快捷键翻译

**Comment by YiiGuxing** [comment]
这一问题将在下一个版本得到修复：commit [`1ebd8b1`](https://github.com/YiiGuxing/TranslationPlugin/commit/1ebd8b18c3b37f873f73098beef6dfd6d89a0d5e)

**Comment by caowenhui** [comment]
好的
