### ISSUE TITLE
mac idea 2019.1 版本，在jdk 源码shift + command + x 提示 File is read-only

### ISSUE THREAD

**Issue by lhs472194266** [YiiGuxing/TranslationPlugin#269]
mac idea 2019.1 版本，在jdk 源码shift + command + x 提示 File is read-only

![image](https://user-images.githubusercontent.com/12750920/58378025-58181d80-7fbe-11e9-8e19-e162d251e111.png)

**Comment by YiiGuxing** [comment]
文件是只读文件，当然不能进行这个操作的。

**Comment by lhs472194266** [comment]
> 文件是只读文件，当然不能进行这个操作的。

我仔细看了一下 快捷，，默认的 shift + command + x 原来是 翻译&替换。

问题解决了。
