### ISSUE TITLE
android studio 无法对方法描述进行翻译

### ISSUE THREAD

**Issue by a442509097** [YiiGuxing/TranslationPlugin#272]
如题, 现在新版的android studio无法固定悬浮窗, 导致不能右键了, 一旦按下任何按键悬浮窗就自动关闭了

**Comment by YiiGuxing** [comment]
请问android studio的版本号是多少？

**Comment by YiiGuxing** [comment]
@a442509097 我试了一下3.4.1正式版和3.5Beta4版都没什么问题啊。
