### ISSUE TITLE
腾讯翻译每月有500万字符免费，建议使用

### ISSUE THREAD

**Issue by jingzz1** [YiiGuxing/TranslationPlugin#2720]
### 需求/建议描述

https://cloud.tencent.com/document/product/551/35017
腾讯翻译我一直在用，在众多翻译平台里算是非常精准的一个，文本翻译每个月有500万字符免费，应该够用了

### 建议的解决方案

https://cloud.tencent.com/document/api/551/15619

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/issues/768#issuecomment-902448093
