### ISSUE TITLE
签名检验失败，应用秘钥保存不上

### ISSUE THREAD

**Issue by travishao** [YiiGuxing/TranslationPlugin#275]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

![image](https://user-images.githubusercontent.com/12822830/60853448-b6c3ee80-a22e-11e9-9d56-a3f98391e641.png)

![image](https://user-images.githubusercontent.com/12822830/60853439-a449b500-a22e-11e9-9050-dd26f3bdbdb6.png)

每次开启都会提醒应用秘钥未填写，然而填写之后当时可以用，重新打开idea的话，又开始提醒签名检验失败

**Comment by YiiGuxing** [comment]
请参阅说明文档FAQ部分：https://github.com/YiiGuxing/TranslationPlugin#faq

**Comment by travishao** [comment]
问题解决了 感谢
