### ISSUE TITLE
翻译出错

### ISSUE THREAD

**Issue by ZeroTianyu** [YiiGuxing/TranslationPlugin#279]
重现步骤：ctrl + shift +o   -》输入汉字-》enter键翻译，会出现下列问题
![LD0UY)%U5XYGQQ$33GT)UCI](https://user-images.githubusercontent.com/33126553/61101399-2be82b80-a49c-11e9-91dd-901ab8e1b877.png)
插件版本：2.3.3
IDE版本：2019.1
操作系统：windows10 1903    10.0.18362.207

**Comment by YiiGuxing** [comment]
#277
