### ISSUE TITLE
配置为npm前端启动的时候右键没有翻译按钮

### ISSUE THREAD

**Issue by yinzhefuyun** [YiiGuxing/TranslationPlugin#2798]
### 需求/建议描述

配置为npm前端启动的时候右键没有翻译按钮

### 建议的解决方案

配置为npm前端启动的时候右键添加翻译按钮

### 附加信息

![image](https://user-images.githubusercontent.com/26876620/207811002-e20d8f4a-d04a-47d6-8e16-f884d0a15b1c.png)
![image](https://user-images.githubusercontent.com/26876620/207810823-880acd82-dc4e-41ba-a0d3-395d4e8ba14e.png)

**Comment by YiiGuxing** [comment]
这玩意儿和终端一个样，没有拓展点，添加不了，连快捷键都不能用。
