### ISSUE TITLE
你好，能否把音标也显示出来，有利于学习，谢谢

### ISSUE THREAD

**Issue by chen366690712** [YiiGuxing/TranslationPlugin#280]
你好，能否把音标也显示出来，有利于学习，谢谢

**Comment by YiiGuxing** [comment]
只有查单词的时候才会有音标。

**Comment by chen366690712** [comment]
是的，就查单词的时候能否把音标也显示出来。有时不方便听声音。

**Comment by YiiGuxing** [comment]
有的，如果没有的话就说明没有

**Comment by chen366690712** [comment]
<img width="518" alt="Jietu20190715-162050" src="https://user-images.githubusercontent.com/23465637/61203337-ade68780-a71c-11e9-997c-3235c2537e82.png">
 我今天刚下载安装的，
<img width="1125" alt="Jietu20190715-162403" src="https://user-images.githubusercontent.com/23465637/61203465-06b62000-a71d-11e9-8205-43083aed9414.png">
只有有道的会有么？

**Comment by YiiGuxing** [comment]
这是谷歌翻译的问题，我无能为力。

**Comment by YiiGuxing** [comment]
谷歌翻译有的单词确实是没有音标的

**Comment by chen366690712** [comment]
好的。谢谢。用有道就可以了。
