### ISSUE TITLE
Sinhala font not suport 

### ISSUE THREAD

**Issue by LalithK90** [YiiGuxing/TranslationPlugin#284]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
Does the IDEA editor support this font?

**Comment by LalithK90** [comment]
An IntelliJ idea does not support the font
