### ISSUE TITLE
可否为安卓火狐和安卓Yandex浏览器适配网页翻译功能插件？

### ISSUE THREAD

**Issue by lgy330335** [YiiGuxing/TranslationPlugin#288]
安卓版的火狐和Yandex是可以装插件的，所以可否为手机端适配网页翻译功能，注意是翻译整个网页，不是翻译部分网页，最好是不跳转翻译，可以适当捐赠，谢谢！

**Comment by YiiGuxing** [comment]
呃......你可以考虑使用Google Chrome Android版，它本身就带得有这样的功能。

**Comment by lgy330335** [comment]
是的，但是我基本不用它，只因它不能装插件。


 
---原始邮件---
发件人: "Yii.Guxing"<notifications@github.com>
发送时间: 2019年7月18日(星期四) 上午9:09
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"lgy330335"<1550391007@qq.com>;
主题: Re: [YiiGuxing/TranslationPlugin] 可否为安卓火狐和安卓Yandex浏览器适配网页翻译功能插件？ (#288)



呃......你可以考虑使用Google Chrome Android版，它本身就带得有这样的功能。

**Comment by YiiGuxing** [comment]
那就没办法了，我并没有那么多的时间和精力来处理这件事情。

**Comment by lgy330335** [comment]
我可适当捐赠的


 
---原始邮件---
发件人: "Yii.Guxing"<notifications@github.com>
发送时间: 2019年7月18日(星期四) 上午9:52
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"lgy330335"<1550391007@qq.com>;
主题: Re: [YiiGuxing/TranslationPlugin] 可否为安卓火狐和安卓Yandex浏览器适配网页翻译功能插件？ (#288)



那就没办法了，我并没有那么多的时间和精力来处理这件事情。
