### ISSUE TITLE
How can I clear translation history ?

### ISSUE THREAD

**Issue by douglarek** [YiiGuxing/TranslationPlugin#29]
Hi @YiiGuxing , thanks for so cool translation tool; it works great;

BTW: how can I clear translation history ?

thanks

xin

**Comment by YiiGuxing** [comment]
呃。。。抱歉，你的那些字母让我感到有些为难，不过会有这功能的。

**Comment by YiiGuxing** [comment]
其实历史记录并不是非常重要，忽略掉就行了，所以不再打算实现该需求了。
