### ISSUE TITLE
微软翻译出现翻译超时的错误

### ISSUE THREAD

**Issue by RainySecret** [YiiGuxing/TranslationPlugin#2904]
### 📝 问题描述

微软翻译，每隔一段时间后，点击翻译，会出现翻译超时的错误，再次点击翻译时又恢复了正常。
![image](https://user-images.githubusercontent.com/69134368/209910129-fe71b55b-ebb4-4529-8af5-2a5adafff59f.png)

### 🏷 插件版本

3.4.0

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
```

**Comment by YiiGuxing** [comment]
网络超时没办法，文档翻译只给3秒钟的时间。
