### ISSUE TITLE
谷歌翻译可以改成国外的api吗

### ISSUE THREAD

**Issue by Elziy** [YiiGuxing/TranslationPlugin#2936]
### 需求/建议描述

替换无法使用的谷歌翻译

### 建议的解决方案

谷歌翻译.cn已经不支持了，但是.com可以使用，能不能把api换成.com的

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/discussions/2315#discussioncomment-3949785

**Comment by Elziy** [comment]
感谢，api没走代理
