### ISSUE TITLE
TKK: Failed to update TKK. (Copy to Clipboard)

### ISSUE THREAD

**Issue by lbintom** [YiiGuxing/TranslationPlugin#297]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by lbintom** [comment]
TKK: Failed to update TKK. (Copy to Clipboard)
是不是更新2019.2的原因 无法使用

**Comment by YiiGuxing** [comment]
检查一下代表设置。检查一下是不是勾选了使用translate.google.com这个选项。
