### ISSUE TITLE
阿里翻译无法使用

### ISSUE THREAD

**Issue by TXMengXue** [YiiGuxing/TranslationPlugin#2976]
### 📝 问题描述

![image](https://user-images.githubusercontent.com/119848825/211135548-ea477f3d-dc3d-474e-ac7a-e3455932e4af.png)

### 🏷 插件版本

3.4.1

### 🔁 翻译引擎

阿里翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
内部版本号 #IU-222.4345.14，2022年10月5日 构建
运行时版本: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o
```

**Comment by YiiGuxing** [comment]
我这边并不能重现这个问题呢，你看看是不是`APP ID`或者`APP KEY`是不是正确配置了？
