### ISSUE TITLE
idea社区版2019.2: TKK: Failed to update TKK

### ISSUE THREAD

**Issue by wlh3133** [YiiGuxing/TranslationPlugin#299]
Idea社区版，2019.1版正常使用，昨天刚升级到2019.2后翻译出现问题
操作系统：MacOS 10.14.6
Idea版本：IntelliJ IDEA Community 2019.2 for macOS x64 
弹窗查词显示“Querying”，然后在EventLog中显示“TKK: Failed to update TKK”

**Comment by YiiGuxing** [comment]
检查一下是不是勾选了使用translate.google.com这个选项。

另外，你的系统环境是不是英文的？

**Comment by Jxh98** [comment]
我也遇到这个问题了，我的系统环境是英文的。

**Comment by YiiGuxing** [comment]
请取消勾选`使用translate.google.com`这个选项，如果系统环境不是中文的话，这个选项会被默认勾选的，我说怎么有那么多人都遇到这个问题呢。

**Comment by wlh3133** [comment]
OK，明天去办公室试一试，非常感谢！

**Comment by whiteGu** [comment]
昨天升级到2019.2版本，下载最新的也遇到了这个问题，我的配置也没有勾选translate.google.com这个选项，同时主语言也是Chinese；但是翻译报错TKK: Failed to update TKK.

**Comment by YiiGuxing** [comment]
@whiteGu 那你这个就是真网络问题了，检查一下网络环境吧，你这类的Issue很多，你可以去看看。

**Comment by Jxh98** [comment]
```2019.2.1```  确实可能有点问题，我设置了 ```setting repository``` 后，```translation``` 就无法使用了 。
注：  取消勾选了 ``` translate.google.com ```
（当然也可能是别的问题） 

个人的解决办法，删除 ```setting repository ```，这样貌似会重置配置文件。

**Comment by YiiGuxing** [comment]
@Jxh98 你这个很有可能是代理的问题，还是你网络环境的问题，我这边2019.2.1的，没有什么问题啊。

再次申明，网络的问题和插件是没有关系的，插件只是依赖于网络，网络出现问题插件自然是无法使用的。

**Comment by shi1234** [comment]
我用的是mac版，在preferences->other Settings->Translation取消勾选“使用translate.google.com”就正常了。
