### ISSUE TITLE
单词本功能优化

### ISSUE THREAD

**Issue by vission8899** [YiiGuxing/TranslationPlugin#2991]
### 需求/建议描述

在全项目中 所有在单词本数据库里的单词  都自动翻译  

这样可以增加对单词的印象与记忆 不然单词本的功能比较孱弱 基本上放进单词本的单词都吃灰了 下次碰到也不知道是个啥 

### 建议的解决方案

形式是【鼠标放上去自动展示翻译结果 项目中保留原文】

**Comment by vission8899** [comment]
好吧 我是想着启动的时候就把单词本刷进map里，每打开一个.java就扫一下map 不太懂插件的设计 实现不了有点可惜了🙁

**Comment by vission8899** [comment]
或者说 仅仅是标记出 在单词本内 也不可以吗？

**Comment by YiiGuxing** [comment]
> 或者说 仅仅是标记出 在单词本内 也不可以吗？

访问单词本是IO操作，大量的操作会影响IDE的性能的，而且这样做的意义并不大，现在的工作重点也并不在单词本上。
