### ISSUE TITLE
修改成java6，偶尔会闪退

### ISSUE THREAD

**Issue by wang153723482** [YiiGuxing/TranslationPlugin#3]
你好，我把java8新特性的相关语句修改为java6以后，可以正常使用，但是**偶尔**会闪退。
选中单词，右键，点击翻译以后，弹出来的窗口直接闪退了，能隐约看到单词已经翻译过来了。
请问能否指点一二，是哪里漏改了么？

![aaaaaaa](https://cloud.githubusercontent.com/assets/1320312/16939349/6c493892-4db3-11e6-8243-9ceb39768096.gif)

**Comment by YiiGuxing** [comment]
@wang153723482   呃。。。这其实并不是你改出来的，是原本就有的，而且我也早就遇到过的，只是没有时间修改。因为我使用了非模状对话框，并在对话框失去焦点的时候把对话框关掉了。所以原因可能是打开对话框后由于某种原因导致对话框失去了焦点。后面我会修复这一问题的，或者你可以尝试修复这一问题。如果你修复了这个问题，还请麻烦你告知修复方法，或者提交pull request，谢谢！

**Comment by wang153723482** [comment]
@YiiGuxing 好的，十分感谢。如果我搞定了我告诉你。

**Comment by YiiGuxing** [comment]
在新的版本中已去除了此对话框的自动关闭。
