### ISSUE TITLE
TKK: Failed to update TKK. 

### ISSUE THREAD

**Issue by Bohr-H** [YiiGuxing/TranslationPlugin#300]
这两天遇到一个问题，插件不能用了，之前一直用得好好的，但自从前两天APPCode更新到2019.2没用之前的配置重新下载之后就一直提示这个错误。插件版本是2.3.8。请问是什么原因，我又该如何解决呢

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/62425919-42874880-b711-11e9-9d44-c6558859801e.png)
duplicate: #299

**Comment by Bohr-H** [comment]
抱歉，没注意看之前的issue，按照299您所说的关掉“使用translate.google.com<http://translate.google.com>”确实就可以了，不过现在又有一个问题，我记得之前那个选项我也是一直打开的而且从来没有出现过任何问题，请问一下这是为什么呢？

Yii.Guxing <notifications@github.com<mailto:notifications@github.com>> 于2019年8月4日周日 下午11:41写道：

[image]<https://user-images.githubusercontent.com/10737066/62425919-42874880-b711-11e9-9d44-c6558859801e.png>
duplicate: #299<https://github.com/YiiGuxing/TranslationPlugin/issues/299>

**Comment by YiiGuxing** [comment]
因为新版需要访问谷歌新的API，google.com的国内已被墙

**Comment by Bohr-H** [comment]
非常感谢您能一直回复解答我的疑惑。我之所以敢勾选那个选项（包括之前），是因为我一直挂着工具，但这个问题只在我更新IDE重装插件后出现，所以我才特别好奇。不过现在不选“google.com”就能用了，我也不打算再纠结了，谢谢您。
在 2019年8月5日 +0800 08:42，Yii.Guxing <notifications@github.com>，写道：

因为新版需要访问谷歌新的API，google.com的国内已被墙

**Comment by YiiGuxing** [comment]
不客气
