### ISSUE TITLE
窗口小于文字宽度， 导致右侧文字被遮挡隐藏

### ISSUE THREAD

**Issue by Joehaivo** [YiiGuxing/TranslationPlugin#301]
## Preflight Checklist

* [1 ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ 1] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details
窗口小于文字宽度， 导致右侧文字被遮挡隐藏
### Environment & Stack Trace
- Plugin version: 2.3.7
- IDE version: Android studio 3.4.2
- Operating System and version: Macos 10.14.4
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
duplicate: #292
