### ISSUE TITLE
添加外网环境的Google翻译（https://translate.google.com/）选项

### ISSUE THREAD

**Issue by guiyuanyuanbao** [YiiGuxing/TranslationPlugin#3011]
### 需求/建议描述

希望可以给出Google翻译的url选项，虽然Google翻译在国内的服务停止了，但是像我这样平时一直在外网环境里的还是可以访问外网的Google翻译（https://translate.google.com/）

### 建议的解决方案

希望可以给出Google翻译的url选项，可以选择外网的Google翻译（https://translate.google.com/）的api

**Comment by YiiGuxing** [comment]
谷歌翻译API的域名早就已经不分什么国内或者国外的了，就只有一个，它会自动访问离你最近的谷歌云节点，然而国内的谷歌云已经不再提供翻译服务了，所以无法使用。如果你想访问国外的谷歌云结点，那就让API走外网就行了，挂梯子什么的就行了。详情请另参阅：

https://github.com/YiiGuxing/TranslationPlugin/discussions/2315#discussioncomment-3949785
