### ISSUE TITLE
网断情况下不提示网络连接错误，提示未知错误

### ISSUE THREAD

**Issue by CHN-STUDENT** [YiiGuxing/TranslationPlugin#302]
### Preflight Checklist

* - I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* - I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

WIFI断了显示未知错误？
![image](https://user-images.githubusercontent.com/21209416/62669169-36291700-b9c1-11e9-82d4-c89ccabca13a.png)
![image](https://user-images.githubusercontent.com/21209416/62669176-404b1580-b9c1-11e9-956c-8c5d2d21422a.png)

### Proposed Solution

我重新连接WIFI又能查询了，但是还是建议提示网络断了。
或者您有什么好建议呢，感谢！

**Comment by YiiGuxing** [comment]
感谢反馈！
