### ISSUE TITLE
总是提示翻译失败，一次没成功。

### ISSUE THREAD

**Issue by bbhxwl** [YiiGuxing/TranslationPlugin#3084]
### 📝 问题描述

总是提示翻译失败，一次没成功。
也看不出来什么问题。
就是按照使用教程来的呢。

### 🏷 插件版本

最新版本

### 🔁 翻译引擎

微软翻译, 谷歌翻译, 百度翻译

### 💻 IDE及运行环境

```plain text
都是今天来说的最新版本。正版软件。
```

**Comment by YiiGuxing** [comment]
会不会是网络的问题？要不你提供一下失败的截图吧。

**Comment by bbhxwl** [comment]
> 会不会是网络的问题？要不你提供一下失败的截图吧。

可以了，可能是我刚装了2个翻译软件，有什么冲突吧，但是我设置了百度密钥，重启电脑，翻译怎么又让我输入密钥呢。

**Comment by scruel** [comment]
@YiiGuxing 谷歌用不了，微软老超时，deepl不支持免费版，只能卸载了。。。
