### ISSUE TITLE
不支持,在LogCal里面使用.希望大神能,做个支持

### ISSUE THREAD

**Issue by MaxQiuYang** [YiiGuxing/TranslationPlugin#31]
不支持,在LogCal里面使用.希望大神能,做个支持

**Comment by YiiGuxing** [comment]
@MaxQiuYang LogCal? 是AndroidStudio里的logcat吗？如果是logcat的话，最新版本是可以使用的，但不能通过右键使用，只能通过快捷键Alt+T翻译。
