### ISSUE TITLE
希望适配第三方idea插件documentationProvider节点

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#3106]
### 需求/建议描述

用户安装了这个翻译插件, 同时安装了另外一个idea插件, 另外那个插件使用自定义文档模块,导致无法翻译内容
用户提交的相关issue: [https://github.com/mdddj/dd_flutter_idea_plugin/issues/9](https://github.com/mdddj/dd_flutter_idea_plugin/issues/9)

### 建议的解决方案

不知道

### 附加信息

另一个插件的document注册节点: [https://github.com/mdddj/dd_flutter_idea_plugin/blob/master/src/main/resources/META-INF/plugin.xml#L126](https://github.com/mdddj/dd_flutter_idea_plugin/blob/master/src/main/resources/META-INF/plugin.xml#L126)

**Comment by mdddj** [comment]
其实去年我也提出过一个类似的问题: https://github.com/YiiGuxing/TranslationPlugin/issues/1522

**Comment by YiiGuxing** [comment]
我已为我的 `DocumentationProvider` 提供了一个ID，你可以将你 `DocumentationProvider` 的 `order` 属性修改为以下内容即可：
```
order="first, after Translation.TranslatedDocumentationProvider"
```

该功能在插件 `v3.4.2` 版本中提供，发布后方可用。

**Comment by YiiGuxing** [comment]
你可以使用这个包进行测试：[TranslationPlugin-3.4.2-SNAPSHOT.230219.zip](https://github.com/YiiGuxing/TranslationPlugin/files/10776990/TranslationPlugin-3.4.2-SNAPSHOT.230219.zip)

**Comment by mdddj** [comment]
大佬幸苦,设置之后好像并没有起作用
```xml
<lang.documentationProvider implementationClass="shop.itbug.fluttercheckversionx.document.DartDocumentExt"
                                    language="Dart" order="first, after Translation.TranslatedDocumentationProvider.Dart"/>
```
![image](https://user-images.githubusercontent.com/29020213/220228700-b2f6e0d5-4193-43f1-aaa7-741d767faa56.png)
![image](https://user-images.githubusercontent.com/29020213/220228778-1995ef57-f331-4959-aff0-51ac00eb6d71.png)

**Comment by YiiGuxing** [comment]
我安装了你新发的[3.0.0](https://github.com/mdddj/dd_flutter_idea_plugin/releases/tag/3.0.0) 和我上面给的我的插件，发现是可以翻译了的啊，只是我这边有一个翻译超时，翻译时间超过3秒就不翻译了，所以有一点概率翻译失败。

![image](https://user-images.githubusercontent.com/10737066/220239282-6e3fbf56-7509-4b32-a42c-29c71491e8c9.png)

**Comment by mdddj** [comment]
👍多谢大佬,真的是网络问题
