### ISSUE TITLE
翻译没法显示音标

### ISSUE THREAD

**Issue by godotg** [YiiGuxing/TranslationPlugin#3113]
### 需求/建议描述

翻译的时候显示音标，英语翻译成汉语的时候希望把英语的音标显示出来，因为大部分人都是看音标的。

### 建议的解决方案

翻译的时候显示音标

**Comment by YiiGuxing** [comment]
是否显示音标是要看翻译引擎的，还要看翻译内容的，翻译结果有音标的现在都已经显示出来了的，如果没有显示，就说明该翻译引擎或者翻译内容不支持音标。一般情况下，谷歌翻译和有道翻译是支持有音标的。
