### ISSUE TITLE
能不能增加默认添加单词本选项，再就是文档里IDE拼错了

### ISSUE THREAD

**Issue by Darling012** [YiiGuxing/TranslationPlugin#313]
### Preflight Checklist

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
谢谢反馈，拼写错误改回来了。但是这个“默认添加单词本”我觉得不太好，可能会导致单词本过于臃肿。

**Comment by Darling012** [comment]
我的想法是，最终的目的还是能够多记单词，达到看javadoc api 不需要再利用工具翻译的目的。

**Comment by YiiGuxing** [comment]
主要是这样的操作可能太过频繁了，而且加入单词本的词句是有限制的，并不是任何内容都可以添加。
