### ISSUE TITLE
单词本可以导出TXT吗?

### ISSUE THREAD

**Issue by Invoker-liu** [YiiGuxing/TranslationPlugin#315]
单词本功能真的很棒,但是有时候需要将单词放到其他的单词工具里面,想问问能不能支持下简单的导出,感觉TXT就能满足大部分需求,谢谢您的无私奉献,祝好运!

**Comment by YiiGuxing** [comment]
后面会有的，可以导出XML、有道XML、JSON等格式，敬请期待！

**Comment by Invoker-liu** [comment]
> 后面会有的，可以导出XML、有道XML、JSON等格式，敬请期待！

谢谢回复,后面感觉功能牛逼哄哄呀!期待更好的功能!

**Comment by YiiGuxing** [comment]
feature: #334
