### ISSUE TITLE
单词本功能很棒! 能不能同步到扇贝单词, 这样就可以一起学习了!

### ISSUE THREAD

**Issue by earlzo** [YiiGuxing/TranslationPlugin#320]
### Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

单词本功能很棒! 能不能同步到扇贝单词, 这样就可以一起学习了!

### Proposed Solution

- 配置扇贝网的 cookie
- 调用生词本的 API 同步单词

### Additional Information

Chrome 翻译插件 https://github.com/waynecz/dadda-translate-crx 也支持同步

**Comment by YiiGuxing** [comment]
插件后面会支持数据导出，至于同步到其他平台，这个暂不考虑。

**Comment by YiiGuxing** [comment]
feature: #334
