### ISSUE TITLE
[Feature Request] On IDEA tab `Structure`, show the translation of all the functions, members and other

### ISSUE THREAD

**Issue by pytkr** [YiiGuxing/TranslationPlugin#3221]
### 需求/建议描述

_Reason_: the outline of a file is very useful, however the translation can bring it to a new level.

_Cost_: the content in tab `Structure` is concise, and the automatical translation will not need high cost.

_Benifit_: glance new code seconds to grasp key contents of it.

### 建议的解决方案

_Effect_: dispaly translation like plugin `show comment`, here is the [link](https://plugins.jetbrains.com/plugin/18553-show-comment) and preview
![screenshot_a8e15ef3-9ec5-492f-a803-3ebfd6ee426f](https://user-images.githubusercontent.com/45117726/221083389-96011261-40b3-412c-b300-d7c2f2790c2a.jpg)

**Comment by YiiGuxing** [comment]
The translation plugin is not considered to rely on any third-party plugins to implement certain functionality. However, some APIs will be opened to provide translation functionality for third-party plugins, which will be implemented in the future.
