### ISSUE TITLE
在What's new 中出现拼写错误 IDE 拼成了IED

### ISSUE THREAD

**Issue by czfadmin** [YiiGuxing/TranslationPlugin#325]
## Preflight Checklist

* [x ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details
![image](https://user-images.githubusercontent.com/13393959/65156559-e595e680-da61-11e9-8113-b5c35e3a3f07.png)

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
嗯，感谢提醒，已经修正过来了，要等下一版本。
