### ISSUE TITLE
 建议增加谷歌翻译的自定义镜像地址

### ISSUE THREAD

**Issue by yangrongzhou** [YiiGuxing/TranslationPlugin#3266]
### 需求/建议描述

我有自己的镜像域名，使用谷歌翻译时就不需要在本机FQ了

### 建议的解决方案

增加一个输入框填写自定义镜像地址
![微信截图_20230308122252](https://user-images.githubusercontent.com/17780769/223619069-3998d83e-87ee-469b-af9c-8fde7dc691cc.png)

### 附加信息

edge浏览器有个扩展“划词翻译”，有一项就是可以配置谷歌翻译镜像地址，可以参考它。

**Comment by YiiGuxing** [comment]
插件没有添加镜像地址的原因：
1. 并不是很稳定；
2. 稳定的仍然需要魔法。
