### ISSUE TITLE
使用Deepl翻译器配置密钥提示密钥无效

### ISSUE THREAD

**Issue by CangShuKeJi** [YiiGuxing/TranslationPlugin#3271]
### 📝 问题描述

我在使用Deepl翻译器并配置密钥时，从我的账户中复制密钥到插件中却提示密钥无效

### 🏷 插件版本

3.4.1

### 🔁 翻译引擎

DeepL 翻译

### 💻 IDE及运行环境

```plain text
PyCharm 2022.1.3 (Professional Edition)
内部版本号 #PY-221.5921.27，2022年6月22日 构建
运行时版本: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
win 11
```

**Comment by YiiGuxing** [comment]
Deepl翻译需要Deepl PRO账号才行

**Comment by CangShuKeJi** [comment]
已经是DeepL API Free类帐户了也不可以吗
![image](https://user-images.githubusercontent.com/125885065/223935890-f38255e4-ce19-4227-be4b-9da41e728efd.png)

**Comment by YiiGuxing** [comment]
也是需要 Deepl PRO 的 FREE 计划。。。

**Comment by CangShuKeJi** [comment]
Advanced计划的呢 我用Advanced计划的账号也提示密钥无效

**Comment by CangShuKeJi** [comment]
是只有DeepL API Pro计划才可以吗

**Comment by YiiGuxing** [comment]
DeepL 有 Advanced计划吗？这个我就不清楚了，插件在实现的时候按Pro实现的，不清楚它是否添加了新的计划。

**Comment by oomgomgxx** [comment]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/58796445/226532091-c92c61de-c23f-4a86-8eaa-9abeebb0b712.png">
账号无效

**Comment by YiiGuxing** [comment]
非常抱歉，关于DeepL账号的问题我也无法解答。如需要帮助，可以到 #472 上求助。
