### ISSUE TITLE
建议添加chatgpt的翻译支持

### ISSUE THREAD

**Issue by skymilong** [YiiGuxing/TranslationPlugin#3277]
### 需求/建议描述

建议添加chatgpt的翻译支持

### 建议的解决方案

通过调用API实现

**Comment by UpDownXH** [comment]
+1，正要发issue，就发有了，强烈建议添加chatgpt支持，那个翻译吊打其他翻译了

**Comment by skymilong** [comment]
类似这种提示：translate `translate` to Chinese in {}

**Comment by CrazyBunQnQ** [comment]
同求，翻译体验你家最强~

**Comment by YiiGuxing** [comment]
开发中。。。

**Comment by strange-qwq** [comment]
> 开发中。。。

建议加一个new bing的翻译支持，只需要登bing账号就能免费用了，可以参考隔壁浏览器插件：https://github.com/chathub-dev/chathub
![image](https://user-images.githubusercontent.com/73089181/230771462-7a80da51-c475-4970-9038-096766127e1d.png)

**Comment by YiiGuxing** [comment]
功能已经开发完成，欢迎抢先体验：
- IDEA 2021.3 +: [TranslationPlugin-3.5.0-SNAPSHOT.230418.zip](https://github.com/YiiGuxing/TranslationPlugin/files/11257906/TranslationPlugin-3.5.0-SNAPSHOT.230418.zip)
- IDEA 2020.3 ~ 2021.2: [TranslationPlugin-3.5.0-SNAPSHOT.230418+203u212.zip](https://github.com/YiiGuxing/TranslationPlugin/files/11257905/TranslationPlugin-3.5.0-SNAPSHOT.230418%2B203u212.zip)

> **Note**
>
> 注意：文档翻译功能将会消耗大量的 `Token`，建议关闭 `自动翻译文档` 功能。

**Comment by YiiGuxing** [comment]
See commit: 4b60cfef7f9b5269ae77fca668e43efc291d4b0b
