### ISSUE TITLE
Idea2019 2.2版本显示无相关服务的有效实例

### ISSUE THREAD

**Issue by zookfish** [YiiGuxing/TranslationPlugin#329]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description
我配置了有道翻译的秘钥，有道官网的秘钥状态也是显示有效的。但是在idea选中单词，无法翻译，直接报"翻译失败：无相关服务的有效实例"

### Environment & Stack Trace
- Plugin version:2.4.0
- IDE version:2019 2.2
- Operating System and version: mac os 10.14.5 
- Stack Trace (for crash):  
     6:11 下午	Translate Error: 翻译失败: 无相关服务的有效实例 (Copy to Clipboard)

    6:11 下午	Translate Error: 翻译失败: 无相关服务的有效实例 (Copy to Clipboard)

    6:11 下午	Translate Error: 翻译失败: 无相关服务的有效实例 (Copy to Clipboard)

    6:11 下午	Translate Error: 翻译失败: 无相关服务的有效实例 (Copy to Clipboard)

    6:12 下午	TKK: 更新TTK失败，请检查网络连接 (Copy to Clipboard)

**Comment by YiiGuxing** [comment]
有道的服务有一定的延迟
