### ISSUE TITLE
如何修改api key

### ISSUE THREAD

**Issue by qifanyang** [YiiGuxing/TranslationPlugin#33]
用的人原来越多了,提示请求频繁,更换API KEY

**Comment by wahyip** [comment]
同样的问题~ 然后去有道申请了另外的key后, 返回结果直接是Nothing

**Comment by YiiGuxing** [comment]
![qq20161212-172154](https://cloud.githubusercontent.com/assets/10737066/21094032/e2c27674-c08f-11e6-8827-1eb08f429c13.png)

**Comment by YiiGuxing** [comment]
@wahyip 是不是你的key有问题，或者没有设置成功？再申请一个试试，我刚试了一下，是没问题的。

**Comment by wahyip** [comment]
@YiiGuxing 可以了, 是有道那边的问题, 申请了key后, 隔了几分钟key才有效~
