### ISSUE TITLE
希望出个单独的Mac版本

### ISSUE THREAD

**Issue by Mora-na** [YiiGuxing/TranslationPlugin#3303]
### 需求/建议描述

希望出个单独的Mac版本，集成到状态栏，如果能集成到右键菜单就更完美了。很喜欢这个页面
<img width="732" alt="image" src="https://user-images.githubusercontent.com/41199418/225801297-99539dbe-a2ae-46d9-9354-451c71730f49.png">

### 建议的解决方案

希望出个单独的Mac版本，集成到状态栏，如果能集成到右键菜单就更完美了。

**Comment by YiiGuxing** [comment]
你喜欢这个插件我感到很荣幸，不过由于个人的精力有限，暂时没有出桌面版本的打算。。。
