### ISSUE TITLE
提示：更新 TKK 失败，请检查网络连接

### ISSUE THREAD

**Issue by hakusai22** [YiiGuxing/TranslationPlugin#3309]
### 📝 问题描述

我已经修改为网易翻译了，单词都能翻译，但是点语言的时候就直接报（提示：更新 TKK 失败，请检查网络连接）

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/58761705/226098640-9165c1e0-84ed-4bc0-a931-2bb916f57def.png">

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/58761705/226098747-e6fc735f-cc86-499c-b5a1-779a429aae23.png">

### 🏷 插件版本

最新1

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
2021q
```

**Comment by YiiGuxing** [comment]
语音使用的还是谷歌的，详见：#2315
