### ISSUE TITLE
希望提供vscode 版本的TranslationPlugin 

### ISSUE THREAD

**Issue by suddenlyyo** [YiiGuxing/TranslationPlugin#3325]
### 需求/建议描述

现在习惯用idea 社区版 但是社区版有一些功能没有，比如rust 社区版是不让调试的，就会使用替代的ide——>vscode,但是它没有一个好的翻译插件，习惯了idea中的TranslationPlugin 后，使用vscode 真的很折磨人.如果可以希望可以提供一个vscode版本的TranslationPlugin 

### 建议的解决方案

提供一个vscode版本的TranslationPlugin

**Comment by YiiGuxing** [comment]
Duplicate of #271
