### ISSUE TITLE
能否制定一个接口规范

### ISSUE THREAD

**Issue by dnslin** [YiiGuxing/TranslationPlugin#3327]
### 需求/建议描述

制定一个接口规范方便第三方开发者对接自己的翻译接口

### 建议的解决方案

一个http(s)的web接口 提供参数和规范 用户就可以自定义自己的翻译接口

**Comment by YiiGuxing** [comment]
这相关方面的工作已经在计划当中，预计会在4.0版本推出，但遗憾的是，我无法承诺具体时间。
