### ISSUE TITLE
对于翻译的一点奢望

### ISSUE THREAD

**Issue by Mr-9** [YiiGuxing/TranslationPlugin#336]
软件很好用，几乎现在编程有点离不开了。不过由于英文本身不太好，在起函数名的时候都是先输入中文，翻译后再复制粘贴上对应的英文。于是，我期望。大神能不能弄个快捷键。直接将翻译出的英文第一个词条自动替换我输入的中文。。。不知道我说的是不是很明白。也许是我要求的有点高了，毕竟免费使用了很长时间了，这只是我的一点小小的奢望。最后还是赞一下大神。仰慕中。。。。

**Comment by YiiGuxing** [comment]
...

[Actions](https://github.com/YiiGuxing/TranslationPlugin#actions)里的 `Translate and Replace...` Action 就是啊，右键菜单的第二项，这么明显的都没注意到么？:sweat_smile::sweat_smile::sweat_smile:

**Comment by Mr-9** [comment]
哇哇，，赞一个，我竟然今天才知道有这么好用的功能。。。。😅😅😅

**Comment by YiiGuxing** [comment]
这个能编辑的地方几乎都能用，没有左键菜单的时候就使用快捷键。
