### ISSUE TITLE
phpstorm 2019版本win10  密匙无法保存

### ISSUE THREAD

**Issue by 626167431** [YiiGuxing/TranslationPlugin#337]
## Preflight Checklist

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
你是不是选不保存密码了？

![image](https://user-images.githubusercontent.com/10737066/65474224-a1657480-dead-11e9-8c73-3f8e1b10ca76.png)

可以尝试将密码保存方式改成In KeePass方式 (Settings > Appearance & Behavior > System Settings > Passwords)

**Comment by 626167431** [comment]
谢谢  确实是这样解决的。 升级过2019后出现的问题
