### ISSUE TITLE
增加对方法/类描述的翻译支持

### ISSUE THREAD

**Issue by tianjindong** [YiiGuxing/TranslationPlugin#338]
非常感谢作者对该插件的开发，大大提升自己的工作效率。但是在IDEA中可以使用快捷键F2（Eclipse模式）打开方法或类的描述框，Translation插件无法对其进行翻译，只能对注释进行翻译，但是注释的每一行开头都有一个“*”，非常影响翻译效果。希望能对该功能进行加强，支持直接对描述框中的内容进行翻译！

**Comment by YiiGuxing** [comment]
只要能选择文本的地方都是可以翻译的，如果选择文本后没有右键菜单或者右键菜单上没有翻译项的，这时候就只能通过 `Translate Text Component` Action 来翻译，快捷键是 `Ctrl + Shift + Y` (现在才发面README上写的快捷键是错误的。。。)，详情见 [README Actions](https://github.com/YiiGuxing/TranslationPlugin#actions) 部分。

另外，关于对注释进行翻译，是可以配置忽略内容的，把 “*” “/” 这些字符忽略掉的，详情见插件配置页。

**Comment by YiiGuxing** [comment]
高级的支持请关注: #130
