### ISSUE TITLE
请问如何使用单词本功能

### ISSUE THREAD

**Issue by XinAnzzZ** [YiiGuxing/TranslationPlugin#339]
找了很久文档，和插件对应的设置，也没有学会单词本功能怎么用，只能来提 issiue 了。。

**Comment by YiiGuxing** [comment]
`What's New` 里的那一张GIF图片就说明了全部啊。。。

**Comment by YiiGuxing** [comment]
如果你看完后还是这么觉得：这有什么用的？
那么说明你没有相关的需求，忘了这个功能吧：右击 `Tool Window` 上的 `Word Book` -> `Remove from Sidebar`，哈！干净了！

其实我也用不着这个功能。。。:sweat_smile::sweat_smile::sweat_smile:

**Comment by XinAnzzZ** [comment]
了解了，谢谢。
