### ISSUE TITLE
重启idea密码会自动清除

### ISSUE THREAD

**Issue by HyggeBo7** [YiiGuxing/TranslationPlugin#3452]
### 📝 问题描述

idea版本： 2023.1
Translation插件：3.4.2
如图，idea重启后会自动清除密码，导致无法使用翻译。
![fy](https://user-images.githubusercontent.com/29586966/231328732-3a72430b-c252-4e56-825b-ae369c86f8bb.png)

### 🏷 插件版本

3.4.2

### 🔁 翻译引擎

阿里翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Windows 11.0
```

**Comment by YiiGuxing** [comment]
请另阅：https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key
