### ISSUE TITLE
可以不要在状态栏显示那么长的"解释"吗?

### ISSUE THREAD

**Issue by sunfuhong** [YiiGuxing/TranslationPlugin#3454]
### 📝 问题描述

这种行为像随地大小便

### 🏷 插件版本

3.4.0

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
GoLand
```

**Comment by YiiGuxing** [comment]
呃。。。我的插件并没有在状态栏显示什么"解释"啊，除了一个小图标，这个图标也不会很长的。或者你贴个截图，我帮你看看那是什么。

**Comment by sunfuhong** [comment]
大概意思是说google很没品直接关闭引擎导致啥啥啥的吧，然后建议啥啥啥的，然后状态栏一直留着那行文字，写代码的时候屏幕的最左到最有都是那句话，关键是还没显示完。。。

**Comment by YiiGuxing** [comment]
哦，你是说这个通知啊，通知最下面就一个“不再显示”，你点一下，下次它就不会再出现了，或者你切换一下翻译引擎，反正google翻译也用不了。。。。
