### ISSUE TITLE
[FR] 添加对 ProtoBuf 支持

### ISSUE THREAD

**Issue by zjns** [YiiGuxing/TranslationPlugin#3468]
### 需求/建议描述

添加对 ProtoBuf 协议对应的描述文件 `.proto` 注释翻译的支持。

### 建议的解决方案

适配 `.proto` 文件注释。 

### 附加信息

<img width="789" alt="image" src="https://user-images.githubusercontent.com/10793522/232199210-bb30b7ee-6a3e-4bf5-a2de-c94bd1632c74.png">

`Android Studio Giraffe | 2022.3.1 Canary 11` 上测试尚未支持。

**Comment by YiiGuxing** [comment]
由于ProtoBuf的所有文档都被认为是代码片段，所以其文档不会被翻译。
