### ISSUE TITLE
【有道翻译】添加领域化翻译支持

### ISSUE THREAD

**Issue by huangxingzhao** [YiiGuxing/TranslationPlugin#3486]
### 需求/建议描述

有道翻译可以添加专业领域如计算机领域，现在插件并没有办法去配置领域，大多数情况下，阅读源码使用的翻译结果都不尽人意。

### 建议的解决方案

允许用户自定义配置领域，然后再调用API的时候加上对应字段就可以了，这个工作量不大

**Comment by huangxingzhao** [comment]
或者更直接的，在每种API调用都留给用户添加自定义字段的方式，这样不管以后API平台有什么改动，插件也能很方便的使用上新的API

**Comment by YiiGuxing** [comment]
👌
