### ISSUE TITLE
clion 翻译不起作用

### ISSUE THREAD

**Issue by bainian** [YiiGuxing/TranslationPlugin#3496]
### 需求/建议描述

1、clion 上的 c++注释光标停留文档自动翻译一直不起作用还是显示原文，不知道是不是设置的问题还是没支持呢？
2、dart 语言的以// 标记的文档注释能不能也支持一下停留自动翻译呢？

### 建议的解决方案

希望支持 clion 中的 c++文档注释。

**Comment by YiiGuxing** [comment]
1. Duplicate of #1986
2. 只会翻译文档注释，一般注释是不翻译的，两者不一样。
