### ISSUE TITLE
建议为每个翻译引擎添加超时时间配置

### ISSUE THREAD

**Issue by skymilong** [YiiGuxing/TranslationPlugin#3497]
### 需求/建议描述

给每个翻译引擎添加一个可配置的 响应超时时间，减少因为网络影响导致的报错，按自己网络情况来控制效果会更好

### 建议的解决方案

添加超时时间配置

**Comment by YiiGuxing** [comment]
这部分应该是要从流程上进行优化，配置这个时间并不能解决问题。

**Comment by skymilong** [comment]
> 这部分应该是要从流程上进行优化，配置这个时间并不能解决问题。

em....但毕竟都是走三方API，可能接口是正常的，但是响应时间超过现在的默认配置的了 就直接报错了

**Comment by YiiGuxing** [comment]
这其中逻辑还是比较复杂的，不是简单配置超时时间就能行的，后面会从流程上慢慢优化的。
