### ISSUE TITLE
翻译提示“更新tkk失败，请检查网络链接”

### ISSUE THREAD

**Issue by gaoxinlei** [YiiGuxing/TranslationPlugin#351]
idea版本2019.2
之前是都正常的，最近发现使用插件翻译时，必报“更新tkk失败，请检查网络连接”，更换多次网络无用，电脑除使用本翻译插件外，连网都是正常的。
![image](https://user-images.githubusercontent.com/29565085/65741843-3e2f4880-e120-11e9-90be-3fb57a0209ef.png)

**Comment by gaoxinlei** [comment]
插件版本是2.4.1，最新了。@YiiGuxing

**Comment by YiiGuxing** [comment]
网络的问题与插件无关，请查阅 [`network`](https://github.com/YiiGuxing/TranslationPlugin/issues?q=label%3A%22network+%3Asatellite%3A%22+is%3Aclosed) 相关的 issue.

**Comment by YiiGuxing** [comment]
请查询一下是否勾选了 “使用google.com”的选项

**Comment by gaoxinlei** [comment]
> 请查询一下是否勾选了 “使用google.com”的选项
我刚刚注意到原来可以选择翻译代理，试了有道和百度，需要申请还要花钱，建了个实例和服务，一绑上马上可以用有道了。
然后到谷歌的设置界面，关了使用translate.google.com，马上就可以了。
谢谢回复。

**Comment by WeiSenhui** [comment]
取消勾选
![image](https://user-images.githubusercontent.com/46078304/73133059-7eff8580-405e-11ea-873b-86bccab8b680.png)

**Comment by Laeeb** [comment]
> 请查询一下是否勾选了 “使用 google.com”的选项

我检索了很多答案没有解决我的问题。我用的是2021.3版本的。后来才知道我的问题是因为我开了魔法软件。只需要设置 "自动检测代理" 就行了。 (修改的的路径附图 : https://sm.ms/image/vAlWQpou9qGk34e)
