### ISSUE TITLE
不能记着密钥

### ISSUE THREAD

**Issue by lkmtdgt** [YiiGuxing/TranslationPlugin#3511]
### 📝 问题描述

每次Android studio 重启后 密钥都要重新填写。
我的ide 版本
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 202

### 🏷 插件版本

最新版

### 🔁 翻译引擎

谷歌翻译, 有道翻译, 百度翻译

### 💻 IDE及运行环境

```plain text
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 202
```

**Comment by YiiGuxing** [comment]
请参考：https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key
