### ISSUE TITLE
音标乱码问题

### ISSUE THREAD

**Issue by kangningliu** [YiiGuxing/TranslationPlugin#352]
音标显示有问题，知道啥意思读不出来也是蛮尴尬的。就凭着音标把它读出来呢。

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/65827285-3cea5100-e2c3-11e9-8d8f-536bd74f2828.png)
![image](https://user-images.githubusercontent.com/10737066/65827297-5b504c80-e2c3-11e9-998b-1c1f7b5003e7.png)

**Comment by YiiGuxing** [comment]
在新建Issue的时候都有这么一个 **Preflight Checklist** ：

## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

请先执行完 **Preflight Checklist** 里的操作再提Issue，谢谢！
