### ISSUE TITLE
在IDEA2019.2.3的新版本中出现错误，无法启动插件

### ISSUE THREAD

**Issue by 18905059768** [YiiGuxing/TranslationPlugin#353]
![批注 2019-09-30 111745](https://user-images.githubusercontent.com/30982989/65847410-04568000-e374-11e9-8084-e557e8b77bcc.png)

**Comment by 18905059768** [comment]
![批注 2019-09-30 112624](https://user-images.githubusercontent.com/30982989/65847693-28669100-e375-11e9-8c00-50968a49b2e6.png)

**Comment by YiiGuxing** [comment]
请将插件更新到v2.4.1以上的版本

**Comment by 18905059768** [comment]
好的，谢谢，该问题是IDEA没有主动推送更新，导致该组件一直不能使用。现在到https://plugins.jetbrains.com/plugin/8579-translation/versions下载了最新版，并且可以使用了。
