### ISSUE TITLE
百度翻译的秘钥每次重启idea都要重新输入

### ISSUE THREAD

**Issue by Liangyongqi** [YiiGuxing/TranslationPlugin#3552]
### 📝 问题描述

百度翻译的秘钥每次重启idea，或者重启电脑之后，都会需要填入秘钥。应该是没有保存。这导致我每次都要输入。

### 🏷 插件版本

3.4.2

### 🔁 翻译引擎

百度翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
```

**Comment by YiiGuxing** [comment]
请参阅：https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key
