### ISSUE TITLE
单词本窗口关闭后，从哪里再次打开？

### ISSUE THREAD

**Issue by 258917407** [YiiGuxing/TranslationPlugin#356]
在单词本的设置窗口中不小心移除了单词本，  单词本从Android Studio右下角那里消失了，在IDE的设置里File ->Settings -> Other Settings ->Translation 也没有找到有关单词本打开或者关闭的选项。

**Comment by YiiGuxing** [comment]
主菜单栏>view>toolwindows

**Comment by 258917407** [comment]
搞定了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yii.Guxing"<notifications@github.com&gt;; 
发送时间: 2019年10月4日(星期五) 中午12:48
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com&gt;; 
抄送: "伪妳メ鈊動ン"<258917407@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 单词本窗口关闭后，从哪里再次打开？ (#356)




主菜单栏&gt;view&gt;toolwindows
