### ISSUE TITLE
webstorm 最新版2019.2.3无法使用，一打开webstorm就停止，插件用的是最新版

### ISSUE THREAD

**Issue by lvzegeng** [YiiGuxing/TranslationPlugin#357]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
请使用2.4.2以上的版本

**Comment by lvzegeng** [comment]
2.4.2是指插件的版本吗




------------------ 原始邮件 ------------------
发件人: "Yii.Guxing"<notifications@github.com>; 
发送时间: 2019年10月5日(星期六) 中午1:29
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>; 
抄送: "吕泽耿"<13025214712@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YiiGuxing/TranslationPlugin] webstorm 最新版2019.2.3无法使用，一打开webstorm就停止，插件用的是最新版 (#357)




请使用2.4.2以上的版本

**Comment by YiiGuxing** [comment]
是的
