### ISSUE TITLE
账号存储方式

### ISSUE THREAD

**Issue by wangtaicheng** [YiiGuxing/TranslationPlugin#359]
能不能把有道和百度翻译的应用id、应用密钥存储到单词本的位置，这样多个IDE就可以共享了

**Comment by YiiGuxing** [comment]
API密钥最好还是使用IDE的安全存储API，这样要安全一点，不然就得明文存储了，而且API密钥填写的频率很小，没有多大的必要。

**Comment by wangtaicheng** [comment]
ok
