### ISSUE TITLE
IntelliJ IDEA 2017.1 EAP 上崩溃无法使用

### ISSUE THREAD

**Issue by sblig** [YiiGuxing/TranslationPlugin#36]
IntelliJ IDEA 2017.1 EAP
Build #IU-171.2014.21, built on December 29, 2016
IntelliJ IDEA EAP User
Expiration date: January 28, 2017
JRE: 1.8.0_112-release-b621 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by YiiGuxing** [comment]
重复：#35

**Comment by YiiGuxing** [comment]
问题已经被修复，由于IntelliJ IDEA 2017现在还只是预览版本，或许还会有其他的问题，并不可靠，所以没有发布新的版本。

**Comment by YiiGuxing** [comment]
v1.3.3中已修复
