### ISSUE TITLE
每一次重启idea后应用密钥变为空,需要重新设置应用密钥才能使用

### ISSUE THREAD

**Issue by 8126** [YiiGuxing/TranslationPlugin#363]
![image](https://user-images.githubusercontent.com/14340643/66631109-22f02d00-ec38-11e9-84d8-3b7a85ae89b8.png)
百度翻译与有道翻译都需要重新设置应用密钥
离线安装或者在线安装都出现该问题

**Comment by YiiGuxing** [comment]
请阅读README中的FAQ部分

**Comment by 8126** [comment]
原来是常见问题,需要设置一下,谢谢!
