### ISSUE TITLE
没有vscode的划词翻译好用

### ISSUE THREAD

**Issue by wangheng669** [YiiGuxing/TranslationPlugin#3646]
### 需求/建议描述

vscode双击或者选中某个单词在右下角就会出现单词的解释,比右击然后点击翻译或者使用快捷键要方便好多
能加上这个功能吗,还是说不支持这种操作

### 建议的解决方案

和vscode一样

**Comment by YiiGuxing** [comment]
翻译操作是一个 "Action" ，"Action" 在 IDE 上你可以自定其触发操作，包括键盘事件、鼠标事件（自然也就包括双、单击事件），具体可以在 IDE 的 “keymap” 上进行绑定，而无需在插件上实现。

**Comment by YiiGuxing** [comment]
一个还不怎么成熟的想法：#3787
