### ISSUE TITLE
不能播放语音

### ISSUE THREAD

**Issue by WangChenPeng** [YiiGuxing/TranslationPlugin#366]
最新版idea 最新版插件 选择有道
翻译等功能均ok
点喇叭图标播放声音时 一直显示下载tts 随后time out
idea挂http梯子可以正常播放声音
怀疑下tts是墙外地址,
之前用2018.3版本的时候 当时那个最新版的翻译插件 选择有道 播放不会被墙

**Comment by YiiGuxing** [comment]
tts使用的是google的API，你看看是不是勾选了google.com这个选项，勾选了这个就是用墙外地址。

**Comment by WangChenPeng** [comment]
试了下ok了,从有道切换到google翻译 然后 取消勾选使用google.com翻译 再选择有道就可用了.
