### ISSUE TITLE
百度翻译，大写正常，小写出错

### ISSUE THREAD

**Issue by Grainfills** [YiiGuxing/TranslationPlugin#371]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

![image](https://user-images.githubusercontent.com/37177191/67263129-c9aab800-f4d9-11e9-9d86-8d77a312aa3d.png)

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/67280541-f8d42000-f4ff-11e9-9f78-7e2da397f7cd.png)
我这好的啊

**Comment by Grainfills** [comment]
@YiiGuxing 
今天正常了。。。玄学bug，另外两个都是正常，昨天怎么重试都是这个小精灵、搞得人懵懵的。感谢大佬回复，现在正常了。我关闭了
