### ISSUE TITLE
问题：开启VPN与关闭都是失败的情况

### ISSUE THREAD

**Issue by WuChenDi** [YiiGuxing/TranslationPlugin#3721]
### 📝 Issue Description

作者您好，很抱歉打扰到您。
我想请教一下，当我的网络超时时，我尝试了切换不同的网络、重启路由器以及使用手机热点和 VPN，但是 Microsoft Translator 仍然无法正常工作。请问您是否知道目前 Microsoft Translator 的支持情况？
非常感谢您的帮助。

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/31385662/6e07ff63-0c51-4e9c-bc42-3f3e5ff935a3)

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/31385662/b0279939-c505-4b07-aeea-1d8317da5352)

### 🏷 Plugin Version

3.4.2

### 🔁 Translation Engine(s)

Microsoft Translator

### 💻 IDE and Operating Environment

```plain text
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
```

**Comment by YiiGuxing** [comment]
微软翻译是不需要VPN就能使用的，你关闭VPN试试。

**Comment by WuChenDi** [comment]
> 微软翻译是不需要VPN就能使用的，你关闭VPN试试。

感谢您的回复，

按照您的回答尝试测试，还是回存在翻译失败，网络超时的情况。
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/31385662/d2156487-f082-4627-9268-d2f051c48b77)

**Comment by YiiGuxing** [comment]
你这种情况是网络问题，请检查你的网络环境。
https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-network-error

**Comment by WuChenDi** [comment]
非常感谢您的回复，我再次重启光猫之后可以正常使用了，开启VPN也可以正常工作了，但是仍然遇到了使用手机热点数据提示网络超时问题。
