### ISSUE TITLE
每日单词的显示问题

### ISSUE THREAD

**Issue by Jack1477** [YiiGuxing/TranslationPlugin#373]
## 首先每日单词是一个非常好用的功能

但是经过几天的使用，发现每日单词的顺序貌似是固定的？即我第一天收藏了First这个单词，我每一天都要从First开始看，能否麻烦作者把每日单词的顺序做成随机的，不然天天都在看前面的单词

## 十分感谢！

**Comment by YiiGuxing** [comment]
每日单词的顺序是随机的

**Comment by Jack1477** [comment]
好的 谢谢答复。
