### ISSUE TITLE
翻译IP地址异常

### ISSUE THREAD

**Issue by NNymc** [YiiGuxing/TranslationPlugin#3748]
### 📝 问题描述

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63448449/896784b7-c03e-48eb-9b83-509df4dea004)

### 🏷 插件版本

3.4.2

### 🔁 翻译引擎

百度翻译

### 💻 IDE及运行环境

```plain text
webstorm 2021.3.3
```

**Comment by YiiGuxing** [comment]
这是一个网络错误，请检查你的环境环境：https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-network-error

**Comment by NNymc** [comment]
多个电脑都是此问题

**Comment by YiiGuxing** [comment]
> 多个电脑都是此问题

那应该是你所在的大网络环境就有问题的，你试试 ping 一下翻译地址：
```
ping fanyi-api.baidu.com
```

**Comment by NNymc** [comment]
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63448449/8e1ec748-5887-4ceb-a826-b7f8864c8099)

**Comment by YiiGuxing** [comment]
会不会是你开了VPN什么的，在IDE内无法访问？

**Comment by YiiGuxing** [comment]
在这里试试
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/842a5405-2880-40e5-8fc0-b119fc7c3ed1)

**Comment by NNymc** [comment]
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63448449/9c3aae90-2e0e-4d04-8e8b-751d23c5d829)

**Comment by NNymc** [comment]
有道是正常的，就百度翻译提示ip地址无法访问

**Comment by NNymc** [comment]
我尝试替换了webstorm版本，重新下载插件等都是一样的

**Comment by YiiGuxing** [comment]
那你重现一次翻译失败之后，上传一下日志文件，我分析一下。
日志文件：主菜单->Help->Show Log in Explorer->idea.log

**Comment by NNymc** [comment]
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63448449/12626597-2016-4af5-b1da-21df33b15b41)

**Comment by NNymc** [comment]
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63448449/6b4ba4c0-65a3-4702-833b-c80c0633caec)

**Comment by YiiGuxing** [comment]
。。。。
你这应该是在百度翻译的控制台上设置了访问IP限制，你设备上的IP和控制台上设置IP不一致，所以你无法访问翻译服务。你更新一下IP限制列表就行了。

**Comment by NNymc** [comment]
确实是，想起来了

**Comment by NNymc** [comment]
你能优化一下提示语吗？

**Comment by YiiGuxing** [comment]
> 你能优化一下提示语吗？

确实得优化一下，容易产生误解。
