### ISSUE TITLE
openai 超时

### ISSUE THREAD

**Issue by zhangyutongdeyonghuming** [YiiGuxing/TranslationPlugin#3763]
### 📝 问题描述

<img width="274" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/53220154/acafec25-751b-42f5-bc43-c75b13f31728">
1.切换了openai引擎，
2.配置了key，
3.打开了vpn

### 🏷 插件版本

3.5.0

### 🔁 翻译引擎

微软翻译, 谷歌翻译, 百度翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Licensed to signup scooter
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3)
    de.netnexus.camelcaseplugin (3.0.12)
    cn.yiiguxing.plugin.translate (3.5.0)

Kotlin: 231-1.8.20-IJ8109.175
```

**Comment by YiiGuxing** [comment]
1. VPN访问OpenAI本就慢又不稳定
2. OpenAI影响时间本身就很长
所以超时一般是正常的，也没什么好的解决办法，只能重试了。。。。

如果你有什么好的解决办法，欢迎提出，感谢支持！

**Comment by YiiGuxing** [comment]
还有，这的API Key是不是过期了哦？

**Comment by zhangyutongdeyonghuming** [comment]
我新申请的key，我再试一下

**Comment by zhangyutongdeyonghuming** [comment]
<img width="883" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/53220154/2ba6094d-67da-480c-b503-03f90d19c319">
<img width="308" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/53220154/e84b830a-3608-46f5-b9a0-0a6d49111f7a">
依旧如此

**Comment by YiiGuxing** [comment]
你看它的提示嘛，图片上看不全，看意思好像是超出配额了：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/5b580aa4-37c8-49fc-9e72-c199b0ab7cca)

或者在账号页面查看：https://platform.openai.com/account/usage

**Comment by zhangyutongdeyonghuming** [comment]
原来是这样，我都没有付款账户，难怪api不能用，看来是解决了，多谢作者😊

**Comment by YiiGuxing** [comment]
确实是已经过期了，我的提示和你的一模一样🤣：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/793358a4-58b0-402a-ab0a-dd0c150b804a)

**Comment by YiiGuxing** [comment]
哎呀！我也想用它，但是它收费，还贼贵。。。。

**Comment by zhangyutongdeyonghuming** [comment]
我以为API也是免费的，可惜可惜😑

**Comment by YiiGuxing** [comment]
可惜现在新账号也比较难注册了，要不然可以在过期后注册新账号，就可以免费再用几个月。。。

**Comment by zhangyutongdeyonghuming** [comment]
是啊，还好注册的早

**Comment by YiiGuxing** [comment]
现在网页上还是可以免费用的，只是API不行，哎~  
后面研究一下能不能调用它web端的接口实现免费使用。。。。

**Comment by zhangyutongdeyonghuming** [comment]
有道理，套层皮可以，看他是token还是什么

**Comment by YiiGuxing** [comment]
嗯，有时间研究一下。
