### ISSUE TITLE
支持 OpenAi API 代理设置

### ISSUE THREAD

**Issue by piaobeiyi** [YiiGuxing/TranslationPlugin#3765]
### 需求/建议描述

鉴于国内无法直接调用 openai 接口，是否考虑加入api代理url设置呢

### 建议的解决方案

据我所知现在很多基于openai的工具都有此功能，以下是chrome chatgpt 翻译插件的设置界面，是否可以参考加入此功能
![截图 2023-06-01 14-48-43](https://github.com/YiiGuxing/TranslationPlugin/assets/11715777/7dde8c22-8684-47d3-b9cd-fe1209aff088)

**Comment by YiiGuxing** [comment]
👌

**Comment by jiuxiaoer** [comment]
这个issues很实用

**Comment by ilazy991** [comment]
+1，很期望可以有指定api base url 功能

**Comment by sqqdcl** [comment]
+1，很期望可以有指定api base url 功能

**Comment by sqqdcl** [comment]
+1，很期望可以有指定api base url 功能

**Comment by Henvy-Mango** [comment]
+1，很期望可以有指定api base url 功能

**Comment by each1026** [comment]
+1

**Comment by by123456by** [comment]
同时希望可以自定义模型

**Comment by Anivie** [comment]
一年过去了，这个功能还在计划表中吗？

**Comment by YiiGuxing** [comment]
> 一年过去了，这个功能还在计划表中吗？

正在开发中

**Comment by YiiGuxing** [comment]
此功能已基本开发完成，欢迎大家抢先体验：
 - IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336924/TranslationPlugin-3.6.0-SNAPSHOT.240220.zip)
 - IDE 2020.3 至 2021.2 版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220+203u212.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336976/TranslationPlugin-3.6.0-SNAPSHOT.240220%2B203u212.zip)

**Comment by by123456by** [comment]
> 此功能已基本开发完成，欢迎大家抢先体验：
> 
> * IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336924/TranslationPlugin-3.6.0-SNAPSHOT.240220.zip)
> * IDE 2020.3 至 2021.2 版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220+203u212.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336976/TranslationPlugin-3.6.0-SNAPSHOT.240220%2B203u212.zip)

可以让模型也允许自定义吗

**Comment by YiiGuxing** [comment]
@by123456by 模型自定义？

**Comment by by123456by** [comment]
> @by123456by 模型自定义？

比如我如果想使用你预设里没有的模型名称

**Comment by YiiGuxing** [comment]
> > @by123456by 模型自定义？
> 
> 比如我如果想使用你预设里没有的模型名称

这个之前也有过考虑，但它会带来一些问题，就是我无法分辨哪些模型是适用的，哪些是不适用的，所以就没实现。

**Comment by by123456by** [comment]
> > > @by123456by 模型自定义？
> > 
> > 
> > 比如我如果想使用你预设里没有的模型名称
> 
> 这个之前也有过考虑，但它会带来一些问题，就是我无法分辨哪些模型是适用的，哪些是不适用的，所以就没实现。

可以作为一个扩展的功能提供，你想分辨也无法分辨，比如未来的更新，我是用非openai的服务

**Comment by YiiGuxing** [comment]
> > > > @by123456by 模型自定义？
> > > 
> > > 
> > > 比如我如果想使用你预设里没有的模型名称
> > 
> > 
> > 这个之前也有过考虑，但它会带来一些问题，就是我无法分辨哪些模型是适用的，哪些是不适用的，所以就没实现。
> 
> 可以作为一个扩展的功能提供，你想分辨也无法分辨，比如未来的更新，我是用非openai的服务

那这个后面再考虑了，任务堆积得太多了，现在没有时间好好考虑清楚。

**Comment by YangAoLib** [comment]
模型选择后无法保存 我选择到gpt-4后 再次打开配置 还是显示的gpt-3.5-turbo

**Comment by YiiGuxing** [comment]
> 模型选择后无法保存 我选择到gpt-4后 再次打开配置 还是显示的gpt-3.5-turbo

IDE 有报错吗？

**Comment by YiiGuxing** [comment]
> 模型选择后无法保存 我选择到gpt-4后 再次打开配置 还是显示的gpt-3.5-turbo

不好意思，应该是我上传了错误的包，晚上我重新上传一次。

**Comment by YiiGuxing** [comment]
> 模型选择后无法保存 我选择到gpt-4后 再次打开配置 还是显示的gpt-3.5-turbo

@YangAoLib 已修复：[TranslationPlugin-3.6.0-SNAPSHOT.240321.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14695364/TranslationPlugin-3.6.0-SNAPSHOT.240321.zip)

**Comment by YiiGuxing** [comment]
2024/04/06更新：
- IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240406.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14893952/TranslationPlugin-3.6.0-SNAPSHOT.240406.zip)
  - 新增 OpenAI TTS

欢迎抢先体验！

**Comment by YiiGuxing** [comment]
> 能否适配一下这个 [PawanOsman/ChatGPT](https://github.com/PawanOsman/ChatGPT) 代理的OpenAI地址

@wdkGitHub 你的问题是不是这两个：#5475，#5476

**Comment by YiiGuxing** [comment]
> > > 能否适配一下这个 [PawanOsman/ChatGPT](https://github.com/PawanOsman/ChatGPT) 代理的OpenAI地址
> > 
> > 
> > @wdkGitHub 你的问题是不是这两个：#5475，#5476
> 
> 是测试那个代理服务时产生的问题

@wdkGitHub 等我对2024.1新版本的兼容性适配完成后我重新编译上传，你再试试。

**Comment by YiiGuxing** [comment]
2024/04/10更新：

- IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240410.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14926524/TranslationPlugin-3.6.0-SNAPSHOT.240410.zip)
  - 兼容 2024.1 IDE
  - Bug 修复

@wdkGitHub 你用这个版本试试

**Comment by YiiGuxing** [comment]
> 👍 可以用，就是容易请求超时，代理速度问题。 如果页面能配置超时时间就好了

这个不行，才时间等待会冻结UI，3秒已经很多了。

**Comment by YiiGuxing** [comment]
> `java.time.format.DateTimeFormatter` 超长了

它这个也太长了，限制是一万字符数。

**Comment by imaiya** [comment]
这个功能还没有发布正式版吗

**Comment by YiiGuxing** [comment]
> 这个功能还没有发布正式版吗

还没有，要等微软 TTS 一起，快了。
