### ISSUE TITLE
如何使用正则过滤大段注释中的星号

### ISSUE THREAD

**Issue by nthpermanent** [YiiGuxing/TranslationPlugin#377]
我在另一个issue里看到了同样的问题，但是那里边说的办法行不通。
我相信写代码写个小半年小一年没有几个不认识编程中单词的意思的，编代码中使用翻译插件的次数寥寥，真正使用翻译功能的是看API的时候，像spring，消息中间件每个方法每个类都有大段的注释，我与同事交流的情况中感觉到这是80%需要翻译的地方（在实际写代码，看代码中使用翻译插件的情况别说20%，甚至2%都不到），其他包括翻译出错信息，idea提示，这都不算大头。
例如一个API方法上的大段注释，我想要去掉星号翻译，基本上都长这样：
![image](https://user-images.githubusercontent.com/35824162/67476083-e128a300-f689-11e9-9948-edc982844499.png)

1.设置正则表达式（正则忘光了，在网上现学的，我设置的正则表达式见图）
![image](https://user-images.githubusercontent.com/35824162/67474568-429b4280-f687-11e9-9ea1-1a26ac3eb4e4.png)
2.选中图中的注释部分，点右键，发现翻译选项消失了。按快捷键，没有反应
3.我猜原因是正则匹配到了星号所在的行，所以插件会忽略这一行不提供翻译功能。
       那么如何正确过滤注释中的星号？注释中有网页标签可以忍受，毕竟几行才出现一次，但是每一行都有的*不能忍。
      可能是我的正则写的很low很错误，能否告知一个正确的正则表达式？如此常见的问题为什么不考虑做一个默认选项在设置里？
      整那么多花花绿绿的低频功能都不如整这个实在。哪个程序员不是因为看api而下载的翻译插件？idea提示，出错信息第一反应都是去google查的。希望更多精力分配在优化api注释的翻译上，多谢~
      最后想问一下separator是干嘛用的，我尝试换了一些字符，没发现有什么变化。翻遍git也没有个解释

**Comment by YiiGuxing** [comment]
首先，我想你对“忽略内容”的理解稍有偏差，“忽略内容”是指，翻译时忽略掉“忽略内容”指定的正则表达式所匹配到的内容。你的正则表达式包含“.*”，这相当于忽略了所有内容，所以你才会发现翻译选项消失了。所以正确的正则表达式应该是：`[/*]+`

其次，关于代码注释的翻译，这个想法已经在很早之前就有了的，也有相关的issue，而issue也挂了相当长的一段时间了，一直没有什么进展，没有去实现。这是为什么呢？因为它并不好实现。首先第一个难关就是，谷歌翻译对HTML内容的翻译API，目前并没有被破解，无法使用。其次就是对HTML内容的解析还是有些繁琐的，做到完美是比较难的。这时你可能会问：搞那么复杂的干什么啊？没必要啊！  是的，这正是“忽略内容”出现的原因，它就是代码注释翻译的一个折方案现而已。如果不需要实现比较完美的代码注释翻译方案，那么“忽略内容”方案就已经足够使用了。

最后，关于separator，它就是在“翻译并替换”时，分隔单词之前的分隔符。例如，将其设置为“*.+”时，会得到下面的内容：
![image](https://user-images.githubusercontent.com/10737066/67482515-6e71f480-f696-11e9-878f-67ecbb7d5231.png)
这一点是我的锅，后面我会把其用途说明清楚。

最后的最后，感谢你的反馈与建议！在回答你的问题时还挖出了一个隐藏得比较深的Bug。。。
