### ISSUE TITLE
OpenAI翻译不可用

### ISSUE THREAD

**Issue by dongzunian** [YiiGuxing/TranslationPlugin#3770]
### 📝 问题描述

OpenAI翻译不可用，配置了API，提示网络错误，梯子环境下也不行，不开梯子也不行

### 🏷 插件版本

3.5.0

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
PyCharm 2023.1.2 (Professional Edition)
Build #PY-231.9011.38, built on May 17, 2023
授权给 kiddy inseams
您有此版本的永久回退许可证。
订阅有效期至 2025年8月1日。
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.4)
    com.intellij.zh (231.283)
    cn.yiiguxing.plugin.translate (3.5.0)
```

**Comment by YiiGuxing** [comment]
那可能是你梯子没有配置对，检查一下。

**Comment by jiuxiaoer** [comment]
idea 是 java 写的 java 是在虚拟机运行的 所以 idea 系列单独代理设置了吗
java 不会走系统代理的

**Comment by L1yp** [comment]
> 

我这里也不能用，开系统代理和IDEA的System Setting里面的Proxy也不能用，可否给个代理例子？我看访问的域名也没有openai.com的

**Comment by YiiGuxing** [comment]
@L1yp 
以我自己的为例，我用的代理客户端是 Tanpopo ，本地代理地址和端口：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/b147207a-43b6-49c5-8b16-8f07307aad09)
```
127.0.0.1:1087
```
IDE 代理设置：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/2eccec42-b8b7-498e-8142-bd8ebc29142c)

**Comment by L1yp** [comment]
谢谢

改成http代理可以，socks5代理不能用，你可以测试下socks5模式行不行

> @L1yp 以我自己的为例，我用的代理客户端是 Tanpopo ，本地代理地址和端口： ![image](https://user-images.githubusercontent.com/10737066/244241772-b147207a-43b6-49c5-8b16-8f07307aad09.png)
> 
> ```
> 127.0.0.1:1087
> ```
> 
> IDE 代理设置： ![image](https://user-images.githubusercontent.com/10737066/244242063-2eccec42-b8b7-498e-8142-bd8ebc29142c.png)
