### ISSUE TITLE
安装后的弹窗关不掉，点叉就卡死IDE

### ISSUE THREAD

**Issue by shank3** [YiiGuxing/TranslationPlugin#3776]
### 📝 问题描述

1. 安装
2. 重启
3. 点击关闭弹窗
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/11381793/238653d3-1aad-45a9-b9ac-721cc77d8cd8)

### 🏷 插件版本

3.5.0

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.7.2623)
    idea.plugin.protoeditor (231.8109.91)
    com.bruce.intellijplugin.generatesetter (2.8.3)
    com.baomidou.plugin.idea.mybatisx (1.5.5)
    cn.cloud.auto.restful.tool (1.4.5)
    wl-spring-assistant (1.3.222.231)
    MavenRunHelper (4.23.222.2964.0)
    cn.yiiguxing.plugin.translate (3.5.0)

Kotlin: 231-1.8.20-IJ8109.175
```

**Comment by YiiGuxing** [comment]
能不能提供一下ide的日志文件？我这边无法重现。。。

**Comment by hghui** [comment]
我也遇到了这个问题，点击关闭就卡死。我的做法是关闭了idea的新UI然后那个提示弹窗就没了。

**Comment by YiiGuxing** [comment]
> 我也遇到了这个问题，点击关闭就卡死。我的做法是关闭了idea的新UI然后那个提示弹窗就没了。

@hghui 
 你的也是MacOS？，能不能提供一下ide的日志文件？日志文件：主菜单->Help->Show Log in Explorer->idea.log

**Comment by shank3** [comment]
重启后先不关弹窗，进设置把插件disable，然后重启再开启就没弹窗了。

我尝试了卸载重装，但是没有弹窗，无法复现了。

**Comment by YiiGuxing** [comment]
> 重启后先不关弹窗，进设置把插件disable，然后重启再开启就没弹窗了。
> 
> 我尝试了卸载重装，但是没有弹窗，无法复现了。

@shank3 
1. 找到IDE的配置目录，`主菜单->Help->Edit Custom Properties` 打开配置文件，然后就可以看到配置目录了：
  ![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/13e4c462-8231-4d4e-abd8-a69b2981ccc4)
2. 打开文件：`配置目录/options/other.xml` 
3. 找到 `cn.yiiguxing.plugin.translate.version` 所在行，删除此行，保存文件
4. 重启IDE，就会重新弹窗了
5. 重现问题后收集日志：`主菜单->Help->Collect Logs and Diagnostic Data`

**Comment by shank3** [comment]
@YiiGuxing hi,我打开对应配置文件没有version, 重启也没有出现弹窗

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/11381793/775ce77f-3dd3-4f0e-8e8a-d8c84e1129b2)

**Comment by shank3** [comment]
@YiiGuxing hi, 我删除了这一行，重启后未出现弹窗，卸载重新安装也未出现。不知跟我升级了IDE有关么？我的最新版本是

IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.8.2631)
    idea.plugin.protoeditor (231.8109.91)
    com.bruce.intellijplugin.generatesetter (2.8.3)
    com.baomidou.plugin.idea.mybatisx (1.5.5)
    cn.cloud.auto.restful.tool (1.4.5)
    MavenRunHelper (4.23.222.2964.0)
    cn.yiiguxing.plugin.translate (3.5.0)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by YiiGuxing** [comment]
> @YiiGuxing hi, 我删除了这一行，重启后未出现弹窗，卸载重新安装也未出现。不知跟我升级了IDE有关么？我的最新版本是

不应该啊，是不是删除了没有保存成功？或者找到的配置目录不对？配置目录名是带有IDE版本的，你看看对应得上不，对应不上就在配置目录父目录里到对应的目录再修改。

**Comment by shank3** [comment]
> 

我重新试了下，可以出现欢迎弹窗了，可能是之前我多删除了 `&quot;got.it.tooltip.cn.yiiguxing.plugin.translate.tooltip.new.translation.engines.openai&quot;: &quot;1&quot;,` 导致，

目前我这里也无法复现这个问题了，请先忽略吧

**Comment by hghui** [comment]
> > 我也遇到了这个问题，点击关闭就卡死。我的做法是关闭了idea的新UI然后那个提示弹窗就没了。>> @hghui你的也是MacOS？，能不能提供一下ide的日志文件？日志文件：主菜单->Help->Show Log in Explorer->idea.log
可以的

> > 我也遇到了这个问题，点击关闭就卡死。我的做法是关闭了idea的新UI然后那个提示弹窗就没了。
> 
> @hghui 你的也是MacOS？，能不能提供一下ide的日志文件？日志文件：主菜单->Help->Show Log in Explorer->idea.log

[idea.log.zip](https://github.com/YiiGuxing/TranslationPlugin/files/11652656/idea.log.zip)

**Comment by YiiGuxing** [comment]
@hghui 你提供的日志并不包含有用的信息，你可能需要在复现问题之后使用此方法收集日志：`主菜单->Help->Collect Logs and Diagnostic Data`
