### ISSUE TITLE
添加代码提示翻译

### ISSUE THREAD

**Issue by gml-9527** [YiiGuxing/TranslationPlugin#378]
老哥，能做个代码报错提示功能的翻译嘛。。。
主要是不能复制那个报错的提示英语，经常都得截图然后拿去百度网页上传图片翻译。。。我这0级英语太菜了。。。
期望上面是英语，下面能有对应的翻译。。。

**Comment by YiiGuxing** [comment]
这部分是可以翻译的：选择需要翻译的文本，然后按翻译快捷键即可对其进行翻译。

在IDE中，只要能够选择的文本，几乎都是可以翻译的，选择文本后，如果不能使用右键菜单翻译，就使用快捷键翻译。

**Comment by gml-9527** [comment]
刚试了下，确实可以通过选择，按快捷键搞定，谢谢了。

**Comment by YiiGuxing** [comment]
不客气
