### ISSUE TITLE
支持 Azure OpenAI 配置 translator

### ISSUE THREAD

**Issue by ziludev** [YiiGuxing/TranslationPlugin#3801]
### 需求/建议描述

如果 OpenAI 翻译支持 Azure OpenAI 就好了， Azure OpenAI 好像可以国内直连

### 建议的解决方案

感觉可以采用主流的使用 secret key 和 config url 的形式配置

**Comment by zhou-jian-qq** [comment]
+1

**Comment by Reader1367** [comment]
+1

**Comment by dengbojing** [comment]
我反馈一个问题:  
```
Caused by: cn.yiiguxing.plugin.translate.trans.openai.exception.OpenAIStatusException: 404 Not Found - DeploymentNotFound. Status=404, Url=https://{resource-name}.openai.azure.com/openai/deployments/gpt-3.5-turbo/chat/completions?api-version=2023-12-01-preview
	at cn.yiiguxing.plugin.translate.trans.openai.OpenAIHttp.throwStatusCodeException(OpenAIHttp.kt:43)
	at cn.yiiguxing.plugin.translate.trans.openai.OpenAIHttp.post(OpenAIHttp.kt:30)
	at cn.yiiguxing.plugin.translate.trans.openai.Azure.chatCompletion(OpenAIService.kt:77)
	at cn.yiiguxing.plugin.translate.trans.openai.OpenAITranslator.translate(OpenAITranslator.kt:69)
	at cn.yiiguxing.plugin.translate.trans.openai.OpenAITranslator.doTranslate(OpenAITranslator.kt:40)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
	... 13 more
```

这个是报错信息,之所以会报错是因为`gpt-3.5-turbo`这个名字的问题, 我模型部署起名字不叫这个名字, 我缩写成gpt35了


`api-version`[这里有](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference)很多个不过我一般都是直接复制`playgorund`里面的`version`,配置里面显示少了几个, 不过不影响使用

**Comment by YiiGuxing** [comment]
@dengbojing 感谢反馈，我这里要先和你确认一下两个问题：
1. 你使用的IDE版本是什么？
2. endpoint 是否有正确配置？因为从异常信息里我看到的是 `https://{resource-name}.openai.azure.com`，会不会是因为这个问题导致的？

另外 `api-version` 我没有添加即将信用的，所以少。

**Comment by dengbojing** [comment]
IDEA版本: 2023.2 
endpoint问题: {resource-name}这个是我发issue自己替换掉的, 因为本身这个值是每个人不相同的, 不是固定统一的,

**Comment by YiiGuxing** [comment]
> IDEA版本: 2023.2 
> endpoint问题: {resource-name}这个是我发issue自己替换掉的, 因为本身这个值是每个人不相同的, 不是固定统一的
> 
> 
> 另: 问题的结论我是通过对比我之前`OpenAI Translator`得出来的, 还有也对比了`playground` 里面得源码, 这个地方确实应该是部署模型得名称
> 
> 
> 

明白了，看来模型只能是手动输入来配置，不能通过选择来配置了。

**Comment by dengbojing** [comment]
是的, Azure里面的模型是你需要预先部署好, 然后才能使用, 使用得时候需要使用部署时候填写得名称
请求得url是这个格式, `https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=2023-05-15`, 其中有两处是自己需要填写的

**Comment by YiiGuxing** [comment]
@dengbojing 麻烦你再帮忙测测：[TranslationPlugin-3.6.0-SNAPSHOT.240221.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14353942/TranslationPlugin-3.6.0-SNAPSHOT.240221.zip)

**Comment by dengbojing** [comment]
可以了, 非常感谢添加这个功能

**Comment by Hailey-Nolan** [comment]
> @dengbojing 麻烦你再帮忙测测：[TranslationPlugin-3.6.0-SNAPSHOT.240221.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14353942/TranslationPlugin-3.6.0-SNAPSHOT.240221.zip)

azure openai 点击翻译文档会出现内容长度超出限制，已跳过翻译。若全部选择点翻译选择的文本会正常翻译，如图
![Uploading image.png…]()
![11](https://github.com/YiiGuxing/TranslationPlugin/assets/123810871/feea9bba-6235-4c10-a641-092979d2bce1)
![git2](https://github.com/YiiGuxing/TranslationPlugin/assets/123810871/7cefd39c-876a-43e6-a886-76e0b466dfed)

**Comment by YiiGuxing** [comment]
@Hailey-Nolan 文档的翻译它还包含得有界面上看不到的HTML标签等内容，容易超出限制。

**Comment by Hailey-Nolan** [comment]
> @Hailey-Nolan 文档的翻译它还包含得有界面上看不到的HTML标签等内容，容易超出限制。

是的，确实是有有html等内容，但是后面我把这些内容都一并包含了进去，依然正常可翻译。抱歉我没有留下截图，对于openai来说16k的上下文似乎并不容易到达上限,所以它是否是一个正常的预期呢？

**Comment by YiiGuxing** [comment]
> > @Hailey-Nolan 文档的翻译它还包含得有界面上看不到的HTML标签等内容，容易超出限制。
> 
> 是的，确实是有有html等内容，但是后面我把这些内容都一并包含了进去，依然正常可翻译。抱歉我没有留下截图，对于openai来说16k的上下文似乎并不容易到达上限,所以它是否是一个正常的预期呢？

这个我没有精准测试过，后面我测试修正一下。

**Comment by YiiGuxing** [comment]
2024/04/06更新：
- IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240406.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14893952/TranslationPlugin-3.6.0-SNAPSHOT.240406.zip)
  - 新增 OpenAI TTS
  - 优化 OpenAI 翻译内容长度限额

欢迎抢先体验！还请有 Azure 账号的伙伴测试一下 Azure OpenAI TTS，测测功能是否能正常使用，特别是看看语速配置是否有效，感谢！

**Comment by YiiGuxing** [comment]
2024/04/10更新：

- IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240410.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14926524/TranslationPlugin-3.6.0-SNAPSHOT.240410.zip)
  - 兼容 2024.1 IDE
  - Bug 修复
 
欢迎抢先体验！
