### ISSUE TITLE
插件更新后OpenAI翻译引擎弹窗关不掉, 遮挡翻译界面

### ISSUE THREAD

**Issue by Lyraen** [YiiGuxing/TranslationPlugin#3802]
### 📝 问题描述

IntelliJ IDEA 2023.1.2 + Transaction插件3.5.0版本
更新之后打开翻译界面出现提示弹窗, 无法关闭
<img width="406" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/37282588/7ecb40dd-2040-49f0-80c3-63e12d2c83d6">

### 🏷 插件版本

3.5.0 + 2023.1.2

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to kiddy inseams
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    cn.yiiguxing.plugin.translate (3.5.0)

Kotlin: 231-1.8.21-IJ9011.34
```

**Comment by YiiGuxing** [comment]
临时的解决办法：调整窗口的高度后就有关闭按钮了。
![img](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/5ddd71b6-5c0a-4b93-a243-37094e09be61)

**Comment by Lyraen** [comment]
可以了, 感谢
