### ISSUE TITLE
希望添加翻译到繁体中文的功能

### ISSUE THREAD

**Issue by qwe7002** [YiiGuxing/TranslationPlugin#381]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

希望添加翻译到繁体中文的功能，目前的Chinese只有简体中文，对面向繁体中文使用区域开发的人来说不是很方便，希望能添加一个

**Comment by YiiGuxing** [comment]
有的，请使用谷歌翻译或者百度翻译。

**Comment by qwe7002** [comment]
非常抱歉是我没看仔细……
