### ISSUE TITLE
Why Central Kurdish(Sorani) is not available in the list!

### ISSUE THREAD

**Issue by GoRaN909** [YiiGuxing/TranslationPlugin#3811]
### 📝 Issue Description

Hello and thanks for this great tool I like it so much and I use in Android studio for translating app source to another language. But there are no my native language in this tool while is officially supported by both Google Translate and Microsoft Translator engines!

Here is the language codes: [Google translate](https://cloud.google.com/translate/docs/languages) 

<table>
<tr><td>
ckb - Kurdish (Sorani)
<td>
ku - Kurdish (Kurmanji)
</table>

[Microsoft Translator](https://learn.microsoft.com/en-us/azure/cognitive-services/translator/language-support):

<table>
<tr><td>
ku - Kurdish (Central)
<td>
kmr - Kurdish (Northern)
</table>

Please add support for another dialect of Kurdish (کوردی) Soran (aka. Central Kurdish).

Regards.

### 🏷 Plugin Version

3.5.0

### 🔁 Translation Engine(s)

Google Translate, Microsoft Translator

### 💻 IDE and Operating Environment

```plain text
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    cn.yiiguxing.plugin.translate (3.5.0)
```

**Comment by YiiGuxing** [comment]
Coming soon.
