### ISSUE TITLE
OpenAI翻译能否支持配置代理地址

### ISSUE THREAD

**Issue by adongden** [YiiGuxing/TranslationPlugin#3846]
### 需求/建议描述

由于一些你懂的原因，需要设置代理
<img width="853" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/122472234/48e6a8d1-8f1f-455c-bc8e-d6697581dac9">

### 建议的解决方案

增加配置API地址，方便配置Proxy的API地址

**Comment by YiiGuxing** [comment]
Duplicate of #3765
