### ISSUE TITLE
最近一直连接不上服务器，没人有这种情况吗

### ISSUE THREAD

**Issue by kydxone** [YiiGuxing/TranslationPlugin#385]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
没有啊，你用的是哪家的翻译

**Comment by kydxone** [comment]
读了FAQ后发现问题了。系统语言不久前变成了英文，故勾选了google.com。此ISSUE可去除。
