### ISSUE TITLE
收藏的翻译单词和语句，从哪里看？

### ISSUE THREAD

**Issue by daiqingliang** [YiiGuxing/TranslationPlugin#388]
收藏的翻译单词和语句，从哪里看呢？
找了好久了，一直没找到。
主要配置界面不就是在Settings--Other Settings--Translation，但是这里只有一个保存历史记录的天数，无法查看我已收藏的翻译

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/68176939-a85dc780-ffc1-11e9-8db7-640e97db699e.png)

**Comment by daiqingliang** [comment]
@YiiGuxing 谢谢

**Comment by daiqingliang** [comment]
closes
