### ISSUE TITLE
Alt + T 与默认快捷键冲突

### ISSUE THREAD

**Issue by qiankunshe** [YiiGuxing/TranslationPlugin#39]
Alt + T 与默认快捷键冲突， Alt + T 默认打开Tools 菜单

**Comment by YiiGuxing** [comment]
@qiankunshe Alt + T 需要选择文本后才能使用，选择文本后它会覆盖默认的。如果不行的话可以自己修改这个快捷键的。其实快捷键都不应该用“Alt +”的，我实在是找不到可用又好按一点的了，才这么设置的。
