### ISSUE TITLE
建议增加一个功能，直接把汉语翻译成英文的驼峰命名法

### ISSUE THREAD

**Issue by xiamaoxuan** [YiiGuxing/TranslationPlugin#390]
举个栗子：
查询用户信息====>queryUserInformation

有这个功能开发能够少写很多代码

**Comment by YiiGuxing** [comment]
这个不是有的吗？“Translate and Replace”，看一下README，然后用一下就知道了。

**Comment by xiamaoxuan** [comment]
哦哦，好的
