### ISSUE TITLE
每日单词可以把上下位置随机吗？

### ISSUE THREAD

**Issue by Jack1477** [YiiGuxing/TranslationPlugin#391]
可不可以让上面和下面随机出现释义或者英文而不是固定 英文和释义或者释义和英文。

看了好多单词都是认得不会拼了。。感谢🙏

**Comment by YiiGuxing** [comment]
每日单词已经做了随机排序了的

**Comment by Jack1477** [comment]
不好意思没有表达清楚。
![image](https://user-images.githubusercontent.com/38455717/68567086-165b3080-0493-11ea-9e88-461da5dbccc3.png)

**Comment by Jack1477** [comment]
上面不总是固定的英文或者中文

**Comment by YiiGuxing** [comment]
这需要自己添加中文单词

**Comment by Jack1477** [comment]
是的我知道，但是添加 China-中国 上面就永远是 “China”，而添加 中国-China上面就永远是“中国”，可否有随机选项

**Comment by YiiGuxing** [comment]
这是单词->释义的关系，并不是英文单词->中文单词的关系，如何能对换位置？释义部分可不是单词，它可能很多个单词。上间结构不同，不能对换的。
