### ISSUE TITLE
单词本怎么使用

### ISSUE THREAD

**Issue by SenSenGitHub** [YiiGuxing/TranslationPlugin#3912]
### Feature/Enhancement Description

目前单词本只可以记录单词吗？请问我添加到单词本的东西是不是可以给一个显示面板呢

### Proposed Solution

目前单词本只可以记录单词吗？请问我添加到单词本的东西是不是可以给一个显示面板呢

**Comment by YiiGuxing** [comment]
如果找不到单词本面板，可以双击  <kbd>Shift</kbd> 键搜索 `wordbook` 即可找到，然后你可以把面板固定到侧边栏。

另外，提交义题时请选择正确的类型，此类型是需求义题，而不是问答义题。感谢支持！
