### ISSUE TITLE
翻译功能无法在javadoc上正常使用

### ISSUE THREAD

**Issue by DXShelley** [YiiGuxing/TranslationPlugin#392]
现状： 在javadoc弹出框中，使用翻译功能会关闭弹出框。

期望： 能否在javadoc弹出框中，使用翻译功能时，保留当前弹框。因为翻译功能主要再看源码注释的时候更常用。每次使用关闭弹框，然后再次打开javadoc弹框的过程，相当繁琐。

**Comment by YiiGuxing** [comment]
关闭javadocdoc弹出框也是没有办法的事，因为弹出框的层级比较高，它会覆盖在翻译对话框上。

如果需要翻译时还可以查看javadoc，那就只能将javadoc弹出框以Tool window的方式打开：在javadoc弹出框上再按一次打开javadoc弹出框的快捷键。

**Comment by DXShelley** [comment]
好的
