### ISSUE TITLE
翻译显示网络错误

### ISSUE THREAD

**Issue by chunyu6666** [YiiGuxing/TranslationPlugin#3929]
### 📝 问题描述

idea翻译显示网络错误相同配置datagrip翻译就没问题
idea用的是测试版

### 🏷 插件版本

最新版

### 🔁 翻译引擎

微软翻译, 谷歌翻译, 有道翻译

### 💻 IDE及运行环境

```plain text
2023.2 eap
```

**Comment by YiiGuxing** [comment]
232版本上现在是有问题的，请耐心等待升级修复

**Comment by YiiGuxing** [comment]
问题已经在 3.5.1 版本中解决，请升级。
