### ISSUE TITLE
在IDEA上使用更新速度慢

### ISSUE THREAD

**Issue by 15004064342** [YiiGuxing/TranslationPlugin#397]
用IDEA开发JAVA项目，用mybatisPlus后代码更新数据大概在8秒多 ，实在太慢了!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by YiiGuxing** [comment]
???

**Comment by YiiGuxing** [comment]
兄弟，是不是走错片场了？

**Comment by 15004064342** [comment]
jrebl这个插件 让我评论我就点进来了&nbsp; 是你们搞错片场连接了吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yii.Guxing"<notifications@github.com&gt;; 
发送时间: 2019年11月28日(星期四) 下午5:34
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com&gt;; 
抄送: "王兆宇"<229496661@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 在IDEA上使用更新速度慢 (#397)




兄弟，是不是走错片场了？
 
&mdash;

**Comment by YiiGuxing** [comment]
哈哈，要么是你点错了，要么是让你点的插件搞错了片场了，我是躺枪啊，哈哈
