### ISSUE TITLE
tts 建议

### ISSUE THREAD

**Issue by wilinz** [YiiGuxing/TranslationPlugin#3979]
### 需求/建议描述

tts 可以采用 微软 edge 大声朗读接口

### 建议的解决方案

接口协议分析在此 [https://gist.github.com/wilinz/13f4bc343754f01c06a90aa9c12e449a](https://gist.github.com/wilinz/13f4bc343754f01c06a90aa9c12e449a)

**Comment by wilinz** [comment]
相关实现代码 [https://github.com/wilinz/flutter_edge_tts/blob/main/lib/main.dart](https://github.com/wilinz/flutter_edge_tts/blob/main/lib/main.dart)

**Comment by YiiGuxing** [comment]
感谢提供的解决方案，其实在接入微软翻译的时候就已经调研过了的，也有思路了的，只是到现在为止，一直没有时间来实现，不过已经计划在下一两个功能版本上接入，可能会比较慢，还请再耐心等一等。

**Comment by liming0** [comment]
> 感谢提供的解决方案，其实在接入微软翻译的时候就已经调研过了的，也有思路了的，只是到现在为止，一直没有时间来实现，不过已经计划在下一两个功能版本上接入，可能会比较慢，还请再耐心等一等。

请问最新版本支持自定义tts了吗？

**Comment by YiiGuxing** [comment]
> > 感谢提供的解决方案，其实在接入微软翻译的时候就已经调研过了的，也有思路了的，只是到现在为止，一直没有时间来实现，不过已经计划在下一两个功能版本上接入，可能会比较慢，还请再耐心等一等。
> 
> 请问最新版本支持自定义tts了吗？

@liming0 已在开发中了，正在实现基础 API，分支 ：https://github.com/YiiGuxing/TranslationPlugin/tree/feature/tts

**Comment by YiiGuxing** [comment]
微软 Edge TTS 将会在即将发布的 v3.6 版本中推出，目前 v3.6 版本的功能开发工作已经完成，正在做版本兼容的收尾工作，很快就会发布。
