### ISSUE TITLE
单词本怎么使用？JSON中是什么格式？

### ISSUE THREAD

**Issue by hajtjh** [YiiGuxing/TranslationPlugin#398]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
http://yiiguxing.github.io/TranslationPlugin/updates.html?v=2.4
