### ISSUE TITLE
在AndroidStudio中使用ConstraintLayout约束布局编辑器时卡死

### ISSUE THREAD

**Issue by sanpark** [YiiGuxing/TranslationPlugin#399]
在使用此编辑器时切换至Design模式给单个控件编辑属性时，使用翻译会卡死

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/69840515-d4096000-1296-11ea-908c-6d45cdbbaee7.png)
是在属性输入框上使用翻译出现的吗？

**Comment by YiiGuxing** [comment]
如果是的话我这边没问题啊

**Comment by sanpark** [comment]
这几天忘记回复了，这个问题没有描述清楚，英翻中没有问题，中翻英的时候出现卡死

**Comment by YiiGuxing** [comment]
一样没问题啊：
![i](https://user-images.githubusercontent.com/10737066/70135562-4332ea00-16c5-11ea-81c4-51c3e59cd52d.gif)

**Comment by sanpark** [comment]
哈哈，总能巧妙的躲开bug点,你试试设置id时 我上传个gif给你看看把
![GIF](https://user-images.githubusercontent.com/3349351/70292174-5e623e80-1818-11ea-9fb4-8f3fa2b0b32a.gif)

**Comment by YiiGuxing** [comment]
## 这并不是插件的BUG，这应该是AS的BUG（甩锅。。。）

关于这个问题出现的原因我的猜测是：
在ID属性输入框失去焦点时，如果ID已经改变，AS会搜索相关的引用并更新引用，这个过程会消耗较多的时间，而且在这个过程中，如果显示其他窗口，就会发生死锁，从而导致整个UI线程阻塞，无法继续执行。
当编辑ID属性时试图打开翻译窗口进行翻译的时候，翻译窗口显示时势必会抢占焦点，从而导致上述过程的发生。这个过程是不可避免的，即使我在显示翻译窗口时事先释放ID属性输入框的焦点，但我并无从知晓AS的处理任务在何时结束，也就是说我并不能准确地确定翻译窗口显示的时机。

综上所述，该问题从插件的角度上看，应该是无解的。要解决这个问题还得需要从AS本身入手（也就是说这个BUG应该提给AS，一会儿我会提给AS的）。

作为一个临时的解决方案，我们可以绕开这个问题：编辑好属性后，使输入框失去一次焦点，然后再尝试进行翻译即可。
![as](https://user-images.githubusercontent.com/10737066/70308773-f4ad5900-1846-11ea-9fef-c20190e87812.gif)


### 以下操作可以证明该问题不是插件的问题：
- 编辑ID属性时按 Ctrl+Alt+S 打开设置窗口，也出现同样的问题（此操作已经和插件没有任何关系）
  ![as](https://user-images.githubusercontent.com/10737066/70307872-0beb4700-1845-11ea-81fd-d1e9d4ff7901.gif)

**Comment by sanpark** [comment]
了解了~！~
