### ISSUE TITLE
向您请教一下这种插件是怎么编写的，我看他们都是使用的groovy编写插件，你这边使用的java代码，我想写个小插件，怎么学习呢，求指导，多谢！

### ISSUE THREAD

**Issue by heiheiwanne** [YiiGuxing/TranslationPlugin#4]

**Comment by YiiGuxing** [comment]
@heiheiwanne groovy编写？怎么会？IDEA 就是用java写的啊，它的插件自然也是要用java写。你是不是指Gradle插件哦？Gradle插件和IDEA插件、AS插件是不一样的。Gradle插件我并不知道如何编写，但IDEA插件、AS插件这个你可以搜索一下“IDEA插件开发”，或者查看官方文档：https://www.jetbrains.com/help/idea/2016.2/plugin-development-guidelines.html。这方面的资料比较少，特别是中文的。你只会找到如何开发一个插件的流程，高级一点的就得看IDEA 的open api了。至于学习嘛，就是看别人的源码，看看别人是怎么写的，IDEA上的插件很多都是开源的，你可以去看看学习。我自己就是这么学的。我这个插件是我好两年前写的了好像，只是当时是写在eclipse上的，现在只是移到IDEA 上了。之前也写了几个代码生成的AS插件，也是看着别人的代码现学现写的，其实并不是很难。
