### ISSUE TITLE
如何删除查询记录？

### ISSUE THREAD

**Issue by zJiaJun** [YiiGuxing/TranslationPlugin#40]
这个翻译插件很不错，辛苦了。

当Alt+0,弹出Show Translation Dialog，怎么删除下拉菜单里的单词记录？

应该类似于缓存这样的？

**Comment by YiiGuxing** [comment]
谢谢！
下拉菜单里的是查询历史记录，它的最大长度是50，是删除不了的，其实也没有多大必要删除。
