### ISSUE TITLE
字体颜色设置

### ISSUE THREAD

**Issue by Cqxstevexw** [YiiGuxing/TranslationPlugin#401]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

+ 选择想要翻译的内容,然后翻译,会弹出一个窗口,上面显示内容包括: 选中的英文内容, 翻译的中文内容等
+ 选中的英文内容, 翻译的中文内容, 部分字体颜色亮度太亮了(我pycharm的主题颜色是偏暗的,个人也喜欢这种风格)
+ 颜色太亮导致眼睛看着有点不太舒服, 
+ 设置没有可以修改显示字体的颜色

### Proposed Solution

+ 希望设置可以有修改翻译字体的颜色, 谢谢

**Comment by YiiGuxing** [comment]
已有实现此功能的计划，但不会在近期实现。

**Comment by Cqxstevexw** [comment]
哦哦, 好的, 谢谢~

**Comment by YiiGuxing** [comment]
关闭原因：短时间内不会被实现，暂时先关闭。
