### ISSUE TITLE
插件配置无法保存

### ISSUE THREAD

**Issue by wzlstudy** [YiiGuxing/TranslationPlugin#4038]
### 📝 Issue Description

系统：macOS 12.6.7 IDEA版本：2023.1.4，插件版本：3.5.1
操作：配置了百度翻译APPID和秘钥后，点击保存，报错如下：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/54768887/6718f6be-4203-441d-867b-60a1569ef3f1)

### 🏷 Plugin Version

3.5.1

### 🔁 Translation Engine(s)

Baidu Translate

### 💻 IDE and Operating Environment

```plain text
系统：macOS 12.6.7 
IDEA版本：2023.1.4
```

**Comment by YiiGuxing** [comment]
https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key
