### ISSUE TITLE
2.6的翻译文档窗口异常

### ISSUE THREAD

**Issue by 972223177** [YiiGuxing/TranslationPlugin#405]
![TIM截图20191206094040](https://user-images.githubusercontent.com/28978619/70288446-b1ce8f80-180c-11ea-9581-a732d2a2abfc.png)
AS版本3.5.3。使用translation document 窗口没办法自适应大小

**Comment by 972223177** [comment]
![TIM截图20191206094040](https://user-images.githubusercontent.com/28978619/70288580-0bcf5500-180d-11ea-81be-736a96b67c0d.png)
每次使用该功能都要手动点击restore size

**Comment by fengchenzhihun1** [comment]
idea 2019.2版本也有这个问题
