### ISSUE TITLE
建议在快捷键看文档注释的时候能做到源码文档注释这种效果

### ISSUE THREAD

**Issue by chenluby** [YiiGuxing/TranslationPlugin#408]
![image](https://user-images.githubusercontent.com/35733171/70384682-aff7fe00-19bd-11ea-9e52-ed6e32e2ece6.png)
![Uploading image.png…]()
例如IDEA 的文档注释是快捷键是Ctrl+Q
在回显的时候直接翻译过来也是很好的体验哦

**Comment by YiiGuxing** [comment]
我并不是没有有过这样的想法，但目前还做不到。如果有大佬能搞定这个，非常欢迎提交相关实现PR。
