### ISSUE TITLE
提示:请求过于频繁,请尝试更换API KEY

### ISSUE THREAD

**Issue by linzhengloser** [YiiGuxing/TranslationPlugin#41]

**Comment by JinXin1995** [comment]
自己去申请一个有道的api key呗，
http://fanyi.youdao.com/openapi?path=data-mode
里面的信息可以随便填，能通过表单验证就行

**Comment by JinXin1995** [comment]
现在有道服务器好像被攻击了，刚刚上有道官网给我跳到一个赌博网站去了

**Comment by YiiGuxing** [comment]
有道又挂了:joy::joy::joy:

**Comment by JavanTang** [comment]
貌似连接失败了

**Comment by YiiGuxing** [comment]
@JavanTang 嗯，现在官网是可以进去了，但是API服务还没好：{"query":"挂了?","errorCode":30}

**Comment by JavanTang** [comment]
现在可以了😀
