### ISSUE TITLE
列选择模式的翻译支持

### ISSUE THREAD

**Issue by ojbk-666** [YiiGuxing/TranslationPlugin#410]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/commit/93915e217cf9c1b722d0d830f944341909ddee26
