### ISSUE TITLE
翻译注释格式被破坏

### ISSUE THREAD

**Issue by BailinSong** [YiiGuxing/TranslationPlugin#412]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
文档格式被破坏：
* 翻译后文档的 “/” 与 “**” 之间出现了多余的空格
* @开头的关键字被带入到翻译范围中

### Description

* 插件配置
![image](https://user-images.githubusercontent.com/2916937/70503231-ebc9c980-1b5d-11ea-90e3-4d7f21632e62.png)

* 翻译截屏
![image](https://user-images.githubusercontent.com/2916937/70503061-7c53da00-1b5d-11ea-80d7-32d6cb408788.png)

### Environment & Stack Trace
- Plugin version: 2.6.1
- IDE version: IDEA 2019.3
- Operating System and version: Mac os 10.15.1

**Comment by YiiGuxing** [comment]
请另阅 #130
