### ISSUE TITLE
可以访问谷歌翻译但是还是提示翻译失败超时

### ISSUE THREAD

**Issue by 1592363624** [YiiGuxing/TranslationPlugin#4183]
### 📝 问题描述

可以访问谷歌翻译但是还是提示翻译失败超时

### 🏷 插件版本

3.5.1

### 🔁 翻译引擎

全部

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
For educational use only.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
```

**Comment by 1592363624** [comment]
其他的翻译也是可以访问 一样显示超时

**Comment by YiiGuxing** [comment]
麻烦提供一下复现的步骤，还有问题截图嘛，我这边正常使用的，无法还原你的问题。

**Comment by Sunnnner** [comment]
> 

<img width="373" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/9432907/ac1c2efb-50b7-4e9f-8343-b4e5e8aed640">
手动切换翻译引擎的时候不起作用
<img width="343" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/9432907/9e158d2e-8aca-4029-b1f5-9c22936dad8b">

pycharm版本如上

**Comment by YiiGuxing** [comment]
@Sunnnner 你是否使用的是插件的最新版本？能提供动态图片，或录屏？

**Comment by 1592363624** [comment]
> @1592363624 你的问题解决了吗？知道是什么原因导致的吗？

我感觉是VPN的原因 我用VPN可以直接访问谷歌和微软的翻译，但是这个插件的用不了，我把VPN关掉了插件倒是可以用了=.=

**Comment by Sunnnner** [comment]
> @Sunnnner 你是否使用的是插件的最新版本？能提供动态图片，或录屏？

我的现在也可以了我给卸载重装了一下现在可以切换了
