### ISSUE TITLE
Provide `id` matching getId() value in plugin.xml

### ISSUE THREAD

**Issue by YannCebron** [YiiGuxing/TranslationPlugin#4195]
### 📝 Issue Description

https://github.com/YiiGuxing/TranslationPlugin/blob/ee636c37da26e53df228ed2b5b1d706eb711a458/src/main/resources/META-INF/plugin.xml#L69

required for 2023.2

### 🏷 Plugin Version

2.2.2.2

### 🔁 Translation Engine(s)

All

**Comment by YiiGuxing** [comment]
Thanks!
