### ISSUE TITLE
增加关闭右键菜单显示的功能

### ISSUE THREAD

**Issue by huodon** [YiiGuxing/TranslationPlugin#421]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

1. 部分用户只使用快捷键访问翻译功能, 并不需要右键菜单
2. 右键菜单需要判断光标上下文,  关闭后更加环保清爽. 

### Proposed Solution

增加关闭右键菜单翻译的选项

**Comment by YiiGuxing** [comment]
请到 `设置` -> `Appearance & Behavior` -> `Menus and Toolbars` -> `Editor Popup Menu` 下进行编辑。
