### ISSUE TITLE
IDEA: Javadoc {@link ***} 翻译BUG

### ISSUE THREAD

**Issue by y616468159** [YiiGuxing/TranslationPlugin#422]
Translate 和 Translate Documentation 翻译结果不一致，案例如下：

来源(spring-beans):
org.springframework.beans.support.ResourceEditorRegistrar#ResourceEditorRegistrar

原文：
Create a new ResourceEditorRegistrar for the given {@link ResourceLoader}
	 * and {@link PropertyResolver}.

Translate：
为给定的{@link ResourceLoader} *和{@link PropertyResolver}创建一个新的ResourceEditorRegistrar。

Translate Documentation：
创建给定一个新的ResourceEditorRegistrar ResourceLoader和PropertyResolver 。

**Comment by YiiGuxing** [comment]
文档翻译的翻译内容里含有HTML内容，有差异实属正常。
