### ISSUE TITLE
点个赞，很好用！

### ISSUE THREAD

**Issue by yuanjinzhong** [YiiGuxing/TranslationPlugin#423]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by yuanjinzhong** [comment]
希望wordbook功能能整合一个账号体系，陌生单词跟着账号走

**Comment by YiiGuxing** [comment]
> 希望wordbook功能能整合一个账号体系，陌生单词跟着账号走

这个受限于资源，不能实现。而且现在的工作重点并不在单词本上。
