### ISSUE TITLE
每次打开idea都需要重新设置Translation翻译引擎

### ISSUE THREAD

**Issue by luce888** [YiiGuxing/TranslationPlugin#4237]
### 需求/建议描述

在之前的版本中并没有这个问题，现在每次当我打开idea需要用的 Translation 的翻译功能时，总是会出现翻译引擎的设置弹窗，需要我重新输入我的应用程序密钥，这并不方便。

### 建议的解决方案

请同时记录保存我的应用程序ID和应用程序密钥，别让我每天使用时再填一遍密钥了。

**Comment by YiiGuxing** [comment]
这个是IDE的锅。。。。
用这个方法试试：
https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key

**Comment by luce888** [comment]
解决了，感谢！


发件人: ***@***.***>
发送时间: 2023年8月11日 11:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [YiiGuxing/TranslationPlugin] 每次打开idea都需要重新设置Translation翻译引擎 (Issue #4237)


这个是IDE的锅。。。。
用这个方法试试：
https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key

―
