### ISSUE TITLE
Golang 某些情况下 Translate Documentation 不显示

### ISSUE THREAD

**Issue by mritd** [YiiGuxing/TranslationPlugin#427]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description

Golang 一些情况下 Translate Documentation 在右键菜单内不显示：
- 字段
- 顶级方法
- 顶级常量

### Environment & Stack Trace
- Plugin version: 2.7.0
- IDE version: GoLand 2019.2
- Operating System and version:  Mac 10.14.6

### Others

根据 README 描述，光标已经放置于文档区域，并且未选中文本，右键菜单中没有找到 `Translate Documentation` 选项，截图如下:

![image](https://user-images.githubusercontent.com/13043245/71981443-6836f180-325d-11ea-9413-4a889e102680.png)

**Comment by YiiGuxing** [comment]
你的光标是否是在行的末尾？行的末尾在语法树里并不属于文档区域内

**Comment by YiiGuxing** [comment]
已知晓是何问题，由于本人对Go语言并不熟悉，漏掉了对Go结构体属性定义的文档翻译的实现。如还有类似的情况，还请提醒一下，感谢反馈。

**Comment by mritd** [comment]
感谢 😊
