### ISSUE TITLE
翻译文档失败：Authentication failed:网络错误

### ISSUE THREAD

**Issue by GeWuYou** [YiiGuxing/TranslationPlugin#4298]
### 📝 问题描述

之前微软翻译还能使用的，但从昨天开始，使用微软翻译一直提示翻译文档失败：Authentication failed:网络错误，尝试了很久，无论是挂梯子还是不挂梯子都不起作用，重启idea与电脑也没有效果，电脑网络是正常的，但从clash的日志可以看到edge.microsoft.com:443 ERROR->dial tcp4 13.107.21.239:443:i/o timeout但我不知道如何解决。之前是即使我挂了梯子微软翻译也是能用的

### 🏷 插件版本

3.5.2

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
操作系统：Windows 10.0
```

**Comment by YiiGuxing** [comment]
你试试用 edge 浏览器访问一个英文网站，然后用浏览器的翻译功能翻译一下网站，看看能不能释放成功？

**Comment by GeWuYou** [comment]
确实，我发现edge的翻译功能似乎不可用了，无论我开启梯子还是关闭梯子，都这样，请问这是怎么一回事？能否提供一下解决办法？谢谢！
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/95328647/06fda0c7-4e35-41ea-98ed-37d29984ff8c)

**Comment by GeWuYou** [comment]
在我折腾了半天无果后，莫名其妙，这个edge又能够翻译了，idea的微软翻译引擎也能用了
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/95328647/3eaeedbd-d795-40f6-be04-bd626da15937)
只能说这个网络太奇怪了，不好意思，这不是你们的问题，这应该是我网络的问题，虽然现在都不知道到底咋好的。

**Comment by YiiGuxing** [comment]
应该是DNS污染的问题。
