### ISSUE TITLE
持久化存储问题

### ISSUE THREAD

**Issue by BolexLiu** [YiiGuxing/TranslationPlugin#43]
你好，我也在写一款翻译插件。但是我做的是本地存储，用IO的方式放在本地。但出现了一个问题。
在windows平台上权限是足够的。到了linux和mac平台就无法直接操作io了。目前没有找到很好的办法解决。 除非用户将文件夹权限改为777才可以写入。但是这个太麻烦了。不方便。求给点提示。

**Comment by YiiGuxing** [comment]
@BolexLiu IDE有自己的存储空间，你可以把你需要存储的数据存放在那里，它是以XML的的形式存储的。可以看一下PersistentStateComponent部分的内容。

**Comment by YiiGuxing** [comment]
Closing as not TranslationPlugin related.

**Comment by BolexLiu** [comment]
感谢，我去看看
