### ISSUE TITLE
多行合并翻译

### ISSUE THREAD

**Issue by drrrMikado** [YiiGuxing/TranslationPlugin#430]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

- 一个长句使用多行`//`来注释时，在用选中翻译的情况下，是否能够合并成一句来翻译呢？

### Proposed Solution

- 合并多行翻译：

这是个示例待翻译源码：
```go
// ErrUnexpectedEOF means that EOF was encountered in the
// middle of reading a fixed-size block or data structure.
var ErrUnexpectedEOF = errors.New("unexpected EOF")
```
来自 [io.go](https://github.com/golang/go/blob/master/src/io/io.go#L42)

插件翻译的结果：
```
// ErrUnexpectedEOF表示在
//读取固定大小的块或数据结构的中间。
```

期望结果：
```
// ErrUnexpectedEOF表示在读取固定大小的块或数据结构的过程中遇到了EOF。
```

**Comment by YiiGuxing** [comment]
请在插件设置页取消勾选“保持文本格式”选项，并忽略`//`，或者使用列选择模式选择多行文本。
