### ISSUE TITLE
无法切换翻译引擎

### ISSUE THREAD

**Issue by AspirinZjh** [YiiGuxing/TranslationPlugin#4300]
### 📝 问题描述

默认为谷歌引擎，当我配置好有道翻译引擎后点击切换无响应，尝试其他引擎也不能切换，是否不兼容最新版的idea呢

### 🏷 插件版本

3.5.2

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
我的IDEA版本：2023.2
```

**Comment by YiiGuxing** [comment]
您好，请问您的这个问题是如何出现的？您又为何关闭了？是解决了吗？如果是已经解决了，请问是如何解决的？

**Comment by GuanTu** [comment]
@YiiGuxing 您好，我本地出现了翻译引擎切换失败问题，IDEA 2023.2.1

![切换失败Gif图](https://github.com/YiiGuxing/TranslationPlugin/assets/22937069/d84ad567-18a1-46ab-bc47-fd94bf01ce97)

**Comment by GuanTu** [comment]
> @GuanTu 请问你安装的插件的版本是多少？又是通过什么方式安装的？

插件版本：3.5.2，通过IDEA中插件市场安装
我电脑上还有GoLand，也有TranslationPlugin，但切换没问题

**Comment by YiiGuxing** [comment]
> > @GuanTu 请问你安装的插件的版本是多少？又是通过什么方式安装的？
> 
> 插件版本：3.5.2，通过IDEA中插件市场安装 我电脑上还有GoLand，也有TranslationPlugin，但切换没问题

@GuanTu 那切换失败的时候，IDE 下面的状态栏右下方有没有一个红色闪烁的图标？

**Comment by GuanTu** [comment]
> > > @GuanTu 请问你安装的插件的版本是多少？又是通过什么方式安装的？
> > 
> > 
> > 插件版本：3.5.2，通过IDEA中插件市场安装 我电脑上还有GoLand，也有TranslationPlugin，但切换没问题
> 
> @GuanTu 那切换失败的时候，IDE 下面的状态栏右下方有没有一个红色闪烁的图标？

好像没有
![动画1](https://github.com/YiiGuxing/TranslationPlugin/assets/22937069/e2d8b8bd-72e1-4f1f-b804-67e50159f051)

**Comment by YiiGuxing** [comment]
@GuanTu 麻烦你提供一下插件的安装文件，一般在这个路径下：
```
C:\Users\{你的账户名}\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\TranslationPlugin
```

将整个 TranslationPlugin 目录打包上传，我分析一下安装包。

**Comment by GuanTu** [comment]
@YiiGuxing 辛苦了

[TranslationPlugin.zip](https://github.com/YiiGuxing/TranslationPlugin/files/12481590/TranslationPlugin.zip)

**Comment by likeadog** [comment]
+1

**Comment by YiiGuxing** [comment]
@GuanTu 重启IDE后仍然无法切换吗？你试试切换到微软翻译，然后重启IDE，看看IDE启动后是微软翻译还是谷歌翻译。

**Comment by YiiGuxing** [comment]
我已经知道是什么问题了，也能复现了，这个问题重启一下IDE就好了。晚上我发个版本修复它，感谢大伙儿！

**Comment by GuanTu** [comment]
> @GuanTu 重启IDE后仍然无法切换吗？你试试切换到微软翻译，然后重启IDE，看看IDE启动后是微软翻译还是谷歌翻译。
> 
> 我这里无法复现这个问题。

是的，重启IDEA就好了，也可以正常切换了
