### ISSUE TITLE
Translate Documentation 和 选中翻译去手动删除`//`后翻译的结果不一致

### ISSUE THREAD

**Issue by drrrMikado** [YiiGuxing/TranslationPlugin#431]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details

- Translate Documentation 和 选中翻译去手动删除`//`后翻译的结果不一致

### Description

复现步骤：
1. 选中整个文档翻译部分，右键选择`Translate`，在弹出的框中点击右上角的图钉，进入可修改翻译文本框中，手动删除`//`
2. **或者**按`CTRL+Q`出Quick Documentation时选择全部注释原本，在按`CTRL+SHIFT+Y`进入翻译，翻译结果也不一致。
3. 使用Google翻译，没有勾选`使用translate.google.com`

问题截图：
![image](https://user-images.githubusercontent.com/11224565/72208516-865f5480-34de-11ea-9ccd-c85566a9a160.png)
![image](https://user-images.githubusercontent.com/11224565/72208701-fbcc2480-34e0-11ea-8991-0c3cf03eab9a.png)

翻译代码：
```go
// EOF is the error returned by Read when no more input is available.
// Functions should return EOF only to signal a graceful end of input.
// If the EOF occurs unexpectedly in a structured data stream,
// the appropriate error is either ErrUnexpectedEOF or some other error
// giving more detail.
var EOF = errors.New("EOF")
```
来源：[io.go](https://github.com/golang/go/blob/master/src/io/io.go#L38)

### Environment & Stack Trace
- Plugin version: 2.7.0
- IDE version: GOLAND 2019.3.1
- Operating System and version: Windows 10 1909

**Comment by YiiGuxing** [comment]
出现这种差异是因为文档翻译送出去翻译的内容是HTML内容，有着HTML标签的干扰所导致的，这是谷歌翻译的问题，我无能为力。如果需要没有差异的，可以使用有道翻译或者百度翻译，这两个翻译不支持HTML内容翻译，所以送到这两个翻译的内容已经将HTML标签去除掉了，所以应该没有什么差异。但正因为这样，翻译之后的内容就无法保存原有的样式了。反正各有优缼点，就看你喜欢用哪个了。
