### ISSUE TITLE
输入应用密钥后确认无效

### ISSUE THREAD

**Issue by majingxuan123** [YiiGuxing/TranslationPlugin#432]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by majingxuan123** [comment]
plugin version：2.7.0
ideaversion 2019.02
operating system：macos 10.13.6
输入应用密钥之后 翻译提示签名校验失败、
随后打开插件设置发现刚输入的密钥又为空了

**Comment by YiiGuxing** [comment]
请总计FAQ部分。
![image](https://user-images.githubusercontent.com/10737066/72236575-6e88ed00-3612-11ea-820e-284caa4cc034.png)

**Comment by YiiGuxing** [comment]
提ISSUE时请按照 `Preflight Checklist` 的步骤预处理一下，谢谢！
