### ISSUE TITLE
can not save secret of translation app

### ISSUE THREAD

**Issue by majingxuan123** [YiiGuxing/TranslationPlugin#433]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
按照FAQ上的处理还是不能解决问题吗？

**Comment by YiiGuxing** [comment]
保存密钥的时候有没有异常？如果有的话请贴出：
![1](https://user-images.githubusercontent.com/10737066/72240609-9cc0f980-361f-11ea-9105-5c389071112c.png)

**Comment by YiiGuxing** [comment]
关闭原因：无回复
