### ISSUE TITLE
弄个离线版？不上网也能玩得233起来！

### ISSUE THREAD

**Issue by Byron4j** [YiiGuxing/TranslationPlugin#434]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
离线翻译没研究过，不过有道到是有离线版的SDK，但是Android的，也不知道能不能移置过来，有空再看下。

**Comment by YiiGuxing** [comment]
关闭原因：近期不会实现，也有可能永远都不会实现。如果有任何疑问，可以重新打开或者另提新Isuue。
