### ISSUE TITLE
dart 文件不能正确提供文档翻译功能

### ISSUE THREAD

**Issue by mcxinyu** [YiiGuxing/TranslationPlugin#436]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description
我在 android studio 上使用 dart 开发，
如下代码中，上部分注释可以触发文档翻译，下面部分无法触发文档翻译。
```
/// An image for a box decoration.
///
/// The image is painted using [paintImage], which describes the meanings of the
/// various fields on this class in more detail.
@immutable
class DecorationImage {
  /// Creates an image to show in a [BoxDecoration].
  ///
  /// The [image], [alignment], [repeat], and [matchTextDirection] arguments
  /// must not be null.
  const DecorationImage({
    @required this.image,
    this.colorFilter,
    this.fit,
    this.alignment = Alignment.center,
    this.centerSlice,
    this.repeat = ImageRepeat.noRepeat,
    this.matchTextDirection = false,
  }) : assert(image != null),
       assert(alignment != null),
       assert(repeat != null),
       assert(matchTextDirection != null);
}
```

**Comment by YiiGuxing** [comment]
可否烦劳您帮忙检查一下有无其他类似的情况？本人对Dart并不熟悉，所以才会有这样的遗漏，感谢！

**Comment by mcxinyu** [comment]
[享用 dart 注释支持](https://dart.cn/guides/language/language-tour#comments)

**Comment by mcxinyu** [comment]
似乎是在类体中第一个注释都识别不了，例如下面的片段，我把fileName移动到第一行就识别不了了。
```
class ABC {
  ///The file name for each image in your image sequence excluding the suffix. For example, if the images in your image sequence are named as
  ///'Frame_00000.png', 'Frame_00001.png', 'Frame_00002.png', 'Frame_00003.png' ...
  ///then the [fileName] should be 'Frame_'. This should be the same for all the images in your image sequence.
  String fileName;
  
  ///The folder of your image sequence relative to your assets. For example, if you add your image sequence to
  ///'assets/ImageSequences/MyImageSequence'
  ///then the [folderName] should be 'ImageSequences/MyImageSequence'. This should be the same for all the images in your image sequence.
  String folderName;

  ///The file name for each image in your image sequence excluding the suffix. For example, if the images in your image sequence are named as
  ///'Frame_00000.png', 'Frame_00001.png', 'Frame_00002.png', 'Frame_00003.png' ...
  ///then the [fileName] should be 'Frame_'. This should be the same for all the images in your image sequence.
  String fileName;
}
```

**Comment by mcxinyu** [comment]
另外，中括号中的单词建议不要翻译，因为那是字段或者类名。类似java的
```{@link className | #fieldName | #methodName()}```

**Comment by YiiGuxing** [comment]
emmm......这并不是注释本身，注释本身没有什么问题。而是文档注释注释的对象，语法哪些定义是可以进行文档注释的。
之前我从Dart插件原代码里猜测并找到的就是两种情况(`DartComponent` 和 `DartVarDeclarationList`)：
```dart
when (val sibling = getNextSiblingSkippingCondition(SKIPPING_CONDITION)) {
    is DartComponent -> sibling.componentName
    is DartVarDeclarationList -> sibling.findChildOfType(DartComponent::class.java)?.componentName
    else -> null
}
```
`DartComponent` 就包含了类、方法、顶变量等的定义。
出现该问题是因为漏掉了 `DartClassMembers` 的情况，所以加上就好了：
```dart
when (val sibling = getNextSiblingSkippingCondition(SKIPPING_CONDITION)) {
    is DartComponent -> sibling.componentName
    is DartClassMembers,
    is DartVarDeclarationList -> sibling.findChildOfType(DartComponent::class.java)?.componentName
    else -> null
}
```

但是我并不能确定是否还有其他的情况。

**Comment by YiiGuxing** [comment]
> 另外，中括号中的单词建议不要翻译，因为那是字段或者类名。类似java的
> `{@link className | #fieldName | #methodName()}`

这个需要Dart插件来提供支持，我只能遵照Dart插件的定义来处理，也就是说我不会修改Dart插件提供的文档的内容，谁知道它以后会弄成什么样的呢？所以只好期望Dart插件哪天能提供类似Java中 `@link` 的支持了。

**Comment by mcxinyu** [comment]
好的，以后发现其他问题我再反馈吧，辛苦了！

下面这个跟此 issues 无关，但是会误导用户，两个左边的单词是正确的，右边的单词是拼错的，但是翻译后出来结果了，我猜是 Google 翻译容错的结果，试了在 Google 翻译的时候会提示“**您是不是要找**”来提示我拼错了。如果谷歌的api有提供响应信息，可以加上。

![QQ截图20200115153119](https://user-images.githubusercontent.com/9566116/72414420-1fc38a80-37ad-11ea-9cba-12c909652a71.jpg)

![QQ截图20200115153921](https://user-images.githubusercontent.com/9566116/72414466-3ff34980-37ad-11ea-80e3-512f48b86581.jpg)

**Comment by YiiGuxing** [comment]
@mcxinyu 关于单词拼错的问题，可否重新提成一个新的Issue？，这样我好根据Issue来处理和开发。

**Comment by mcxinyu** [comment]
ok
