### ISSUE TITLE
如果在翻译框打字输入一段话，过一会就不能翻译了，第二天又恢复了

### ISSUE THREAD

**Issue by ycc-sf** [YiiGuxing/TranslationPlugin#4360]
### 📝 问题描述

现象：如果在翻译框打字输入一段话，过一会就不能翻译了，第二天又恢复了；
猜测：输入框是实时检测每个字符输入就触发翻译接口，所以直接在翻译框里打字的话会频繁调用接口，然后被限流了？

### 🏷 插件版本

3.5.3

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
2022.3.3 CommunityEdition
```

**Comment by YiiGuxing** [comment]
啊？谷歌又调接口调用频率限制了？这确实是你所猜测的情况。看来得优化一下这个实时翻译了。
