### ISSUE TITLE
建议当单词拼错时添加提醒

### ISSUE THREAD

**Issue by mcxinyu** [YiiGuxing/TranslationPlugin#437]
请看截图。左边的单词是正确的，右边的单词是拼错的，但是翻译后出来结果了，我猜是 Google 翻译容错的结果，试了在 Google 翻译的时候会提示“您是不是要找”来提示我拼错了。如果谷歌的api有提供响应信息，可以加上提示。

![QQ截图20200115153119](https://user-images.githubusercontent.com/9566116/72414971-6960a500-37ae-11ea-9dde-026dbecf1e01.jpg)

![QQ截图20200115153921](https://user-images.githubusercontent.com/9566116/72414977-6cf42c00-37ae-11ea-8916-2ceb36d3ba10.jpg)

**Comment by YiiGuxing** [comment]
## Proposed Solution
- Param: `dt=qca`
- Result:
  ```json
  {
    "spell": {
      "spell_res": "spell",
      "correction_type": [1],
      "confident": false
    }
  }
  ```

**Comment by mystic-cg** [comment]
spelling check, Jetbrains,默认就是开启的

**Comment by mystic-cg** [comment]
最近还推出了Grazie插件.

> Provides intelligent spelling and grammar checks for text that you write in the IDE.

**Comment by YiiGuxing** [comment]
@mystic-cg 实现这个功能并不难，非常简单的，所以是可以实现的。而且IDE的拼写检查好像只有在编辑器里提供，其他地方就不行了，所以这个功能还是有必要的。
