### ISSUE TITLE
对openai添加自定义的api接口地址

### ISSUE THREAD

**Issue by Autumn-one** [YiiGuxing/TranslationPlugin#4370]
### 需求/建议描述

目前的openai翻译只能接入openai官方的key，但是官方的服务在国内用起来需要很麻烦的捣腾，会有一些第三方的openai服务代理来简化这个步骤，我们可以注册openai代理服务，一般代理服务的接口和openai的接口是全兼容的，所以只需要自定义接口地址就好了，例如aiproxy的接口地址就是：https://api.aiproxy.io/v1/chat/completions

### 建议的解决方案

对于openai提供自定义接口地址的功能，默认为openai的官方地址，如果用户用的是第三方的代理那么可以让用户自行修改接口地址并使用第三方的api key。
具体可以参照浏览器插件：沉浸式翻译的openai相关设置
![图片](https://github.com/YiiGuxing/TranslationPlugin/assets/26438145/e408417f-a05b-472c-960c-23da806f34bf)

**Comment by YiiGuxing** [comment]
下个版本会加上的

**Comment by Autumn-one** [comment]
> 下个版本会加上的

👍👍👍👍
