### ISSUE TITLE
默认可以是英文转中文吗？

### ISSUE THREAD

**Issue by yh3434** [YiiGuxing/TranslationPlugin#438]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
默认就是英文转中文啊，除非你设置主语言为非中文的。

**Comment by yh3434** [comment]
好的，谢谢，电脑系统是英文的，可以考虑出个设置默认语言的的功能。

**Comment by YiiGuxing** [comment]
主语言就是根据系统语言而定的，系统是中文则主语言为中文，系统是英文则主语言为英文。

**Comment by Notelzg** [comment]
> 好的，谢谢，电脑系统是英文的，可以考虑出个设置默认语言的的功能。

我也需要

**Comment by YiiGuxing** [comment]
@Notelzg 你可以手动设置
