### ISSUE TITLE
建议添加可以自定义api

### ISSUE THREAD

**Issue by blazert** [YiiGuxing/TranslationPlugin#4385]
### 需求/建议描述

鉴于openai访问的限制，希望添加可以自定义api地址的选项，包括deepl翻译

### 建议的解决方案

现在很多热心大佬给出的完全兼容openai接口以及deepl翻译api的国内访问地址，希望在这两个（openai和deepl）引擎配置项添加自定义api地址

**Comment by YiiGuxing** [comment]
openai 的将会在下一个版本添加，deepl 相关的，可以关注 #3225.
