### ISSUE TITLE
国内gpt的api

### ISSUE THREAD

**Issue by LiJoeAllen** [YiiGuxing/TranslationPlugin#4386]
### 需求/建议描述

讯飞啥的这些api啥时候接一下😄O(∩_∩)O

### 建议的解决方案

讯飞啥的这些api啥时候接一下😄O(∩_∩)O

**Comment by YiiGuxing** [comment]
合并至 #5276

如果目标 gpt 兼容 OpenAi API，则可通过自定义API 地址、模型名、提示词实现调用：#6235
