### ISSUE TITLE
字体模糊

### ISSUE THREAD

**Issue by ryanwlb** [YiiGuxing/TranslationPlugin#439]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
mac idea 2019.3版本  最新版translation插件

### Description
用触摸板上下滑动翻译界面字体会重叠模糊，查询翻译速度比2019.1版本变慢很多，查询结果已经出来了界面还一直在显示querying
![image](https://user-images.githubusercontent.com/16047642/72660017-c3f23f00-3a02-11ea-8431-452e370ff308.png)

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
重叠绘制是只有用触摸板的时候才会出现吗？是升级后出现的吗？从哪个版本升级上来后出现的？哪个版本的插件是能正常绘制的？最新版本的插件在哪个版本的IDEA能正常绘制？IDEA是不是使用了什么主题插件？

本人没有MAC电脑，无法找出原因。

**Comment by YiiGuxing** [comment]
我试了一下，MacOS 10.13，插件2.7.1，并未出现重叠绘制的情况啊，不过没有触摸板。

**Comment by YiiGuxing** [comment]
无法复现啊：
![image](https://user-images.githubusercontent.com/10737066/72680176-faf34e00-3af1-11ea-9ada-b0b1d6b65cce.png)
![image](https://user-images.githubusercontent.com/10737066/72680180-00509880-3af2-11ea-8ef5-c22401d99604.png)
![image](https://user-images.githubusercontent.com/10737066/72680185-05ade300-3af2-11ea-8a9c-517506073c8f.png)

**Comment by YiiGuxing** [comment]
关闭：无回复

**Comment by ryanwlb** [comment]
可能是本地ide问题，已经好了，谢谢老哥更新，辛苦
