### ISSUE TITLE
插件名具体叫什么，readme里没写，搜translate太多了

### ISSUE THREAD

**Issue by jp1017** [YiiGuxing/TranslationPlugin#440]
所以，很难找到呀，，，，，，，

**Comment by YiiGuxing** [comment]
README 《安装》部分写得挺清楚的啊：

> - **使用 IDE 内置插件系统安装:**
>   - <kbd>Preferences(Settings)</kbd> > <kbd>Plugins</kbd> > <kbd>Browse repositories...</kbd> > <kbd>搜索并找到"Translation"</kbd> > <kbd>Install Plugin</kbd>

emmm...新版本没有<kbd>Browse repositories...</kbd>了，是<kbd>Marketplace</kbd>了。
顺便提一下，下载量最多的就是了，:cherry_blossom::chicken:
