### ISSUE TITLE
建议加一个微软bing翻译

### ISSUE THREAD

**Issue by soulgoast** [YiiGuxing/TranslationPlugin#442]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

办公环境中，网络不稳定，google翻译有时候无响应。

**Comment by YiiGuxing** [comment]
也曾有过这个打算，但无奈于没有微软翻译服务的帐号，也不知道是否可免费使用，连测试一下的都不能。它在线翻译网页上的API好像可用，但还不知道能用多久，而且查单词的话没有音标。

**Comment by YiiGuxing** [comment]
有空我再试一下使用在线翻译网页上的API实现一个。

**Comment by soulgoast** [comment]
好的，感谢。------------------ 原始邮件 ------------------
发件人: "Yii.Guxing"<notifications@github.com>
发送时间: 2020年1月21日(星期二) 下午5:02
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>;
抄送: "都本"<759433926@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [YiiGuxing/TranslationPlugin] 建议加一个微软bing翻译 (#442)



有空我再试一下使用在线翻译网页上的API实现一个。
 
&mdash;

**Comment by kings1990** [comment]
所以实现了么，感觉bing翻译对计算机领域的翻译是比较友好的

**Comment by YiiGuxing** [comment]
> 所以加个实现了么，感觉bing翻译对计算机领域的翻译是比较友好的，谷歌翻译出来的不准确，深受其害

目前还没有

**Comment by kings1990** [comment]
恩,我也是插件作者,翻译技术类文档的时候确实感觉bing准一些
