### ISSUE TITLE
每次重启idea，百度翻译api密钥就没了

### ISSUE THREAD

**Issue by wentlwr** [YiiGuxing/TranslationPlugin#4440]
### 📝 问题描述

1.配置好百度翻译api，可以正常使用
2.重启idea，选词翻译，跳出如图界面，密钥丢失，需要重新登录
![图片](https://github.com/YiiGuxing/TranslationPlugin/assets/81084625/7d753820-0ec9-4df7-98c9-d86b0f255864)

### 🏷 插件版本

3.5.4+203u212,以及上一个版本，都有所描述的问题

### 🔁 翻译引擎

百度翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to ChinaNB
Subscription is active until December 31, 2099.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```

**Comment by YiiGuxing** [comment]
请参阅：https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key
