### ISSUE TITLE
百度翻译翻译的文档格式异常

### ISSUE THREAD

**Issue by XiaYule2022** [YiiGuxing/TranslationPlugin#4480]
### 📝 Issue Description

原文
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/106853902/27a67478-766b-45db-83a8-d515c25f9312)
微软翻译正常，翻译结果
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/106853902/070a6248-e812-4069-b4a8-4526be2e2d12)

但是切换到百度翻译文档格式就会发生异常
翻译后
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/106853902/201fb773-f34a-4c7f-b3ce-3ece580b0f45)

### 🏷 Plugin Version

3.5.4+203u212

### 🔁 Translation Engine(s)

Baidu Translate

### 💻 IDE and Operating Environment

```plain text
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 23, 2023
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: debugger.watches.in.variables=false, documentation.show.toolbar=true
Non-Bundled Plugins: com.github.nreg.SearchWithBing (1.0), com.ptg.quickcodegeneration.plugin (1.4.1), com.xstudio.com.xstudio.plugin.idea (1.0.17), com.alibaba.p3c.smartfox (2.1.1), com.java256.typingCat (0.0.9), izhangzhihao.rainbow.brackets (2023.3.5-ij), com.baomidou.plugin.idea.mybatisx (1.6.0), io.zhile.research.ide-eval-resetter (2.3.5), cn.yiiguxing.plugin.translate (3.5.4+203u212)
Kotlin: 212-1.5.31-release-546-IJ4638.7
```

**Comment by YiiGuxing** [comment]
百度翻译不支持 HTML 文档翻译，因此对文档的翻译不能保存原文档样式。
