### ISSUE TITLE
更新TTK失败，请检查网络连接

### ISSUE THREAD

**Issue by guofeiwu** [YiiGuxing/TranslationPlugin#453]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
TKK 更新TTK失败，请检查网络连接
			
### Description

1.点击翻译
![image](https://user-images.githubusercontent.com/22710134/75111133-62606880-5671-11ea-9b28-410cecaae370.png)
2.无法查询到结果
![image](https://user-images.githubusercontent.com/22710134/75111159-920f7080-5671-11ea-929b-ea98edc55fff.png)
3.我之前用的idea 是2018.3，用的插件版本不是最新版本可用。是不是适配问题？

### Environment & Stack Trace
- Plugin version:2.7.3
- IDE version: 2019.3.3
- Operating System and version:  mac os  10.14.6

**Comment by guofeiwu** [comment]
https://github.com/YiiGuxing/TranslationPlugin#faq 未使用代理，并且https://translate.google.com/这个在国内不使用VPN也是能访问的。

**Comment by guofeiwu** [comment]
![image](https://user-images.githubusercontent.com/22710134/75111309-6e4d2a00-5673-11ea-8cb6-1f0f8600a15e.png)
去除了这个勾选框，望作者在下个版本中去掉这个自动勾选，这个很坑。其他的功能还是很nice。

**Comment by YiiGuxing** [comment]
这个选项是根据系统环境自动设置的，如果系统语言环境是非中文的话，此选项是默认勾选的。

**Comment by summertravel** [comment]
奇怪的是我的windows系统设置的语音就是中文，还是默认勾选了。感谢@guofeiwu

**Comment by guofeiwu** [comment]
> 奇怪的是我的windows系统设置的语音就是中文，还是默认勾选了。感谢@guofeiwu

No thanks,You should say thanks to the developer。

**Comment by i-ce-fish** [comment]
取消勾选translate.google.com选项后还需要重启IDEA才能生效

**Comment by guofeiwu** [comment]
> 取消勾选translate.google.com选项后还需要重启IDEA才能生效

我这边没有重启，OK了

**Comment by Kirito0512** [comment]
> 取消勾选translate.google.com选项后还需要重启IDEA才能生效

默认没勾选，重启idea，依然不行。。google也能打开。。

**Comment by YiiGuxing** [comment]
@Kirito0512 有可能是代理的问题

**Comment by YiiGuxing** [comment]
鉴于google服务在国内访问并不稳定，在下一下版本将 `translate.google.com` 选项在内部改用为 `translate.googleapis.com` ，这个服务在国内也是可以访问的，届时如果在使用 `translate.google.cn` 仍然无法使用的情况下，可以尝试勾选 使用`translate.google.com` 选项进行翻译。

**Comment by gaochengyidlmu** [comment]
可以检查一下 idea 的 proxy，我之前配置了 proxy，后来忘记了，这次遇到这个问题就卡了半天
![image](https://user-images.githubusercontent.com/18210759/140934929-8449858a-137e-4192-b09d-b30a31dc7bbe.png)
