### ISSUE TITLE
每日单词可以自动发音吗?

### ISSUE THREAD

**Issue by chenkaiSsS** [YiiGuxing/TranslationPlugin#455]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
抱歉，我不太明白您为什么要这么做，我认为这么做完全没有必要，除非您有足够充分的理由来说服我。
