### ISSUE TITLE
是否可以增加代理设置

### ISSUE THREAD

**Issue by buchijiang** [YiiGuxing/TranslationPlugin#456]
想使用Google的api翻译，但是获取不到，我有科学上网，用pac模式，插件就无法愉快的使用了
所以想增加代理设置

**Comment by YiiGuxing** [comment]
1. 插件有Google翻译国内的API，你可以在插件设置页进行配置。
2. IDE有代理设置，你可以在IDE的代理设置页进行代理配置。
