### ISSUE TITLE
作者你好，能否把translate.google.com改成https://translate.google.cn/,cn是不用翻墙的

### ISSUE THREAD

**Issue by imzion** [YiiGuxing/TranslationPlugin#457]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
请到插件设置页配置
