### ISSUE TITLE
建议增加自建DeepL、OpenAI翻译 API URL

### ISSUE THREAD

**Issue by donglex** [YiiGuxing/TranslationPlugin#4587]
### 需求/建议描述

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/45646429/af6afec4-9031-4f95-bd70-fb8f8e4ece5a)
建议这里增加一个自定义的API URL，而不是局限于官方的网址。😊

### 建议的解决方案

建议新增自建DeepL、OpenAI的API URL

**Comment by YiiGuxing** [comment]
Duplicate of #3765 , #3225
