### ISSUE TITLE
申请了有道的API KEY,但是提示无效的API KEY

### ISSUE THREAD

**Issue by 09xuanjian** [YiiGuxing/TranslationPlugin#46]
如题，申请了两个了，还是一样提示这个

![image](https://cloud.githubusercontent.com/assets/9784328/24397059/c3f709bc-13d7-11e7-808d-45a3902ecfdb.png)

![image](https://cloud.githubusercontent.com/assets/9784328/24397499/fea0f07c-13d8-11e7-8ffc-43a64259f08f.png)

**Comment by YiiGuxing** [comment]
@09xuanjian 你的key from是不是填错了？申请得到的是两个值，keyfrom 和 key ，分别填上就行了的。我看你的keyfrom 和 key好像是一样的，这不太可能的，是不是填错了？

**Comment by 09xuanjian** [comment]
额，可以了，我弄错了~~
