### ISSUE TITLE
关于翻译文档注释的建议

### ISSUE THREAD

**Issue by catmade** [YiiGuxing/TranslationPlugin#460]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

翻译 java 注释时，会将注释里的代码也翻译了。可以通过设置过滤内容的正则表达式来忽略部分内容：
![image](https://user-images.githubusercontent.com/38749472/76839237-1ec3dd80-6870-11ea-82db-1569d35bb397.png)
但是 java 注释里的注解比较多，有的注释还夹杂着html标签。没有深入研究 java 注释格式的话，写不出比较全面的正则表达式来过滤这些内容（反正我写不出来。。。😂好吧，我承认是我懒）。

### Proposed Solution

- 建议给出几种默认的正则表达式来针对性的翻译
- 允许用户添加自己的正则表达式
- 用户可以选择性的启用指定的正则表达式，来满足不同的翻译需求。
具体的话，如下图：
![image](https://user-images.githubusercontent.com/38749472/76840878-deb22a00-6872-11ea-9045-9d7a897f3f65.png)

**Comment by YiiGuxing** [comment]
- #130
- http://yiiguxing.github.io/TranslationPlugin/updates.html?v=2.6
