### ISSUE TITLE
在Mac上，当我同时使用IDEA和AndroidStudio 安装这个插件的时候，出现这个BUG

### ISSUE THREAD

**Issue by xiaolei123** [YiiGuxing/TranslationPlugin#462]
在Mac上，当我同时使用IDEA和AndroidStudio 安装这个插件的时候，IDEA和AndroidStudio都安装了这个插件。

1.都使用这个翻译插件，
2.都用的有道的翻译引擎，
3.使用同一个有道的密钥，

当我在AndroidStudio配置好的时候，AndroidStudio可以正常翻译，但是IDEA说密钥错误。
当我在IDEA配置好的时候，IDEA可以正常翻译，但是AndroidStudio提示密钥错误。

**Comment by YiiGuxing** [comment]
可以尝试将密码保存方式改成`In KeePass`方式 (Settings > Appearance & Behavior > System Settings > Passwords)

**Comment by YiiGuxing** [comment]
关闭原因：无回复
如有任何问题，可以随时重新打开。
