### ISSUE TITLE
Android studio提示IDE版本过旧

### ISSUE THREAD

**Issue by Zheng-Shuo** [YiiGuxing/TranslationPlugin#464]
如题，android studio使用的是3.6.1，Translation使用的是2.8.0，每次打开android studio都会提示过旧的IDE版本，将来的版本将不再支持此版本的IDE，请升级IDE以持续获取新的功能，idea使用的2019.3.3不会出现该提示，请问我应该怎么做？

**Comment by YiiGuxing** [comment]
由于IDE的一些API在2020.2版本时将会被删除，如果不做适配的话到时候插件将无法使用，因此插件在3.0版本时会适配好新的API。然而做适配的版本又不兼容2019.3以下的版本，所以才会有这一个提示。只要点击“不再提示”就会在当前的版本内不再提示了，如果AS所基于的IDE版本升级了，只要不是2019.3及以上的版本，它还是会重新提示的，只能再点“不再提示”。

2.x版本的插件将会兼容到2020.1版本的IDE，3.0版本发布的时候我想AS也应该升级到2019.3以上了。
