### ISSUE TITLE
mac os环境下,加载图标会忽大忽小

### ISSUE THREAD

**Issue by AsukaD** [YiiGuxing/TranslationPlugin#466]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
这是启用翻译插件的加载效果
![image](https://user-images.githubusercontent.com/43928593/77979951-9f86dd00-7338-11ea-9cff-47de54fbce33.png)
这是不启用的
![image](https://user-images.githubusercontent.com/43928593/77979964-add4f900-7338-11ea-9a19-25f6dbb602ff.png)
不仅插件本身的加载图标会忽大忽小，还会导致其他的加载图标忽大忽小，比如maven

### Environment & Stack Trace
- Plugin version: 2.8.0
- IDE version: 2019.3.4
- Operating System and version: macOS 10.15.4

**Comment by YiiGuxing** [comment]
啊~还能有这样的操作？这就很尴尬了。。。
