### ISSUE TITLE
openai 翻译，能不能增加接口地址的配置

### ISSUE THREAD

**Issue by yanghx-git** [YiiGuxing/TranslationPlugin#4677]
### 需求/建议描述

建议增加 接口地址的配置，可以设置一些国内gpt接口代理。
因为直连openai 延迟高，ip也容易挂

<img width="627" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/30469680/e11f459f-350a-4790-9425-04a3c7faecab">

### 建议的解决方案

自定义 接口地址

**Comment by YiiGuxing** [comment]
重复： #3765
开发中，如果急用，可以先使用 #3225 里的版本，此版本包含此功能，但不在正式渠道列表中，在此功能的正式版本发布之前可能不会有维护版本的更新（其中存在的 bug 不会被修复）。
