### ISSUE TITLE
翻译文档的功能在 rider 上面无法使用 

### ISSUE THREAD

**Issue by ifnk** [YiiGuxing/TranslationPlugin#4683]
### 需求/建议描述

我开了 翻译文档的功能 
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/39295458/edd4da41-5517-4fcb-b491-5ff06fb0614f)

但是 在rider 里面无法翻译 文档 ，点了也没有反应
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/39295458/fa1c5416-40b1-4040-9e1d-c201c391ea08)

但是在webstorm 里面是好用的 
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/39295458/66d94eec-e187-4ac1-81e3-2fd318a08292)

### 建议的解决方案

建议 rider 也添加 翻译文档的功能

**Comment by YiiGuxing** [comment]
Duplicate of #1986
