### ISSUE TITLE
可以添加忽略翻译{@code Period}类似这种的功能么???

### ISSUE THREAD

**Issue by bangiao** [YiiGuxing/TranslationPlugin#469]
软件很好用, 不过用了一段时间发现了两个问题, 下面是我举得例子: 

java.time.Period#between类似于翻译这个方法
鼠标右键translate Documentation后下面翻译成: 

`获得Period包括年，月和日两个日期之间的号码。
开始日期被包括在内，但结束日期是没有的。****`

看上面这个翻译存在问题
如果我选取这段注释, 添加了忽略正则表达式 

> (\*{1,}|/{1,}-{1,}|/)

发现翻译很正确, 但是{@code Period}被翻译成了 {@code期间} 而且段落没有效果, 变成了 <p>

`获取一个{@code期间}，该期间由两个日期之间的年，月和日组成。 <p>包括开始日期，但不包括结束日期。`

如果能变成这样就完美了

`获取一个{@code Period}，该期间由两个日期之间的年，月和日组成。 // 有一个回车
包括开始日期，但不包括结束日期。`

**Comment by YiiGuxing** [comment]
文档翻译不准确是因为翻译内容中含有HTML标签，这是没有办法的事，谷歌都搞不定的事，我就更不能了。。。。
至于忽略`{@code ...}`这样的内容，只要正则表达式正确，就是可以的，你可以试试这个表达式：
```regex
\{@code (?=[^\{\}]+\})|(?<=(\{@code [^\{\}]+))\}
```
然后就可以获得这样的翻译：`获取一个周期，该周期由两个日期之间的年，月和天数组成。` 
（需要把`保留文本格式`选项取消勾选翻译才更准确）

**Comment by YiiGuxing** [comment]
#470
