### ISSUE TITLE
hi, 我导入你的插进项目到intellij  里面，我想修改东西，但是不能编译成功

### ISSUE THREAD

**Issue by androidBsat** [YiiGuxing/TranslationPlugin#47]
hi, 我导入你的插进项目到intellij  里面，我想修改东西，但是不能编译成功

**Comment by YiiGuxing** [comment]
@androidBsat 是不是报类找不到错误？这个需要idea 2016 以上的版本才行，最好下载一个最新的版本来试试，现在版本都到2017.1了。

**Comment by androidBsat** [comment]
1.我用的2017.1的，我发现直接导入你的不可以编译，我就把src 和resource拷贝出来，自己新建了一个插件工程，拷贝进去。虽然可以运行，但是我觉得好笨---。--- 

你用的是2017.1的吗？ 

2.这些操作intellij  的open api 你在哪看的？我找不到。比如：
 static {
        TextAttributes attributes = new TextAttributes();
        attributes.setBackgroundColor(new JBColor(new Color(0xFFE4E4FF), new Color(0xFF344134)));
        attributes.setEffectType(EffectType.LINE_UNDERSCORE);
        attributes.setEffectColor(new JBColor(0xFFEE6000, 0xFFCC7832));

        HIGHLIGHT_ATTRIBUTES = attributes;
    }


这里的TextAttributes ，没有api 完全瞎摸黑，不知道怎么写。

你好厉害啊！

**Comment by YiiGuxing** [comment]
1. 直接导入你的不能编译应该是没有设置SDK的问题，导入后设置一下Plugin SDK就可以了。实在不行用你那方法也是可以的。
2. api 是有的，但文档太少，几乎没有，可以通过源代码来了解。一开始我也是完全摸黑的，只是乱摸多摸就找到自己想要的了。多看源码，看人家是怎么实现的，找到与你想要实现的相似的功能，然后找到它，看看它是如何实现的，照着做就是了。还有你可以利用ide的自动完成功能、代码搜索功能来找到自己想要的api。还有，多留意ide在代码上的警告，警告信息很有可能给你提供一些帮助，就像JBColor这个类我就是通过警告信息才知道的，这才实现了黑白两个不同主题的颜色样式。警告我一般是当作错误来处理的。。。作为一个重度强迫症患者，对警告什么的完全无免疫力，完全不能忍，一定要干掉。。。

最后提一句，open api 的限制太大了，也可以使用非open api ，只不过你不能保证它在以后的版本中会不会被修改而已。
