### ISSUE TITLE
单词本 文件存储的位置

### ISSUE THREAD

**Issue by googx** [YiiGuxing/TranslationPlugin#471]
我使用翻译的时候,收藏了某个单词,这个单词进入了单词本中, 我觉得这个功能很好, 可以考虑增加更多的功能在上面,我之前也想写一个这样的插件. 

我现在自己有个需求, 想把这个单词里面的文件的变化进行文件监控, 这样我收藏的单词就会实时推送给我., 需要知道这个文件存在哪个路径下?

**Comment by YiiGuxing** [comment]
`C:\Users\{USER_NAME}\.translation\wordbook.db`
它是一个SQLite3数据库文件。

**Comment by googx** [comment]
thinks ,刚刚我已经看你代码找到了这个数据库文件了..嘿嘿
