### ISSUE TITLE
Support a new translator API: DeepL

### ISSUE THREAD

**Issue by STRRL** [YiiGuxing/TranslationPlugin#472]
# Feature request
Hi, I find a amazing translator [DeepL](https://www.deepl.com/) recently. It works better with technical documents than google translator.

But it's API need subscription. I already buy a developer license for personal usage, so I will be pleasure to help implantation this feature.

**Comment by YiiGuxing** [comment]
Pull Request Welcome!

**Comment by STRRL** [comment]
Hi, I found that DeepL makes no anti-robot strategy on it's API. I can use this directly.

But I am NOT sure if it is a kind of abuse or not.🤔

**Comment by YiiGuxing** [comment]
As long as the API with authentication is used, it will not constitute abuse.

**Comment by febelery** [comment]
@YiiGuxing  这个有没有开发计划呢？
还是等 @STRRL  这位同学的PULL REQUEST

**Comment by YiiGuxing** [comment]
@febelery 打上 `feature request` 标签的是有开发计划的。目前还不知道 @STRRL 有没有正在实现。不过打上 `PR welcome` 标签的是表示欢迎任何同学提交实现的PULL REQUEST，也表示我本人不会优先实现。我准备开始实现的时候，我会去掉 `PR welcome` 标签的。所以，如果有哪位同学准备要实现的话，请事先告诉我。

**Comment by asasas234** [comment]
@STRRL 期待你的实现，我用了下DEEPL 确实翻译效果更好

**Comment by YiiGuxing** [comment]
@STRRL Hi! I'm finally going to start adding support for DeepL translator, but I can't subscribe to the DeepL developer account, can I borrow your account token for development and testing? I guarantee that I will only use it for development and testing, and will not leak your account tokens. If you are willing to, please send your account token to my email: yii.guxing@gmail.com.
Thanks!

**Comment by febelery** [comment]
有新的进展吗?

**Comment by YiiGuxing** [comment]
> 有新的进展吗?

@febelery 由于无法申请获得账号，暂时搁置了。。。

**Comment by zenof** [comment]
@YiiGuxing 也许可以通过 [OpenL](https://docs.openl.club/#/API/format) 来达到目的，提供了包括 DeepL 在内的大部分翻译服务 API

**Comment by silas229** [comment]
Are there any news? Meanwhile, there is even a free version of the DeepL API available.

**Comment by YiiGuxing** [comment]
> Are there any news? Meanwhile, there is even a free version of the DeepL API available.

@silas229 Currently, DeepL does not support China, so my account cannot be authenticated and I cannot get the relevant token for development and testing.

**Comment by Violet-VE** [comment]
你可以尝试注册一个美国账号。可以使用这个网站获取美国信息用来注册http://haoweichi.com/
顺便催一下更(懒癌晚期不想敲代码)

**Comment by kpalatzky** [comment]
@YiiGuxing  When will this be included in the official Release?

**Comment by YiiGuxing** [comment]
> @YiiGuxing When will this be included in the official Release?

@kpalatzky It's hard to evaluate, but I'll do it soon.

**Comment by YiiGuxing** [comment]
> > @YiiGuxing When will this be included in the official Release?
> 
> @kpalatzky It's hard to evaluate, but I'll do it soon.

I am currently messed up by various bugs. I now kind of regret adding the error reporting feature, if I didn't add this feature, I wouldn't have known that there would be so many errors. 😅😅😅

**Comment by YiiGuxing** [comment]
Hi guys!

This feature is ready for release, but there is still some time before the official release. If you want early access, you can add the 
following plugin repository URL to your IDE's plugin repository list to get the plugin preview updates: 

```
https://plugins.jetbrains.com/plugins/snapshot/8579
```

![image](https://user-images.githubusercontent.com/10737066/180499449-7a8b329e-b0ad-4c2d-aee7-86c1537aab9b.png)

![image](https://user-images.githubusercontent.com/10737066/180499528-0e6fe2f4-f796-47d2-b0d6-2d3a2afa2c02.png)

See details: [Custom Release Channels](https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html)

If you find any problems during the experience, please feel free to feedback, thank you!

**Comment by oogleabcd** [comment]
你好，我试过deepl。很好用。deepl的免费api每月限量50w字符，请问有计划实现deepl的每月用量显示吗？你的工作很有价值，我捐了，继续加油。

**Comment by YiiGuxing** [comment]
> 你好，我试过deepl。很好用。deepl的免费api每月限量50w字符，请问有计划实现deepl的每月用量显示吗？你的工作很有价值，我捐了，继续加油。

@oogleabcd 展示使用量这个想法不错，我看了下deepl的API文档，正好有相关的API。这事我先记下了，最近由于工作太忙，一直没能把此版本完善发布，等有空我就添加这个功能。
感谢您的支持！

**Comment by YiiGuxing** [comment]
> 你好，我试过deepl。很好用。deepl的免费api每月限量50w字符，请问有计划实现deepl的每月用量显示吗？你的工作很有价值，我捐了，继续加油。

@oogleabcd Hi! 你提出的使用信息展示需求已经开发完成：

![image](https://user-images.githubusercontent.com/10737066/194719695-1e064b12-d313-48fd-af51-38053f24630f.png)

且已发布到 [`snapshot`](https://plugins.jetbrains.com/plugin/8579-translation/versions/snapshot) 频道中，还麻烦你帮忙测试一下，如遇到BUG，请随意反馈，感谢支持！

**Comment by oogleabcd** [comment]
> 
谢谢，遇到问题我会马上跟你说。

**Comment by oogleabcd** [comment]
> > 你好，我试过deepl。很好用。deepl的免费api每月限量50w字符，请问有计划实现deepl的每月用量显示吗？你的工作很有价值，我捐了，继续加油。
> 
> @oogleabcd Hi! 你提出的使用信息展示需求已经开发完成：
> 
> ![image](https://user-images.githubusercontent.com/10737066/194719695-1e064b12-d313-48fd-af51-38053f24630f.png)
> 
> 且已发布到 [`snapshot`](https://plugins.jetbrains.com/plugin/8579-translation/versions/snapshot) 频道中，还麻烦你帮忙测试一下，如遇到BUG，请随意反馈，感谢支持！

谢谢，遇到问题我会马上跟你反馈。
