### ISSUE TITLE
2020 新版 IDEA 内置文档渲染支持

### ISSUE THREAD

**Issue by cn-src** [YiiGuxing/TranslationPlugin#474]
2020 新版 IDEA 内置了文档渲染。那么已有文档翻译是不是就可以不用弹窗了，就像这个官方的一样在左侧加个按钮，然后用内置的文档渲染方式显示成翻译后的内容。:smile:

<img width="750" alt="Jietu20200406-112958" src="https://user-images.githubusercontent.com/8263180/78520675-fccbd400-77f9-11ea-876e-2dc5a80f50d8.png">

**Comment by YiiGuxing** [comment]
这个倒是可以尝试一下

**Comment by asasas234** [comment]
期待有这个功能

**Comment by happyzero** [comment]
期待这个功能

**Comment by mzzsfy** [comment]
期待

**Comment by jimboomm** [comment]
@YiiGuxing 选择IDEA渲染后的文档的文字，右键后没有翻译菜单，按Ctrl+shift+Y也没有反应。
![image](https://user-images.githubusercontent.com/28443021/101568399-77926200-3a0d-11eb-905d-edb144545985.png)

**Comment by YiiGuxing** [comment]
> @YiiGuxing 选择IDEA渲染后的文档的文字，右键后没有翻译菜单，按Ctrl+shift+Y也没有反应。
> ![image](https://user-images.githubusercontent.com/28443021/101568399-77926200-3a0d-11eb-905d-edb144545985.png)

@jimboomm 这块暂时还不支持

**Comment by YiiGuxing** [comment]
经过调研，发现目前文档渲染的相关API都是私有的，无法调用。而且该模块没有任何扩展点，无法对其进行功能扩展。所以只能看看后期官方会不会开放相关API，或者提供扩展点了。。。 😭

**Comment by YiiGuxing** [comment]
在给IDEA提开放文档渲染API和扩展点的需求的时候，他们给了这么一个文档：
https://jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/documentation.html
从文档上发现，通过 `com.intellij.documentationActionProvider` 扩展点也是可以做一些事情的，但无奈文档渲染相关API没有开放，无法替换渲染视图的内容，也就是只能做一个弹窗翻译了，而且扩展点只能在2020.3版本以上可用。。。

**Comment by YiiGuxing** [comment]
![rendered-doc](https://user-images.githubusercontent.com/10737066/104191785-eb82b880-5458-11eb-9f81-fd6c46ce6d6f.gif)

就问你们6不6？。。。不好意思，嘚瑟了。。。

**Comment by mzzsfy** [comment]
> ![rendered-doc](https://user-images.githubusercontent.com/10737066/104191785-eb82b880-5458-11eb-9f81-fd6c46ce6d6f.gif)
> 
> 就问你们6不6？。。。不好意思，嘚瑟了。。。

期待

**Comment by YiiGuxing** [comment]
哈哈，基础功能搞定了，正要下手开整，没想倒大佬帮做好了（#640），只不过这功能需要用到2020.3版本的API，这样的话2020.3之前的版本就得不到支持了。。。

**Comment by mzzsfy** [comment]
这个功能什么时候能上线呀,等了好久了

> ![rendered-doc](https://user-images.githubusercontent.com/10737066/104191785-eb82b880-5458-11eb-9f81-fd6c46ce6d6f.gif)
> 
> 就问你们6不6？。。。不好意思，嘚瑟了。。。

**Comment by YiiGuxing** [comment]
@mzzsfy 不会太久了。。。。
