### ISSUE TITLE
word book

### ISSUE THREAD

**Issue by BaiMingxu1** [YiiGuxing/TranslationPlugin#476]
Hello, how to use the word book? Can you provide a screenshot? Why is the word Ben always empty in my AndroidStudio? How can I translate the words automatically recorded in my word book

**Comment by YiiGuxing** [comment]
![image](http://yiiguxing.github.io/TranslationPlugin/updates/img/v2_4/word_book.gif)

**Comment by YiiGuxing** [comment]
![word_book](https://user-images.githubusercontent.com/10737066/79038182-ecf12d00-7c09-11ea-9928-3cd4432d0a0e.gif)

**Comment by BaiMingxu1** [comment]
Thank you, ha ha, that's great

**Comment by BaiMingxu1** [comment]
The perfect solution to my problem
