### ISSUE TITLE
快捷键跟 codota 冲突....

### ISSUE THREAD

**Issue by blankhang** [YiiGuxing/TranslationPlugin#479]
## Issue Details
Ctrl + Shift + Y  / Ctrl + Shift + O 均被  codota 给占用了...
### Description

不知道跟我先安装的 codota 有无关系 也没找到修改两者快捷键的地方

按  Ctrl + Shift + Y  会弹出 codota 的 代码搜索输入框
按  Ctrl + Shift + O  会弹出 codota 的 代码搜索结果

### Environment & Stack Trace
- Plugin version:   2.8.1
- IDE version:   IDEA 2020.1
- Operating System and version:  Windows 7

**Comment by YiiGuxing** [comment]
可通过定义快捷键来解决此类问题。

**Comment by blankhang** [comment]
请问 如何定义快捷键?

**Comment by YiiGuxing** [comment]
要么改codota插件的，要么改翻译插件的。

![image](https://user-images.githubusercontent.com/10737066/79212136-be798900-7e79-11ea-95d4-ec5f297c1966.png)
