### ISSUE TITLE
XDG_DATA_HOME 在macOS 上不生效

### ISSUE THREAD

**Issue by kj-creater** [YiiGuxing/TranslationPlugin#4804]
### 需求/建议描述

在macOS上不能获取 `XDG_DATA_HOME`，插件依然使用默认的缓存目录 `${HOME}/.TranslationPlugin`  IDEA: `2023.2.3`

1. 移除所有缓存等目录
2. 下载源代码Debug可以正常使用 `XDG_DATA_HOME` 目录；和预期一致
3. 从插件商店安装使用了默认的 `${HOME}/.TranslationPlugin`；和预期不一致
4. 猜测可能是IDEA版本不同所致；

相关 #788 #873  

### 建议的解决方案

在较新的IDEA上测试并验证`XDG_DATA_HOME`

**Comment by YiiGuxing** [comment]
请问从插件市场安装下来是哪个版本的插件？

**Comment by kj-creater** [comment]
我在插件市场下载的最新版本的，自己编译的也不能使用正确的目录，我觉得 如果找不到或未设置 `XDG_DATA_HOME` 时，回退目录放到别处即可，不用放到家目录，至于这个别处是指哪里，还要研究下这个[XDG规范](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html )

**Comment by YiiGuxing** [comment]
如此说来应该是环境中并没有 `XDG_DATA_HOME` ，那就先保持现状吧。
