### ISSUE TITLE
Adding "Paste" option to Context Menu within the plugin.

### ISSUE THREAD

**Issue by kanansnote** [YiiGuxing/TranslationPlugin#4813]
### Feature/Enhancement Description

By clicking to "Detect language" area, having "Paste" option in Context Menu to put the copied text into that area.

### Proposed Solution

This will prevent of using ```CTRL + V``` key combination for every single time.

**Comment by kanansnote** [comment]
@YiiGuxing Any update, regarding this case?

**Comment by YiiGuxing** [comment]
This is a relatively small feature change, and it won't be released as a standalone version. We need to wait until there are enough other changes to release them together. Please be patient.

**Comment by kanansnote** [comment]
Sorry, but this isn't about patience. It's about accountability. It's been almost a week, and there hasn't been any communication from you regarding whether this will be implemented. 

Therefore, I'm closing this issue as 'not planned', as I shouldn't have to wait indefinitely for something unknown. This seems like the most straightforward action to take. Goodbye.

**Comment by YiiGuxing** [comment]
😅😅😅 I feel you've magnified the issue. This project is solely developed by me, and my energy is limited. I have work and personal matters to attend to, and in the past year, I've had very little free time. Only on weekends might I find the time to address project issues; otherwise, the task list wouldn't have accumulated so many items. I hope you understand, and thank you for your support!

**Comment by kanansnote** [comment]
Well, that's the thing: Making excuses like "it's my project, I don't have a time to work on it, etc." won't work, as it's essential to take responsibility for actions you commit to. Opening an issue is an integral part of contributing to projects and here addressing small details do surely matter; if unable to work on it, it's best to communicate that. And calling me out for "magnifying the issue" is a bias; it's about negotiating work and progress.

So, I am not interested in this project, anymore. Good luck.

**Comment by YiiGuxing** [comment]
😓 Well, I'm speechless.

**Comment by YiiGuxing** [comment]
In addition, I'm sorry for wasting so much of your energy and letting you down.
