### ISSUE TITLE
翻译语言无法固定为英文

### ISSUE THREAD

**Issue by roveyx** [YiiGuxing/TranslationPlugin#482]
使用的是有道翻译。

eg : 要翻译 Ponitcut
默认出来的是马来语的翻译，
截图 : [默认情况](http://qiniu.guoyongxiao.com/c7721710ad8e4e5a8d2ae783efb9a044)

我希望的是默认出来的是英文，试了下设置解决不了，只能手动改为英文
截图 : [手动改为英文](http://qiniu.guoyongxiao.com/236928d6588943af9776638396ed8c86)

我估计是因为这个词是个组合词，在词典中无法找到这个单词，就会出现这种情况，但是这个种情况在编程中很常见，我希望可以将这个语言固定为英文，目前我的英文水平不高，会频繁碰到这个情况，希望可以优化一下，谢谢。

**Comment by YiiGuxing** [comment]
在本地是很难判断要翻译的内容是什么语言的，所以只能交给翻译引擎来判断，这个情况是翻译引擎的判断结果，我无法干扰它的判断，也不能强制设置为某一种语言，因为前面说了，本地没有识别语言的能力，所以只能手动设置。

**Comment by YiiGuxing** [comment]
或者你可以更换其他翻译引擎，有道和百度的可能会少出这种情况。
