### ISSUE TITLE
红图标建议保留

### ISSUE THREAD

**Issue by Zengsh123** [YiiGuxing/TranslationPlugin#483]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
原来右上角两个图标，一个红的，一个蓝的，红的是左右两个大框，这样翻译段落很方便、直观

### Proposed Solution
不知道为什么红的没了，其实红的真的实用

**Comment by YiiGuxing** [comment]
红图标在Toolbar上是有的：
![image](https://user-images.githubusercontent.com/10737066/80440145-b2da9780-893a-11ea-90e3-7dc54decf542.png)
但在NavigationBar上默认情况下被去除掉了，你可以手机把它添加回来：
![image](https://user-images.githubusercontent.com/10737066/80440255-f9c88d00-893a-11ea-8b61-482a7a340363.png)

**Comment by Zengsh123** [comment]
太感谢了
