### ISSUE TITLE
内外环境

### ISSUE THREAD

**Issue by zhang-zhonggui** [YiiGuxing/TranslationPlugin#4841]
### 需求/建议描述

公司在内网环境开发，不能访问外网，我想使用这个插件，有什么办法实现吗？一个不怎么重要的需求，无需太在意

### 建议的解决方案

类似与有道的离线翻译，导入词典之类的

**Comment by YiiGuxing** [comment]
除非你能绕过内网访问外网，否则无法实现，插件并不支持离线翻译
