### ISSUE TITLE
每次重启idea，都需要重新配置有道秘钥

### ISSUE THREAD

**Issue by wzAtbj** [YiiGuxing/TranslationPlugin#4849]
### 📝 问题描述

问题描述：每次重启idea后，使用插件都需要重新输入api。长时间没有使用后，再次使用需要重新输入api

### 🏷 插件版本

3.5.6

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
1、window 版本：10
2、idea 版本：2023.2（UItimate Edition）
3、插件版本：3.5.6
```

### 📋 堆栈跟踪

```plain text
无
```

**Comment by YiiGuxing** [comment]
https://yiiguxing.gitee.io/translation-plugin/#/faq?id=faq-save-key

**Comment by lonelyss** [comment]
解决了吗

**Comment by YiiGuxing** [comment]
> 解决了吗

@lonelyss https://translation-plugin.pages.dev/#/faq?id=faq-save-key
