### ISSUE TITLE
在goland中不能翻译控制台打印出的日志，只能翻译代码中内容，希望有这个功能哇！（IDE2019.3版以上可用）

### ISSUE THREAD

**Issue by serendippers** [YiiGuxing/TranslationPlugin#488]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
控制台只能使用快捷键翻译，你试试

**Comment by serendippers** [comment]
我就是快捷键，idea可以，但是goland不可以（controal+command+u）

**Comment by YiiGuxing** [comment]
可能是快捷键冲突了，换一个试试呢？

**Comment by serendippers** [comment]
emmmm  goland代码里可以用（controal+command+u）快捷键翻译，但是控制台打印的日志就不行了！

**Comment by YiiGuxing** [comment]
可能是快捷键被占用了，你可以设置一个新的无冲突快捷键试一试

**Comment by YiiGuxing** [comment]
刚下了个goland试了一下，发现Windows的也不能使用，也不是快捷键冲突的问题。只不过最近比较忙，迟些日子再来看看是怎么回事。

**Comment by serendippers** [comment]
多谢大佬
