### ISSUE TITLE
关于OPENAI接口重复加载预设

### ISSUE THREAD

**Issue by zhnkc9** [YiiGuxing/TranslationPlugin#4913]
### 📝 Issue Description

# 关于OPENAI接口重复加载预设

我的执行条件是openai的3.5模型

是用`go-chatgpt-api`项目端模拟出来的接口

由于我是自建代理站点, 基于3.5.6版本 ,我直接反编译了`Openai.java`修改其中的接口地址

看了一下字节码,只有 `/v1/chat/completions` 这一个请求

![img](https://github.com/YiiGuxing/TranslationPlugin/assets/42533530/28631b22-809e-461e-a551-bbd144822019)

从ide到代理站点,整个流程是跑通的

但是他会重复加载预设,加载一次 chat+1

翻译的间隔不超过2秒,有的时候会用一个会话,不过几秒后还是会新建

![img_1](https://github.com/YiiGuxing/TranslationPlugin/assets/42533530/7ba7c6b8-5e03-419b-908d-c5e74f59e7d2)

![img_3](https://github.com/YiiGuxing/TranslationPlugin/assets/42533530/f220e50b-8287-4c2e-aef8-12aab184a267)

最后 感谢作者的开源项目 !  

### 🏷 Plugin Version

3.5.6

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
pycharm 2023.3.2
PY-233.11799.259, built on December 4, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**Comment by YiiGuxing** [comment]
调用 OpenAI API 是不会在 ChatGTP 的会话列表中生成会话的，你是不是把 API 代理到 ChatGTP 网站上的接口上了？如果是，那就需要你自己解决了，可以尝试在请求参数中添加 `history_and_training_disabled: true` 参数。
