### ISSUE TITLE
2.9.0怎么翻译渲染文档

### ISSUE THREAD

**Issue by asasas234** [YiiGuxing/TranslationPlugin#493]
我更新到了最新版，但是没找到怎么翻译渲染后文档的方法

**Comment by YiiGuxing** [comment]
查看快速文档即可，比如Windows的Ctrl+Q。

**Comment by asasas234** [comment]
我试了不好使，在非渲染文档模式下，是可以的，渲染模式下不行

**Comment by YiiGuxing** [comment]
渲染模式？什么是渲染模式？

**Comment by asasas234** [comment]
![image](https://user-images.githubusercontent.com/4795442/82140061-82ae5680-985f-11ea-83b0-e500fa07f521.png)
就是点击这里以后变成下面的样子，就没办法用查看快速文档翻译了
![image](https://user-images.githubusercontent.com/4795442/82140068-a1ace880-985f-11ea-910c-f3d7432217fa.png)

**Comment by YiiGuxing** [comment]
你可以使用光标放在这个文档的目标元素上，如：类名、方法名等，再使用快捷键查看快速文档。
http://yiiguxing.github.io/TranslationPlugin/updates.html?v=2.9

**Comment by ekesaiting** [comment]
选择有道翻译后，Windows的Ctrl+Q可以翻译，但是右键点击不行，还是显示原文

**Comment by YiiGuxing** [comment]
渲染模式的文档目前还不支持在上面翻译，你看它上面想选择文本都是不能的。

**Comment by asasas234** [comment]
明白了
