### ISSUE TITLE
希望文檔提示能同時顯示原文

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#495]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

![image](https://user-images.githubusercontent.com/167966/82171223-4596a280-98f9-11ea-9e91-2585ce59fe09.png)

希望能同時顯示原文

**Comment by YiiGuxing** [comment]
这个功能我也是非常想要的，但在目前是无法实现的，这需要IDEA的支持。我现在正在和JetBrains合作开发此插件，我会向JetBrains的工作人员求助，看看以后是否有可能实现此功能。

**Comment by YiiGuxing** [comment]
将在3.0版本得到实现（仅2019.3以上的IDE版本可用）。
见： #508
