### ISSUE TITLE
安装此插件会导致markdown预览空白, 即使是禁用此插件后,仍然预览空白, 只有恢复ide的默认设置,才能重新预览成功

### ISSUE THREAD

**Issue by achieve-dream1221** [YiiGuxing/TranslationPlugin#4957]
### 📝 问题描述

起初是以为jetbrains ide的问题, 但是网上搜到各种此类解决问题的办法(关闭gpu, 修改运行时), 依旧无效, 于是尝试了恢复默认后, markdown可以正常预览了, 接着安装了这个翻译插件, 然后有不能预览, 于是发现了这个bug
# 安装翻译插件的效果
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/57209087/e088b6a4-8574-4cc4-ac74-ef891cc7b6a2)
# 禁用翻译插件的效果
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/57209087/b619c82f-1b21-407c-9e55-24e2b0f8dabc)
# 从未安装过翻译插件的效果
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/57209087/5c90aac9-c621-4856-a460-09e9cbe7e183)

### 🏷 插件版本

3.5.6

### 🔁 翻译引擎

全部

### 💻 IDE及运行环境

```plain text
PyCharm 2023.3.1 (Professional Edition)
Build #PY-233.11799.298, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.experimental.ui.inter.font=true
  python.debug.asyncio.repl=true
Non-Bundled Plugins:
  MatlabSupport (0.8.5)
  com.intellij.zh (233.199)
  com.github.copilot (1.4.4.3955)
  com.intellij.mermaid (0.0.18+IJ.232)
  cn.yiiguxing.plugin.translate (3.5.6)
```

**Comment by achieve-dream1221** [comment]
处理器: AMD 7840HS
换了一台intel的处理器, 不会出现这个问题

**Comment by YiiGuxing** [comment]
这应该和释放插件是没有任何关系的，我的插件理论上和 markdown  插件八杆子打不着的。你看看无法预览的时候 IDE 有没有报错？

**Comment by achieve-dream1221** [comment]
> 这应该和我的插件是没有任何关系的，我的插件理论上和 markdown 插件八杆子打不着的。你看看无法预览的时候 IDE 有没有报错？

感谢回复, 我找到问题所在了, 我开启了ide的http代理设置, 导致markdown预览被代理了, 无法正常渲染, 并非插件的问题, 非常抱歉
