### ISSUE TITLE
打开快速文档翻译会导致本身的文档翻译功能失效

### ISSUE THREAD

**Issue by Vixb1122** [YiiGuxing/TranslationPlugin#497]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 2.9
- IDE version: STUDIO 4.0 RC1 
- Operating System and version: Windows 10

如果打开了快速文档翻译，那么右击文档注释，点击翻译文档，无法正确触发翻译。关闭后，文档翻译正常。

**Comment by YiiGuxing** [comment]
哈哈哈。。。好像是被反向翻译回去了。。。
