### ISSUE TITLE
文档翻译的Resource希望能够不进行翻译

### ISSUE THREAD

**Issue by vescape920** [YiiGuxing/TranslationPlugin#498]
> 资源：/用户/ kescape /库/ Application Support / JetBrains公司/工具箱/应用/ PhpStorm / CH-0 / 201.7223.96 / PhpStorm.app /内容/插件/ PHP / lib中/ php.jar！/stubs/standard/standard_2.php

如上所示，资源对应的是源代码路径，希望不要进行翻译。

**Comment by YiiGuxing** [comment]
仅支持谷歌翻译
