### ISSUE TITLE
Possibility to turn off automatic translation

### ISSUE THREAD

**Issue by Avatarek78** [YiiGuxing/TranslationPlugin#499]
Hi, 
after last udpate to version 2.9.0. I'm discovere that, all javadoc is automatically translated into my (Czech) language. This is absolutelly unwanted feature which cannot be turned off! Wanted behaviour is that only translate when I mark the text and press keyboard shortcut. Please add possibility to turn this feature off. Many thanks. 
![image](https://user-images.githubusercontent.com/18666680/82183313-090d7b80-98e6-11ea-8205-d4d088fda632.png)

**Comment by YiiGuxing** [comment]
Hi,
This feature can be turned off, you can turn it off in the plugin settings page: settings -> translation -> Options -> Translate documentation.

**Comment by Avatarek78** [comment]
> Hi,
> This feature can be turned off, you can turn it off in the plugin settings page: Settings -> Translation -> Options -> Translate documentation.

Thanks for advice, but how can I get there? This is the first what I try but with no luck. I'm able to find only options Disable or Uninstall plugin but not settings what you mention. Please, can you post me some screenshot to reveal where is this settings is?

**Comment by Avatarek78** [comment]
Yes I found it! This is under Other Settings menu. I was never be there :-)  
![image](https://user-images.githubusercontent.com/18666680/82184603-34916580-98e8-11ea-8d36-aebaf14b444f.png) Thanks and I wish you great success in your further development because your plugin is very helppfull :-)

**Comment by YiiGuxing** [comment]
Sorry, I missed a step.
