### ISSUE TITLE
webstorm2016.2  不能使用 ，

### ISSUE THREAD

**Issue by shishifanbuxie** [YiiGuxing/TranslationPlugin#5]
插件列表中 图标是灰色的 
![image](https://cloud.githubusercontent.com/assets/8510150/17314914/4f72dde4-589a-11e6-8997-4cdfd3ce30a9.png)

**Comment by YiiGuxing** [comment]
@shishifanbuxie 现在WS,PS,PC等产品都可以使用了，请用1.2版，v1.2的已经更新，以前的还是不行的。

**Comment by shishifanbuxie** [comment]
我装的是 1.2的 TranslationPlugin-v1.2-SNAPSHOT.jar
![image](https://cloud.githubusercontent.com/assets/8510150/17392193/4b0cff9a-5a4e-11e6-9534-284489d88c44.png)

**Comment by YiiGuxing** [comment]
@shishifanbuxie 呃。。。。请重新下载安装。
