### ISSUE TITLE
关于代码中文注释翻译成英文问题

### ISSUE THREAD

**Issue by ryanwlb** [YiiGuxing/TranslationPlugin#501]
感谢作者开发这个插件很好用，想反馈个问题，翻译文档这个功能很好，但是有一些代码我写的中文注释给我翻译成了英文。。。希望能自动检测源语言，如果是中文就不要翻译了

**Comment by YiiGuxing** [comment]
本地是很难判断要翻译的内容是什么语言的，而且这个现象也只有有道翻译才会出现，因为有道会自动反转语言，解决办法是，将主要主要语言设置为中文，而不是默认的自动，但这样的话在进行平时的时候就无法享受到有道自动反转语言的便捷了。
