### ISSUE TITLE
文档实时翻译功能无法翻译除标准库之外的注释

### ISSUE THREAD

**Issue by CodingOX** [YiiGuxing/TranslationPlugin#503]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description
Java 的源码或者 Kotlin的源码这些翻译是没有问题的,比如下图：
![image](https://user-images.githubusercontent.com/9800933/82289633-cd52de80-99d7-11ea-88d9-9310884499a3.png)

但是对于`Maven`引用的外部文档，无法进行实时翻译，下面是截图：
![image](https://user-images.githubusercontent.com/9800933/82289582-b14f3d00-99d7-11ea-904a-e6c4ec64adf8.png)
![image](https://user-images.githubusercontent.com/9800933/82289596-b90ee180-99d7-11ea-9704-b019f4f66d60.png)

### Environment & Stack Trace
- Plugin version:2.9.1
- IDE version: IDEA 2020.1
- Operating System and version: Mac

**Comment by YiiGuxing** [comment]
我这边是可以的啊。我猜你那边的文档提供方式应该是在线文档，可以尝试更换为源码文档方式：
![image](https://user-images.githubusercontent.com/10737066/82297406-30973d80-99e5-11ea-9ff5-919b2db3d95b.png)

打开类文件，点击右上角的下载源代码即可快速切换到源码文档方式。
![image](https://user-images.githubusercontent.com/10737066/82297504-545a8380-99e5-11ea-8901-ad6b4279ad6b.png)

**Comment by YiiGuxing** [comment]
由于IDE的限制，文档实时翻译功能在一些地方可能无法使用，这一情况在将来的2020.2版本之后可能会得到改善，到时再根据实际情况做出相应的处理，尽量能让此功能能在更多更全面的场景下使用。
