### ISSUE TITLE
怎么切换翻译引擎

### ISSUE THREAD

**Issue by hicker-kin** [YiiGuxing/TranslationPlugin#5039]
### 需求/建议描述

我不想用默认的翻译引擎，怎么切换？  另外，我的3.5.6的插件怎么看不好到openai的引擎？

### 建议的解决方案

增加翻译引擎切换，补全手册

### 附加信息

无

**Comment by YiiGuxing** [comment]
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/41cb4060-8c73-4f7e-8b2a-6e0d2538ee02)

https://yiiguxing.github.io/TranslationPlugin/#/docs?id=usage-switch-translation-engine

**Comment by hicker-kin** [comment]
太棒了，OK。没看到配置在右下角，已经好了，感谢！
