### ISSUE TITLE
更新插件重启loading卡死无响应

### ISSUE THREAD

**Issue by xiaohundun** [YiiGuxing/TranslationPlugin#504]
IDEA 版本：2020.1.1
Plugin 版本：2.9.1
OS ：Mac os
在选择项目界面禁用插件启动没有问题
启动之后在设置里重新启用Plugin并重启问题不重现

**Comment by YiiGuxing** [comment]
请提供日志文件。

找到日志文件的方法：Help -> Show log in explorer -> idea.log 。
![image](https://user-images.githubusercontent.com/10737066/82291697-0f7e1f00-99dc-11ea-864d-e199812e6717.png)

请尽量提供最小的日志文件（在重现问题之前先删除该文件）。

**Comment by xiaohundun** [comment]
> 请提供日志文件。
> 
> 找到日志文件的方法：Help -> Show log in explorer -> idea.log 。
> ![image](https://user-images.githubusercontent.com/10737066/82291697-0f7e1f00-99dc-11ea-864d-e199812e6717.png)
> 
> 请尽量提供最小的日志文件（在重现问题之前先删除该文件）。


[log.txt](https://github.com/YiiGuxing/TranslationPlugin/files/4648614/log.txt)

[threadDump-20200519-140135.txt](https://github.com/YiiGuxing/TranslationPlugin/files/4648615/threadDump-20200519-140135.txt)

**Comment by YiiGuxing** [comment]
这个问题是必出的吗？如果是更新其他插件呢，也会出现吗？

**Comment by YiiGuxing** [comment]
请提供一下IDE版本信息：

![image](https://user-images.githubusercontent.com/10737066/82294393-a5b44400-99e0-11ea-96d6-be98347075d4.png)

**Comment by xiaohundun** [comment]
> 这个问题是必出的吗？如果是更新其他插件呢，也会出现吗？

像我之前说的，更新了这个插件之后出了这个问题，之前没有碰到过，在选择项目界面先把这个插件禁用启动没有问题，启动之后再把插件enable重启问题也无法重现

**Comment by xiaohundun** [comment]
> 请提供一下IDE版本信息：
> 
> ![image](https://user-images.githubusercontent.com/10737066/82294393-a5b44400-99e0-11ea-96d6-be98347075d4.png)

IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 12
Registry: compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, Lombook Plugin, SequenceDiagram, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, MavenRunHelper, izhangzhihao.rainbow.brackets, cn.yiiguxing.plugin.translate

**Comment by xiaohundun** [comment]
> 这个问题是必出的吗？如果是更新其他插件呢，也会出现吗？

我试下其他jb家的软件安装这个插件试试

**Comment by YiiGuxing** [comment]
你可以试试其他的插件会不会也出现这个问题。
手动安装以下插件，然后在IDEA内通过更新安装最新版本，看看会不会也出现这个问题：
[BashSupport-1.7.17.201.zip](https://github.com/YiiGuxing/TranslationPlugin/files/4648797/BashSupport-1.7.17.201.zip)

**Comment by xiaohundun** [comment]
问题无法重现，关闭。
