### ISSUE TITLE
当电脑使用了代理无法使用微软翻译建议添加请求头过滤

### ISSUE THREAD

**Issue by brook-w** [YiiGuxing/TranslationPlugin#5045]
### 📝 问题描述

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/42824702/31592d28-3e2f-403f-9bb9-6a58b7a53307)
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/42824702/0a694f52-8ce3-45ad-9e27-502eef9fdd00)

### 🏷 插件版本

不关注版本

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
不关注IDE 这是一个通用 bug
```

**Comment by YiiGuxing** [comment]
这应该是代理的问题，您可以在代理软件中将微软翻译的地址过虑掉：`api.cognitive.microsofttranslator.com` `edge.microsoft.com`
