### ISSUE TITLE
建议取消2.9.0增加的对 Quick Documentation 翻译的支持

### ISSUE THREAD

**Issue by luobodd** [YiiGuxing/TranslationPlugin#506]
个人日常习惯，对于IDEA 中Quick Documentation的内容比较迅速得知方法(java方法命名见名知其意)，翻译过后反而更影响了我的开发效率，故，回退至2.8.0版本

**Comment by YiiGuxing** [comment]
在插件设置页面有选项关闭的啊。我在What's New面板里写得有的啊，有哪些新功能，如何使用，写得都挺清楚的啊，你们都不看的么？那我岂不是白写了那么多了么。。。。。。我写得可累了 ^_^

**Comment by ddlzr** [comment]
如果这个地方也写Quick Documentation，大家可能就知道应该取消勾选哪个了
![image](https://user-images.githubusercontent.com/22073788/82463148-0af65b00-9aef-11ea-803e-42b3a56da00a.png)

**Comment by YiiGuxing** [comment]
emmm...... 叫“文档实时翻译”会不会更好一点？

**Comment by AngryFeng** [comment]
Quick Documentation的翻译有点尬，纯人机逐词翻译

**Comment by YiiGuxing** [comment]
@YiiGuxing 没办法，目前好像也就这个程度了，也不知道用DeepL会不会好一点。
