### ISSUE TITLE
文档中图片无法正常显示

### ISSUE THREAD

**Issue by miaomiaozizi** [YiiGuxing/TranslationPlugin#507]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
启用文档翻译功能后，对于Java文档注释中含有图片的，无法正常解析出图片
### Description
![image](https://user-images.githubusercontent.com/26435318/82529257-2902a080-9b6d-11ea-9b74-6d91616f0904.png)
开启文档翻译后的显示效果
![image](https://user-images.githubusercontent.com/26435318/82529295-446dab80-9b6d-11ea-8f97-473d3ef28c65.png)
原始文档显示效果

### Environment & Stack Trace
- Plugin version: 2.9.1
- IDE version: IDEA 2020.1.1
- Operating System and version:  Windows 10

**Comment by YiiGuxing** [comment]
文档上的图片是可以被加载的，只是会非常慢，甚至加载失败，但这并不是插件的问题。Java Swing组件本身对HTML渲染并不是很好。。。
