### ISSUE TITLE
有没有办法设置 不翻译代码部分?

### ISSUE THREAD

**Issue by jwwsjlm** [YiiGuxing/TranslationPlugin#5085]
### 需求/建议描述

![QQ截图20240114061308](https://github.com/YiiGuxing/TranslationPlugin/assets/48446617/5cb47fb0-47b3-47b1-9882-709d5b63327e)
![QQ截图20240114061327](https://github.com/YiiGuxing/TranslationPlugin/assets/48446617/7c4dd66b-a083-4a80-a310-cea450fdd9da)
如图所示 他直接把if什么的直接翻译成如果了.能不能调用jb的 高亮之类的?内置的命令这些不翻译?

### 建议的解决方案

如图所示

**Comment by jwwsjlm** [comment]
https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5@v5.5.1#NewBotAPI
不知道是不是golang的这个文档不太标准 我使用谷歌浏览器的一键翻译 他也会乱翻 但是好像github之类的 他好像就不会

**Comment by YiiGuxing** [comment]
一般文档中的代码块都有一个标准的语法或者结构的，所以应该是此文档中使用了非标准的代码块导致的。你可以对比语言的标准库里的文档来验证一下。

**Comment by jwwsjlm** [comment]
> 一般文档中的代码块都有一个标准的语法或者结构的，所以应该是此文档中使用了非标准的代码块导致的。你可以对比语言的标准库里的文档来验证一下。

好像就是golang的不太标准 不过安装golang的尿性估计也不会改...

**Comment by YiiGuxing** [comment]
这是一个 Go 文档注释的官方指南上的一个代码块例子 [Go Doc Comments (Code blocks)](https://golang.google.cn/doc/comment#code)：

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/cf549824-1f9f-44ea-8e64-ef2b8810f19f)

可见代码块内的代码并没有被翻译，插件只会认这种标准的，非标准的我也没有办法，我无不可能一一去识别的。
