### ISSUE TITLE
2.9.1文档翻译功能不起作用，还有as提示过久的版本

### ISSUE THREAD

**Issue by Ayvytr** [YiiGuxing/TranslationPlugin#509]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
可以使用的啊：
![image](https://user-images.githubusercontent.com/10737066/83009158-ddf2fc80-a048-11ea-97b7-50fab8cf32f9.png)

提示过旧的版本那是因为目前AS基于IDEA的版本过低，在将来的版本将不再被支持，我觉得AS4.0以后可能就好了。

**Comment by Ayvytr** [comment]
我这用的是3.6.3，现在不管勾不勾翻译文档，都不翻译，都是英文

**Comment by YiiGuxing** [comment]
我用的也是3.6.3啊。有没有报错什么的？

**Comment by Ayvytr** [comment]
今天更新4.0还是没翻译，中间插件还提示更新了，更新之后还这样，不知道啥原因造成的

**Comment by YiiGuxing** [comment]
这样吧，你提供一下AS的日志：
![image](https://user-images.githubusercontent.com/10737066/83217357-253ed180-a19e-11ea-91b7-7ed4d78fb18e.png)
这个目录下有个idea.log文件，你把这个文件上传过来。
请提供最小的日志文件：关闭AS，然后删除这个文件，再启动AS，尝试几次文档翻译，关闭AS，最后上传这个文件。

**Comment by Ayvytr** [comment]
[idea.log](https://github.com/YiiGuxing/TranslationPlugin/files/4704833/idea.log)

**Comment by W-quan** [comment]
更新Android studio 4.0 后提示插件不兼容

```
11:36 PM	Plugin Error: Plugin "Translation" is incompatible (target build range is 171 to 192.*).
```

**Comment by YiiGuxing** [comment]
@W-quan 升级一下插件就可以了。

**Comment by YiiGuxing** [comment]
@Ayvytr 从日志上看并无什么问题，但是我这边确实是可以翻译的。你能否提供一下你翻译失败的截图？

**Comment by Ayvytr** [comment]
右键翻译文档可以，ctrl+q我记得2.9.0可以直接翻译，更新了就不行了，是取消了？

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by YiiGuxing** [comment]
请确认一下2.9.0是否真的可以翻译。

**Comment by YiiGuxing** [comment]
另外，请提供相关截图，谢谢！

**Comment by Dboy233** [comment]
![image](https://user-images.githubusercontent.com/37604230/83342665-9d370400-a324-11ea-88f5-1041863ec423.png)

**Comment by YiiGuxing** [comment]
@Dboy233 请升级插件

**Comment by Ayvytr** [comment]
上班的电脑上也不行了。不管勾选不勾选翻译文档都不起作用。另外发现个新问题，右键翻译文档，太长的话报错，比如View，翻译报：Failed to translate documentation: 翻译失败: Request Entity Too Large

**Comment by YiiGuxing** [comment]
@Ayvytr 请提供截图

**Comment by YiiGuxing** [comment]
关于太长报错，这个是翻译API的限制，这个目前不做处理。

**Comment by Ayvytr** [comment]
上次上传的可能没成功，截图其实看不出啥问题。这次的现象和视频里的差不多
[r.zip](https://github.com/YiiGuxing/TranslationPlugin/files/4709273/r.zip)

**Comment by YiiGuxing** [comment]
是不是安装了什么其他插件？文档翻译是通过拦截文档生成过程实现的，如果有其他插件也拦截这个过程的话可能就会导致文档翻译拦截失败的。

**Comment by Ayvytr** [comment]
![plugins](https://user-images.githubusercontent.com/14284198/83374713-03905500-a3ff-11ea-9004-05aae7bd6499.JPG)
安装的插件就是看到的这些，翻译是最后一个

**Comment by YiiGuxing** [comment]
使用有道翻译也是不行的吗？

**Comment by Ayvytr** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        也不行
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ayvytr
                            
                    
                        
                            
                                    ayvytr@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年6月1日 11:58，Yii.Guxing<notifications@github.com> 写道： 




使用有道翻译也是不行的吗？



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YiiGuxing** [comment]
@Ayvytr 麻烦安装下面这个包，多尝试几次文档翻译，然后提供一下日志，日志还是用上面提到过的方式。

[TranslationPlugin-2.9.1-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/4709690/TranslationPlugin-2.9.1-SNAPSHOT.zip)

**Comment by Ayvytr** [comment]
我这成小白鼠了，好忧桑

**Comment by YiiGuxing** [comment]
> 我这成小白鼠了，好忧桑

。。。最后一次了，只是确认一下是不是拦截翻译过程失败了。主要是我这里根本无法重现问题呀！这不是想要解决问题嘛。。。。感谢！

**Comment by Ayvytr** [comment]
[r1.zip](https://github.com/YiiGuxing/TranslationPlugin/files/4709741/r1.zip)

**Comment by YiiGuxing** [comment]
@Ayvytr 大哥，我错了！可能还需要一两次，通过日志发现拦截翻译过程并没有失败，这说明它还有得救呀！只是不知道什么原因翻译失败，我猜测是超时了。这回我增加了更详细的日志打印，大哥再帮帮忙呗。。。不用录屏，只使用几次Ctrl+Q就行，不用使用翻译其他翻译来对比（日志会被干扰），感谢~

**Comment by YiiGuxing** [comment]
[TranslationPlugin-2.9.1-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/4709902/TranslationPlugin-2.9.1-SNAPSHOT.zip)

**Comment by Ayvytr** [comment]
[idea.log](https://github.com/YiiGuxing/TranslationPlugin/files/4709938/idea.log)

**Comment by YiiGuxing** [comment]
@Ayvytr 请问这一次你使用了几次Ctrl+Q，你是不是使用了一次右键菜单上的文档翻译？

**Comment by Ayvytr** [comment]
对，第1次右键，几次ctrl+q

**Comment by YiiGuxing** [comment]
唉！经过认真地分析你提供的日志文件，非常遗憾地告诉你，插件拦截文档生成的过程确实是失败的，所以这就没有办法了。因为这个功能的基石就是这个拦截，无法拦截就无法使用。目前也只能使用这种方式，但这种方式的问题就是它受IDE环境的影响，比如如果IDE内也有其他插件拦截这个过程，那么翻译插件的拦截就可能被打破，从而导致失效。

**Comment by YiiGuxing** [comment]
在将来的IDE版本（至少2020.2）中，我们会改进文档翻译的实现方式，到时候可能就不会出现这个问题了。可是要等到AS升级IDE版本到2020.2那可能就要比较长时间了，AS的IDE版本总是落后好几个版本，4.0才是2019.3.。。。

**Comment by Ayvytr** [comment]
你本机要是可以的话说不定还有救

**Comment by YiiGuxing** [comment]
我这边安装的AS也是最新的4.0，但文档翻译却是能正常使用。这说明此功能在你那边应该是被AS的应用环境影响到了，如果你真的很需要这个功能的话，可以尝试重新安装AS，并重置AS的配置（删除配置目录）。如果还是不行，那我可能就已经疯掉了。。。。只能等到它的必修版实现了。。。。

**Comment by Ayvytr** [comment]
不急。ctrl+q不起作用还有右键。
我开了5个窗口，有两个可以，这两个都是kotlin的，3个没开kotlin，不知道这个有没有影响

**Comment by Ayvytr** [comment]
或者说是不支持Android源代码中的注释。这个作用域不太确定，又试了一下感觉不是这么单纯

**Comment by YiiGuxing** [comment]
好的，那就将这个问题关闭了

**Comment by YiiGuxing** [comment]
也有同学反馈原代码文档不能翻译的，但我这边都是正常的，说明这种实现方式还是不好，只能等待其改进版的实现了。
