### ISSUE TITLE
翻译窗口乱码！

### ISSUE THREAD

**Issue by csh159** [YiiGuxing/TranslationPlugin#5092]
### 📝 Issue Description

![微信图片_20240115173532](https://github.com/YiiGuxing/TranslationPlugin/assets/4157414/88aa7316-f846-47ea-b0f8-db5e94bc0d23)
![微信图片_20240115173613](https://github.com/YiiGuxing/TranslationPlugin/assets/4157414/d37b3059-a177-433d-86ad-67fad18feaac)
![微信图片_20240115173608](https://github.com/YiiGuxing/TranslationPlugin/assets/4157414/07f4a7eb-acc4-426b-b175-73a1c111a58b)

### 🏷 Plugin Version

3.5.6

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
1
```

### 📋 Stacktrace

```plain text
1
```

**Comment by YiiGuxing** [comment]
修改字体就可以了

**Comment by csh159** [comment]
> 修改字体就可以了

修改什么字体才行？修改了微软雅黑还是不行哦！

**Comment by csh159** [comment]
> 修改字体就可以了

好了，以为是设置开工具的字体，是要设置插件的字体 ！
