### ISSUE TITLE
这个为什么在创建类或者文件的时候不能用?

### ISSUE THREAD

**Issue by T-Merak** [YiiGuxing/TranslationPlugin#51]
比方说在创建类文件重命名的时候,调用快捷键没有反应还有其他资源文件的时候也是一样,大神能加入这个功能吗?

**Comment by YiiGuxing** [comment]
@T-Merak 可以用的，但必须选择文字后才能使用，默认快捷键是<kbd>alt+t</kbd>，如果快捷键无效的话可能是快捷键和对话框上的快捷键冲突了，修改快捷键就可以了，Action是**Translate Text Component**

**Comment by T-Merak** [comment]
我就是想用 alt+r 啊,这个不能实现吗?因为创建类的时候用到 翻译替换 比较多啊 @YiiGuxing 大神要是可以的化加上去吧,真的很希望有这个功能

**Comment by YiiGuxing** [comment]
@T-Merak 这里 alt+r 是不能用的，以后我再看看能不能加吧

**Comment by T-Merak** [comment]
哦哦,辛苦大神了...
