### ISSUE TITLE
文档翻译与直接翻译存在异义

### ISSUE THREAD

**Issue by qtcdxxyuc** [YiiGuxing/TranslationPlugin#511]
谷歌翻译模式下，相同的原句子，在注释中的翻译与直接在谷歌翻译中获得的结果存在差别。
对于第一行语句而言，内置的手动翻译与谷歌翻译的结果一致，而注释翻译是不同的。

`A Context carries a deadline, a cancellation signal, and other values across API boundaries.`

<img width="566" alt="截屏2020-05-28 下午3 14 51" src="https://user-images.githubusercontent.com/18543889/83110782-2f0cfa00-a0f6-11ea-9d71-e6635d0803b1.png">

---

<img width="386" alt="截屏2020-05-28 下午3 15 01" src="https://user-images.githubusercontent.com/18543889/83110809-38966200-a0f6-11ea-886c-5a3f50f2decd.png">

**Comment by YiiGuxing** [comment]
由于文档翻译中翻译的内容是HTML内容，有HTML标签的干扰，有差异在所难免。

**Comment by o2e** [comment]
> 由于文档翻译中翻译的内容是HTML内容，有HTML标签的干扰，有差异在所难免。

@YiiGuxing 能不能优化一下这个问题？比如说过滤掉html标签再翻译？ 现在的翻译结果都读不懂 还不如直接手动来 这个问题使得这个功能变得没有用了😭

**Comment by YiiGuxing** [comment]
@o2e 有道和百度的就是过虑了HTML标签后的效果，已经没有页面跳转的功能了，反正有得有失。。。
