### ISSUE TITLE
文档翻译不起作用

### ISSUE THREAD

**Issue by DuckDuck88** [YiiGuxing/TranslationPlugin#513]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by DuckDuck88** [comment]
- 插件版本 v2.91-192
- ide版本  2019.1
- 操作系统  win10

**Comment by YiiGuxing** [comment]
#509
