### ISSUE TITLE
AS4.0插件不能用

### ISSUE THREAD

**Issue by Dboy233** [YiiGuxing/TranslationPlugin#515]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
 AS4.0上插件不能用
### Description
![image](https://user-images.githubusercontent.com/37604230/83342622-1da93500-a324-11ea-89a2-948ca23dc89c.png)

### Environment & Stack Trace
- Plugin version: 2.9.1
- IDE version: Android Studio 4.0
- Operating System and version: Windows 10

**Comment by Dboy233** [comment]
我看到了相同的问题

**Comment by BiJim** [comment]
the same to me

**Comment by YiiGuxing** [comment]
升级插件即可
