### ISSUE TITLE
Selected words are not translated

### ISSUE THREAD

**Issue by Ivanov-Anton** [YiiGuxing/TranslationPlugin#516]
## Issue Details
Do not translate all selected words
### Description
In Translate(Inclusive or Exclusive)I select two word for example and got popup with translate only last word, please resolve thos issue

Note that in previous vension plagin 'Translation' from RubyMine IDE the translation worked well

**Comment by YiiGuxing** [comment]
In the Include or Exclude mode, words are automatically selected based on cursor position, and selected words are ignored. If you want the selected word not to be ignored, please use the Translate action.
