### ISSUE TITLE
关于单词本

### ISSUE THREAD

**Issue by mysmlz** [YiiGuxing/TranslationPlugin#5164]
### 需求/建议描述

讲真,这东西存在感有点低,我甚至一度以为这是idea的功能,直到我百度了才知道是插件的功能,而且每次新开项目(idea中"新建项目")都会在侧边栏显示,有些"烦"(我只是喜欢简洁的侧栏)

### 建议的解决方案

要不就别每次新建项目都在侧栏出来了

**Comment by YiiGuxing** [comment]
右击图标，可以隐藏的啊
