### ISSUE TITLE
希望文档翻译功能可以添加指定翻译语言功能 

### ISSUE THREAD

**Issue by kwer8080** [YiiGuxing/TranslationPlugin#518]
希望文档翻译功能可以添加指定语言功能 现在翻译文档会将中文文档翻译成英文 这个给我带来了些许困扰

**Comment by YiiGuxing** [comment]
抱歉，这个无法做到，因为文档生成的过程是系统行为，这过程是同步的，不是异步回调的，是不能暂停的，是不可能停下来让我们选择指定语言的，解决办法是不使用有道翻译。。。

**Comment by kwer8080** [comment]
好的 感谢
