### ISSUE TITLE
是否考虑支持Azure gpt ( support Azure gpt)?

### ISSUE THREAD

**Issue by dengbojing** [YiiGuxing/TranslationPlugin#5190]
### 需求/建议描述

希望能支持Azure的gpt配置
Hope to support Azure's GPT configuration.

### 建议的解决方案

目前只有Openai 的key,  希望能加个配置填写Azure gpt的URL, 像[OpenAI Translator](https://github.com/openai-translator/openai-translator)那样设置

just like  [OpenAI Translator](https://github.com/openai-translator/openai-translator) configuration

**Comment by YiiGuxing** [comment]
已在开发中

**Comment by YiiGuxing** [comment]
Duplicate of #3801

**Comment by YiiGuxing** [comment]
此功能已基本开发完成，欢迎大家抢先体验：
 - IDE 2021.3 及以上版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336924/TranslationPlugin-3.6.0-SNAPSHOT.240220.zip)
 - IDE 2020.3 至 2021.2 版本：[TranslationPlugin-3.6.0-SNAPSHOT.240220+203u212.zip](https://github.com/YiiGuxing/TranslationPlugin/files/14336976/TranslationPlugin-3.6.0-SNAPSHOT.240220%2B203u212.zip)

由于没有 Azure 账号，因此此功能没有经过任何测试，希望有 Azure 账号的同学帮忙测试测试，如遇Bug还也请反馈一下，感谢！
