### ISSUE TITLE
有没有想法支持Xcode ？

### ISSUE THREAD

**Issue by Chaiyahang** [YiiGuxing/TranslationPlugin#5197]
### 需求/建议描述

希望支持Xcode，这个在AS上相当好用，解决了很多API注释的翻译难问题

### 建议的解决方案

希望可以把这个非常Nice的插件移植到xcode 中

### 附加信息

Thanks

**Comment by YiiGuxing** [comment]
已经没有剩余的精力与时间了，VS Code 的移植都没有，更别说 X Code 了。
