### ISSUE TITLE
我的主要语言设置的是中文，翻译文档功能无法起作用，但是会把我的中文文档翻译成英文！

### ISSUE THREAD

**Issue by DuckDuck88** [YiiGuxing/TranslationPlugin#520]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [1] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
翻译文档不起作用，而且会把中文转换为英文
### Environment & Stack Trace
- Plugin version: 2.91 192
- IDE version: 
- Operating System and version: win10

**Comment by Hyperion-v** [comment]
这个怎么解决阿,我也遇到这个问题了

**Comment by YiiGuxing** [comment]
@Hyperion-v 查一下类似的Iusse
