### ISSUE TITLE
最新版本网易有道引擎不支持idea2023.3.4版本

### ISSUE THREAD

**Issue by rollbackNow** [YiiGuxing/TranslationPlugin#5210]
### 📝 问题描述

1.目前我使用idea2023.3.4版本其他翻译引擎好使，但是网易有道翻译引擎会出现无相关服务的实例的报错 我不知道是不是我版本没用对还是怎么样 望解答
![微信图片_20240219160733](https://github.com/YiiGuxing/TranslationPlugin/assets/151449137/1bcbf001-c2c0-4325-962d-3fc9a58ff0d9)
![微信图片_20240219160742](https://github.com/YiiGuxing/TranslationPlugin/assets/151449137/a2460722-e617-4f05-be5a-8005dff83fc8)

### 🏷 插件版本

3.5.6

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Licensed to signup scooter
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2099.
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 12
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  coderead.IdeaPlugins.maven (1.1)
  com.jetbrains.jax.ws (233.13135.65)
  jd-intellij (0.8.1)
  com.intellij.spring.webflow (233.14475.28)
  mobi.hsz.idea.gitignore (4.5.2)
  org.intellij.scala (2023.3.27)
  com.baomidou.plugin.idea.mybatisx (1.5.5)
  cn.yiiguxing.plugin.translate (3.5.4)
Kotlin: 233.14475.28-IJ
```

**Comment by YiiGuxing** [comment]
相关的服务没有开通，请按有道翻译设置对话框上的提示开通相关的服务。

**Comment by rollbackNow** [comment]
感谢您的回复 那么我应该用哪个版本的才可以？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月19日 16:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YiiGuxing/TranslationPlugin] 最新版本网易有道引擎不支持idea2023.3.4版本 (Issue #5210) |

相关的服务没有开通，请按有道翻译设置对话框上的提示开通相关的服务。

**Comment by YiiGuxing** [comment]
和插件版本没有关系，你要在有道翻译控制台里的翻译应用开通 “网页翻译” 服务

**Comment by rollbackNow** [comment]
我更改为网页翻译了 但还是不行啊
![Uploading 1708395844531.png…]()

**Comment by rollbackNow** [comment]
![Uploading 1708395844531.png…]()

**Comment by rollbackNow** [comment]
现在翻译单词可以了，但是翻译文档会报缺少必备参数是什么意思
![Uploading Snipaste_2024-02-20_10-37-16.png…]()

**Comment by rollbackNow** [comment]
![Snipaste_2024-02-20_10-37-28](https://github.com/YiiGuxing/TranslationPlugin/assets/151449137/428df424-0b00-4bbb-b6dc-8279d0664bf3)

**Comment by rollbackNow** [comment]
![Uploading Snipaste_2024-02-20_10-37-16.png…]()

**Comment by rollbackNow** [comment]
![Snipaste_2024-02-20_10-37-28](https://github.com/YiiGuxing/TranslationPlugin/assets/151449137/f55b457c-ec8d-470e-ba81-07cfad7f5273)

**Comment by rollbackNow** [comment]
![Snipaste_2024-02-20_10-37-16](https://github.com/YiiGuxing/TranslationPlugin/assets/151449137/982b609b-ace3-4c58-8ce7-c90e4ec3514f)

**Comment by YiiGuxing** [comment]
问题解决了就好
