### ISSUE TITLE
希望增加deeplx的选项

### ISSUE THREAD

**Issue by wuliangtdi** [YiiGuxing/TranslationPlugin#5234]
### 需求/建议描述

原有的就只有deepl的选项，还需要申请key，不是很方便，希望增加一个deeplx的选项

### 建议的解决方案

沉浸式翻译中有DeepLX的选项，可以看看沉浸式翻译
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/50443578/6310ae5f-94c7-42d1-ab05-b104d08337ba)

**Comment by YiiGuxing** [comment]
见 #3225
