### ISSUE TITLE
为单词表新增单词提供一个action

### ISSUE THREAD

**Issue by EvanMeek** [YiiGuxing/TranslationPlugin#524]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
目前貌似没有为单词表添加任何的action，希望能将关于单词表的功能添加个对应的action，方便全键盘操作。

### Proposed Solution
目前的添加单词到单词本的方式是：对单词翻译后点击浮动窗口中的”收藏“按钮。希望可以新的一种方式：不需要弹出浮动窗口，可以直接对某个单词操作(提供一个action，以添加至单词表中)，这样直接调用action就可以将一个词添加到单词本中十分方便，从而也省去了不必要的操作。

### Additional Information
如果能采用这个建议，那真是太好了。

**Comment by Monster0303** [comment]
[对单词翻译后点击浮动窗口中的”收藏“按钮]

我连这个都没看到，是取消生词本的功能了吗？
<img width="226" alt="image" src="https://user-images.githubusercontent.com/40815364/90385060-1c7edd00-e0b5-11ea-9896-bbe2058fccd1.png">

**Comment by YiiGuxing** [comment]
在即将发布的3.0版本上会在翻译对话框内添加一些快捷键（在翻译气泡中不可用），包括收藏快捷键，到时候可以通过快捷键  `Ctrl+Shift+O` -> `Ctrl+F` 来实现全键盘的收藏操作。到时候更新之后请留意阅读发行说明了解详细内容。
