### ISSUE TITLE
openai翻译希望支持设置自定义api url

### ISSUE THREAD

**Issue by jaychoubaby** [YiiGuxing/TranslationPlugin#5259]
### 需求/建议描述

由于国内问题，无法直接访问openai api，如果可以自定义api url，则可以解决这个问题

### 建议的解决方案

类似翻译插件已经支持，例如：https://github.com/openai-translator/openai-translator
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/26641387/a193d903-a73e-46c0-bdfb-3bc0ebfdf4b1)

**Comment by YiiGuxing** [comment]
Duplicate of #3765
