### ISSUE TITLE
AndroidStudio编辑xml布局部分组件会造成IDE卡顿

### ISSUE THREAD

**Issue by DeMonLiu623** [YiiGuxing/TranslationPlugin#527]
在AndroidStudio的xml文件中编辑布局，使用Button，ImageButton等组件的时候会造成卡顿3-5秒，非常难受。
一开始我以为时AndroidStudio或者是SDK的问题，所以都先后卸载重装了。
结果装回TranslationPlugin插件后还是卡顿。  卸载TranslationPlugin后又恢复正常，非常奇怪。  
然而除了Button类的组件会卡顿，其他组件又都是正常的，所以我很困惑。  
提交个Issues看一下是否其他人有相同经历。  
如果作者有时间麻烦帮忙看一下是否有这个bug，真的喜欢这个插件，写代码有点离不开了。
再次感谢作者

**Comment by YiiGuxing** [comment]
能否提供一下操作的GIF图？

**Comment by DeMonLiu623** [comment]
我重新安装AndroiStudio时偷懒直接保留了setting中的插件，然后直接复制到setting文件中用的。刚才卸载TranslationPlugin后，在Github上手动下载了插件选择从硬盘重新安装完后，发现又不卡了。  
既然解决了就算了，代码这东西就是这么神奇。
下次遇到再给作者大大反馈。  
感谢作者大大的恢复，插件真的好用。赞。
