### ISSUE TITLE
建议右键窗口添加更多功能

### ISSUE THREAD

**Issue by softfn** [YiiGuxing/TranslationPlugin#53]
有时快捷键有问题，建议把这个提供的功能都添加到右键菜单，并归一组展示。而不是只有一个alt + 1功能可选。

**Comment by YiiGuxing** [comment]
1. 建议自定义快捷键；
2. 右键菜单不宜添加过多Action，如个人需要，建议自己添加：Settings > Appearance & Behavior > Menus and Toolbars > Editor Popup Menu.

**Comment by softfn** [comment]
可能是兼容性问题，在Gogland下，Translate And Replace...  功能无法使用，使用上面方式添加，这个功能也不会在右键菜单的中显示（其它功能可以）。

**Comment by YiiGuxing** [comment]
Translate And Replace... 功能只有在取到汉字（或者包含汉字）的时候才会显示，该功能只支持从中文到英文的转换。
