### ISSUE TITLE
希望针对<code/>、{@link}这些标记做出优化

### ISSUE THREAD

**Issue by lagrange-doggy** [YiiGuxing/TranslationPlugin#530]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

比如看到\<code>**String**\<code/>，直接忽略掉\<code/>标签，同时String不必翻译，
看到{@link xxxxx}也是忽略@link，同时xxxx不翻译，我的意思是：**凡是一个类的，均不必翻译，直接显示英文**

**Comment by YiiGuxing** [comment]
嗯，这个确实是可以做进一步优化的。。。

**Comment by YiiGuxing** [comment]
经测试发现，使用谷歌翻译进行自动文档翻译时，可以有效地忽略掉code等标签，因此并不需要再进行任何优化。至于有道和百度翻译，由于其自身功能的限制，是无法实现忽略code等标签的翻译的。
