### ISSUE TITLE
IDea Community Edition 不支持SNMP4J包的文档翻译

### ISSUE THREAD

**Issue by phenemenon** [YiiGuxing/TranslationPlugin#534]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description

1.MAVAN SNMP4J包
2.使用Ctrl + Q打开快速文档
3.没有自动翻译

### Environment & Stack Trace
- Plugin version: 2.9.1
- IDE version:  IDEA 2020.1.2
- Operating System and version: Windows 10 1909

**Comment by YiiGuxing** [comment]
目前文档自动翻译并不完善，有很多限制的。

**Comment by phenemenon** [comment]
但是我兄弟的ultimate版就是正常的。。。是只能用U版吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yii.Guxing"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 上午10:52
收件人:&nbsp;"YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com&gt;;
抄送:&nbsp;"藍天苩雲丅"<690149726@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] IDea Community Edition 不支持SNMP4J包的文档翻译 (#534)





 
目前文档自动翻译并不完善，有很多限制的。

**Comment by YiiGuxing** [comment]
不是的，因素很多，现在的文档翻译是通过hook方式实现的，如果hook被打断，那就翻译不了。你可以试试引用jarjar包的时候指定下载源代码。

**Comment by phenemenon** [comment]
非常感谢~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yii.Guxing"<notifications@github.com&gt;; 
发送时间: 2020年6月23日(星期二) 上午10:57
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com&gt;; 
抄送: "藍天苩雲丅"<690149726@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] IDea Community Edition 不支持SNMP4J包的文档翻译 (#534)





 
不是的，因素很多，现在的文档翻译是通过hook方式实现的，如果hook被打断，那就翻译不了。你可以试试引用jarjar包的时候指定下载源代码。
 
&mdash;
