### ISSUE TITLE
希望可以接入 腾讯翻译

### ISSUE THREAD

**Issue by josways** [YiiGuxing/TranslationPlugin#537]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Additional Information

https://console.cloud.tencent.com/tmt
https://cloud.tencent.com/document/product/551/15612
https://cloud.tencent.com/document/product/551/35017

**Comment by zhuhelong** [comment]
如果需要接入 腾讯翻译君，可以看看我这个项目  https://github.com/zhuhelong/Translator，欢迎小伙伴一起完善。

**Comment by zhuhelong** [comment]
如果需要接入 腾讯翻译君，可以看看我这个项目 https://github.com/zhuhelong/Translator 欢迎小伙伴一起完善。
