### ISSUE TITLE
更改idea系统编码格式为UTF-8以后translation plugin显示出现乱码问题

### ISSUE THREAD

**Issue by ringfu** [YiiGuxing/TranslationPlugin#538]
### Description
更改idea系统编码格式为UTF-8以后translation plugin显示出现乱码问题
idea版本：2020.1.2，translation plugin版本：2.9.1
![2020-07-02_102444](https://user-images.githubusercontent.com/31812889/86309728-02955200-bc4f-11ea-8ccd-3345918b2fdb.jpg)

**Comment by YiiGuxing** [comment]
更改idea系统编码格式为UTF-8？请问是在哪改的？

**Comment by ringfu** [comment]
> 更改idea系统编码格式为UTF-8？请问是在哪改的？

我的错误修改File-setting-editor-file encoding;
现在找到我的乱码问题所在了：我在File-setting-translation中将 “字体” 默认值覆盖了，这里是乱码原因所在
![2020-07-02_错误所在](https://user-images.githubusercontent.com/31812889/86332327-f6c08480-bc7c-11ea-9767-1ce1c917ea9e.jpg)

**Comment by ringfu** [comment]
> 更改idea系统编码格式为UTF-8？请问是在哪改的？
