### ISSUE TITLE
一些实用的功能建议(自动检测, 音标等)

### ISSUE THREAD

**Issue by bluer007** [YiiGuxing/TranslationPlugin#539]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

插件很好用, 这里提一些功能建议, 希望更上一层楼  

1. 强化自动检测语言功能, 例如中文时自动翻译到英文, 而英文时自动翻译成中文 

2. 在弹出的翻译结果中, 支持发音的快捷键(希望是空格键), 因为设置为自动发音后, 陌生单词要多听几次才清楚发音, 现在只能手工点击发音按钮, 对于键盘操作者来说不方便

3. 在翻译结果中, 显示音标就更好了, 除了能听到发音, 还可以自己看着音标小声拼读

**Comment by YiiGuxing** [comment]
1. 呃。。。难道现在的行为不是这样的吗？
2. 快捷键的话到是可以有，但不会是空格键，因为有两个发音，需要两个快捷键的。
3. 音标是有的，但只有单词才会有，而且部分单词还没有。这是翻译API给的结果，它没返回的话我无能为力。。。

**Comment by bluer007** [comment]
> 1. 呃。。。难道现在的行为不是这样的吗？
> 2. 快捷键的话到是可以有，但不会是空格键，因为有两个发音，需要两个快捷键的。
> 3. 音标是有的，但只有单词才会有，而且部分单词还没有。这是翻译API给的结果，它没返回的话我无能为力。。。

刚刚试验了一把1, 发现我设置为目标语言: 上次使用的语言了, 还原为默认就好了
至于2, 3点, 看看作者你怎么设计呗, 有的话就更加锦上添花了

**Comment by YiiGuxing** [comment]
在即将发布的3.0版本上会在翻译对话框内添加一些快捷键，包括播放语音快捷键，到时候更新之后请留意阅读发行说明。
