### ISSUE TITLE
下载并安装：插件“Translation”下载或安装失败

### ISSUE THREAD

**Issue by liuyuchuan** [YiiGuxing/TranslationPlugin#5398]
### 📝 问题描述

新安装的IDEA：IntelliJ IDEA 2023.3.5 (Ultimate Edition)
执行安装插件操作：IDEA --> settings --> 插件 --> Marketplace --> input Translation --> execute 安装，it give me the next message。

<img width="370" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/12453224/3fe8b52e-45c7-491d-ae1f-3d9515261579">

### 🏷 插件版本

3.5.7

### 🔁 翻译引擎

全部

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.3.5 (Ultimate Edition)
Build #IU-233.14808.21, built on March 12, 2024
Runtime version: 17.0.10+1-b1087.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.starxg.mybatis-log-plugin-free (1.3.0)
  com.intellij.zh (233.287)
Kotlin: 233.14808.21-IJ
```

**Comment by YiiGuxing** [comment]
这应该是网络问题，你可以从项目的 release 页下载并手动安装，可以参照项目 readme 操作。

**Comment by liuyuchuan** [comment]
> 这应该是网络问题，你可以从项目的 release 页下载并手动安装，可以参照项目 readme 操作。

是的，应该是我的网络问题，导致下载不成功。重启机器可行，谢谢给予回复。
