### ISSUE TITLE
1.3.4版本设置页字体选择框显示问题

### ISSUE THREAD

**Issue by zhouzl18** [YiiGuxing/TranslationPlugin#54]
android studio 2.3.2 设置字体的时候下拉列表宽度很窄。

**Comment by YiiGuxing** [comment]
@zhouzl18 能截个图么？

**Comment by zhouzl18** [comment]
图片地址[http://pan.baidu.com/s/1o8t1IRK](url)

**Comment by zhouzl18** [comment]
@YiiGuxing 我选择了一个字体后就正常了，宽度就能撑开了。

**Comment by YiiGuxing** [comment]
有时间我看下吧，呃。。。。其实Issues里可以直接添加图片的，把图片拖到输入框里就行了。。。。谢谢你的反馈。

**Comment by YiiGuxing** [comment]
[`b0e7f99`](https://github.com/YiiGuxing/TranslationPlugin/commit/b0e7f99bb1a94543ec0d18587622b9b7267a8759)
