### ISSUE TITLE
翻译出错，提示：too many requests

### ISSUE THREAD

**Issue by ringfu** [YiiGuxing/TranslationPlugin#541]
在translation保持默认设置情况下，翻译报错：“翻译失败：Too Many Requests"
![2020-07-07_093146](https://user-images.githubusercontent.com/31812889/86684421-1cf77300-c035-11ea-97ac-d8727864ff86.jpg)

**Comment by YiiGuxing** [comment]
很不幸，访问过于频繁，你的IP被限制了，可以稍候再试。
