### ISSUE TITLE
翻译时 检测语言无法直接阅读

### ISSUE THREAD

**Issue by isMc-li** [YiiGuxing/TranslationPlugin#5417]
### 📝 Issue Description

翻译时 检测语言无法直接阅读 需要切换为具体的语种才能阅读 

### 🏷 Plugin Version

最新

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
IDEA2023.3.3
```

**Comment by YiiGuxing** [comment]
这种情况仅在阿里翻译时存在，因为阿里翻译在翻译后不提供检测出的语言，因此TTS无法识别并播放。
