### ISSUE TITLE
一个简单的bug

### ISSUE THREAD

**Issue by Pilgrim-xing** [YiiGuxing/TranslationPlugin#544]
## bug反馈
选择百度翻译之后 需要输入账号，这是重新选择google翻译，使用翻译功能会一直报错：“翻译失败：账号错误”，重启可解决问题。

这个bug应该是切换百度翻译之后，系统验证账号，在切换到google翻译之后依旧还在检验导致。

## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
无法复现啊，请检查一下右下角的这个图标：
![image](https://user-images.githubusercontent.com/10737066/87125183-a40a4c80-c2bc-11ea-8f6d-6105f88b9546.png)

我怀疑你切换后没有保存应用。
