### ISSUE TITLE
翻译和朗读能否单独设置

### ISSUE THREAD

**Issue by stackJx** [YiiGuxing/TranslationPlugin#5455]
### 需求/建议描述

翻译引擎和朗读引擎单独设置

### 建议的解决方案

很多没有朗读的 ，可以设置一些免费的朗读比如edge 或者单独设置只用 谷歌的 朗读

**Comment by YiiGuxing** [comment]
多 TTS 服务正在开发中，目前己发布的版权仅有一个 TTS 服务。
