### ISSUE TITLE
注释的翻译能不能保留原英文

### ISSUE THREAD

**Issue by zackzhangkai** [YiiGuxing/TranslationPlugin#546]
由于注释的翻译大多数并没有原文更能表达意思。能不能有个设置把注释的翻译关掉，或是显示原注释的内容？

来感受下它的翻译，太别扭了，有想把这个插件disabled的冲动。
![image](https://user-images.githubusercontent.com/20178386/87487217-a9c2b200-c66f-11ea-900a-5f5d6a6375c5.png)

其实这个插件，最好是主动去查询，比如，某个单词或是某句话我不懂，想主动去查下，这时候你提供接口去跟我查。而不是一股脑的，全部都给我翻译了。

**Comment by YiiGuxing** [comment]
在设置页面取消勾选“翻译文档”选项即可关闭此功能。

**Comment by YiiGuxing** [comment]
每发布一个新的功能都相应的发行文档，介绍新功能并说明用法的，这个功能的发行文档也是介绍了如何关闭的啊，以后请多留意一下发行文档。

**Comment by zackzhangkai** [comment]
好的，谢谢，确实可以。
