### ISSUE TITLE
分隔符能否设置为'\t'

### ISSUE THREAD

**Issue by aresis** [YiiGuxing/TranslationPlugin#5479]
### 需求/建议描述

分隔符能否设置为'\t'
对于主题词，经常会连在一起翻译

### 建议的解决方案

如果能设置\t为分隔符就好了

**Comment by YiiGuxing** [comment]
\t 翻译会有什么问题吗？

**Comment by aresis** [comment]
分隔符那里好像无法输入 \t

**Comment by YiiGuxing** [comment]
你可以先在记事本里面输入然后再复制粘贴上去，只能这样了😅

**Comment by aresis** [comment]
但是这样并没有真正地分隔开😔

**Comment by YiiGuxing** [comment]
我还是没有完全明白你的使用场景，你能截个图什么的吗？

**Comment by aresis** [comment]
![屏幕截图 2024-04-07 205925](https://github.com/YiiGuxing/TranslationPlugin/assets/55878832/7b50d8bf-b9c3-478c-a728-4a0673ccd890)
就是这样主题模型生成的主题词

**Comment by YiiGuxing** [comment]
这个可以有

**Comment by aresis** [comment]
我要等下一个版本更新吗？还是重装即可

**Comment by YiiGuxing** [comment]
> 我要等下一个版本更新吗？还是重装即可

等下一个版本更新，现在还在做2024.1版本的兼容适配。
