### ISSUE TITLE
Suggest:可以添加常见例句吗?

### ISSUE THREAD

**Issue by JavaAIer** [YiiGuxing/TranslationPlugin#549]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
只有单词,没有例句是缺少灵魂的.
### 问题描述
1. 选中单词
2. 翻译,发音,同义词,生词本等做得很完美了,某种程度上已经是加九锡,称魏王,貌似无可挑剔了
3. 但是还可以更进一步,直接在Idea里面抢了金山词霸,有道词典的饭碗(有个定语,在idea里面).直接称帝--idea翻译大帝.
4. 功德圆满--万年之后可定谥号:统一语言文字发音度量衡之川斯雷特-文-帝.

### 环境 & 错误日志
都不重要,重点在上面可描述的句子.

**Comment by YiiGuxing** [comment]
。。。这个可以有

**Comment by YiiGuxing** [comment]
谷歌翻译现已支持单词示例
