### ISSUE TITLE
高DPI缩放情况下图标模糊

### ISSUE THREAD

**Issue by qiyuey** [YiiGuxing/TranslationPlugin#55]
操作系统macOS，Windows未测试，发音图标存在模糊现象🙂

![image](https://cloud.githubusercontent.com/assets/7856182/26295348/0bae359c-3efc-11e7-9e3d-d26a0c7055e5.png)

**Comment by YiiGuxing** [comment]
请问是显示器DPI还是调整界面字体大小导致的？

**Comment by qiyuey** [comment]
UI Options的字体没有调整过，Editor的字体调整过

**Comment by YiiGuxing** [comment]
那其他图标正常吗？比如右键菜单上的。烦请截个图（把ide自身的图标也截进去，我看一下不同之处），谢谢

**Comment by qiyuey** [comment]
右键菜单的图片并不会模糊
![image](https://cloud.githubusercontent.com/assets/7856182/26305433/d5a91a0e-3f21-11e7-9e9d-08892625fc0b.png)
![image](https://cloud.githubusercontent.com/assets/7856182/26305468/f21c53ea-3f21-11e7-918b-58b9d162dff9.png)

**Comment by YiiGuxing** [comment]
已修复，可以从这里下载预先使用：[TranslationPlugin.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1018762/TranslationPlugin.zip)
感谢反馈！
