### ISSUE TITLE
OpenAI 翻译接口支持配置代理接口

### ISSUE THREAD

**Issue by mlbzsske** [YiiGuxing/TranslationPlugin#5518]
### 需求/建议描述
作者好~ 软件非常好用，非常感谢提供这么棒的软件，现在这边有一个小小的建议

现在国内有很多包装 openAI 接口的服务，支持无缝兼容 openAI 的原接口

### 建议的解决方案

在 openAI 引擎的配置页提供一个新的输入框，可输入代理地址

**Comment by YiiGuxing** [comment]
Duplicate of #3765
