### ISSUE TITLE
请问作者什么时候考虑吧这个插件加入vscode市场 呢

### ISSUE THREAD

**Issue by super117893344p** [YiiGuxing/TranslationPlugin#5528]
### 需求/建议描述

主要是iDE用惯了 , vscode 的插件用的不太顺手, 而且种类良莠不齐

### 建议的解决方案

希望作者可以考虑一下

**Comment by YiiGuxing** [comment]
已经没有更多的时间和精力了，这里的任务都堆积了很多了，就更别说其他 IDE 的了，，，

**Comment by YiiGuxing** [comment]
Merged: #271

**Comment by super117893344p** [comment]
唉, 确实可惜,  jetbrains插件市场与vscode 语言不通, 你得用typescript重新写一遍 ,vscode唯一能用的翻译插件也就comment Translate, 不过响应速度没有translation那么丝滑
