### ISSUE TITLE
快捷键 开关

### ISSUE THREAD

**Issue by wxyShine** [YiiGuxing/TranslationPlugin#5541]
### 需求/建议描述

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/42802152/086cf3fb-7275-4925-8821-d50fdcdbd933)
你好 这个快捷键ctrl shift s  是否支持关闭掉呢

### 建议的解决方案

在插件设置中支持 快捷键开关/自定义快捷键

**Comment by YiiGuxing** [comment]
可在 settings > keymap 中删除或自定义
