### ISSUE TITLE
Feature:过滤单行注释符号 `//`

### ISSUE THREAD

**Issue by plain-dev** [YiiGuxing/TranslationPlugin#555]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

翻译单行注释时 `//` 符号影响翻译效果

### Proposed Solution

建议过滤一下 ⏳

### Additional Information

如图所示

![Z3kXbu](https://gitee.com/plain-dev/oss/raw/master/v2/Z3kXbu.png)

**Comment by YiiGuxing** [comment]
见 #470
