### ISSUE TITLE
翻译功能没有生效

### ISSUE THREAD

**Issue by andisolo** [YiiGuxing/TranslationPlugin#557]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。
  1. 随便找一个带有javadoc的文件,打开Toggle Rendered View功能
  2. 使用快捷键翻译时没有反应。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
该模式目前无法翻译
