### ISSUE TITLE
2020.2 版本乱码

### ISSUE THREAD

**Issue by happyzero** [YiiGuxing/TranslationPlugin#558]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version: 2.9.1
- IDE version: IDEA 2020.2
- Operating System and version: Windows 10

**Comment by YiiGuxing** [comment]
请配置正确的字体
