### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by zhangtianshun403** [YiiGuxing/TranslationPlugin#559]
### Problem Description
编写代码以及学习时大部分时候都不会碰鼠标，但需要使用翻译功能时用快捷键唤出翻译窗口后必须用鼠标点掉才能继续打字，我认为这样时常会打断思路。
### Proposed Solution
当翻译窗口存在时，再按一次ctrl+shift+o来关闭窗口。

**Comment by YiiGuxing** [comment]
如果是泡泡窗口的话，按任意键就可关闭。如果是翻译对话框的话，按ESC键即可关闭。

**Comment by zhangtianshun403** [comment]
了解
