### ISSUE TITLE
最近Android Studio升级，是不是Alt+R不能用了？

### ISSUE THREAD

**Issue by pocketfpv** [YiiGuxing/TranslationPlugin#56]
发现Alt+R会开启菜单。
但即使修改keymap也不能使用替换翻译功能。

**Comment by YiiGuxing** [comment]
可能使用的啊，2.3.2和3.0 canary1都能用啊，你使用的是哪个版本？插件版本又是哪个版本？
尝试升级插件版本到最新的版本，还有替换翻译功能只能替换中文，请确认。也可能是冲突，Alt+R在功能可用的情况下会优先于默认功能的，或者使用右键菜单的”Translate And Replace...“试一下，如果可以的话应该是快捷键冲突，换一个试试。

**Comment by softfn** [comment]
Gogland下这个快捷键也没法使用

**Comment by YiiGuxing** [comment]
Translate And Replace... 功能只有在取到汉字（或者包含汉字）的时候才会显示，该功能只支持从中文到英文的转换。

**Comment by YiiGuxing** [comment]
@pocketfpv @softfn 
如果有问题的话一般情况下IDE会报异常的

**Comment by pocketfpv** [comment]
诶？Alt+R只能中文到英文么？
之前可以英文到中文的翻译吧？

**Comment by YiiGuxing** [comment]
是的，之前可以，后来我给改了。。。
