### ISSUE TITLE
翻译框下方的名词，动词，例子看不见了

### ISSUE THREAD

**Issue by freeit0525** [YiiGuxing/TranslationPlugin#5605]
### 📝 Issue Description

翻译框下方的名词，动词，例子看不见了

### 🏷 Plugin Version

lasted

### 🔁 Translation Engine(s)

Youdao Translate, Baidu Translate

### 💻 IDE and Operating Environment

```plain text
idea 2024.4.1
jvm Graalvm21
```

**Comment by YiiGuxing** [comment]
1. 百度本就没有更多的翻译信息。
2. 有道原本是有一些额外的信息的，但现在已经被取消掉了，不再返回，原因不明，后面是否会恢复也不明。

**Comment by freeit0525** [comment]
> 1. 百度本就没有更多的翻译信息。
> 2. 有道原本是有一些额外的信息的，但现在已经被取消掉了，不再返回，原因不明，后面是否会恢复也不明。

谢谢
