### ISSUE TITLE
之前翻译并替换有修改代码命名风格能力，不知道哪个版本更新开始没了

### ISSUE THREAD

**Issue by AungV** [YiiGuxing/TranslationPlugin#5656]
### 需求/建议描述

早期版本翻译并替换有命名风格能力，一直在使用。
更新新版本后，只有翻译成中文再翻译英文才能选择命名风格。来回翻译可能会导致用词变化。希望能够还原

### 建议的解决方案

希望能够还原替换命名风格能力。好用，一直在用。

**Comment by YiiGuxing** [comment]
修改代码命名风格？我不明白你的意思，你能举个例子吗？

**Comment by AungV** [comment]
> 修改代码命名风格？我不明白你的意思，你能举个例子吗？

其实不是翻译功能。
就是下划线格式转驼峰，大驼峰转全大写之类的。
最近换了个新pc下了最新的版本，就只有中转英的时候才出线风格选择了。

**Comment by YiiGuxing** [comment]
是啊，一直是这样的啊，中文怎么会有大驼峰这些的？

**Comment by YiiGuxing** [comment]
我大概明白你的意思了，你的意思是不是，即使是对英文字母进行翻译与替换，得到的也是英文的，并有下划线，大驼峰这些的是吗？如果是这样的话，现在默认是英文会转中文的，如果你需要达到你需要的效果，这么设置就可以了：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/e75132c2-0e81-4b2b-afda-7ddc4cf4fc48)

**Comment by YiiGuxing** [comment]
或者你也可以这么设置：

![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/2c24c08e-b838-4aaa-87b6-dd85f67d590f)

勾选这个选项，然后在进行翻译与替换时手动选择英文，这样也就可以达到同样的效果，且不会影响到默认的翻译操作。

**Comment by AungV** [comment]
> 你也可以这么

谢谢。确实ok。
