### ISSUE TITLE
修改单词本默认存储路径

### ISSUE THREAD

**Issue by xiaozhuai** [YiiGuxing/TranslationPlugin#5658]
### 需求/建议描述

当前单词本的默认存储路径为`${HOME}/.TranslationPlugin`，建议修改为`${HOME}/.config/TranslationPlugin`.
最近在整理home目录时发现这个问题，有太多应用在用户目录下创建各种各样的目录，大部分情况下都是非必要的，用户不了解也不需要修改它们。因此将其放入更深一层的目录是合理的。

### 建议的解决方案

修改单词本默认存储路径。

**Comment by YiiGuxing** [comment]
你可以尝试在系统变量里添加一个名为 `XDG_DATA_HOME` 的变量，其值为你需要指定的目录的路径
