### ISSUE TITLE
翻译失败：未知错误 cannot retry due to proxy authentication

### ISSUE THREAD

**Issue by SenixCoder** [YiiGuxing/TranslationPlugin#569]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

1. 公司内网环境，必须配置proxy；配置了百度翻译
2. 翻译是报错  翻译失败：未知错误， 看具体异常显示的是由于代理的认证，无法重试
3. 同样的配置使用有道翻译是正常的

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
代理是idea平台提供的，插件并不涉及这部分内容

**Comment by nishubin** [comment]
你好我们公司也是内网的，百度，有道，谷歌，的api地址是多少好通知运维配置代理。

**Comment by YiiGuxing** [comment]
> 你好我们公司也是内网的，百度，有道，谷歌，的api地址是多少好通知运维配置代理。

@nishubin 

- 阿里：http://mt.aliyuncs.com/api/translate/web/general
- 百度：https://fanyi-api.baidu.com/api/trans/vip/translate
- 谷歌：https://translate.googleapis.com/translate_a/single
- 有道：https://openapi.youdao.com/api

**Comment by SenixCoder** [comment]
/*********************************************** Name: Senix** Msg: 我已收到您的消息，会尽快回复********************************************/
