### ISSUE TITLE
【建议】建议增加字节跳动的【火山翻译】

### ISSUE THREAD

**Issue by xcocean** [YiiGuxing/TranslationPlugin#5691]
### 需求/建议描述

# 当前版本`5.3.8`
【建议】建议增加字节跳动的【火山翻译】
火山翻译，翻译速度极快，比百度的还要快

### 建议的解决方案

能够丰富翻译组件选择性

### 附加信息

当前版本`5.3.8`

**Comment by YiiGuxing** [comment]
Duplicate of #4106
