### ISSUE TITLE
有道翻译己关闭API Key的申请，并于2017-12-31关闭原有的API

### ISSUE THREAD

**Issue by xlee00** [YiiGuxing/TranslationPlugin#57]
![image](https://cloud.githubusercontent.com/assets/8790862/26518494/4ad56646-42e4-11e7-883f-175ceac454ab.png)
有道翻译 API 平台已经全面升级，当前平台的key申请已经停止，请前往新平台有道智云申请及后续使用。
此平台将于 2017-12-31 后停止运行，敬请尽快升级。

新的平台中，提供Android SDK和IOS SDK ，但是不再提供原有api支持。

**Comment by YiiGuxing** [comment]
感谢提醒，我会尽快升级API。就是不知道还能不能免费使用，不能的话那就真坑了。。。。

**Comment by xlee00** [comment]
首先我们要感谢你做了个这么好的工具。
然后现在Android 和 IOS 还可以免费体验，但是具体的内部API我还没有看。

**Comment by xlee00** [comment]
如果后面发现不能直接使用，我们可以看看有什么办法转换一下。
如果实在不行，就要考虑其它API了。

**Comment by YiiGuxing** [comment]
唉，升级以后每天只有10万字符的翻译量了（http://ai.youdao.com/billing.html）。
虽然和现在一样每个人都可以自己申请一个，但申请起来很麻烦了，好像还需要审核。看来多API平台的支持得加快日程了，虽然[日程](https://github.com/YiiGuxing/TranslationPlugin/projects/1)里已经有了必应词典的支持，但目前还没有心思动啊。。。

**Comment by NinthCode** [comment]
现在只能使用默认的API了,现在申请的没有用,不过你可以试试百度翻译的公共API

**Comment by YiiGuxing** [comment]
@NinthCode 先等一等吧，我会尽快升级新的API接口的，这几天没时间。

**Comment by YiiGuxing** [comment]
![code](https://user-images.githubusercontent.com/10737066/26936689-f17f29c0-4ca1-11e7-89ef-b5ebd7fa9547.png)

这段代码值31块钱：

![...](https://user-images.githubusercontent.com/10737066/26936853-5af0a384-4ca2-11e7-83c9-0799bcc0de93.png)

![a41f7285d94f182d043705](https://user-images.githubusercontent.com/10737066/26936865-66fe0c02-4ca2-11e7-89fd-08c0c6964332.jpg)

**Comment by xlee00** [comment]
不是很明白这样到底是要实现什么功能。一秒两次是什么功能。

**Comment by YiiGuxing** [comment]
@xlee00 没什么功能，就是想看看使用量超过限制以后会怎样，结果欠费了，而欠费后就不能使用了。所谓的每日有10w的字符量是要在帐户还没有欠费的提前下的，所以，升级API以后就不会存在公共的API Key了，每个人都得自己有一个。而且欠费后得自己处理，不过每天10w字符的量，个人应该是够用的，只要不要像上面的那样使用。百度的API也是这种情况。
另外，平台提供的key是私密性的，不能公开。所以需要保证用户的key的安全性。所以开发的进度变慢了，这一版本的完成时间得往后延长了。

**Comment by leopoo** [comment]
0 0 配置多个有道API 百度API密钥, 本地统计发送字符数量,   到10然后切换😁

**Comment by Methol** [comment]
我觉得只要强制所有的人都用自己的key就行了，不给公用的key。
一天10w根本用不完，用其他源也可以，但是也要考虑其他源的质量，是不是像有道这么好用。

保证key的安全性这个也确实需要做，但是应该不是那么重要，插件都是用户自己装的，他们也能考虑到这些风险。idea的其他插件，类似gitlab，那些token也是明文保存的。

**Comment by hadooop** [comment]
其实我今天去有道云申请了一个新的key，但是申请完成后（不知操作对否），在最后要填入key from 的时候居然不知道怎么填写，问他们qq的客服说默认为空；
还请您给个说明；
应用名称	应用ID	应用密钥	分类	状态	开通服务

**Comment by YiiGuxing** [comment]
@hadooop 新平台的key不能应用于现在的版本，要等到下一版本才能使用，现在的版本还要是老平台的key，老平台的key现在已经不能申请了

**Comment by YiiGuxing** [comment]
@Methol 等升级了新的API，想不强制也不行了。至于key的安全性是有必要的，而且也是重要的，毕竟可能涉及到用户个人利益的东西，还是将用户的风险降到最低的好。

**Comment by ReinWD** [comment]
哇赶上开发现场， 先膜一波dalao
话说换个请求URL是不是就能行了

**Comment by ReinWD** [comment]
简单看了一下新版API，接入大概需要做以下工作：
1.添加新版本请求链接生成工具 YouDaoEncryptor.java(官方提供，可以直接pull request)。
2.在SettingPanel.form中添加Toggle：启用新版翻译API。
3.若用户启用此Toggle且填入相应的id与Key，则Translator.java.line:117中方法弃用，并实现新版本API请求逻辑。
4.完蛋，返回数据的结构也改了。
5.同样利用toggle的状态判断解析类型目标，model中增加新版POJO。
6.将返回数据接回显示窗口。
如果信任我的话，我可以于明天尝试为此项目开发以上内容（不过本人水平有限，如果开发的功能不够完善欢迎前辈给我相应的建议~（最好能把上文提到的相关实现相关的类名提交给我~）
by  一个Java、Android的小萌新

**Comment by YiiGuxing** [comment]
@Methol @yfbdxz @ReinWD 
最近收到了几位道友（呃。。。）的PR，在这里首先表示感谢，但是由于和版本的规划有些冲突，而自己已经开发到接近尾声了，所以并没有采纳，而关于这一个版本的开发也不必再提交PR了。
这里也顺便说明一下进度和一些版本的规划吧：
- 关于进度，其实基本上已经快完成了。只是考虑key的安全性的问题，如果过于麻烦，可能会放弃这个问题，用明文存储了。
- 而版本的规划嘛，其实这一版本的工件只将API升级就行了。另：
  1. 并不需要考虑兼容老的API，因为老的API将会被关闭无法使用。
  2. 也不需要考虑以其他翻译平台API接入的问题，因为这个问题是下一个大版本才需要考虑的，而下一个大版本整个插件将要完全重写。
  3. 在下一个大版本中，插件将不会对较低版本的IDE提供支持，所以这一版不光要升级API，还要提供一个比较稳定好用的版本出来才行。

**Comment by yueLife** [comment]
今早发现这个问题，准备过来提醒下。没想到已经有了，我算是知道的慢了- -

**Comment by YiiGuxing** [comment]
新版本预览包：[TranslationPlugin](https://github.com/YiiGuxing/TranslationPlugin/files/1079698/TranslationPlugin.zip)
需要的同学可以先下载使用，顺便帮忙测一下，谢谢！
新版本将会在近期发布。

**Comment by CNHLM** [comment]
新版怎么申请key和keyfrom啊，没看到啊

**Comment by YiiGuxing** [comment]
@CNHLM https://github.com/YiiGuxing/TranslationPlugin/tree/v1.3#使用
