### ISSUE TITLE
能否添加手动设置翻译目的语言的功能

### ISSUE THREAD

**Issue by gaochengyidlmu** [YiiGuxing/TranslationPlugin#570]
需求来源：mac 环境切换为了 en，所以在 auto 模式下嗅探时会使用 mac 的 en 环境，导致每次都是从 en 翻译到 en
目前使用方式：每次翻译手动从 en 切换为 cn，比较繁琐
希望功能：
1. 手动指定默认目的语言
2. 记录上次手动修改的目的语言，下次默认采用该语言

二者实现一个即可，谢谢

PS: 本想自己把 auto 模式写死成 cn 的，但无奈不太会 java，不知道如何打包，只能申请求助了 (囧)

**Comment by YiiGuxing** [comment]
可在设置页配置主要语言

**Comment by gaochengyidlmu** [comment]
好！顶！赞！

![image](https://user-images.githubusercontent.com/18210759/91811232-c340ad00-ec61-11ea-8217-a5b4c9e9e628.png)
