### ISSUE TITLE
Rider无法使用ctrl+q快速翻译

### ISSUE THREAD

**Issue by xingyunzhi199** [YiiGuxing/TranslationPlugin#572]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
Rider无法使用ctrl+q快速翻译
### 问题描述
Rider无法使用ctrl+q快速翻译

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
由于Rider的文档生成方式的原因，它是不能通过这种方式翻译的。
