### ISSUE TITLE
能不能设置不自动翻译,每次鼠标移动到方法上显示内容出来就是翻译过的,体验极差

### ISSUE THREAD

**Issue by TTnTTT** [YiiGuxing/TranslationPlugin#575]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
自2.9.2版本起已经关闭默认自动翻译文档了，如果您打开了这个选项，请到设置页面关闭自动翻译文档的选项。
