### ISSUE TITLE
More flexible language selection support via OpenAI 

### ISSUE THREAD

**Issue by rixbeck** [YiiGuxing/TranslationPlugin#5762]
### Feature/Enhancement Description

I was glad to see the new option for using OpenAI for translations. Moreover the best it is working via its OpenAI protocol support locally, for example with LM Studio.
The only drawback is just can be selected the hard coded target languages.
It would be great somehow to define freely the requested target language.

### Proposed Solution

Text field for desired default target language maybe.

**Comment by YiiGuxing** [comment]
Using hard-coded definitions for languages is an unavoidable compromise because we need to share them among multiple translators. Therefore, we must use the same set of standards to facilitate mutual conversion and provide localized names. As a result, this request will not be implemented.
