### ISSUE TITLE
导入的单词本是乱码的

### ISSUE THREAD

**Issue by heroPool** [YiiGuxing/TranslationPlugin#578]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

我将另一个设备的上idea的单词本导出到本电脑的idea上，单词本出现了乱码，json、xml格式都乱码
![image](https://user-images.githubusercontent.com/26159915/93730789-c7c30a80-fbfc-11ea-9548-a7bfc44d7a47.png)

**Comment by YiiGuxing** [comment]
能否提供导出的文件？

**Comment by heroPool** [comment]
[workbook.zip](https://github.com/YiiGuxing/TranslationPlugin/files/5253619/workbook.zip)
txt,xml,json，都不行，文件是从另一个电脑的workbook导出来的

**Comment by YiiGuxing** [comment]
麻烦您安装这个版本，再导入试试：
[TranslationPlugin-3.0-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/5255561/TranslationPlugin-3.0-SNAPSHOT.zip)

**Comment by heroPool** [comment]
好像不起作用，

**Comment by YiiGuxing** [comment]
使用你提供的文件我这边导入都是没有问题的。导入之前要先删除之前导入的乱码的词条，再重新导入，导入的时候是不会覆盖重复词条的，只会忽略。

**Comment by zhuhelong** [comment]
希望导出到 Anki 吗？可以看看我这个项目 https://github.com/zhuhelong/Translator ，欢迎小伙伴来一起完善。

**Comment by YiiGuxing** [comment]
无回应，暂时关闭，如果您有任何问题可以重新打开此问题。
