### ISSUE TITLE
Android Studio 升级插件，原来的设置被重置

### ISSUE THREAD

**Issue by bihailantian** [YiiGuxing/TranslationPlugin#580]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

Android Studio 上升级到版本2.9.1-192，上一个版本(版本号不记得)的设置被重置了，希望插件升级能保留上一个版本的设置，或者提供方法保留上一个版本的设置。

### 环境 & 错误日志
- 插件版本: 2.9.1-192
- IDE版本: Android studio 3.6.1
- 操作系统版本:  Windows 10

**Comment by YiiGuxing** [comment]
升级如果是跨大版本的话是有可能被重置的，在2.0版本内的设置没有大的改动的，应该不会被重置的啊。请问是重置了哪些项？

**Comment by bihailantian** [comment]
翻译文档设置。上个版本已经去掉勾选☑️，升级后重新勾选上了。

**Comment by YiiGuxing** [comment]
那可能是你在使用快捷键的时候又给它勾上了，在聚焦快速文档窗口的时候使用翻译的快捷键“Ctrl+Shift+Y”会切换文档翻译的勾选状态。

**Comment by bihailantian** [comment]
哦，这样子啊
