### ISSUE TITLE
关掉第一次提示窗口后idea闪退

### ISSUE THREAD

**Issue by Ouyangchunchen** [YiiGuxing/TranslationPlugin#5821]
### 📝 问题描述

![Screenshot_20240613_220431](https://github.com/YiiGuxing/TranslationPlugin/assets/23051757/391869c4-47ae-4391-b02b-c4cef8029f27)
右上角提示窗口点击后闪退

### 🏷 插件版本

 3.6.2

### 🔁 翻译引擎

全部

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.0-31-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.zh (241.271)
  GrepConsole (13.0.2-IJ2023.3)
  com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (3.3.2+2322)
  cn.yiiguxing.plugin.translate (3.6.2)
Kotlin: 241.14494.240-IJ
Current Desktop: KDE
```

**Comment by YiiGuxing** [comment]
感谢您的反馈！还麻烦您再帮忙进一步确认一下问题：点击  `主菜单 -> Help -> Translation -> What's New` ，看看是不是会出现同样的问题。
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/44b632dd-b011-485c-831f-5d64193554ea)

**Comment by Ouyangchunchen** [comment]
感谢大佬回复,根据上述步骤已确认会造成卡死崩溃

**Comment by YiiGuxing** [comment]
请问为何关闭了此问题？是不再出现这个问题了吗？
