### ISSUE TITLE
能不能支持 DeepLX翻译和ChatTTS

### ISSUE THREAD

**Issue by Wang-Mer** [YiiGuxing/TranslationPlugin#5823]
### 需求/建议描述

能不能支持
DeepLX翻译和ChatTTS

### 建议的解决方案

ChatTTS：https://github.com/2noise/ChatTTS/blob/main/README_CN.md
DeepLX：https://deeplx.owo.network/

**Comment by YiiGuxing** [comment]
- 关于 DeepLX，请另参阅 #3225
- 关于 ChatTTS，后面会添加自定义TTS服务的功能，应该可以支持到。

**Comment by Wang-Mer** [comment]
好的
