### ISSUE TITLE
英文不显示音标了

### ISSUE THREAD

**Issue by countree** [YiiGuxing/TranslationPlugin#5826]
### 📝 问题描述

1.翻译弹窗显示英文音标，不知道怎么读，没法记单词了

### 🏷 插件版本

3.6.2

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
windows10
idea  2024.1
```

**Comment by YiiGuxing** [comment]
那是因为有道不再返回音标了，目前也就只有谷歌翻译带音标了，其他的都没有了。

可以用TTS读嘛~~~
