### ISSUE TITLE
翻译时报错

### ISSUE THREAD

**Issue by king607267** [YiiGuxing/TranslationPlugin#583]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
安装好插件并重启IDE，配置好有道后划词右键点击翻译出现错误如图
![微信截图_20201013113516](https://user-images.githubusercontent.com/17718178/95812548-40267280-0d48-11eb-9c31-7dbf9f5d6eb3.png)

### 环境 & 错误日志
- 插件版本: 2.9.2
- IDE版本: 2020.2
- 操作系统版本: ubuntu18.04.5

**Comment by YiiGuxing** [comment]
请问你是怎么安装的插件的？

**Comment by king607267** [comment]
你好，我是通过网站下载了zip解压然后File-》Plugins-》install Plugin from disk 指定TranslationPlugin-2.9.2.jar安装的

**Comment by YiiGuxing** [comment]
自己下载的安装包不要解压，直接指定zip包安装

**Comment by king607267** [comment]
好的非常感谢。现在可以正常使用了。
