### ISSUE TITLE
建议可以自定义快捷键

### ISSUE THREAD

**Issue by lengmianshi** [YiiGuxing/TranslationPlugin#5837]
### 需求/建议描述

开发经常用的快捷键被占用了很难受，比如ctr + shift + o导包或是取消导入不用的包，ctr+shift+x大小写切换……
在开发过程中，个人觉得翻译的操作是很低频的，而idea的快捷键才是最常用的，建议不要覆盖

### 建议的解决方案

可自定义快捷键

**Comment by YiiGuxing** [comment]
快捷键是可以可自定义的：`Settings -> Keymap -> Plugins -> Translation`
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/59ec398e-f053-479b-8c74-24e308428329)

当初定快捷键的时候只是参考 IDEA 默认快捷键上面定的，并没有考虑到其他IDE，所以在其他IDE上可能会有冲突。

**Comment by lengmianshi** [comment]
> 快捷键是可以可自定义的：`Settings -> Keymap -> Plugins -> Translation` ![image](https://private-user-images.githubusercontent.com/10737066/340909236-59ec398e-f053-479b-8c74-24e308428329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzA3OTksIm5iZiI6MTcxODc3MDQ5OSwicGF0aCI6Ii8xMDczNzA2Ni8zNDA5MDkyMzYtNTllYzM5OGUtZjA1My00NzliLThjNzQtMjRlMzA4NDI4MzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA0MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZGExY2Q2YmNiYTBkZWRlODJmODk2MmRjNzVjZWM1MDVlMDEzNGFlMDlhMzY0NzI4Mzk4MmYyYzdiNWYzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oL7f_Wlwb_ODynx0GDYa10bBg9A3PZwEZ6oPkYaQ7lQ)
> 
> 当初定快捷键的时候只是参考 IDEA 默认快捷键上面定的，并没有考虑到其他IDE，所以在其他IDE上可能会有冲突。

非常感谢，已经可以了
