### ISSUE TITLE
阿里翻译引擎支持直接使用tts播放源文本

### ISSUE THREAD

**Issue by GaN601** [YiiGuxing/TranslationPlugin#5848]
### 需求/建议描述

当源文本的翻译选项是检测语言时, 无法播放文本. 希望能取消这个限制, 支持直接播放文本

### 建议的解决方案

解除语言选项为检测语言时不能使用tts播放源文本的限制

**Comment by YiiGuxing** [comment]
TTS 服务一般需要提供文本的语言，因此没有语言无法播放，如果你希望没有语言也可以播放，可以考虑 open AI TTS.

**Comment by GaN601** [comment]
> TTS 服务一般需要提供文本的语言，因此没有语言无法播放，如果你希望没有语言也可以播放，可以考虑 open AI TTS.

那能否提供默认来源语种选项而不是指定auto呢? 以前的版本我记得是可以设置成默认为文本是某个语种

**Comment by YiiGuxing** [comment]
> > TTS 服务一般需要提供文本的语言，因此没有语言无法播放，如果你希望没有语言也可以播放，可以考虑 open AI TTS.
> 
> 那能否提供默认来源语种选项而不是指定auto呢? 以前的版本我记得是可以设置成默认为文本是某个语种

你遇到这个问题的根本原因是你所使用的翻译服务不提供语言自动检测功能所导致的。如果默认指定源语言则会带来更大的问题——无法方便地在两种语言这间自由翻译。
对于这个问题，有两个方式可以解决：
1. 补全翻译服务的语言自动检测功能，如果是阿里翻译，就要好处理一些，它好像有语言检测的接口，而 openai 就难办一些，需要其一些高级的功能，工作量不小，还好 open AI TTS 不需要提供语言就可以播放。
2. 本地检测语言，这个我也有研究过，可以实现，但这是个优先级较低的任务，近期还不考虑。

综上所述，如果你使用的是阿里翻译，近期内你的需求应该是可以得到解决的，其他的我就无法保证了，精力有限，任务还很多，而我又无法全身心投入到这上面来。

**Comment by GaN601** [comment]
> > > TTS 服务一般需要提供文本的语言，因此没有语言无法播放，如果你希望没有语言也可以播放，可以考虑 open AI TTS.
> > 
> > 
> > 那能否提供默认来源语种选项而不是指定auto呢? 以前的版本我记得是可以设置成默认为文本是某个语种
> 
> 你遇到这个问题的根本原因是你所使用的翻译服务不提供语言自动检测功能所导致的。如果默认指定源语言则会带来更大的问题——无法方便地在两种语言这间自由翻译。 对于这个问题，有两个方式可以解决：
> 
> 1. 补全翻译服务的语言自动检测功能，如果是阿里翻译，就要好处理一些，它好像有语言检测的接口，而 openai 就难办一些，需要其一些高级的功能，工作量不小，还好 open AI TTS 不需要提供语言就可以播放。
> 2. 本地检测语言，这个我也有研究过，可以实现，但这是个优先级较低的任务，近期还不考虑。
> 
> 综上所述，如果你使用的是阿里翻译，近期内你的需求应该是可以得到解决的， open AI 的我就无法保证了，要么硬等，要么使用 open AI TTS。而本地语言检测，这个就是遥遥无期了，精力有限，任务还很多，而我又无法全身心投入到这上面来。

非常感谢, 我目前正好使用的是阿里翻译, 如果功能实现在我能力范围之内, 也许我可以尝试提交pr

**Comment by YiiGuxing** [comment]
> > > > TTS 服务一般需要提供文本的语言，因此没有语言无法播放，如果你希望没有语言也可以播放，可以考虑 open AI TTS.
> > > 
> > > 
> > > 那能否提供默认来源语种选项而不是指定auto呢? 以前的版本我记得是可以设置成默认为文本是某个语种
> > 
> > 
> > 你遇到这个问题的根本原因是你所使用的翻译服务不提供语言自动检测功能所导致的。如果默认指定源语言则会带来更大的问题——无法方便地在两种语言这间自由翻译。 对于这个问题，有两个方式可以解决：
> > 
> > 1. 补全翻译服务的语言自动检测功能，如果是阿里翻译，就要好处理一些，它好像有语言检测的接口，而 openai 就难办一些，需要其一些高级的功能，工作量不小，还好 open AI TTS 不需要提供语言就可以播放。
> > 2. 本地检测语言，这个我也有研究过，可以实现，但这是个优先级较低的任务，近期还不考虑。
> > 
> > 综上所述，如果你使用的是阿里翻译，近期内你的需求应该是可以得到解决的， open AI 的我就无法保证了，要么硬等，要么使用 open AI TTS。而本地语言检测，这个就是遥遥无期了，精力有限，任务还很多，而我又无法全身心投入到这上面来。
> 
> 非常感谢, 我目前正好使用的是阿里翻译, 能否指示下我应该如何实现呢? 如果功能实现在我能力范围之内, 也许我可以尝试提交pr

其实也很简单，只需要在 `AliTranslator.kt` 的 60 行前添加调用检测目标文本语言API获取检测结果并作为翻译的源语言参数继续翻译即可： https://github.com/YiiGuxing/TranslationPlugin/blob/f2ae155665345e3d892a9890ad7d1399dc9d93fd/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/ali/AliTranslator.kt#L60

如果急用，你可以自己添加实现代码自己编译先暂时使用着，等着我后续的正式版本。如果你想要提交PR，请提交到 [v3.6/next](https://github.com/YiiGuxing/TranslationPlugin/tree/v3.6/next) 分支。
