### ISSUE TITLE
能不能加一个编辑器全选后文档注释翻译的功能呢

### ISSUE THREAD

**Issue by Super3Windcloud** [YiiGuxing/TranslationPlugin#5852]
### Feature/Enhancement Description

能不能加一个编辑器全选后文档注释翻译的功能呢

### Proposed Solution

能不能加一个编辑器全选后文档注释翻译的功能呢

### Additional Information

能不能加一个编辑器全选后文档注释翻译的功能呢

**Comment by YiiGuxing** [comment]
Merged into #1760
