### ISSUE TITLE
国际化，翻译strings.xml 或者 json 文件到其他语言

### ISSUE THREAD

**Issue by W-quan** [YiiGuxing/TranslationPlugin#5857]
### 需求/建议描述

参考： [AndroidLocalizePlugin](https://github.com/Airsaid/AndroidLocalizePlugin)

### 建议的解决方案

参考： [AndroidLocalizePlugin](https://github.com/Airsaid/AndroidLocalizePlugin)

**Comment by YiiGuxing** [comment]
目前还暂不考虑添加此类的功能。
