### ISSUE TITLE
建议插件支持自动去掉某些字符功能.

### ISSUE THREAD

**Issue by wuweijian1997** [YiiGuxing/TranslationPlugin#586]
### Problem Description
建议插件支持自动去掉某些字符功能.例如去掉 / [ ] 等字符.
很多英文源码都是类似一下格式
```
// abaabaaba
// abaabaabab
// abababab [ aaa ]ab
```
如果我想翻译这段源码,里面夹杂着//挺影响阅读.要是用户自己手动去掉也是很麻烦的一件事,我看英文中也很少用到 / [ ]等字符,个人觉得去掉不影响阅读,或开放一个替换的配置文件给用户,可以手动设置替换掉翻译字符串中的某些字符

**Comment by YiiGuxing** [comment]
设置页面有根据正则表达式去除的
