### ISSUE TITLE
快速文档实时翻译将中文翻译成英文

### ISSUE THREAD

**Issue by EmptyDreams** [YiiGuxing/TranslationPlugin#587]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

`快速文档实时翻译`功能会把中文文档翻译成英文，英文翻译成中文，希望可以加设置来控制一下，不翻译中文文档。

**Comment by YiiGuxing** [comment]
可以在快速文档窗口使用快捷键切换翻译状态，详情请看README文件
