### ISSUE TITLE
Translation error in the number range in the following image

### ISSUE THREAD

**Issue by Vallenbo** [YiiGuxing/TranslationPlugin#5879]
### 📝 问题描述

Translation error in the number range in the following image
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63105184/f11415e3-5ac0-4724-a141-eabe50d58ac0)
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/63105184/9c223198-837b-4db9-9c1d-180e553e547d)

### 🏷 插件版本

3.6.2

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
GoLand 2024.1.4
Build #GO-241.18034.61, built on June 21, 2024
授权给 fuzzes ally
您有此版本的永久回退许可证。
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 16
```

**Comment by YiiGuxing** [comment]
这是翻译服务提供商提供的翻译结果，插件是无法识别和修正的。
