### ISSUE TITLE
翻译后朗读原文

### ISSUE THREAD

**Issue by 2832607827** [YiiGuxing/TranslationPlugin#5896]
### 需求/建议描述

如何翻译后立即朗读英文,翻译后都要点一下检测语言->英文->才能播放播放
![1](https://github.com/YiiGuxing/TranslationPlugin/assets/144209446/f9bf77f6-3d01-48bc-9817-f4624ed90a45)

### 建议的解决方案

111

**Comment by YiiGuxing** [comment]
翻译后自动播放TTS需要勾选以下的选项：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/3398999e-3f29-4274-b163-2cca6ea1f437)

但前提是要播放的文本有确定的语言，可暂时使用其他的翻译引擎，阿里翻译后面会添加语言的检测，到那时才能用，或者使用openai tts，它不需要有确定的语言就可以播放。

**Comment by YiiGuxing** [comment]
下一版本阿里翻译将可以使用此功能。
