### ISSUE TITLE
idea全屏状态下打开Translation会卡死

### ISSUE THREAD

**Issue by LOTHL** [YiiGuxing/TranslationPlugin#591]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
idea全屏状态下插件会卡死，idea也会卡住
### 问题描述
进入全屏打开插件，插件也会以全屏状态打开，而且不能输入内容，关不掉，也无法缩小，idea也会卡住

### 环境 & 错误日志
- 插件版本: 2.9.2
- IDE版本: 2020.2.3
- 操作系统版本: MacOS11

**Comment by YiiGuxing** [comment]
我在Windows上无法复现，麻烦你提供一下屏幕截图和idea日志文件，谢谢！
idea日志文件获取方法：主菜单->Help->Show Log in Explorer->idea.log（先打开日志目录，删除log文件后，再进行操作）
