### ISSUE TITLE
android studio 4.1  out of commission

### ISSUE THREAD

**Issue by jingkais** [YiiGuxing/TranslationPlugin#592]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by jingkais** [comment]
android studio 在商店中无法获取

**Comment by YiiGuxing** [comment]
android studio 4.1是可以从插件全局仓库中获取的，可能是网络问题加载不出来，可以多试几次。

**Comment by jingkais** [comment]
nice !我搭了梯子就找到了
