### ISSUE TITLE
自定义模型与URL

### ISSUE THREAD

**Issue by hu-1996** [YiiGuxing/TranslationPlugin#5925]
### 需求/建议描述

现在市面上已经有免费的大模型(比如siliconflow家的siliconcloud)可以使用，但是需要填写三方的URL和模型名字，三方模型符合openai规范

### 建议的解决方案

建议可以自己填写URL，模型名字，api key

**Comment by YiiGuxing** [comment]
> 同问，想使用 deepseek 的 API 进行翻译，发现无法自定义模型名称

下个版本就有了，已经在开发了。

**Comment by YiiGuxing** [comment]
合并至 #5276

**Comment by YiiGuxing** [comment]
阶段性版本已完成，欢迎抢先体验：#6235
