### ISSUE TITLE
文档说的【插件配置页面】在哪里呀

### ISSUE THREAD

**Issue by livem** [YiiGuxing/TranslationPlugin#593]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题描述
- http://yiiguxing.github.io/TranslationPlugin/updates.html
```
Quick Documentation 翻译选项是默认开启的，如果你想关闭此选项，可到在**插件配置页面**进行关闭。
```
IDEA 插件的配置页面，在哪里呢？找了很久找不着，求教，谢谢~

**Comment by YiiGuxing** [comment]
<img width="576" alt="capture_20201112002641632" src="https://user-images.githubusercontent.com/10737066/98837589-1a42d980-247e-11eb-87da-aa1d7ae3d541.png">

**Comment by livem** [comment]
[http://yiiguxing.github.io/TranslationPlugin/updates.html](http://yiiguxing.github.io/TranslationPlugin/updates.html)

最好把截图粘贴到上述新手指导文档里面，谢谢啦~

**Comment by YiiGuxing** [comment]
> http://yiiguxing.github.io/TranslationPlugin/updates.html
> 
> 最好把截图粘贴到上述新手指导文档里面，谢谢啦~

@livem  下个版本的设置页面的入口在主UI显眼的地方，应该不会再出现找不到的情况了。。。

**Comment by livem** [comment]
赞赞👍




With kind regards,
-------------------------------------------------------------
liveM


在2020年11月14日 10:16，Yii.Guxing<notifications@github.com> 写道：

http://yiiguxing.github.io/TranslationPlugin/updates.html

最好把截图粘贴到上述新手指导文档里面，谢谢啦~

@livem 下个版本的设置页面的入口在主UI显眼的地方，应该不会再出现找不到的情况了。。。
