### ISSUE TITLE
没看懂这两个选项怎么操作 , 可以演示一下吗

### ISSUE THREAD

**Issue by Super1Windcloud** [YiiGuxing/TranslationPlugin#5937]
### 需求/建议描述

![image](https://github.com/user-attachments/assets/4bc0cd04-0425-4bd0-a645-c94ab171de76)

### 建议的解决方案

![image](https://github.com/user-attachments/assets/4bc0cd04-0425-4bd0-a645-c94ab171de76)

**Comment by YiiGuxing** [comment]
1. 一次翻译文本过多的时候会折叠
2. 翻译后自动朗读，老外机翻回去的，没注意到。
