### ISSUE TITLE
单词本希望添加全选删除功能

### ISSUE THREAD

**Issue by heroPool** [YiiGuxing/TranslationPlugin#594]
你好，单词本希望添加全选删除功能，导入单词文档格式希望说明下

**Comment by heroPool** [comment]
> 你好，单词本希望添加全选删除功能，导入单词文档格式希望说明下

**Comment by YiiGuxing** [comment]
单词本多选删除功能将在 [v3.0](https://github.com/YiiGuxing/TranslationPlugin/milestone/14) 得到支持， 全选可使用 `Ctrl+A` 快捷键。
