### ISSUE TITLE
使用自定义openai接口翻译时候会把英文翻译成西班牙文

### ISSUE THREAD

**Issue by GongNanyue** [YiiGuxing/TranslationPlugin#5941]
### 📝 问题描述

<img width="385" alt="image" src="https://github.com/user-attachments/assets/15d67eb4-1184-4c76-b4a8-0a2c831aa316">
是不是系统提示词错误 
对于沉浸式翻译插件使用相同的自定义api可以正确翻译成中文
api网站是https://a.chat-api.cn/

### 🏷 插件版本

3.6.4

### 🔁 翻译引擎

全部

### 💻 IDE及运行环境

```plain text
PyCharm 2024.1.4 (Professional Edition)
Build #PY-241.18034.82, built on June 25, 2024
授权给 
订阅有效期至 2024年12月12日。
For educational use only.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.zh (241.271)
  com.github.copilot (1.5.14.6008)
  cn.yiiguxing.plugin.translate (3.6.4)
```

**Comment by YiiGuxing** [comment]
我这边正常的。。。。

![image](https://github.com/user-attachments/assets/2e30311c-e17d-4890-b502-d75af9f4406d)


我用的是 aihubmix 的，同一个提示词，为什么会这样我就不清楚了。后面支持自定义提示词应该就会好一点吧。
