### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by dojeee** [YiiGuxing/TranslationPlugin#5945]
### 📝 Issue Description

老是Error，切换任何源都不行。

![image](https://github.com/user-attachments/assets/df8aa6e4-678a-450b-8d32-50538f2a4039)

### 🏷 Plugin Version

plugin : 3.5.6

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
Idea : 2023.3.7 (Ultimate Edition)
OS : Ubuntu 22.04
```

**Comment by YiiGuxing** [comment]
检查一下是不是代理的问题？

**Comment by YiiGuxing** [comment]
如果用的是微软翻译，尝试清除所有代理设置，微软翻译不需要代理

**Comment by YiiGuxing** [comment]
最好还是升级一下插件！

**Comment by dojeee** [comment]
Change VM options config:

`-Djsse.enableSNIExtension=false  ------------>  -Djsse.enableSNIExtension=true`
 
![image](https://github.com/user-attachments/assets/f1b99b4d-9982-4328-a50a-6461367c160f)
