### ISSUE TITLE
DeepL 新增翻譯 繁體中文

### ISSUE THREAD

**Issue by YunoLiu0202** [YiiGuxing/TranslationPlugin#5947]
### 需求/建议描述

DeepL 新增翻譯主要語言 Chinese (traditional) - (ZH-HANT)

### 建议的解决方案

![image](https://github.com/user-attachments/assets/5b7d05bb-1597-47be-9a3c-4b242e37963f)

### 附加信息

https://www.deepl.com/zh/blog/deepl-translator-now-supports-traditional-chinese
https://developers.deepl.com/docs/resources/supported-languages

**Comment by YiiGuxing** [comment]
👌
