### ISSUE TITLE
继上个关闭的issue 

### ISSUE THREAD

**Issue by Super1Windcloud** [YiiGuxing/TranslationPlugin#5948]
### 需求/建议描述

![image](https://github.com/user-attachments/assets/fd3c073f-8a5b-43c8-83c2-706f4cc7265c)

你代码这里的逻辑是 已经经过翻译后的text ,下一步就是替换原文本 , 所以经过我的测试, 在替换之前把上面的这些字符替换,就能够正常渲染的 , 且试无妨 ,老哥信我一次 , 就是部分中文字符导致渲染异常的 , markdown除了汉字其他都是英文符号, 按照上面的规则 replace一下很简单的 , 替换之前返回当前光标所在文件的文件名, 然后正则匹配是否是markdown后缀
```kotlin
fun getCurrentFile(project: Project): VirtualFile? {
    // 获取当前打开的编辑器
    val editor = FileEditorManager.getInstance(project).selectedEditor?.editor ?: return null
    // 获取编辑器中当前打开的文件
    return editor.virtualFile.name
}
import java.util.regex.Pattern

val pattern = Pattern.compile(".*\\.md$") 
```
后面就是 text= text.replace( ) ,中文符号我这里打不出来  , html可以不用管, 应该没有多少人会在markdown里面用html 

### 建议的解决方案

后面就是 text= text.replace( ) ,中文符号我这里打不出来 
判断当前editor.selectionRange 所在文件名是否满足 *.md , 满足则对text 进行text.replace()
替换规则有
1- 空字符串替换或者注释掉text所有存在的 html元素
2- 替换所有 中文 '）' '(' 为 英文 括号
3 - 连续三个单引号字符 ''' 替换为 ``` JavaScript模板字符串那个符号,
4 - 中文冒号: 替换为英文的:
 , html可以不用管, 应该没有多少人会在markdown里面用html  ,老哥考虑一下,  请相信我 , 没什么工作量的

**Comment by YiiGuxing** [comment]
我知道这样做非常简单，实现起来毫不费力，最终的效果也不错，但是如此粗野的方式还是接受不能的。在我的计划中，在4.0版本将会提供第三方拓展的功能，向第三方提供翻译能力，到时候您可以轻易使用插件提供的翻译功能拓展出自己需要的功能。在此之前您还是暂时自己编译使用吧，待到4.0版本发布，您就只需要维护自己拓展出的部分功能即可。
