### ISSUE TITLE
Too many requests 错误

### ISSUE THREAD

**Issue by angelo-13** [YiiGuxing/TranslationPlugin#595]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
访问频率过高，请稍候再试，或者更换其他家的翻译服务
