### ISSUE TITLE
文本翻译功能没了

### ISSUE THREAD

**Issue by afsfge** [YiiGuxing/TranslationPlugin#596]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
![image](https://user-images.githubusercontent.com/17295616/100225283-f0e37c80-2f58-11eb-801b-b278305710d9.png)

插件最新版（2.9.2），发现以上功能没有了，我记得之前idea右上角是有一个橙色的图标的，现在就一个蓝色的了

![image](https://user-images.githubusercontent.com/17295616/100225658-841cb200-2f59-11eb-9afd-d55f1f4369ba.png)

![image](https://user-images.githubusercontent.com/17295616/100225386-17a1b300-2f59-11eb-97d5-d352b2d5364b.png)

![image](https://user-images.githubusercontent.com/17295616/100225398-1d979400-2f59-11eb-9ac1-d06da9ad7b0f.png)

**Comment by YiiGuxing** [comment]
只是导航栏去除掉了，在主工具栏上还有的：
![image](https://user-images.githubusercontent.com/10737066/100226801-343eea80-2f5b-11eb-8ffc-419138e832d9.png)
如果想要在导航栏恢复该图标，可以在菜单设置里进行添加。不过我认为已经没有必要了，因为即将发布的新版本完全去除了这个功能，而代替的新的功能将会更方便好用。敬请期待！

**Comment by afsfge** [comment]
好嘞
