### ISSUE TITLE
老哥, 我现在有个完美翻译想法  

### ISSUE THREAD

**Issue by Super1Windcloud** [YiiGuxing/TranslationPlugin#5962]
### Feature/Enhancement Description

 可以对markdown文件 使用 pandoc  , marked , showdownjs,  Flexmark-Java等库把 markdown  转换为html然后递归遍历所有子元素的内容,所有存在内容则进行翻译并替换 , 最后将html重新转换为markdown,拿到返回值替换原文本 

### Proposed Solution

 可以对markdown文件 使用 pandoc  , marked , showdownjs,  Flexmark-Java等库把 markdown  转换为html然后递归遍历所有子元素的内容,所有存在内容则进行翻译并替换 , 最后将html重新转换为markdown,拿到返回值替换原文本

**Comment by YiiGuxing** [comment]
其实也没那么复杂，因为IDE已经将 markdown 文档解析好了的，识别文档内容并不是什么难事。但这一功能与我最初的理念相冲突，我并不打算在插件中集成对某一种文档进行特殊化地处理的功能，这些在我的计划中是要交给插件的子扩展（子插件）来处理的。这就是插件下一步的应用框架，也是我下一步要做的工作，等这一部分的工作完成了，那大家都可以对插件进行扩展，加入自己需要的功能。所以，对于不破坏这个应用框架的功能需求我会酌情考虑，反之则不会。而你的需求本应该是属于子扩展（子插件）的功能范畴，是新新框架发布后才能考虑的。所以这里还是不能采纳你的需求。

另外告诉你一个事，如果你正在实现一个自己使用的话，也不用你提供的思路上的那么麻烦，因为除了百度翻译，其他翻译是能够直接翻译 HTML 文档的，处理流程可简化为：`markdown` -> `HTML` -翻译-> `翻译后的HTML` -> `markdown`，希望对你有用。
