### ISSUE TITLE
IDEA 2016.2    选择整行文本进行翻译，出现Dialog被撑变形情况，如图

### ISSUE THREAD

**Issue by shishifanbuxie** [YiiGuxing/TranslationPlugin#6]
![image](https://cloud.githubusercontent.com/assets/8510150/17392815/83036840-5a52-11e6-98cc-5c8f5e264452.png)

**Comment by YiiGuxing** [comment]
@shishifanbuxie 感谢反馈，有时间我看一下，在暗色的主题上是正常的，你可以先用着暗色的主题。

**Comment by YiiGuxing** [comment]
已修复: [commit db1aed7](https://github.com/YiiGuxing/TranslationPlugin/commit/db1aed703eef245603140313886e78c28eacf35f)
@shishifanbuxie
