### ISSUE TITLE
离线使用报TTK异常，之前可以离线使用，突然就TTK异常了

### ISSUE THREAD

**Issue by huanyue6660** [YiiGuxing/TranslationPlugin#600]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
TTK需要一个小时更新一次
