### ISSUE TITLE
按 ctril + shift + Y 自动翻译后，点击空白处弹框没有消失，变成了半透明，重启idea就没问题了

### ISSUE THREAD

**Issue by xiaobucvg** [YiiGuxing/TranslationPlugin#601]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
烦请提供重现步骤，谢谢
