### ISSUE TITLE
说真的最近更新的一版感觉改变了太多，不喜欢

### ISSUE THREAD

**Issue by moon-util** [YiiGuxing/TranslationPlugin#603]
翻译的时候目标语言一直都是中文，输入了中文需要再返回一遍吗？自动监测应该检测到输入中文，自动翻译成英文，检测到输入英文应该自动翻译成中文，而且应该不用任何设置默认就是这样；

**Comment by YiiGuxing** [comment]
哈哈，应该是修改太多了，把这个给搞没了，下个版本给弄回来。。。。

**Comment by RinOrz** [comment]
+1，以前是可以中文自动翻译英文，英文自动翻译中文的，现在还要切换，好麻烦

**Comment by mzzsfy** [comment]
现在这个版本ui对于格式保留没以前友好吧?我是感觉以前的界面高大上,现在跟其他软件没啥区别了,还有对原文默认折叠超级好评

**Comment by YiiGuxing** [comment]
。。。。
之前的UI对输入太不友好了，现在的UI就是为了解决这个问题的，只是细节上的处理没有做到位，这是我们的问题，我们会持续优化改进的，请给我们一点时间。
再说了，现在这套UI的设计是 **JetBrains** 官方设计并实现的，你们怎么能质疑权威呢？！[手动滑稽]

**Comment by mzzsfy** [comment]
> 。。。。
> 之前的UI对输入太不友好了，现在的UI就是为了解决这个问题的，只是细节上的处理没有做到位，这是我们的问题，我们会持续优化改进的，请给我们一点时间。
> 再说了，现在这套UI的设计是 **JetBrains** 官方设计并实现的，你们怎么能质疑权威呢？！[手动滑稽]

但是更low了.不是吗?

**Comment by YiiGuxing** [comment]
> > 。。。。
> > 之前的UI对输入太不友好了，现在的UI就是为了解决这个问题的，只是细节上的处理没有做到位，这是我们的问题，我们会持续优化改进的，请给我们一点时间。
> > 再说了，现在这套UI的设计是 **JetBrains** 官方设计并实现的，你们怎么能质疑权威呢？！[手动滑稽]
> 
> 但是更low了.不是吗?

个人觉得到是挺好的，这与每个人的喜好有关，我们当然无法满足所有人，这之中我们肯定会有所取舍。

**Comment by RinOrz** [comment]
UI感觉还好啊，谷歌翻译UI也这样，挺好的，主要就是功能，比以前差了好多

**Comment by YiiGuxing** [comment]
> UI感觉还好啊，谷歌翻译UI也这样，挺好的，主要就是功能，比以前差了好多

功能性确实是差了好多，这个必须承认，我们会改进的，只是需要点时间。

**Comment by mzzsfy** [comment]
ui没问题，只是变low了，没有说不好

> UI感觉还好啊，谷歌翻译UI也这样，挺好的，主要就是功能，比以前差了好多

**Comment by YiiGuxing** [comment]
如果有好的建义，欢迎到[讨论版块](https://github.com/YiiGuxing/TranslationPlugin/discussions)提出，大家一起讨论。
