### ISSUE TITLE
在源码页面鼠标放在注释上鼠标右键没以前的翻译按钮，需要鼠标选中文本内容再按快捷键翻译，如果源码注释过长很不方便

### ISSUE THREAD

**Issue by EmptyKYP** [YiiGuxing/TranslationPlugin#604]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
右键文档翻译已经被“快速文档实时翻译”替换掉了，对文档的翻译你可以在使用 `Ctrl+Q` 查看文档时，如果这时文档没有被翻译，则使用 `Ctrl+Shift+Y` 进行翻译文档，再按一次关闭翻译：
![1](https://user-images.githubusercontent.com/10737066/101300532-e1c1d000-3870-11eb-9705-a7ff1fddac60.gif)

**Comment by juyss** [comment]
这样做需要两步,以前直接右键选择就可以了,感觉不如之前方便,这样的改变是有其他的用意么?

**Comment by YiiGuxing** [comment]
> 这样做需要两步,以前直接右键选择就可以了,感觉不如之前方便,这样的改变是有其他的用意么?

@juyss 不是两步，在快速文档窗口上使用 `Ctrl+Shift+Y` 这个操作是一个开关操作，按一次打开，再按一次关闭这样，打开之后，以后你每 查看文档它都会自动翻译，直到你把它关掉。之前的右键文档翻译由于实现过于复杂，而且仅能在有限的几种语言上使用，而现在的这种方式理论上没有语言的限制。另外之前的方式只能在注释块源码内使用，使用范围很小，而现在的方式，只要你能看到文档，就能随时翻译，没有范围限制。

**Comment by brickmanli** [comment]
> > 这样做需要两步,以前直接右键选择就可以了,感觉不如之前方便,这样的改变是有其他的用意么?
> 
> @juyss 不是两步，在快速文档窗口上使用 这个操作是一个开关操作，按一次打开，再按一次关闭这样，打开之后，以后你每 查看文档它都会自动翻译，直到你把它关掉。之前的右键文档翻译由于实现过于复杂，而且仅能在有限的几种语言上使用，而现在的这种方式理论上没有语言的限制。另外之前的方式只能在注释块源码内使用，使用范围很小，而现在的方式，只要你能看到文档，就能随时翻译，没有范围限制。`Ctrl+Shift+Y`

可大多时候是去源码里面看文档，而不是使用`Ctrl+Q`去看文档。
如果这样，那源码里面去看翻译文档，应该咋弄好呢？

**Comment by YiiGuxing** [comment]
> > > 这样做需要两步,以前直接右键选择就可以了,感觉不如之前方便,这样的改变是有其他的用意么?
> > 
> > 
> > @juyss 不是两步，在快速文档窗口上使用 这个操作是一个开关操作，按一次打开，再按一次关闭这样，打开之后，以后你每 查看文档它都会自动翻译，直到你把它关掉。之前的右键文档翻译由于实现过于复杂，而且仅能在有限的几种语言上使用，而现在的这种方式理论上没有语言的限制。另外之前的方式只能在注释块源码内使用，使用范围很小，而现在的方式，只要你能看到文档，就能随时翻译，没有范围限制。`Ctrl+Shift+Y`
> 
> 可大多时候是去源码里面看文档，而不是使用`Ctrl+Q`去看文档。
> 如果这样，那源码里面去看翻译文档，应该咋弄好呢？

@brickmanli 在源码里你一样可以使用`Ctrl+Q`，两者效果都一样啊，只是打开姿势不一样而已嘛。

**Comment by 937624219** [comment]
希望能把这个用法加入提示,不然一直不知道

**Comment by YiiGuxing** [comment]
@937624219 这个不好做提示吧，强行主动提示体验可不好。只能在版本发行说明（what's new）里做说明，这个在版本升级的时候已经强制主动弹出过一次的，如果看了这个说明的，一般都能知道这个用法的。建议功能性版本升级的时候都看一下版本发行说明。

**Comment by RinOrz** [comment]
@YiiGuxing 能否提供设置按钮加回此功能？我觉得在大部分情况下我可能都不是很想完全翻译文档，而是在某些时候看不懂了才直接翻译某段

**Comment by YiiGuxing** [comment]
#620

**Comment by YiiGuxing** [comment]
> @YiiGuxing 能否提供设置按钮加回此功能？我觉得在大部分情况下我可能都不是很想完全翻译文档，而是在某些时候看不懂了才直接翻译某段，以前那样右键文档部分直接点击文档翻译item就好了，而不需要放到文档上面等弹窗出来再按下繁琐的快捷键，这样属实有点不方便

@RinOrz  文档的右键翻译也是完全翻译文档的，如果你打开了自动翻译就不需要再按快捷键的。

**Comment by nthpermanent** [comment]
这个改版真的很难用，我是mac用户，你说的快捷键我都没法用，ctrl-q对应mac中是什么？Keymap-Tranlationz中的快捷键我都试过也不能翻译文档。
正常用户很少会关注插件升级说明，3.0版本用户必须找到这个github页面才会用文档翻译，不麻烦吗？

**Comment by YiiGuxing** [comment]
@nthpermanent :grinning: 老铁，说明你对IDE的了解不够啊，我说的主要不是Ctrl-Q，是查看文档快捷键Ctrl-Q，这个不是插件的快捷键，是IDE查看文档的快捷键，mac上的这个快捷键我也不知道啊。这个快捷键应该是基本快捷键吧，查看文档都要用到。至于升级日志。。。呃。。。这个就是一个使用说明书，都强行弹出了，体验都不太友好了，这都不看一下的话，那我可真是没辙了。。。。:joy:

**Comment by zzuhkp** [comment]
> 这个改版真的很难用，我是mac用户，你说的快捷键我都没法用，ctrl-q对应mac中是什么？Keymap-Tranlationz中的快捷键我都试过也不能翻译文档。
> 正常用户很少会关注插件升级说明，3.0版本用户必须找到这个github页面才会用文档翻译，不麻烦吗？

楼上的老哥，Mac Idea 查看文档的快捷键是 `control + j`，可以先选中方法，然后按快捷键就会弹窗显示注释，如果按`control + command + u`就可以打开或者关闭快速文档翻译，如果打开了快速文档翻译，按`control + j`查看文档的时候就显示翻译后的文档了
