### ISSUE TITLE
Hindi fonts not working

### ISSUE THREAD

**Issue by balane** [YiiGuxing/TranslationPlugin#606]
After installing the latest update, when I try to translate English to Hindi the characters all show up as squares.

**Comment by YiiGuxing** [comment]
You need to configure the font on the plugin settings page.

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/101304505-56017100-387b-11eb-950b-7b08c9df19a4.png)
![image](https://user-images.githubusercontent.com/10737066/101304558-76313000-387b-11eb-8c20-66df2f2e4bc8.png)

**Comment by balane** [comment]
I’ve tried selecting several different fonts in that dialog and the translations are still not rendering.

**Comment by YiiGuxing** [comment]
I think you didn’t choose the right font.

**Comment by balane** [comment]
I’ve tried several fonts and none of them work for Hindi. All other languages work.

**Comment by YiiGuxing** [comment]
You can install the applicable fonts before trying.
