### ISSUE TITLE
请问下2018.3.3 要用哪个版本的TranslationPlugin 试了很多版本 都报错不兼容

### ISSUE THREAD

**Issue by zyk2891** [YiiGuxing/TranslationPlugin#607]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
2.9.1-192

https://plugins.jetbrains.com/plugin/8579-translation/versions

![image](https://user-images.githubusercontent.com/10737066/101304679-cf995f00-387b-11eb-9af6-73a0f064ab36.png)

**Comment by zyk2891** [comment]
> 2.9.1-192
> 
> https://plugins.jetbrains.com/plugin/8579-translation/versions
> 
> ![image](https://user-images.githubusercontent.com/10737066/101304679-cf995f00-387b-11eb-9af6-73a0f064ab36.png)

主要是idea的官网上不去 一直挂。。。所以才来github直接找

**Comment by zyk2891** [comment]
> 2.9.1-192
> 
> https://plugins.jetbrains.com/plugin/8579-translation/versions
> 
> ![image](https://user-images.githubusercontent.com/10737066/101304679-cf995f00-387b-11eb-9af6-73a0f064ab36.png)

好像不行啊。。还是报错 Fail to load plugin descriptor from file TranslationPlugin-2.9.1-192.zip

**Comment by YiiGuxing** [comment]
2.9.0-192、1.8.1 这些都不行？  试试从IDE内部的插件仓库安装嘛。

**Comment by zyk2891** [comment]
> 2.9.0-192、1.8.1 这些都不行？ 试试从IDE内部的插件仓库安装嘛。

都不行。。IDE内部插件仓库一直转圈打不开。。

**Comment by zyk2891** [comment]
> 2.9.0-192、1.8.1 这些都不行？ 试试从IDE内部的插件仓库安装嘛。
没找见1.8.1在哪哎

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/releases
