### ISSUE TITLE
translate and replace shows empty popup on IntelliJ IDEA 2024.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by marcelser** [YiiGuxing/TranslationPlugin#6072]
### 📝 Issue Description

1.) Select german text
2.) right click and select "Translate and Replace"
3.) you get a small empty popup

Interestingly just using "Translate" from the Context Menu instead of "Translate & Replace" works fine. There I get a popup where I can select the target language. The Replace one is broken. Maybe note that I'm using the new design of IntelliJ

### 🏷 Plugin Version

3.6.4

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.intellij.plugins.hcl (241.14494.313)
  aws.toolkit.core (3.26-241)
  com.perl5 (2024.1)
  org.jetbrains.plugins.go-template (241.14494.150)
  Pythonid (241.14494.314)
  com.github.copilot (1.5.20.6554)
  cn.yiiguxing.plugin.translate (3.6.4)
  aws.toolkit (3.26-241)
Kotlin: 241.14494.240-IJ
```

### 📋 Stacktrace

```plain text
This really breaks the plugins main functionality and makes it unusable and is a critical bug.
```

**Comment by YiiGuxing** [comment]
Thank you for your feedback. May I ask which language you have selected in the "Primary Language" option on the plugin settings page?
