### ISSUE TITLE
IntelliJ idea 2020.3 v3.0 文档翻译菜单(Translate Documentation)消失

### ISSUE THREAD

**Issue by liuyuan199303** [YiiGuxing/TranslationPlugin#608]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
IntelliJ idea 2020.3  TranslationPlugin v3.0 文档翻译菜单(Translate Documentation)消失
### 问题描述
更新TranslationPlugin v3.0后，文档翻译的菜单(Translate Documentation)消失，如下图:

![image](https://user-images.githubusercontent.com/20607146/101305316-57cc3400-387d-11eb-9d28-c3d826e118d4.png)

### 环境 & 错误日志
- 插件版本：TranslationPlugin v3.0
- IDE版：:IntelliJ idea 2020.3
- 操作系统版本: macOs Big Sur

**Comment by YiiGuxing** [comment]
#604

**Comment by YiiGuxing** [comment]
#620
