### ISSUE TITLE
spring源码文档无法翻译

### ISSUE THREAD

**Issue by chenhaoaixuexi** [YiiGuxing/TranslationPlugin#609]
## 问题详情
"文档翻译"功能对spring框架的源码注释没有响应，没有翻译出相关的中文内容。
可以翻译java自身库的源码注释

### 环境 & 错误日志
- 插件版本: 3.0
- IDE版本: 2020.1付费版
- 操作系统版本: macOs Catalina 10.15.6
![image](https://user-images.githubusercontent.com/32390273/101315353-5ad31e80-3895-11eb-9439-090ddda9bc11.png)
![image](https://user-images.githubusercontent.com/32390273/101315397-71797580-3895-11eb-8095-d7bf5125650a.png)

**Comment by YiiGuxing** [comment]
在我这边是可以翻译的，无法复现，目前还不知道是什么原因导致的，从翻译实现的原理来猜测，很有可能是你那边安装的插件，它们之中有的拦截了文档的生成过程，打破了翻译流程的完整性，导致无法翻译。不过这仅仅是个人猜测。

**Comment by Sowevo** [comment]
遇到了相同的问题,关注一下
已禁用了所有的其他插件
另外日志哪里找

## 环境 & 错误日志
插件版本: 3.0
IDE版本: 2020.3
操作系统版本: macOS Big Sur 11.1

**Comment by 13032820513** [comment]
同问，Spring相关源码无法自动翻译

**Comment by YiiGuxing** [comment]
> 同问，Spring相关源码无法自动翻译

@13032820513 你的也是macOS吗？

**Comment by jayele** [comment]
同上面 @Sowevo 基本一样，操作系统：macOS Big Sur 11.1。
我的现象：文档注释右键只有“Translate”, 没有出现之前翻译文档选项。

**Comment by josways** [comment]
> 同上面 @Sowevo 基本一样，操作系统：macOS Big Sur 11.0.1。
> 我的现象：文档注释右键只有“Translate”, 没有出现之前翻译文档选项。

#620
