### ISSUE TITLE
打开翻译界面，CPU 占用率突然上升

### ISSUE THREAD

**Issue by Monster0303** [YiiGuxing/TranslationPlugin#610]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ x ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

重现问题的步骤。
![1](https://user-images.githubusercontent.com/40815364/101332715-9deebb00-38b0-11eb-8afa-e2c32deec956.png)

打开上面这个界面，即使什么都不做，cpu 也会突然飙升并一直占用率很高，风扇开始哇啦哇啦的转。。。

但是这个界面就不会出现这样的问题
![2](https://user-images.githubusercontent.com/40815364/101332755-b068f480-38b0-11eb-9c3c-284c32296f1f.png)

之前没有这样的问题，我经常即使不写代码，也会打开 pycharm 作为单词查询使用，这个软件太好用了，但是在这次更新后出现这个问题，这是大面积的问题吗？我该如何做？

谢谢！

### 环境 & 错误日志
- 插件版本: 3.0
- IDE版本: PyCharm 2020.3 (Community Edition)
- 操作系统版本: MAC 10.15.7

**Comment by YiiGuxing** [comment]
我在Windows上也重现了这个问题，虽然CPU占用率不是很高，我会尽快修复此问题，感谢你的反馈。

**Comment by Monster0303** [comment]
![截屏2020-12-08 下午2 38 38](https://user-images.githubusercontent.com/40815364/101449144-36de0e80-3963-11eb-9b95-90080c10d4e3.png)
还有这个，快捷键划词翻译时会在单词后边追加一个 `≈` 的符号，这个问题还挺明显的，你可以已经发现这个问题了，这样的话就忽略这条反馈吧，谢谢

**Comment by YiiGuxing** [comment]
> ![截屏2020-12-08 下午2 38 38](https://user-images.githubusercontent.com/40815364/101449144-36de0e80-3963-11eb-9b95-90080c10d4e3.png)
> 还有这个，快捷键划词翻译时会在单词后边追加一个 `≈` 的符号，这个问题还挺明显的，你可能已经发现这个问题了，这样的话就忽略这条反馈吧，谢谢

我在windows上并没有出现这个问题啊，能否录个屏给我看一下？

**Comment by YiiGuxing** [comment]
> ![截屏2020-12-08 下午2 38 38](https://user-images.githubusercontent.com/40815364/101449144-36de0e80-3963-11eb-9b95-90080c10d4e3.png)
> 还有这个，快捷键划词翻译时会在单词后边追加一个 `≈` 的符号，这个问题还挺明显的，你可能已经发现这个问题了，这样的话就忽略这条反馈吧，谢谢

会不会是快捷键输入的？  我这不有MacOS，重现不了 :(  。。。。。

**Comment by Monster0303** [comment]
> > ![截屏2020-12-08 下午2 38 38](https://user-images.githubusercontent.com/40815364/101449144-36de0e80-3963-11eb-9b95-90080c10d4e3.png)
> > 还有这个，快捷键划词翻译时会在单词后边追加一个 `≈` 的符号，这个问题还挺明显的，你可能已经发现这个问题了，这样的话就忽略这条反馈吧，谢谢
> 
> 会不会是快捷键输入的？ 我这不有MacOS，重现不了 :( 。。。。。

多谢提醒，原因是快捷键，我的快捷键是 option + 字母，会出现特殊字符，谢谢，这是我的问题
