### ISSUE TITLE
选择IDEA渲染后的文档的文字，右键后没有翻译菜单，按Ctrl+shift+Y也没有反应。

### ISSUE THREAD

**Issue by jimboomm** [YiiGuxing/TranslationPlugin#611]
@YiiGuxing 选择IDEA渲染后的文档的文字，右键后没有翻译菜单，按Ctrl+shift+Y也没有反应。
![image](https://user-images.githubusercontent.com/28443021/101568399-77926200-3a0d-11eb-905d-edb144545985.png)

_Originally posted by @jimboomm in https://github.com/YiiGuxing/TranslationPlugin/issues/474#issuecomment-741493920_

**Comment by jimboomm** [comment]
插件版本：3.0
IDEA版本：2020.3 
环境：windows 10

**Comment by brickmanli** [comment]
我也遇到了这个问题，今天更新了最新的版本，然后翻译文档的按钮就不见了。
只能使用 Ctrl+shift+Y 翻译，但是并不是文档翻译
插件版本：3.0
IDEA版本：2020.2.3
环境：windows 10

![image](https://user-images.githubusercontent.com/43296325/101710081-c7376300-3acb-11eb-8404-2f1fe4b22ca7.png)

**Comment by YiiGuxing** [comment]
> 我也遇到了这个问题，今天更新了最新的版本，然后翻译文档的按钮就不见了。
> 只能使用 Ctrl+shift+Y 翻译，但是并不是文档翻译
> 插件版本：3.0
> IDEA版本：2020.2.3
> 环境：windows 10
> 
> ![image](https://user-images.githubusercontent.com/43296325/101710081-c7376300-3acb-11eb-8404-2f1fe4b22ca7.png)

@brickmanli 你的问题和这个问题不是同一个问题，应该是这个：#608

**Comment by YiiGuxing** [comment]
如想获取最新进展或动态，请关注 #474

**Comment by YiiGuxing** [comment]
合并到 #474
