### ISSUE TITLE
convert to other languages无法正常翻译成想要的语言

### ISSUE THREAD

**Issue by hockgod520** [YiiGuxing/TranslationPlugin#612]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

我已使用收费的翻墙工具翻墙，并且保证翻墙工具开启；google正常访问
我使用在Android Studio 4.0上使用convert to other languages试图将英文翻译成法语、捷克语等语言。相应的strings.xml能正常生成，xml下也有对应的name生成，但是就是翻译文本时空的类似：	<string name="Nutrientintake"></string>

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by hockgod520** [comment]
插件版本：2.9.2
AndroidStudio 4.0

举例：<string name="save"></string>
生产的样式正确，内容为空

**Comment by YiiGuxing** [comment]
？？？
是不是提错地方了？我的插件并不提供`convert to other languages`的功能啊。。。  :-)

**Comment by hockgod520** [comment]
抱歉确实是搞错了，很抱歉打扰到你。
