### ISSUE TITLE
添加.h头文件文档翻译(rider)

### ISSUE THREAD

**Issue by mdddj** [YiiGuxing/TranslationPlugin#6137]
### 需求/建议描述

添加.h文件文档翻译
<img width="852" alt="image" src="https://github.com/user-attachments/assets/e974b1e7-a3b2-4d17-a364-7b51b7a123da">

### 建议的解决方案

添加翻译action

**Comment by xuhuanzy** [comment]
rider的文档翻译看下这个分支能不能用: https://github.com/xuhuanzy/TranslationPluginAdapt
如果用不了可以发个demo给我

**Comment by mdddj** [comment]
> rider的文档翻译看下这个分支能不能用: https://github.com/xuhuanzy/TranslationPluginAdapt 如果用不了可以发个demo给我

试了不太行,demo有2个G,可以新建一个UE5项目,用rider打开

**Comment by xuhuanzy** [comment]
非ue的api的文档翻译正常吗？

**Comment by mdddj** [comment]
> 非ue的api的文档翻译正常吗？

大佬这个不太清楚,我这好像不能索引纯c++的项目

**Comment by xuhuanzy** [comment]
正常使用
![image](https://github.com/user-attachments/assets/d6b18daa-16e8-4a71-979a-3a5b4339b312)

**Comment by xuhuanzy** [comment]
可能要优化下ue的输出, 不过我分支没几个在用的, 等星数多了再说吧
![image](https://github.com/user-attachments/assets/a571f388-4c71-4be0-9fa6-8e84d941b490)

**Comment by mdddj** [comment]
> 可能要优化下ue的输出, 不过我分支没几个在用的, 等星数多了再说吧 ![image](https://private-user-images.githubusercontent.com/90585805/371778343-a571f388-4c71-4be0-9fa6-8e84d941b490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzE4NzEsIm5iZiI6MTcyNzU3MTU3MSwicGF0aCI6Ii85MDU4NTgwNS8zNzE3NzgzNDMtYTU3MWYzODgtNGM3MS00YmUwLTlmYTYtOGU4NGQ5NDFiNDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAwNTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjUyY2YzMjNiZDUzYjhlZjNjNWJjZTAzZWI5NzBhMjFlYTRiMzJhYzdiOGMyMDUzODU3YmI3YWJjNDFmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PnLQcm_5KBB4vtx9pc-5CMmG0a-H2A0beLuC0QXCrto)

大佬太强了,刚刚试了下又可以了

**Comment by YiiGuxing** [comment]
合并至 #1986
