### ISSUE TITLE
UI优化

### ISSUE THREAD

**Issue by YiiGuxing** [YiiGuxing/TranslationPlugin#615]
![img](https://user-images.githubusercontent.com/10737066/102299096-5392cb80-3f8d-11eb-9fbd-1b41f7a3c555.png)

**Comment by MicalMMM** [comment]
老铁你这3.0的版本不好用啊，翻译不能自动识别语言和目标语言了，还有不能翻译注释文档了。

**Comment by YiiGuxing** [comment]
@MicalMMM 由于改得太多，很多问题没有注意到，后面慢慢优化回来，至于不能翻译注释文档，有相关的问题和讨论，你可以去看看。

**Comment by muxu-i** [comment]
请问下，怎么降级？ 这3.0真难用

**Comment by YiiGuxing** [comment]
> 请问下，怎么降级？ 这3.0真难用



@muxu-i  下载想用的版本，然后手动从本地磁盘安装即可。新版本我会慢慢优化的，请给我点时间啊。。。:sob: :sob: :sob: （PS：与主题无关的问题，请另外打开一个问题啊~~~  ）

**Comment by mzzsfy** [comment]
> > 请问下，怎么降级？ 这3.0真难用
> 
> @muxu-i 下载想用的版本，然后手动从本地磁盘安装即可。新版本我会慢慢优化的，请给我点时间啊。。。😭 😭 😭 （PS：与主题无关的问题，请另外打开一个问题啊~~~ ）

等新版,这版本真的没有上版本体验好
