### ISSUE TITLE
快把我的右键翻译文档，还给我啊~~~

### ISSUE THREAD

**Issue by shenbururen** [YiiGuxing/TranslationPlugin#616]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Additional Information

![image](https://user-images.githubusercontent.com/19234220/102459114-27a44280-4080-11eb-8346-91bf603fc45d.png)

**Comment by MJJKG5** [comment]
更新3.0后右键 Translate Documentation 消失

**Comment by YiiGuxing** [comment]
#620
