### ISSUE TITLE
什么时候可以支持2020.3 reader 模式的翻译，文档整篇的翻译也没有了，quick document 翻译貌似也消失了

### ISSUE THREAD

**Issue by newShiJ** [YiiGuxing/TranslationPlugin#617]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
reader 的文档系统、语法解析等和其他IDE是不一样的，它目前好像是在线生成的，所以有的功能无法使用。。。只能等待官方的支持。

**Comment by mzzsfy** [comment]
可以将原本的文档翻译整回来不?现在读源码又不是那么方便了

**Comment by newShiJ** [comment]
> 可以将原本的文档翻译整回来不?现在读源码又不是那么方便了

看了项目相关介绍，好像现在是靠快速文档翻译给替代了，不过确实觉得有文档整块的翻译读源码比较爽一点

**Comment by mzzsfy** [comment]
> > 可以将原本的文档翻译整回来不?现在读源码又不是那么方便了
> 
> 看了项目相关介绍，好像现在是靠快速文档翻译给替代了，不过确实觉得有文档整块的翻译读源码比较爽一点

确实少了那个感觉,ui改动也挺大的

**Comment by YiiGuxing** [comment]
如果觉得需要恢复“文档右键翻译”，可以到这里（#620）进行投票。

**Comment by mzzsfy** [comment]
> 如果觉得需要恢复“文档右键翻译”，可以到这里（#620）进行投票。

已经投了,每天要看好多源码,大段文档用快速翻译真的不太友好
