### ISSUE TITLE
请求替换谷歌翻译域名

### ISSUE THREAD

**Issue by Vixb1122** [YiiGuxing/TranslationPlugin#618]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
目前的translate.google.com和translate.google.cn在公司网络下经常翻译失败

### Proposed Solution
使用translate.googleapis.com替换上面两个域名，这个域名全球通用，不用挂梯子

### Additional Information
可以参考下划词翻译插件：
https://hcfy.limingkai.cn/log.html#v7-2-0
https://hcfy.limingkai.cn/log.html#v7-2-2
https://github.com/lmk123/crx-selection-translate
https://github.com/lmk123/crx-selection-translate/issues/797

**Comment by YiiGuxing** [comment]
现在用的就是translate.googleapis.com

**Comment by Vixb1122** [comment]
在android studio里面不能翻译，然后用谷歌插件能翻译

**Comment by YiiGuxing** [comment]
会不会是代理才导致不能翻译的？检查一下AS的代理设置。在IDEA里能翻译吗？

**Comment by Vixb1122** [comment]
我搜代码里面还有 translate.google.cn 和 translate.google.com，其实只使用 translate.googleapis.com 就够了。

![image](https://user-images.githubusercontent.com/17810492/102559966-16087c80-410c-11eb-8649-61025d2bf089.png)

https://github.com/YiiGuxing/TranslationPlugin/blob/fc102f9772038dea19e2023a9afad985a9c4b042/src/main/kotlin/cn/yiiguxing/plugin/translate/Constants.kt#L25-L26

https://github.com/YiiGuxing/TranslationPlugin/blob/b3fdd5460584cb8f29faf4046cfa0e0aca210e18/src/main/kotlin/cn/yiiguxing/plugin/translate/util/Http.kt#L8-L9

https://github.com/YiiGuxing/TranslationPlugin/blob/b3fdd5460584cb8f29faf4046cfa0e0aca210e18/src/main/kotlin/cn/yiiguxing/plugin/translate/util/Http.kt#L45-L54

没有开代理，我稍后抓包看下as插件翻译时域名是啥。

**Comment by YiiGuxing** [comment]
那个translate.google.com不是用来请求的，只是放到请求头里。translate.googleapis.com有时候还是访问不了，所以cn先留着。你发一下翻译失败的异常信息，分析一下应该就能知道什么原因了。
