### ISSUE TITLE
老哥,请求添加一个功能,  用于自动翻译当前激活标签页的所有英文文档和英文注释 

### ISSUE THREAD

**Issue by Super1Windcloud** [YiiGuxing/TranslationPlugin#6187]
### 需求/建议描述

老哥,请求添加一个功能,  用于自动翻译当前激活标签页的所有英文文档注释 

### 建议的解决方案

老哥,请求添加一个功能,  用于自动翻译当前激活标签页的所有英文文档注释 

### 附加信息

老哥,请求添加一个功能,  用于自动翻译当前激活标签页的所有英文文档注释

**Comment by YiiGuxing** [comment]
合并至 #1760
