### ISSUE TITLE
默认的快捷键设置为ctrl+shift+o，这个是更新引用常用的快捷键

### ISSUE THREAD

**Issue by piglingcn** [YiiGuxing/TranslationPlugin#6192]
### 需求/建议描述

默认的快捷键设置为ctrl+shift+o，这个是更新引用常用的快捷键，冲突了。

### 建议的解决方案

默认的快捷键设置为ctrl+shift+o，这个是更新引用常用的快捷键，或者设置别的不常用的

**Comment by YiiGuxing** [comment]
当初定快捷键的时候确实没有考虑到多个 IDE 产品上的，后面的就不好改了，再说本来就没有多少空闲的快捷键可用，就更不用说要考虑其他产品的了，没办法，不过还好这不快捷键你可修改、自定义的。
