### ISSUE TITLE
关于恢复右键文档翻译的投票

### ISSUE THREAD

**Issue by YiiGuxing** [YiiGuxing/TranslationPlugin#620]
我说，老铁们，在已经有快速文档实时翻译的情况下，我们真的还需要**右键文档翻译**这样的功能吗？

👍 ：必须恢复！立刻！马上！
👎 ：完全没有必要嘛~
👀 ：我就看看……

欢迎投票，欢迎讨论。

**Comment by josways** [comment]
我的文档翻译直接就没了快速翻译 功能也不生效。（Ctrl+Q）
Win 10
IDEA 2020.3.4
Translation 3.0

**Comment by josways** [comment]
> 我的文档翻译直接就没了快速翻译 功能也不生效。（Ctrl+Q）
> Win 10
> IDEA 2020.3.4
> Translation 3.0

找到原因了 这个功能貌似是默认关闭的？
![image](https://user-images.githubusercontent.com/30266923/103128509-a0367f00-46d0-11eb-86f7-543c15378cb1.png)

**Comment by YiiGuxing** [comment]
> > 我的文档翻译直接就没了快速翻译 功能也不生效。（Ctrl+Q）
> > Win 10
> > IDEA 2020.3.4
> > Translation 3.0
> 
> 找到原因了 这个功能貌似是默认关闭的？
> ![image](https://user-images.githubusercontent.com/30266923/103128509-a0367f00-46d0-11eb-86f7-543c15378cb1.png)

是的，你可以使用快捷键快速打开或者关闭

**Comment by yinsansui** [comment]
所以，解决办法是啥？怎么把这个功能打开呢。

**Comment by YiiGuxing** [comment]
@yinsansui 只能从代码上恢复

**Comment by YiiGuxing** [comment]
#628
