### ISSUE TITLE
为什么不能设置成英语翻译成中文？每次翻译中文还要再选择中文。

### ISSUE THREAD

**Issue by owenwong520** [YiiGuxing/TranslationPlugin#622]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

翻译设置的目标语言没有中文选项，这个翻译软件不是写给中国人用的吗？
### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
目标语言请在翻译界面进行选择。
