### ISSUE TITLE
在IDEA 2024.2.4 文档翻译不可用

### ISSUE THREAD

**Issue by Ajie528** [YiiGuxing/TranslationPlugin#6225]
### 📝 问题描述

1.设置微软翻译
2.主要语言设置中文（简体）
3.目标语言设置主要或者英语
4.把鼠标放到SDK的函数名中，出现的还是英文文档
5.鼠标右键进行文档翻译还是显示原文档都是英文，没有任何变化

### 🏷 插件版本

3.6.6

### 🔁 翻译引擎

微软翻译, 阿里翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Kotlin 插件: K2 模式(测试版)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4092M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  net.ashald.envfile (3.4.2)
  CMD Support (1.0.5)
  com.star.easydoc.easy-javadoc (4.3.1)
  ru.adelf.idea.dotenv (2024.2.1)
  org.jetbrains.android (242.23726.103)
  com.android.tools.design (242.23726.38)
  Dart (242.22855.32)
  com.localizely.flutter-intl (1.18.8-2024.2)
  izhangzhihao.rainbow.brackets.lite (1.2.0)
  com.alibabacloud.intellij.cosy (1.4.4)
  JRebelPlugin (2024.4.0)
  com.baomidou.plugin.idea.mybatisx (1.6.3)
  cn.yiiguxing.plugin.translate (3.6.6)
Kotlin: 242.23726.103-IJ
```

**Comment by YiiGuxing** [comment]
这是因为你开启了 Kotlin 的 K2 模式，K2 模式目前还不支持文档翻译，这个现在正在开发中，不出意外， 3.7 版本会得到支持。

**Comment by MiniFullC** [comment]
> 这是因为你开启了 Kotlin 的 K2 模式，K2 模式目前还不支持文档翻译，这个现在正在开发中，不出意外， 3.7 版本会得到支持。

如果不开启 K2 ，IDEA有严重的UI冻结BUG

[jetbrains issue: UI-Freezes](https://youtrack.jetbrains.com/issue/JBR-7768/UI-Freezes-After-Git-Update-Operation)

**Comment by YiiGuxing** [comment]
> > 这是因为你开启了 Kotlin 的 K2 模式，K2 模式目前还不支持文档翻译，这个现在正在开发中，不出意外， 3.7 版本会得到支持。
> 
> 如果不开启 K2 ，IDEA有严重的UI冻结BUG
> 
> [jetbrains issue: UI-Freezes](https://youtrack.jetbrains.com/issue/JBR-7768/UI-Freezes-After-Git-Update-Operation)

可先降级到 2024.2 版本，等正式发布后再升级，插件支持 k2 模式还需要一些时间。

**Comment by YiiGuxing** [comment]
合并至 #5981

**Comment by geekscloud** [comment]
> 这是因为你开启了 Kotlin 的 K2 模式，K2 模式目前还不支持文档翻译，这个现在正在开发中，不出意外， 3.7 版本会得到支持。

看来是出意外了哈哈哈哈, 3.7还未支持
