### ISSUE TITLE
微软 Edge TTS 报 403 错误

### ISSUE THREAD

**Issue by feng0945** [YiiGuxing/TranslationPlugin#6226]
### 📝 问题描述

点击播放音频报错 TTS 播放失败：Invalid status code received: 403 Status line: HTTP/1.1 403 Forbidden 

### 🏷 插件版本

3.6.6

### 🔁 翻译引擎

微软翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2024.1.3 (Ultimate Edition)
```

**Comment by YiiGuxing** [comment]
看来微软不希望我继续薅羊毛了。。。。

**Comment by zhang-zhonggui** [comment]
> 看来微软不希望我们继续薅羊毛了。。。。
请问未来还有什么可以代替的吗！或者有什么新的替代品之类的

**Comment by YiiGuxing** [comment]
还有，微软这个它只是在国内有问题。。。。我看看播放TTS的时候能不能用上代理，如果它后面不管国内外都无法使用，可能就得去除掉了，毕竟是非法掉用人家的接口。

**Comment by YiiGuxing** [comment]
试了一下 ChatTTS 生成太慢了。。。大家有没有可本地运行的开源 TTS 推荐的？

**Comment by bread1028** [comment]
是不是可以考虑加上字节的火山翻译，好像是免费的，就是不知道效果怎么样

**Comment by YiiGuxing** [comment]
> 是不是可以考虑加上字节的火山翻译，好像是免费的，就是不知道效果怎么样

@bread1028 火山翻译 不支持 HTML 翻译，这是我目前没有优先集成进插件的主要原因，将其优先降低了，4.0版本以后再考虑。

**Comment by javaController123** [comment]
不可以直接走用户的代理去链路Google吗？

**Comment by YiiGuxing** [comment]
> 不可以直接走用户的代理去链路Google吗？

没明白你的意思……

**Comment by YiiGuxing** [comment]
问题已解决： 09f9567deb0d4985c4deb93177ce477a926cb981

[TranslationPlugin-3.7.0-alpha.1.zip](https://github.com/user-attachments/files/17892716/TranslationPlugin-3.7.0-alpha.1.zip)

**Comment by xiaojun0502** [comment]
> 问题已解决： [09f9567](https://github.com/YiiGuxing/TranslationPlugin/commit/09f9567deb0d4985c4deb93177ce477a926cb981)
> 
> [TranslationPlugin-3.7.0-alpha.1.zip](https://github.com/user-attachments/files/17892716/TranslationPlugin-3.7.0-alpha.1.zip)
> 
> 版本讨论：#6235

这个东西怎么用

**Comment by YiiGuxing** [comment]
> > 问题已解决： [09f9567](https://github.com/YiiGuxing/TranslationPlugin/commit/09f9567deb0d4985c4deb93177ce477a926cb981)
> > 
> > [TranslationPlugin-3.7.0-alpha.1.zip](https://github.com/user-attachments/files/17892716/TranslationPlugin-3.7.0-alpha.1.zip)
> > 
> > 版本讨论：#6235
> 
> 这个东西怎么用

https://intellij-translation.yiiguxing.top/#/docs?id=installation
