### ISSUE TITLE
打开翻译页面IDEA的GPU占用率飙升，导致电脑温度快速上升。

### ISSUE THREAD

**Issue by RayeGong** [YiiGuxing/TranslationPlugin#623]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
打开翻译页面活动监视器里IDEA的GPU占用率飙升至40%，电脑温度由40度飙升至接近90度。

### 环境 & 错误日志
- 插件版本: 3.0
- IDE版本: IDEA 2020.2.3
- 操作系统版本: macOS Catalina 10.15.7

**Comment by YiiGuxing** [comment]
Duplicate: #610
