### ISSUE TITLE
搜索结果带音标就更好了

### ISSUE THREAD

**Issue by J-echo0722** [YiiGuxing/TranslationPlugin#624]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
音标带下的，只是有的查询没有，就没有显示了
