### ISSUE TITLE
翻译功能的例句是否考虑同时显示中文

### ISSUE THREAD

**Issue by ichtj** [YiiGuxing/TranslationPlugin#6240]
### 需求/建议描述

翻译一个单词后,下拉显示的单词例句有时候某个单词不理解,无法记忆他在这个句子中的整体意思

### 建议的解决方案

翻译功能的例句是否考虑同时显示中文

### 附加信息

翻译功能的例句是否考虑同时显示中文

**Comment by ichtj** [comment]
![image](https://github.com/user-attachments/assets/a260e12a-9c95-428d-b9c4-1da98352bb16)

**Comment by YiiGuxing** [comment]
有没有例句翻译要看翻译服务是否提供，谷歌翻译并没有提供，所以没有。面微软释放提供了，所以它有。
