### ISSUE TITLE
pycharm专业版2024.3csv文件的翻译

### ISSUE THREAD

**Issue by 11e11** [YiiGuxing/TranslationPlugin#6248]
### 📝 Issue Description

在**pycharm专业版2024.3.1**中安装了translation插件，但在pycharm中打开**csv**文件，选中其中一行的内容右键后没有翻译选项
在pycharm2022社区版安装translation插件后可以直接翻译csv文件中的内容

### 🏷 Plugin Version

3.6.7

### 🔁 Translation Engine(s)

All

### 💻 IDE and Operating Environment

```plain text
PyCharm 2024.3.1 (Professional Edition)
Build #PY-243.22562.180, built on December 11, 2024

For educational use only.
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 1024M
Cores: 8
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ideolog (222.3.2.0)
  cn.yiiguxing.plugin.translate (3.6.7)
```

**Comment by YiiGuxing** [comment]
如果你是在这个编辑器上的话，那么右键菜单应该是有的：
![Snipaste_2024-12-18_09-15-02.png](https://github.com/user-attachments/assets/88b10f98-32a0-4ca7-8424-a1c0d7d4b7a0)

如果是这个的话就只能通过快捷键操作（在在编辑单元格的时候）：
![Snipaste_2024-12-18_09-16-04.png](https://github.com/user-attachments/assets/d620a45f-0e5b-4e6c-a22f-1a52a65524fd)
