### ISSUE TITLE
idea插件升级后，使用麻烦了，想查找单词，本来一步的事，现在需要操作很多，还要自己去选择翻译的方式，以前的挺好用的，为什么要改

### ISSUE THREAD

**Issue by pbokai** [YiiGuxing/TranslationPlugin#627]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
目前正在对此做优化工作，请耐心等待。:confounded:

**Comment by YiiGuxing** [comment]
[v3.0.1](https://github.com/YiiGuxing/TranslationPlugin/milestone/19?closed=1)
