### ISSUE TITLE
插件界面闪退

### ISSUE THREAD

**Issue by zjslqshqz** [YiiGuxing/TranslationPlugin#629]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
平时Mac连接外接显示器工作，能正常弹出翻译插件界面。但是在没有外接显示器的时候，无法正常显示，插件界面闪退。
如下图：
![2021-01-01 21 21 20](https://user-images.githubusercontent.com/6870067/103439422-b962a100-4c77-11eb-849c-2aaaad9f1115.gif)

### 环境 & 错误日志
- 插件版本: 3.0.1
- IDE版本: phpStorm 2020.3
- 操作系统版本: Mac 10.15.7

**Comment by YiiGuxing** [comment]
这时候在窗口右下角应该有一个感叹号图标，点击可以获取错误信息，麻烦贴出来一下，谢谢

**Comment by YiiGuxing** [comment]
还有就是3.0版本是否能正常工件？

**Comment by zjslqshqz** [comment]
> 这时候在窗口右下角应该有一个感叹号图标，点击可以获取错误信息，麻烦贴出来一下，谢谢

并没有发生错误，没有感叹号，只要我接上外接显示器就能正常显示了。
而且，接上外接显示器，我把 phpStorm 界面，放在内置显示器，点开插件。插件界面会出现在外接显示器上。

**Comment by zjslqshqz** [comment]
> 还有就是3.0版本是否能正常工件？

一样的

**Comment by YiiGuxing** [comment]
@zjslqshqz 麻烦你帮忙测试一下问题是否得到修复，感谢！

[TranslationPlugin-3.0.2-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/5760420/TranslationPlugin-3.0.2-SNAPSHOT.zip)

**Comment by zjslqshqz** [comment]
> @zjslqshqz 麻烦你帮忙测试一下，看看问题是否得到修复，感谢！
> 
> [TranslationPlugin-3.0.2-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/5760420/TranslationPlugin-3.0.2-SNAPSHOT.zip)

正常了，可以正常显示了

**Comment by YiiGuxing** [comment]
:ok_hand: 晚上我把代码提交了。
