### ISSUE TITLE
Android studio 无法卸载

### ISSUE THREAD

**Issue by ChenXiaoYao407** [YiiGuxing/TranslationPlugin#637]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
无法卸载应该是IDE的问题，可以尝试多试几次，实在不行也可以到插件目录将插件相关文件删除即可。
