### ISSUE TITLE
在翻译替换的时候，希望增加常量名替换（字母全部大小，使用_分割）

### ISSUE THREAD

**Issue by yuandoudou928** [YiiGuxing/TranslationPlugin#639]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
*[x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin/commit/3a78254a13244b9a5bf120e7a0bf921c7e28a044
