### ISSUE TITLE
无法关闭

### ISSUE THREAD

**Issue by jinh97** [YiiGuxing/TranslationPlugin#641]
idea最新版2020.3点击翻译图标打开窗口后没办法关闭。使用2020.1试了一下，正常。
![8](https://user-images.githubusercontent.com/40655558/104400154-08200d00-558d-11eb-838f-b44055a1a562.png)
正常情况点击其它区域就应该关闭了

**Comment by YiiGuxing** [comment]
你应该是点了窗口右上角的固定窗口按钮了，这时候可以按ESC键关闭窗口

**Comment by jinh97** [comment]
确实好了。在上面那副图片中我也尝试过取消固定，但是没反应。但是现在按了ESC键后，都正常了。非常感谢！！！
