### ISSUE TITLE
在翻译对话框中设置语言无效，会被即时翻译设置覆盖

### ISSUE THREAD

**Issue by wj-ll** [YiiGuxing/TranslationPlugin#645]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

1. 设置里将 target language 设为 Last used language 
2. 即时翻译里设为翻译英文->中文
3. 点击 "Pin" 打开翻译对话框
4. 设置翻译英文->韩语
5. 选择文本并点击翻译，翻译变为英文->中文

### 环境 & 错误日志
- 插件版本: 3.0.1
- IDE版本: IntelliJ IDEA 2020.3.1 (Ultimate Edition) Build #IU-203.6682.168
- 操作系统版本: macOS Catalina 10.15.7

**Comment by YiiGuxing** [comment]
感谢反馈，已修复，下个版本可用。
