### ISSUE TITLE
Translate And Replace只有一个结果时，鼠标移过后结果显示不全

### ISSUE THREAD

**Issue by wj-ll** [YiiGuxing/TranslationPlugin#646]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
![](https://youtrack.jetbrains.com/api/files/74-989993?sign=MTYxMDc5ODQwMDAwMHwxMS03MjI0MTh8NzQtOTg5OTkzfGZkVkZ5aEtvYzlqaVRaVEphenhVVlJU%0D%0AamcwT0lQVER2SVZHRjlTcVpRajgNCg%0D%0A&updated=1610454386871)
-->

### 环境 & 错误日志
插件版本: 3.0.1
IDE版本: IntelliJ IDEA 2020.3.1 (Ultimate Edition) Build #IU-203.6682.168
操作系统版本: macOS Catalina 10.15.7

**Comment by YiiGuxing** [comment]
这不是插件的问题，是IDE的问题，只能等待官方修复。
更多信息与进度请关注：https://youtrack.jetbrains.com/issue/IDEA-260190
