### ISSUE TITLE
Google 无法正常翻译，添加备用的地址

### ISSUE THREAD

**Issue by yang163email** [YiiGuxing/TranslationPlugin#647]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
使用 Google 翻译的时候，有时候会出现翻译不了的错误，并且已经勾选了 ‘使用 translate.google.com’ 选项。

### Proposed Solution
是否可以新增 .hk 后缀的选项，或者自己填写后缀。

**Comment by WangJincheng4869** [comment]
的确是，总是莫名其妙的报错。然后检查网络是没有问题的

**Comment by YiiGuxing** [comment]
其实不管是哪个后缀的，其服务器都在美国，该墙的还是被墙。出现翻译不了的，最大的可能是翻译过于频繁了，这时候需要降低翻译频率（最好关闭文档实时翻译，频繁翻译主要来自此功能），频繁翻译会被限制。现在还没有找到有效的解决办法，所以不太稳定，毕竟是白嫖人家的嘛。。。。
