### ISSUE TITLE
翻译文档目标语言设置上次使用无效，翻译为主要语言

### ISSUE THREAD

**Issue by wj-ll** [YiiGuxing/TranslationPlugin#648]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
设置主要语言为日语，目标语言为上次使用
在即时翻译中设置为翻译英文-> 中文
点击翻译文档，文档被翻译为日文而不是中文

### 环境 & 错误日志
插件版本: 3.0.1
IDE版本: IntelliJ IDEA 2020.3.1 (Ultimate Edition) Build #IU-203.6682.168
操作系统版本: macOS Catalina 10.15.7

-->

**Comment by YiiGuxing** [comment]
文档翻译仅翻译为主要语言
