### ISSUE TITLE
即时翻译中在语言列表中键入字母，直接选中第一个首字母为该字母的语言而不是定位到以该字母为首字母的语言处

### ISSUE THREAD

**Issue by wj-ll** [YiiGuxing/TranslationPlugin#650]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
即时翻译中在语言列表中键入字母，直接选中第一个首字母为该字母的语言而不是定位到以该字母为首字母的语言处。
在设置和翻译对话框中，键入字母会定位而不是直接选中。

### 环境 & 错误日志
插件版本: 3.0.1
IDE版本: IntelliJ IDEA 2020.3.1 (Ultimate Edition) Build #IU-203.6682.168
操作系统版本: macOS Catalina 10.15.7

**Comment by YiiGuxing** [comment]
这种一步到位的操作的用户体验并不总是最好的，比如在这个场景中，如果有多个首字母一样的语言的话，用户选择的机会都没有了。

**Comment by wj-ll** [comment]
对，这就是我所说的问题，现在是直接选中了，我认为只应该定位，我的意思是设置和翻译对话框中的行为才应该是正常的，而即时翻译里面的直接选中不对

**Comment by YiiGuxing** [comment]
不好意思，是我没看清楚问题。我去操作了一下，确实有这个问题。
