### ISSUE TITLE
希望翻译的内容加上音标

### ISSUE THREAD

**Issue by allenzhangp** [YiiGuxing/TranslationPlugin#653]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
音标单词一般是有的，短语或句子是没得的，单词有些也不得，这个要看API有没有提供，API不提供也不得办法。。。。
