### ISSUE TITLE
界面多翻译引擎建议

### ISSUE THREAD

**Issue by k650dg4d2** [YiiGuxing/TranslationPlugin#656]
大哥,有没有兴趣把界面做成沙拉查词这样,这样也能体现出来多翻译引擎
![QQ截图20210130230117](https://user-images.githubusercontent.com/32454224/106359698-36546980-634f-11eb-98fe-e041d0cb62f6.png)

**Comment by YiiGuxing** [comment]
个人并不喜欢这样的展示方式
