### ISSUE TITLE
建议先自动过滤掉注释符, 然后再发送给翻译引擎处理

### ISSUE THREAD

**Issue by TerryLiu** [YiiGuxing/TranslationPlugin#658]
首先非常感谢这个作品,非常棒,它给我阅读代码注释提供了很大的帮助.

但是在翻译多行注释时,往往会被注释符给打断翻译或朗读的连贯性,所以建议在提交翻译前,先过滤掉换行符后面的注释符号.
包括 星号*, 斜杠/ ,(主要有 双斜杠// , 三斜杠/// )
或者是放开让用户自行设置这种 **前置过滤字符**

愿这个软件越来越优秀!

**Comment by YiiGuxing** [comment]
已有此功能，更多请另阅 #470
