### ISSUE TITLE
IDEA窗口之间的兼容

### ISSUE THREAD

**Issue by JavaCoffeePro** [YiiGuxing/TranslationPlugin#659]
## 检查清单
* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
在IDEA窗口上固定一个浮动翻译窗口
然后打开 Settings -> Editor -> Color Scheme
在右下方的文本去选择文本进行翻译

但无论是快捷键还是右键使用翻译选项
都无法进行翻译

![4H4ZEI@@LEN$U }% M Q{79](https://user-images.githubusercontent.com/68426449/107045611-a99f2500-6800-11eb-8755-05eb3f7d88fa.png)

于是我尝试使用 workspace 上已固定的翻译窗口

但无法使用，且伴随着IDEA提示音
在向我说明，我的焦点正在 settings 窗口上，请先关闭 settings 窗口

于是我只能再次打开 translate.google.cn

正常的情况应该是不管有没有固定的翻译窗口，都应该出现翻译的消息框，而不是什么也没有

### 环境 (没有崩溃)
- 插件版本: 3.0.0
- IDE版本: IDEA 2020.3.2
- 操作系统版本: Windows 10

**Comment by YiiGuxing** [comment]
不知道IDE什么时候偷偷把这个地方的项目环境给改没了，所以才会出现这个问题，还一直没被发现。。。。
