### ISSUE TITLE
新建文件比如新建类的时候在类名输入框里能添加上翻译并替换吗?

### ISSUE THREAD

**Issue by longge125521** [YiiGuxing/TranslationPlugin#66]
新建文件比如新建类的时候在类名输入框里能添加上翻译并替换吗?感觉这个功能有的时候也蛮有用的,可能大神们用的不多,如果大神不麻烦的话希望以后的版本加上.谢谢了

**Comment by YiiGuxing** [comment]
翻译并替换只能在编辑器里使用，其他地方是无法使用的。
至于以后，我并不能保证在什么时候才能加上。。。我先在Projects里加个[任务](https://github.com/YiiGuxing/TranslationPlugin/projects/1#card-3469583)吧，以后慢慢实现

**Comment by fandeus** [comment]
如果在日志输出的地方也能用上就好了，毕竟有很多错误的日志需要翻译。

**Comment by YiiGuxing** [comment]
@fandeus 可以使用的。详见：#31

**Comment by longge125521** [comment]
好的 谢谢了
