### ISSUE TITLE
AS 4.0.1 提示不兼容这个插件的v3.0.1版本, AS 4.1版本有问题,又不敢升级

### ISSUE THREAD

**Issue by TerryLiu** [YiiGuxing/TranslationPlugin#660]
AS 4.0.1 提示不兼容这个插件的v3.0.1版本, AS 4.1版本有问题,又不敢升级(以前升级过,又降回来了).
只有我遇到这个问题吗?

**Comment by YiiGuxing** [comment]
不兼容是因为其IntelliJ IED版本过低，AS 4.1以上的版本才可用。
