### ISSUE TITLE
插件3.0.1与之前版本在使用show translation dialog 文本域弹窗的行为不一致

### ISSUE THREAD

**Issue by sakura-he** [YiiGuxing/TranslationPlugin#670]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

请详细描述问题，确保包括:
  1. 选中待翻译的文本或者光标插入到待翻译的文本中,点击菜单栏中的show translation dialog图标或者按下show translation dialog的快捷键
  2. 弹出的文本域弹窗不会将选中的待翻译的文本上屏到弹出的show translation dialog文本域中。
  3. 向3.0版本那样,弹出的文本域弹窗会将选中的待翻译的文本上屏到弹出的show translation dialog文本域中自动翻译。就向使用''translatin'快捷键那样自动翻译选中的内容
  4. 如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/49332986/108931711-0c0e7700-7683-11eb-8db2-35a3d83fc055.png)
![image](https://user-images.githubusercontent.com/49332986/108931902-6f000e00-7683-11eb-8ef9-0974e864b559.png)

### 环境 & 错误日志
- 插件版本: 3.0.1 
- IDE版本: IDEA 2020.3.2 
- 操作系统版本:  Windows 10

**Comment by YiiGuxing** [comment]
在3.1版本可以恢复此行为： #652
