### ISSUE TITLE
Annotations and interfaces from javax.validation cannot be auto-translated.

### ISSUE THREAD

**Issue by pytkr** [YiiGuxing/TranslationPlugin#677]
Meanwhile, annotations and interfaces from `javax.inject` can be auto-translated. 
So, how to make annotations and interfaces from `javax.validation` be auto-translated, thanks!

**Comment by YiiGuxing** [comment]
Can you provide relevant screenshots?

**Comment by pytkr** [comment]
> Can you provide relevant screenshots?

**OK in javax.inject**
![OK in javax.inject](https://user-images.githubusercontent.com/45117726/110270559-0c9efa00-8001-11eb-9d17-f7ed5cbf777a.jpg)

**Failed in javax annotation**
![Failed in javax annotation](https://user-images.githubusercontent.com/45117726/110270683-4d970e80-8001-11eb-9ace-1e9ad59e0555.jpg)

**Comment by YiiGuxing** [comment]
After version [3.1](https://github.com/YiiGuxing/TranslationPlugin/milestone/20?closed=1) is released, please verify in version [3.1](https://github.com/YiiGuxing/TranslationPlugin/milestone/20?closed=1)

#643
