### ISSUE TITLE
自动翻译注解为中文

### ISSUE THREAD

**Issue by ouyanglong721** [YiiGuxing/TranslationPlugin#678]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [X] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [X] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
注解,或者javadoc中的注解会被自动翻译
### 问题描述

注解,或者javadoc中的注解会被自动翻译,能将这个自动翻译注解的功能取消吗,未找到取消的开关
![image](https://user-images.githubusercontent.com/52189456/109630569-0b447c00-7b80-11eb-9b3f-69361c19db4c.png)
![image](https://user-images.githubusercontent.com/52189456/109630769-45ae1900-7b80-11eb-9185-77c71a758a36.png)
![image](https://user-images.githubusercontent.com/52189456/109630827-52327180-7b80-11eb-8028-78950c559498.png)

### 环境 & 错误日志
- 插件版本: 3.0.1
- IDE版本: IDEA 2020.2
- 操作系统版本:  Windows10

**Comment by YiiGuxing** [comment]
这个不是插件翻译是的，你应该是安装中文语言包插件的，是它提供的本地语言，插件翻译的话会整个文档都翻译的。

**Comment by ouyanglong721** [comment]
了解,感谢解答
