### ISSUE TITLE
idea的reader mode模式下右键菜单没有翻译按钮

### ISSUE THREAD

**Issue by dongshaofei666** [YiiGuxing/TranslationPlugin#679]
### Preflight Checklist
Plugin version: 3.0.1

IDE version: IntelliJ IDEA 2020.3.2

Operating System and version: Windows 10

### Problem Description
在idea的reader mode模式下，选中要翻译的注释，然后右键，没有翻译按钮；

### Proposed Solution
希望为idea的reader mode模式右键菜单中也加一个翻译按钮

### Additional Information

![Snipaste_2021-03-02_23-50-46](https://user-images.githubusercontent.com/41518696/109677928-18c82900-7bb5-11eb-821e-9a71c71dd740.png)

![Snipaste_2021-03-02_23-51-53](https://user-images.githubusercontent.com/41518696/109677935-19f95600-7bb5-11eb-801a-e79b7b1c0de1.png)

**Comment by YiiGuxing** [comment]
merged: #474
