### ISSUE TITLE
The words in the comments should be able to be translated in reader mode

### ISSUE THREAD

**Issue by hzxcaq** [YiiGuxing/TranslationPlugin#681]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
The words in comments can not be translated when idea is Reader Mode
![图片](https://user-images.githubusercontent.com/32083844/109762555-b9593000-7c2b-11eb-965a-6a7c692791df.png)

### Proposed Solution

It should be translatable

**Comment by YiiGuxing** [comment]
see: #640
