### ISSUE TITLE
秘钥不能永久保存？？

### ISSUE THREAD

**Issue by xc116** [YiiGuxing/TranslationPlugin#683]
IDEA社区版，每次重启后都需再次配置秘密？ 是姿势不对吗？
IDEA版本信息如下：
IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: color.scheme.Github farshid Light v2 (rainglow), color.scheme.IdeaLight, color.scheme.Spring Light, com.intellij.marketplace, com.jetbrains.darkPurpleTheme, github.cweijan.test-theme, net.antelle.intellij-xcode-dark-theme, net.vektah.codeglance, com.alibaba.p3c.smartfox, com.baomidou.plugin.idea.mybatisx, com.euphoricity.gitignore, com.poratu.idea.plugins.tomcat, MavenRunHelper, cn.yiiguxing.plugin.translate

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin#faq

**Comment by YiiGuxing** [comment]
Response timeout.
