### ISSUE TITLE
Android Studio 2.3.3 + Translation 1.3.5 超时

### ISSUE THREAD

**Issue by IEC-lucy** [YiiGuxing/TranslationPlugin#69]
刚刚更新的插件到1.3.5，然后根据插件的提示，我去申请了有道智云的应用key和密钥，但是一直提示链接超时。

**Comment by YiiGuxing** [comment]
在windows上我也常遇到，过一会儿又可以了，但是我用浏览器访问也是超时，所以应该是和插件没有关系，再观察吧。

**Comment by YiiGuxing** [comment]
这个问题应该是网络环境的问题
