### ISSUE TITLE
可以添加翻译String本地化的功能吗

### ISSUE THREAD

**Issue by MrYZJ** [YiiGuxing/TranslationPlugin#691]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
String本地化这个功能比较需要，很少相关能用的插件

**Comment by MrYZJ** [comment]
> 不懂就问，请问什么是String本地化 :D

Android开发中的strings.xml文件中的字符翻译，就是把它翻译成很多国语言实现APP本地化

**Comment by qq1427998646** [comment]
我也觉得是, Android localization 总是卡死, 其他什么都不好用. 还就这个插件在更新, 而且能正常翻译.

**Comment by YiiGuxing** [comment]
目前没有太多精力去做特异化的工作，现在的工作重点还是在通用IDE上。当然，非常期待收到任何PR。 😄

**Comment by qq1427998646** [comment]
感谢回复!
你是个非常活跃的开发者!&nbsp;


如果以后有兴趣, 客户考虑更新一下他的. 他本身做的不错, 但是就是似乎会卡死, 一直无法翻译整个资源文件.
https://github.com/Airsaid/AndroidLocalizePlugin?hmsr=joyk.com&amp;utm_source=joyk.com&amp;utm_medium=referral







              公司:&nbsp;                   湖南日科仪器有限公司&nbsp;      
               姓名: 谢信 (销售部)      
      电话: 0731-85263092 &nbsp; 400-604-1618 
      手机: 15387513086 （微信同号） 
      产品: VOC检测仪、各种气体检测仪、仪表监控系统、环境监控系统、气体报警主机 
      网址： 
      &nbsp; &nbsp; &nbsp; &nbsp; www.pid-voc.com 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com.cn
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.cn
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 可以添加翻译String本地化的功能吗 (#691)





 
目前没有太多精力去做特异化的工作，现在的工作重点还是在通用IDE上。当然，非常期待收到任何PR。 😄

**Comment by YiiGuxing** [comment]
简单地实现了一个Android Studio strings.xml文件翻译的功能：
[TranslationPlugin-3.2-AS-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/6682644/TranslationPlugin-3.2-AS-SNAPSHOT.zip)

有需要的可以下载用此插件包使用（目前还不确定要不要放到正式版本中）。

代码分支（欢迎兴趣的同学可以在此基础上完善这个功能）：https://github.com/YiiGuxing/TranslationPlugin/tree/as-string-resources-translation

用法：
<img width="332" alt="1" src="https://user-images.githubusercontent.com/10737066/122680877-181ad780-d224-11eb-899d-ab1f5d3ccdee.png">
<img width="241" alt="2" src="https://user-images.githubusercontent.com/10737066/122680879-1c46f500-d224-11eb-9226-942abb543255.png">

**Comment by qq1427998646** [comment]
感谢回复更新！
捐赠100元人民币以兹鼓励你们这些活跃的开发者！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月21日(周一) 凌晨0:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YiiGuxing/TranslationPlugin] 可以添加翻译String本地化的功能吗 (#691)




 
简单地实现了一个Android Studio strings.xml文件翻译的功能：
 TranslationPlugin-3.2-AS-SNAPSHOT.zip
 
有需要的可以下载用此插件包使用（目前还不确定要不要放到正式版本中）。
 
代码分支（欢迎兴趣的同学可以在此基础上完善这个功能）：https://github.com/YiiGuxing/TranslationPlugin/tree/as-string-resources-translation
 
用法：

**Comment by YiiGuxing** [comment]
@qq1427998646 感谢您的慷慨捐赠！
