### ISSUE TITLE
希望使用百度翻译的时候也能展示音标信息

### ISSUE THREAD

**Issue by luck-cheng** [YiiGuxing/TranslationPlugin#695]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
音标信息需要服务商接口提供，如果接口未提供，我实在是不能无中生有啊。。。:D

**Comment by luck-cheng** [comment]
好的呢，可怕的百度
