### ISSUE TITLE
能不能减低插件的idea版本需求？

### ISSUE THREAD

**Issue by xusonfan** [YiiGuxing/TranslationPlugin#699]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

目前最新的插件需要idea20.1+版本，本来可以用旧的版本，可是旧版的google翻译现在不能用了，能不能降低插件的版本需求呢？我的idea目前是19.3版本的。

**Comment by YiiGuxing** [comment]
我会尽快补一个修复版本的。

**Comment by YiiGuxing** [comment]
修复版本已发布：https://plugins.jetbrains.com/plugin/8579-translation/versions
