### ISSUE TITLE
Mac不支持拼音

### ISSUE THREAD

**Issue by wien-wyc** [YiiGuxing/TranslationPlugin#7]
mac下intellij idea2016无法在插件界面中输入中文

**Comment by YiiGuxing** [comment]
@wien-wyc  用1.2是可以的

**Comment by wien-wyc** [comment]
外接显示器情况下，1.2版本插件弹窗只会出现在主屏。比如intelij开在外接显示屏上，而插件弹窗则出现在Mac桌面。。。而1.1版本则正常。

**Comment by YiiGuxing** [comment]
@wien-wyc 现在应该可以了: [commit 5715db0](https://github.com/YiiGuxing/TranslationPlugin/commit/5715db09a22d4b01d688b639c2e9e74a386ba0ce)
