### ISSUE TITLE
有道翻译 Api 不能用了吗？

### ISSUE THREAD

**Issue by meekzhou** [YiiGuxing/TranslationPlugin#70]
# 问题如题

* AS 版本：2.3.3
* 插件版本：1.3.5

# 错误如下
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fgyk98x8dij30f204cgm4.jpg)

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin#使用

**Comment by meekzhou** [comment]
谢谢
