### ISSUE TITLE
为何不支持翻译string.xml资源文件? 

### ISSUE THREAD

**Issue by qq1427998646** [YiiGuxing/TranslationPlugin#710]
Android localization 1.5.1版本总是卡死.
翻译中, 就你的是OK的,
所以为何不做翻译string.xml?

**Comment by YiiGuxing** [comment]
目前没有太多精力去做特异化的工作，现在的工作重点还是在通用IDE上。当然，非常欢迎提任何PR。 😄

**Comment by YiiGuxing** [comment]
merged: #691

**Comment by YiiGuxing** [comment]
简单地实现了一个Android Studio strings.xml文件翻译的功能：
[TranslationPlugin-3.2-AS-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/6682644/TranslationPlugin-3.2-AS-SNAPSHOT.zip)

有需要的可以下载用此插件包使用（目前还不确定要不要放到正式版本中）。

代码分支（欢迎兴趣的同学可以在此基础上完善这个功能）：https://github.com/YiiGuxing/TranslationPlugin/tree/as-string-resources-translation

用法：
<img width="332" alt="1" src="https://user-images.githubusercontent.com/10737066/122680877-181ad780-d224-11eb-899d-ab1f5d3ccdee.png">
<img width="241" alt="2" src="https://user-images.githubusercontent.com/10737066/122680879-1c46f500-d224-11eb-9226-942abb543255.png">

**Comment by qq1427998646** [comment]
您好!
刚刚测试了一下您的插件, 右击资源文件并没有产生菜单, 您得空看一下. 谢谢!



              公司:&nbsp;                   湖南日科仪器有限公司&nbsp;      
               姓名: 谢信 (销售部)      
      电话: 0731-85263092 &nbsp; 400-604-1618 
      手机: 15387513086 （微信同号） 
      产品: VOC检测仪、各种气体检测仪、仪表监控系统、环境监控系统、气体报警主机 
      网址： 
      &nbsp; &nbsp; &nbsp; &nbsp; www.pid-voc.com 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com.cn
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.cn
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 凌晨0:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 为何不支持翻译string.xml资源文件?  (#710)





 
简单地实现了一个Android Studio strings.xml文件翻译的功能：
 TranslationPlugin-3.2-AS-SNAPSHOT.zip
 
有需要的可以下载用此插件包使用（目前还不确定要不要放到正式版本中）。
 
代码分支（欢迎兴趣的同学可以在此基础上完善这个功能）：https://github.com/YiiGuxing/TranslationPlugin/tree/as-string-resources-translation
 
用法：

**Comment by YiiGuxing** [comment]
@qq1427998646 仅在Android Studio里可用，且使用谷歌翻译引擎，且文件是`res/values/strings.xml`或者`res/values-**/strings.xml`。

**Comment by qq1427998646** [comment]
哦, 原来如此, 可否考虑做一下百度的?


因为出现:&nbsp;


13:42	String Resources Translation
			翻译失败: 解析错误
			复制到剪贴板



估计给屏蔽了? 不过我也勾选了 <使用 translate.google.com&gt; , 这个应该没有被屏蔽吧?



              公司:&nbsp;                   湖南日科仪器有限公司&nbsp;      
               姓名: 谢信 (销售部)      
      电话: 0731-85263092 &nbsp; 400-604-1618 
      手机: 15387513086 （微信同号） 
      产品: VOC检测仪、各种气体检测仪、仪表监控系统、环境监控系统、气体报警主机 
      网址： 
      &nbsp; &nbsp; &nbsp; &nbsp; www.pid-voc.com 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com.cn
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.cn
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 中午1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 为何不支持翻译string.xml资源文件?  (#710)





 
@qq1427998646 仅在Android Studio里可用，且使用谷歌翻译引擎，且文件是res/values/strings.xml或者res/values-**/strings.xml。

**Comment by YiiGuxing** [comment]
会不会是内容太才了？谷歌翻译目前没有被屏蔽，但会有一些限制。
百度不支持XML文档翻译。

**Comment by qq1427998646** [comment]
哦哦哦, 我明白你现在的工作原理了.


刚刚测试了一下,&nbsp; 如果你源语言选择了简体中文, 它提示无法解析, 让他自动检测就没问题.


不过有2个不正确的地方.


1. 右击, 选择翻译后, 它不是新生成1个values-en这样的目录, 而是覆盖这个文件.&nbsp; 如果能通过选择的语言自动生成就好了.


2. 翻译后, 会偶个i标签 和 B标签, 暂时不知道Android是否能正确识别.


例如:&nbsp;
<string name="title_screenshot"&gt;<i&gt;截图</i&gt;<b&gt;スクリーンショット</b&gt;</string&gt;



              公司:&nbsp;                   湖南日科仪器有限公司&nbsp;      
               姓名: 谢信 (销售部)      
      电话: 0731-85263092 &nbsp; 400-604-1618 
      手机: 15387513086 （微信同号） 
      产品: VOC检测仪、各种气体检测仪、仪表监控系统、环境监控系统、气体报警主机 
      网址： 
      &nbsp; &nbsp; &nbsp; &nbsp; www.pid-voc.com 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com.cn
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.cn
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 为何不支持翻译string.xml资源文件?  (#710)





 
会不会是内容太才了？谷歌翻译目前没有被屏蔽，但会有一些限制。
 百度不支持XML文档翻译。

**Comment by YiiGuxing** [comment]
1. 正如我之前所说的：目前没有太多精力去做特异化的工作。主要的计划任务我也里也有一大堆等着我去做，而且最近这段时间发生太多事情了，使得我应接不暇，开发进度已经停滞很长一段时间了。但由于很多同学发邮件给我说很需要strings.xml文件翻译这个功能，所以我才开发了这么一个简单的功能，只能提供基本的需求，没有智能化的功能，那样花的时间太多了，因此才单独做了一个定制包，没有放到正式版本中。
2. 出现`i`标签 和`b`标签应该是内容包含有html标签导致的，翻译内容会带有原文与译文，分号包在 `i` 标签和 `b` 标签内，这个需要手动去除。

**Comment by qq1427998646** [comment]
好的.


没关系, 我已经用将整个xml文件复制到谷歌上, 然后再复制过来, 只是要翻页. 能暂时解决我的问题.


你是个很活跃的开发者, 而且里面的翻译功能都能用, 很多插件的翻译, 总是无法正常工作.


您忙, 886



              公司:&nbsp;                   湖南日科仪器有限公司&nbsp;      
               姓名: 谢信 (销售部)      
      电话: 0731-85263092 &nbsp; 400-604-1618 
      手机: 15387513086 （微信同号） 
      产品: VOC检测仪、各种气体检测仪、仪表监控系统、环境监控系统、气体报警主机 
      网址： 
      &nbsp; &nbsp; &nbsp; &nbsp; www.pid-voc.com 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.com.cn
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;www.hnrike.cn
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 为何不支持翻译string.xml资源文件?  (#710)





  
正如我之前所说的：目前没有太多精力去做特异化的工作。主要的计划任务我也里也有一大堆等着我去做，而且最近这段时间发生太多事情了，使得我应接不暇，开发进度已经停滞很长一段时间了。但由于很多同学发邮件给我说很需要strings.xml文件翻译这个功能，所以我才开发了这么一个简单的功能，只能提供基本的需求，没有智能化的功能，那样花的时间太多了，因此才单独做了一个定制包，没有放到正式版本中。
 
出现i标签 和b标签应该是内容包含有html标签导致的，翻译内容会带有原文与译文，分号包在 i 标签和 b 标签内，这个需要手动去除。
