### ISSUE TITLE
翻译内容不能打中文

### ISSUE THREAD

**Issue by Hajar177** [YiiGuxing/TranslationPlugin#718]
在我输入内容翻译的时候，发现内容里面只能输入英文，无法输入中文转英文

**Comment by Hajar177** [comment]
![image](https://user-images.githubusercontent.com/57106248/113685658-0fbd0100-96f9-11eb-8550-5e852ba697ec.png)

**Comment by YiiGuxing** [comment]
这个应该是输入法的问题，与插件无关的。
