### ISSUE TITLE
切换到有道智云报 status：505

### ISSUE THREAD

**Issue by douglarek** [YiiGuxing/TranslationPlugin#72]
<img width="780" alt="tp" src="https://user-images.githubusercontent.com/1488134/27618613-f042827e-5b82-11e7-858a-c9c10d32f442.png">

`macOS 10.12.5 && IDEA 2017.1.4 && TranslationPlugin v1.3`

**Comment by YiiGuxing** [comment]
可能是有道服务器的问题，我这边无法复现。可以多试几次。

**Comment by douglarek** [comment]
有没有办法查看 log

**Comment by YiiGuxing** [comment]
Help > Show Log in Finder > idea.log
能把这log文件上传来我看看吗？

**Comment by douglarek** [comment]
```
https://openapi.youdao.com/api?appKey=xxxx &from=EN&to=zh-CHS&salt=1498620968939&sign=48E8B28A980E34DC7EEB84D701C36B14&q=On+Subscribe```

**Comment by YiiGuxing** [comment]
嗯，这确实是个问题，我改改。
