### ISSUE TITLE
方法中翻译提示网络异常

### ISSUE THREAD

**Issue by zhanghuizong** [YiiGuxing/TranslationPlugin#722]
![image](https://user-images.githubusercontent.com/4384876/114487979-1987bc80-9c43-11eb-8d5b-4ac6ef8241b1.png)

**Comment by YiiGuxing** [comment]
请求过于频繁，请稍等再试

**Comment by YiiGuxing** [comment]
目前没有什么办法能有效解决，只能降低翻译频率。
