### ISSUE TITLE
支持IDEA ReaderMode下的单词翻译

### ISSUE THREAD

**Issue by leoooven** [YiiGuxing/TranslationPlugin#724]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Proposed Solution

IDEA看三方源码时，支持Reader Mode，此时注释会以渲染后的样式表现。这种情况下，选中单个单词右键没有翻译选项，也无法通过快捷键翻译。  

最新版本插件支持翻译整个文档，但无法划词翻译。 如图  
![image](https://user-images.githubusercontent.com/41411542/114497305-6627c380-9c54-11eb-8738-59c9a342830a.png)

**Comment by YiiGuxing** [comment]
Reader Mode只能翻译整个文档，是不支持选择翻译，这个需要IDE提供相关支持才行。
