### ISSUE TITLE
建议在注释被渲染时能翻译选中的单词

### ISSUE THREAD

**Issue by dongshaofei666** [YiiGuxing/TranslationPlugin#729]
idea version: 2021.1
plugin version: 3.1

因为不管用哪个翻译引擎，好多时候都翻译的不准确，很多时候只是想知道某个词的意思，不必整段翻译。

在注释文档没有被渲染时，可以选中某个单个词通过快捷键（默认ctrl+shift+y，可以自定义成自己方便的快捷键）进行翻译，非常方便；

但是对于被渲染后的注释，却不能这样了，如图所示，因此我只能切换渲染状态再取词翻译了，但是这样做打断了我的阅读，不是很方便
![image](https://user-images.githubusercontent.com/41518696/114640081-f4a64e80-9d01-11eb-8595-51a1e5ca3fa4.png)

**Comment by YiiGuxing** [comment]
其实我也很想实现这样的功能，但这需要IDE的支持，文档渲染模块都被IDE内部隐藏了起来的，只留一个小扩展点，这才得以实现整个渲染文档的翻译。。。。。

要实现对选中的文本进行翻译，就得使用非常规的手段，但没人能保证其内部代码不会再被修改，所以，我才没有使用这种方式来实现这一功能。

**Comment by YiiGuxing** [comment]
![img](https://user-images.githubusercontent.com/10737066/126184043-515da48a-48fe-401e-a46e-d1288ce40146.gif)
