### ISSUE TITLE
填入id key之后不能apply也不能ok 点击之后没反应

### ISSUE THREAD

**Issue by zwonb** [YiiGuxing/TranslationPlugin#73]
22:20	NoSuchMethodError: com.intellij.ide.passwordSafe.PasswordSafe.setPassword(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)V
翻译之后也一直停留在Querying...

**Comment by zwonb** [comment]
Translation threw an uncaught NoSuchMethodError. Disable Plugin

**Comment by YiiGuxing** [comment]
请卸载插件后重新安装，从官方插件仓库上安装。
