### ISSUE TITLE
Document translate in the IDEA javascript .ts file

### ISSUE THREAD

**Issue by MiniFullC** [YiiGuxing/TranslationPlugin#732]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description
1. When I try to translate the document comments in the IDEA javascript .ts file, nothing happens.But when I click the button on the left side of the comment (Toggle Rendered View) and switch back again, the translation takes effect.
2. I tried to perform document translation in a Java file, but the above problem did not occur, the translation took effect directly.
![image](https://user-images.githubusercontent.com/37063727/114798392-db67d580-9dc7-11eb-9e6e-9701fec082d1.png)
![image](https://user-images.githubusercontent.com/37063727/114798460-f89ca400-9dc7-11eb-9dfa-628c78a5c47b.png)

### Environment & Stack Trace
- Plugin version:  3.1   (IDEA plugins)
- IDE version:  IDEA 2021.1 Ultimate
- Operating System and version:  Windows 10  20H2

**Comment by YiiGuxing** [comment]
![screen](https://user-images.githubusercontent.com/10737066/114802564-84b2c980-9dd0-11eb-8561-180ef85900d9.gif)

**Comment by YiiGuxing** [comment]
The files in the project have the same problem:
![screen2](https://user-images.githubusercontent.com/10737066/114802610-9a27f380-9dd0-11eb-9e3e-c6ff30473190.gif)
