### ISSUE TITLE
弹框关不掉 2021.1 版本

### ISSUE THREAD

**Issue by RuoBingCoder** [YiiGuxing/TranslationPlugin#739]
### Idea 版本  2021.1

- 翻译完弹窗关不掉！希望后期加入窗口最小化和关闭按钮！

**Comment by YiiGuxing** [comment]
关不掉？你应该是点到了窗口右上角的固定窗口按钮了，再点一次取消固定，或者按ESC键就可以关掉了。

**Comment by RinOrz** [comment]
@YiiGuxing 固定按钮有时候会莫名其妙的自己选中

**Comment by YiiGuxing** [comment]
那你肯定是点击了气泡弹窗的固定按钮了，这个固定也会固定翻译窗口的。

**Comment by RuoBingCoder** [comment]
@YiiGuxing 没注意！现在好像没问题了！🙏
