### ISSUE TITLE
点击朗读按钮，没有声音

### ISSUE THREAD

**Issue by xixi36500** [YiiGuxing/TranslationPlugin#744]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
如题，点击按钮没有声音
### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
请问是否报错？

**Comment by xixi36500** [comment]
> 请问是否报错？

没有报错，其它都是正常的

**Comment by YiiGuxing** [comment]
那很有可能是网络的问题，谷歌翻译是否能使用？

**Comment by xixi36500** [comment]
@YiiGuxing 
网络正常的，谷歌翻译能用，就是没声音，我的音乐播放器都声音
![image](https://user-images.githubusercontent.com/6984456/116646979-0cd9c700-a9ac-11eb-850f-a0952cc111b5.png)

**Comment by xixi36500** [comment]
@YiiGuxing 还有个问题，为什么没有音标呢？是bug，还是其它原因？

**Comment by YiiGuxing** [comment]
请提供版本信息和运行环境信息，按模板提供。


另外，音标只会在单个词才会有，且不一定会有。

**Comment by xixi36500** [comment]
@YiiGuxing 

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by xixi36500** [comment]
@YiiGuxing
### 环境
- 插件版本: 3.1
- IDE版本:  IDEA 2020.3.1
- 操作系统版本: Windows 10

**Comment by xixi36500** [comment]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
朗读时没有声音

### 问题描述
请详细描述问题，确保包括:
  1. 点击朗读，没有声音，截图如下：
![](https://user-images.githubusercontent.com/6984456/116686042-d751cf80-a9e5-11eb-8acb-3a684bc0ed46.png)


### 环境 & 错误日志
- 插件版本: 3.1
- IDE版本: phpstorm 2020.3.1
- 操作系统版本:  Windows 10

**Comment by YiiGuxing** [comment]
我使用2020.3和2021.1版本的PS并未能复现此问题，会不会是在系统的问题是合成器中被静音了呢？
![屏幕截图 2021-04-30 231317](https://user-images.githubusercontent.com/10737066/116715985-d2067c00-aa09-11eb-9745-5dfa97aa0699.png)

或者PS版本的问题，升级到2020.3试试？或者重新安装PS或插件试试？

**Comment by xixi36500** [comment]
@YiiGuxing 是的，是这个原因，非常感谢你，有声音感觉就是不一样
