### ISSUE TITLE
我认为更新的太快了

### ISSUE THREAD

**Issue by 15592636895** [YiiGuxing/TranslationPlugin#746]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
？？？

**Comment by mzzsfy** [comment]
我认为更新的不够快[狗头]

**Comment by ningyudie** [comment]
我觉得更新速度还行 [滑稽]

**Comment by YiiGuxing** [comment]
最近在忙工作上的事情，好多BUG都没有时间处理。。。。。
