### ISSUE TITLE
os 10.12.5设置的快捷件会失效

### ISSUE THREAD

**Issue by fandeus** [YiiGuxing/TranslationPlugin#75]
我设了快捷键，但是快捷键会失效。

**Comment by YiiGuxing** [comment]
设置快捷键失效的可能原因有如下：
- 没有设置成功
- 与其他快捷键冲突
- 另外，在一些状态下一些操作（特别是翻译与替换操作）是不可用的，这时候快捷键会无动作的。
一般情况下快捷键无效是冲突与操作错误，请确认一下。

**Comment by fandeus** [comment]
现在已经好了，谢谢大神的辛苦开发。这个工具很棒
