### ISSUE TITLE
插件导致 IDEA 2021.1.1 部分功能错误(禁用插件功能恢复正常)

### ISSUE THREAD

**Issue by ToutatisGc** [YiiGuxing/TranslationPlugin#753]
禁用插件功能恢复正常

**Comment by kuailecs54** [comment]
![image](https://user-images.githubusercontent.com/32322827/117231409-c247c700-ae51-11eb-8698-b6b89a76e20b.png)
3.1 版本 和 该插件最新版, 兼容问题  导致 idea 启动报错, 并且 project 树 都出不来

**Comment by ToutatisGc** [comment]
> ![image](https://user-images.githubusercontent.com/32322827/117231409-c247c700-ae51-11eb-8698-b6b89a76e20b.png)
> 3.1 版本 和 该插件最新版, 兼容问题 导致 idea 启动报错, 并且 project 树 都出不来

破案了

**Comment by Marblog** [comment]
+1

**Comment by zpfenger** [comment]
我也是，差点重装IDEA，我禁用下就好了

**Comment by MrXionGe** [comment]
确实是这样的，暂时禁用吧。等作者适配一下就好了。

**Comment by ljynfo** [comment]
我最惨，重装IDE后还是不行，最后禁用插件就好了，这个问题也太严重了吧

**Comment by winskin** [comment]
重装了一次idea, 发现是插件冲突, 惊了

**Comment by O-kai** [comment]
禁用kotlin1.5之后就可以正常使用translation了

**Comment by hanschan1024** [comment]
same issue.

**Comment by hasa193** [comment]
一样，赶紧禁用了

**Comment by BaoBaoss** [comment]
> 禁用kotlin1.5之后就可以正常使用translation了

大佬请问怎么禁用kotlin，我都进不到plugin界面

**Comment by BaoBaoss** [comment]
> 禁用插件功能恢复正常

大佬请问怎么禁用kotlin，我都进不到plugin界面

**Comment by winskin** [comment]
> > 禁用插件功能恢复正常
> 
> 大佬请问怎么禁用kotlin，我都进不到plugin界面

重装, 或者重新打开idea, 在选项目的界面进入

**Comment by BaoBaoss** [comment]
> > > 禁用插件功能恢复正常
> > 
> > 
> > 大佬请问怎么禁用kotlin，我都进不到plugin界面
> 
> 重装, 或者重新打开idea, 在选项目的界面进入

懂了懂了，谢谢大佬

**Comment by YiiGuxing** [comment]
merged: #747
