### ISSUE TITLE
ID和密钥填入无法查询

### ISSUE THREAD

**Issue by zJiaJun** [YiiGuxing/TranslationPlugin#76]
首先感谢开源的翻译小工具，点赞。

按"使用说明"操作了之后，填入应用ID和密钥，点击Apply无反应。

只能OK返回，查询翻译，提示 "账号无效或者账号已欠费 - 设置"

#73 和这个描述挺像的。已经卸载后，重新插件库安装过，还是这样子。

IDEA.log
`2017-06-30 21:29:44,773 [ 413700]   INFO - ng.plugin.translate.Translator - {"errorCode":"111","l":"auto2auto"}`

环境如下:
IntelliJ IDEA 2017.1.4
Build #IU-171.4694.23, built on June 6, 2017
Subscription is active until November 23, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

**Comment by YiiGuxing** [comment]
1. 点击Apply是没有任何直接反馈的，Apply只会保存数据，不会返回，这个没有问题。
2. 至于无法翻译，是账号有问题，请注意检查。

**Comment by zJiaJun** [comment]
检查过了，ID和密钥。
复制网站上的密钥填入，还是提示“账号无效或者账号已欠费 - 设置"
手动打了一遍，提示“签名检验失败 - 设置”

**Comment by YiiGuxing** [comment]
请检查账号是否己欠费，应用是否是已经绑定翻译服务。这是账号的问题，或者另找一个账号试试。

**Comment by YiiGuxing** [comment]
实在不行的话你可以使用官方提供的java demo来试一试你的key：http://ai.youdao.com/docs/api.s#java-demo

**Comment by zJiaJun** [comment]
看来问题是不能马上生效。
id和密钥也没动过，隔了一天又好了

**Comment by YiiGuxing** [comment]
那就是有道的问题了。。。
