### ISSUE TITLE
[优化建议]  - 英语翻译的音标优化

### ISSUE THREAD

**Issue by zhanghuizong** [YiiGuxing/TranslationPlugin#762]
![image](https://user-images.githubusercontent.com/4384876/118213261-298ff780-b4a0-11eb-996c-26d4da990489.png)

单词: **caffeine**  的 **[ˈkæfiːn]**

**Comment by YiiGuxing** [comment]
emmm...这个没有办法，毕竟音标也是翻译接口给的，没有办法控制。

**Comment by zhanghuizong** [comment]
> emmm...这个没有办法，毕竟音标也是翻译接口给的，没有办法控制。

所有接口都返回都是如此吗

**Comment by YiiGuxing** [comment]
因接口而异，有的接口直接就有有音标

**Comment by zhanghuizong** [comment]
好吧, 这个实现不了太可惜了~~
