### ISSUE TITLE
[讨论]引擎开发问题咨询

### ISSUE THREAD

**Issue by d-w-x** [YiiGuxing/TranslationPlugin#763]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

1. 在[方法](https://github.com/YiiGuxing/TranslationPlugin/blob/a116e424acbc6a6576115b39768d125b7c74294d/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/AbstractTranslator.kt#L62)
```kotlin
getRequestParams(
        text: String,
        srcLang: Lang,
        targetLang: Lang,
        isDocumentation: Boolean
    )
```
    中 ，请问 isDocumentation `true`  的时候 text 是什么形式？

2. 对于多行文本，text的什么样子的？

3. 已有的翻译引擎（例如百度）对于包含多行的doc是怎么翻译的？

4. 能否使用邮件或者其他快捷通讯（或者您找个时间持续关注一会issue），向您详细咨询下开发步骤？

**Comment by YiiGuxing** [comment]
1. `isDocumentation=true` 时，对于谷歌翻译引擎，`text` 为HTML文档，而其他翻译引擎，就是普通文本。
2. 对于多行文本的翻译，`text`就是包含换行符的普通文本，没有什么特殊的。
3. 对于文档翻译，支持HTML文档翻译的就直接翻译HTML文档，不支持的就解析HTML文档为普通文本再进行翻译，详见`documention`包。

**Comment by D-W-X** [comment]
请问您在使用百度翻译接口的时候，对多行文本怎么处理的？现在腾讯云那边翻译接口不支持换行符，您有什么建议吗？

感觉如果把换行符去掉进行翻译，翻译的句子效果会好些（防止有些文档在非停顿处换行），但是翻译的结果就成了一长串文本，不知道插件会不会有显示问题。

**Comment by YiiGuxing** [comment]
对于普通文本翻译，是有选项由用户决定是否保留换行符和多余的空白符的。


而对于文档翻译，就不能去掉换行符和多余的空白符了，因为文档结构是复杂的，是有文本排版的，不能粗暴地去掉。

**Comment by YiiGuxing** [comment]
已集成翻译接口，都是支持多行翻译的，并没有做特殊处理。

**Comment by YiiGuxing** [comment]
如果接口不支持多行文本翻译的话，普通翻译直接去除换行符是没什么问题的，但对于文档翻译就不行了，显示会有问题。逐行翻译可能是行不通的，接口访问频率太高了，应该会被限制的。

**Comment by D-W-X** [comment]
能否提供下您使用百度翻译后结果的截图？

我目前是这样的：
![新插件截图](https://user-images.githubusercontent.com/35656321/118247125-65917f80-b4d5-11eb-9bd0-2419516dbe01.png)

**Comment by D-W-X** [comment]
> 能否提供下您使用百度翻译后结果的截图？
> 
> 我目前是这样的：

实在是抱歉，因为买不起百度和有道翻译，所以不知道这两个目前的效果...

**Comment by YiiGuxing** [comment]
效果就是这样的

**Comment by YiiGuxing** [comment]
稍微看了一下腾讯翻译接口的文档，其翻译限制太大了，不适合插件的大部分场景，并没有多少接入的价值。

**Comment by D-W-X** [comment]
翻译限制?你是指哪些特殊的限制吗？
我使用的时候感觉明显有影响的就是html标签处理不好，其他的还行？

**Comment by D-W-X** [comment]
关于异常[这里](https://github.com/YiiGuxing/TranslationPlugin/blob/master/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Exceptions.kt#L26)，项目强制要求服务器那边返回的异常是数字，应该是为了本地化考虑？但是腾讯那边返回的直接就是对应的文字，所以您这边建议是新加入异常还是想办法对原来的 `TranslateResultException` 兼容？

**Comment by D-W-X** [comment]
> 稍微看了一下腾讯翻译接口的文档，其翻译限制太大了，不适用于插件的大部分使用场景，所以并没有多少接入的价值。

或者您的意思是不打算向项目引入腾讯翻译的兼容？
自己编写的化私用即可？

**Comment by YiiGuxing** [comment]
主要的是对文档翻译太不友好了，百度有道至少支持多行翻译。其他限制倒是问题不大。

**Comment by YiiGuxing** [comment]
你提供的截图是腾讯翻译  翻译的结果吗？

**Comment by D-W-X** [comment]
> 主要的是对文档翻译太不友好了，百度有道至少支持多行翻译。其他限制倒是问题不大。

抱歉这个是我之前使用接口时自己的问题，表达不太合理，要是引起不便请谅解。

当时只是我自己不知道如何处理多行的问题，看谷歌引擎翻译的太完美了，没有其他引擎参考。

**Comment by D-W-X** [comment]
> 你提供的截图是腾讯翻译  翻译的结果吗？

是的。
所以你能同时提供下百度和有道的结果，我对比下吗？
翻译某个java文档就好了。

**Comment by D-W-X** [comment]
（顺便，qq邮箱的回复issue太挫了...久等。）

**Comment by YiiGuxing** [comment]
嗨！我还以为腾讯翻译不支持多行翻译呢，有道百度对文档的翻译就是你截图中的效果是一样的。那么其他的限制本身问题就不大，处理一下就行了。那么它还是可以接入的，有接入价值的。

**Comment by YiiGuxing** [comment]
> （顺便，qq邮箱的回复issue太挫了...久等。）

没关系的，慢慢来。

**Comment by D-W-X** [comment]
> 关于异常[这里](https://github.com/YiiGuxing/TranslationPlugin/blob/master/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Exceptions.kt#L26)，项目强制要求服务器那边返回的异常是数字，应该是为了本地化考虑？但是腾讯那边返回的直接就是对应的文字，所以您这边建议是新加入异常还是想办法对原来的 `TranslateResultException` 兼容？

异常这里您有想法吗？

**Comment by YiiGuxing** [comment]
> > 关于异常[这里](https://github.com/YiiGuxing/TranslationPlugin/blob/master/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Exceptions.kt#L26)，项目强制要求服务器那边返回的异常是数字，应该是为了本地化考虑？但是腾讯那边返回的直接就是对应的文字，所以您这边建议是新加入异常还是想办法对原来的 `TranslateResultException` 兼容？
> 
> 异常这里您有想法吗？

腾讯翻译api的返回是有对应的返回码的，所以还是要以返回码为准，你可以参考百度和有道的实现，因为它们都是同一类型的，但是腾讯翻译api这个异常码比较多，所以没有必要全部提示，捡几个可能会经常出现的来进行提示就行。提示信息自然是需要本化的，不过本地化这部分你不用管，所有语言你都填中文就行，自会有JetBrains的翻译员帮忙翻译的。

**Comment by D-W-X** [comment]
> > > 关于异常[这里](https://github.com/YiiGuxing/TranslationPlugin/blob/master/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Exceptions.kt#L26)，项目强制要求服务器那边返回的异常是数字，应该是为了本地化考虑？但是腾讯那边返回的直接就是对应的文字，所以您这边建议是新加入异常还是想办法对原来的 `TranslateResultException` 兼容？
> > 
> > 
> > 异常这里您有想法吗？
> 
> 腾讯翻译api的返回是有对应的返回码的，所以还是要以返回码为准，你可以参考百度和有道的实现，因为它们都是同一类型的，但是腾讯翻译api这个异常码比较多，所以没有必要全部提示，捡几个可能会经常出现的来进行提示就行。提示信息自然是需要本化的，不过本地化这部分你不用管，所有语言你都填中文就行，自会有JetBrains的翻译员帮忙翻译的。

你可以点以下链接，你那里强制性的要求异常类型是数字。
但是腾讯翻译api的返回码是字符串。

**Comment by YiiGuxing** [comment]
对了，感谢你的帮忙，实现新功能！

**Comment by D-W-X** [comment]
我这边正在向腾讯云那边咨询他们报错本地化情况的问题。

![腾讯云](https://user-images.githubusercontent.com/35656321/118263359-bbbbee00-b4e8-11eb-9bcd-ccdd66007b77.png)
如图所示的是腾讯云的错误代码情况。

**Comment by YiiGuxing** [comment]
> 我这边正在向腾讯云那边咨询他们报错本地化情况的问题。
> 
> ![腾讯云](https://user-images.githubusercontent.com/35656321/118263359-bbbbee00-b4e8-11eb-9bcd-ccdd66007b77.png)
> 如图所示的是腾讯云的错误代码情况。

咦，为什么和我看的文档不一样？那这样的话你就只能重新定义一个异常了。

**Comment by YiiGuxing** [comment]
@D-W-X 并不是的，只是最近比较忙，很多需求都推在那没有得到处理，而且已经相关的需求issue的：#537，并且issue也打上了 PR Welcome 的标签，所以，非常期待能够收到你的PR哦！

**Comment by YiiGuxing** [comment]
> > 稍微看了一下腾讯翻译接口的文档，其翻译限制太大了，不适用于插件的大部分使用场景，所以并没有多少接入的价值。
> 
> 或者您的意思是不打算向项目引入腾讯翻译的兼容？
> 自己编写的化私用即可？

@D-W-X 并不是的，看你之前的描述，我以为腾讯翻译不支持多行翻译，才有这一说。而且目前已经有相关的需求issue的：#537，只是最近比较忙，很多需求都推在那没有得到处理。那个issue也被我打上了 PR Welcome 的标签，所以，非常希望，也非常期待能够收到你的PR哦！

**Comment by D-W-X** [comment]
> > 我这边正在向腾讯云那边咨询他们报错本地化情况的问题。
> > 如图所示的是腾讯云的错误代码情况。
> 
> 咦，为什么和我看的文档不一样？我看到的是数字类型的。。。。那这样的话你就只能重新定义一个异常了。

所以其实这么说的话，应该是原先的异常定义有问题，从可扩展角度来说，要是能修改最好了。
不过也不急到时候看吧。

**Comment by D-W-X** [comment]
> > > 稍微看了一下腾讯翻译接口的文档，其翻译限制太大了，不适用于插件的大部分使用场景，所以并没有多少接入的价值。
> > 
> > 
> > 或者您的意思是不打算向项目引入腾讯翻译的兼容？
> > 自己编写的化私用即可？
> 
> @D-W-X 并不是的，看你之前的描述，我以为腾讯翻译不支持多行翻译，才有这一说。而且目前已经有相关的需求issue的：#537，只是最近比较忙，很多需求都推在那没有得到处理。那个issue也被我打上了 PR Welcome 的标签，所以，非常希望，也非常期待能够收到你的PR哦！

ok，那可以的。
不过今天突然毕设改需求了，又得一段时间改毕设了。

现在腾讯这边我除了异常其他都还行，但是还是等我过些天有空修好吧。

**Comment by D-W-X** [comment]
更进一步的，其实感觉现在还有个问题，api的设置里只有 api和key。
![config](https://user-images.githubusercontent.com/35656321/118295650-b1ace600-b50e-11eb-8939-d496d07afe73.png)
但腾讯这里需要一个额外的地区配置。

我大概看了下这里新增选项好像很麻烦，可能你这里编写的时候可扩展性也没选好。

新引擎的开发人员应该是可以方便的向这里面加入其他参数，比如说是不是需要单独使用proxy，比如说根据地区选项选择实际请求的url。

这里可能要麻烦你后期大幅度修改的。

**Comment by D-W-X** [comment]
> @D-W-X 并不是的，看你之前的描述，我以为腾讯翻译不支持多行翻译，才有这一说。而且目前已经有相关的需求issue的：#537，只是最近比较忙，很多需求都推在那没有得到处理。那个issue也被我打上了 PR Welcome 的标签，所以，非常希望，也非常期待能够收到你的PR哦！

现在和您你商量也是考虑到未来的可扩展性，而不是我自己一加了之，给个pr，后面别人想写新的就继续堆...这*山就起来了。

所以也感谢你的及时回复的。

**Comment by YiiGuxing** [comment]
> > > > 稍微看了一下腾讯翻译接口的文档，其翻译限制太大了，不适用于插件的大部分使用场景，所以并没有多少接入的价值。
> > > 
> > > 
> > > 或者您的意思是不打算向项目引入腾讯翻译的兼容？
> > > 自己编写的化私用即可？
> > 
> > @D-W-X 并不是的，看你之前的描述，我以为腾讯翻译不支持多行翻译，才有这一说。而且目前已经有相关的需求issue的：#537，只是最近比较忙，很多需求都推在那没有得到处理。那个issue也被我打上了 PR Welcome 的标签，所以，非常希望，也非常期待能够收到你的PR哦！
> 
> ok，那可以的。
> 不过今天突然毕设改需求了，又得一段时间改毕设了。
> 
> 现在腾讯这边我除了异常其他都还行，但是还是等我过些天有空修好吧。

嗯嗯，以学业为重。

**Comment by YiiGuxing** [comment]
> 更进一步的，其实感觉现在还有个问题，api的设置里只有 api和key。
> ![config](https://user-images.githubusercontent.com/35656321/118295650-b1ace600-b50e-11eb-8939-d496d07afe73.png)
> 但腾讯这里需要一个额外的地区配置。
> 
> 我大概看了下这里新增选项好像很麻烦，可能你这里编写的时候可扩展性也没选好。
> 
> 新引擎的开发人员应该是可以方便的向这里面加入其他参数，比如说是不是需要单独使用proxy，比如说根据地区选项选择实际请求的url。
> 
> 这里可能要麻烦你后期大幅度修改的。

确实是的，其实我很早就已经发现了的，最开始设计的时候就没有设计好，没有考虑周到，所以其可扩展性很差。随着功能起来越多，其弊端就越来越明显。但是当我意识到的时候，代码已经有一定的规模了，修改不是一时半会就能改好的，又忙着开发新功能，所以这部分的重构就一直被搁置着。所以说，这技术债，是最难还的。。。:cry:

**Comment by YiiGuxing** [comment]
> > 更进一步的，其实感觉现在还有个问题，api的设置里只有 api和key。
> > ![config](https://user-images.githubusercontent.com/35656321/118295650-b1ace600-b50e-11eb-8939-d496d07afe73.png)
> > 但腾讯这里需要一个额外的地区配置。
> > 
> > 我大概看了下这里新增选项好像很麻烦，可能你这里编写的时候可扩展性也没选好。
> > 
> > 新引擎的开发人员应该是可以方便的向这里面加入其他参数，比如说是不是需要单独使用proxy，比如说根据地区选项选择实际请求的url。
> > 
> > 这里可能要麻烦你后期大幅度修改的。
> 
> 确实是的，其实我很早就已经发现了的，最开始设计的时候就没有设计好，没有考虑周到，所以其可扩展性很差。随着功能越来越多，其弊端就越来越明显。但是当我意识到的时候，代码已经有一定的规模了，修改不是一时半会就能改好的，又忙着开发新功能，所以这部分的重构就一直被搁置着。所以说，这技术债，是最难还的。。。:cry:
> 
> 而且，最近短时间内也是没有重构的可能的，也不知道什么时候才能开始着手处理。。。。

**Comment by D-W-X** [comment]
异常处理那块我过些天考虑考虑吧，看看怎么弄合适。
配置界面这里只能是你，或者等至少熟悉kt的人来了。
我这种java半吊子，kt只能模仿着写写，要搞创新啊设计啊显然是不行啦。

**Comment by d-w-x** [comment]
message("error.invalidAccount", HTML_DESCRIPTION_TRANSLATOR_CONFIGURATION) (相当于随便写个账号密码)这里应该打开插件配置窗口，我这边测试无法打开，可能你这边后续要检查下相关信息。

idea 2021.1.1

**Comment by YiiGuxing** [comment]
> message("error.invalidAccount", HTML_DESCRIPTION_TRANSLATOR_CONFIGURATION) (相当于随便写个账号密码)这里应该打开插件配置窗口，我这边测试无法打开，可能你这边后续要检查下相关信息。
> 
> idea 2021.1.1

嗯，这里有个bug.
