### ISSUE TITLE
翻译显示界面乱码问题

### ISSUE THREAD

**Issue by 15751064254** [YiiGuxing/TranslationPlugin#77]
![image](https://user-images.githubusercontent.com/13188598/27781051-d3691340-5ffe-11e7-882b-6adcd0837012.png)

![image](https://user-images.githubusercontent.com/13188598/27781038-c6bf54b0-5ffe-11e7-8e5d-bfc3e39a091e.png)

**Comment by YiiGuxing** [comment]
- 插件设置页面乱码，IDE UI字体请使用支持中文的字体：
  ![ui](https://user-images.githubusercontent.com/10737066/27781257-b5f4c308-5fff-11e7-829a-109961eea787.png)

- 插件页面乱码请看#50
