### ISSUE TITLE
一定情况下无法输入中文（我没有用中文汉法包，默认的英文界面）

### ISSUE THREAD

**Issue by maoweifan** [YiiGuxing/TranslationPlugin#770]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by maoweifan** [comment]
直接是输入法切不到中文

**Comment by YiiGuxing** [comment]
这可能是输入法的问题哦。。。

**Comment by maoweifan** [comment]
但是前几个版本是没有这个问题的 不排除是输入法的问题（Windows10自带的输入法）不知道有多少人遇到过同样的问题

**Comment by YiiGuxing** [comment]
> 但是前几个版本是没有这个问题的 不排除是输入法的问题（Windows10自带的输入法）不知道有多少人遇到过同样的问题

就插件的输入框上有此问题吗？IDE自己的输入框有没有问题？

**Comment by maoweifan** [comment]
只在插件的输入框有此问题，idea的编辑器是没有这个问题的，可以在idea中打完然后右键翻译，把光标移到插件的输入框，输入法就变成了英文，而且切不到其他语言输入法

**Comment by YiiGuxing** [comment]
我并不能复现此问题，尝试一下其他的输入法呢，是否也是有一样的问题？
![动画](https://user-images.githubusercontent.com/10737066/121107777-25ef5680-c83b-11eb-9801-8330b30b0b9e.gif)

**Comment by maoweifan** [comment]
好的 等我遇到此问题的时候录制一个gif或者是mp4 这个复现是有机率的 我也尝试下其他输入法
