### ISSUE TITLE
希望能夠支援控制語音的音量大小

### ISSUE THREAD

**Issue by bluelovers** [YiiGuxing/TranslationPlugin#773]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

希望能夠支援控制語音的音量大小

**Comment by YiiGuxing** [comment]
我认为语音音量应该由系统控制，如果想要单独控制IDEA的音量，可以使用系统音量合成器控制，所以此需求不会被实现。
