### ISSUE TITLE
想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动

### ISSUE THREAD

**Issue by liangzhenyu-1993** [YiiGuxing/TranslationPlugin#774]

**Comment by YiiGuxing** [comment]
可否描述一下具体步骤，以及你想要的效果？

**Comment by liangzhenyu-1993** [comment]
每次输入如果包含中文，一输入分号就自动翻译，有时候写得长一点的字符串，idea还卡顿一小会




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月7日(星期一) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动 (#774)





 
可否描述一下具体步骤，以及你想要的效果？

**Comment by YiiGuxing** [comment]
一输入分号就自动翻译？插件没有这样的骚操作啊，我也没能复现这个问题啊。。。你用的是什么IDE嘛，哪个版本的？
![动画1](https://user-images.githubusercontent.com/10737066/121107660-e294e800-c83a-11eb-971b-d7279f5fea04.gif)

**Comment by liangzhenyu-1993** [comment]
2020.1版本；
确定是该插件的问题，我禁用掉它就不会出现我上述的问题，一启用问题就来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 上午9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动 (#774)





 
一输入分号就自动翻译？插件没有这样的骚操作啊，我也没能复现这个问题啊。。。你用的是什么IDE嘛，哪个版本的？

**Comment by liangzhenyu-1993** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动 (#774)





 
一输入分号就自动翻译？插件没有这样的骚操作啊，我也没能复现这个问题啊。。。你用的是什么IDE嘛，哪个版本的？

**Comment by YiiGuxing** [comment]
。。。。能否请你录个屏？我要先复现问题才好找出问题所在。

**Comment by liangzhenyu-1993** [comment]
你的复现和我不一样，反正一条语句末尾先没有分号（你的预读已经有了），经常我碰到是最后才写分号（这条语句也是要符合语法的），
可以试试 String s="中文" 再加上 分号试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 上午9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动 (#774)





 
一输入分号就自动翻译？插件没有这样的骚操作啊，我也没能复现这个问题啊。。。你用的是什么IDE嘛，哪个版本的？

**Comment by YiiGuxing** [comment]
一样的无法复现，这很奇怪啊，插件没有做自动翻译的功能啊。。。。
![动画](https://user-images.githubusercontent.com/10737066/121116795-ad43c680-c849-11eb-93e7-09d21b155c9d.gif)

**Comment by liangzhenyu-1993** [comment]
这就很奇怪了，推测可能是我配置IDEA输入结束符时关联了什么快捷键了，我先再排查先了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 中午11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiiGuxing/TranslationPlugin] 想要sout，输入中文后，再输入结束分号，就自动翻译，此时整个IDEA就卡住，可不可以把这个抽出配置，可自动可手动 (#774)





 
一样的无法复现，这很奇怪啊，插件没有做自动翻译的功能啊。。。。

**Comment by YiiGuxing** [comment]
> 这就很奇怪了，推测可能是我配置IDEA输入结束符时关联了什么快捷键了，我先再排查先了

**Comment by YiiGuxing** [comment]
> 这就很奇怪了，推测可能是我配置IDEA输入结束符时关联了什么快捷键了，我先再排查先了

这很有可能哦

**Comment by YiiGuxing** [comment]
> 这就很奇怪了，推测可能是我配置IDEA输入结束符时关联了什么快捷键了，我先再排查先了

这很有可能哦
