### ISSUE TITLE
翻译不了

### ISSUE THREAD

**Issue by L-sty** [YiiGuxing/TranslationPlugin#776]
右键翻译一直转圈；重新下载插件没用；重启电脑也没用

**Comment by YiiGuxing** [comment]
可能是你那不能访问谷歌翻译，可以使用百度或者有首的试一下。

**Comment by L-sty** [comment]
整好了，好像是C盘的文件出了点问题，配置文件是个空的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月10日(周四) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YiiGuxing/TranslationPlugin] 翻译不了 (#776)




 
可能是你那不能访问谷歌翻译，可以使用百度或者有首的试一下。
