### ISSUE TITLE
服务不可用

### ISSUE THREAD

**Issue by leaf918** [YiiGuxing/TranslationPlugin#779]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
![image](https://user-images.githubusercontent.com/170311/122365802-90b43680-cf8d-11eb-8fb2-9183a8a85814.png)

### 问题描述
baidu 个人api key 不可用
google 提示：请求过多，请稍候再试

### 环境 & 错误日志
- 插件版本: 3.11
- IDE版本: clion-2021.1.1
- 操作系统版本:

**Comment by YiiGuxing** [comment]
谷歌的只能等一段时间再试试了。
百度的你要确认一下appid,appkey是否正确，或者是不是有延迟。

**Comment by leaf918** [comment]
百度的appid,appkey确认是正确的。

**Comment by YiiGuxing** [comment]
请按百度翻译开放平台的翻译服务申请流程正确地申请相关资源并配置。
