### ISSUE TITLE
怀疑插件导致的Mac OS中文输入法卡死问题

### ISSUE THREAD

**Issue by kael-aiur** [YiiGuxing/TranslationPlugin#780]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

在使用一段时间之后，发现idea会突然变的非常卡顿，并且发现切换到其他程序，只要使用中文输入法都会变得非常卡顿，按下一个字符需要等待很久才会显示，切换到英文输入时，感觉上比较正常，但是英文输入在idea中也比较卡顿。

这个情况出现过两次，第一次没检查出原因，直接重启了电脑，第二次出现之后，我逐个程序关闭，发现关闭idea后其他程序输入中文就正常了，然后重新打开idea后发现又不正常了。

然后我又尝试禁用idea的插件，我自己下载三个插件：Kotlin,Smtart Tomcat, Translation。
第一次直接禁用了Kotlin和Translation，重启idea，发现一切正常了，不再卡顿。

自此我怀疑Kotlin和Translate两个插件导致的的卡顿，但是因为我没有用Kotlin编程，而且Kotlin是官方提供的插件，导致的问题的可能性不太大，所以比较怀疑Translate插件。

PS: 关闭Translation插件之后，重新启用插件，重启Idea，目前看起来是正常的。
出现此问题的时候，使用的是有道翻译引擎，上一次使用的是谷歌翻译引擎，最近换成有道是因为谷歌一直提示查询次数过多，请稍后重试。

### 环境 & 错误日志
- 插件版本: 3.1.1
- IDE版本: 2021.1.2 Community
- 操作系统版本: macOS Big Sur 11.4(20F71)

**Comment by YiiGuxing** [comment]
可否请你帮忙排查一下这个问题？提供一下出现卡顿问题后idea的日志文件？

**Comment by kael-aiur** [comment]
> 可否请你帮忙排查一下这个问题？提供一下出现卡顿问题后idea的日志文件？
> 
> 获取日志方法：主菜单栏-help-show log in explorer-idea.txt

昨天的日志没看到异常，下次再出现这个问题的时候，我再拿日志，这个问题不常现，可能得用个好几天才出现。

**Comment by YiiGuxing** [comment]
如再遇到此问题，可以重新打开。
