### ISSUE TITLE
Annotations and interfaces from org.aspectj cannot be auto-translated.

### ISSUE THREAD

**Issue by pytkr** [YiiGuxing/TranslationPlugin#781]
Weirdly, annotations and interfaces from **org.aspectj** cannot be auto-translated, maybe the same kind of bug like #677 .

**Comment by YiiGuxing** [comment]
Can you provide relevant screenshots?

**Comment by pytkr** [comment]
> Can you provide relevant screenshots?

Other classes can show documentation translation, however, these classes in package `org.aspectj.weaver` cannot.
**Failed in org.aspectj.weaver**
<img width="1104" alt="Failed in org aspectj weaver" src="https://user-images.githubusercontent.com/45117726/122844456-4c7db900-d334-11eb-98ba-a1c837d4e27a.png">

**Failed in org.aspectj.apache.bcel.classfile**
<img width="1077" alt="Failed in org aspectj weaver 2" src="https://user-images.githubusercontent.com/45117726/122844483-56072100-d334-11eb-8da8-0d059232ec26.png">

**Comment by pytkr** [comment]
> Can you provide relevant screenshots?

Other classes can show documentation translation, however, these classes in package `org.aspectj.weaver` cannot.
**Failed in org.aspectj.weaver**
<img width="1104" alt="Failed in org aspectj weaver" src="https://user-images.githubusercontent.com/45117726/122844456-4c7db900-d334-11eb-98ba-a1c837d4e27a.png">

**Failed in org.aspectj.apache.bcel.classfile**
<img width="1077" alt="Failed in org aspectj weaver 2" src="https://user-images.githubusercontent.com/45117726/122844483-56072100-d334-11eb-8da8-0d059232ec26.png">

**Comment by YiiGuxing** [comment]
Thank you for your feedback, I will find time to solve this problem.

**Comment by YiiGuxing** [comment]
@pytkr Hi!
I am sorry for the late solve. 
After testing, the documentation for the `org.aspectj.weaver` package is translated properly:

![20210720100920](https://user-images.githubusercontent.com/10737066/126252083-e7d28ea4-4a0e-4e25-b849-50aa09d61f8f.jpg)
![20210720101043](https://user-images.githubusercontent.com/10737066/126252088-583adc25-d6e8-4f4d-b2c6-b0c3c53c4139.jpg)

I can't reproduce the problem you describe, can you provide your way of introducing dependencies? This is the way I introduced it:

```xml
<dependency>
    <groupId>org.aspectj</groupId>
    <artifactId>aspectjweaver</artifactId>
    <version>1.8.13</version>
</dependency>
```

![20210720102210](https://user-images.githubusercontent.com/10737066/126252435-ed4973c7-d005-4dca-b796-02478c8fd854.jpg)

**Comment by pytkr** [comment]
> @pytkr Hi!
> I am sorry for the late solve.
> After testing, the documentation for the `org.aspectj.weaver` package is translated properly:
> 
> ![20210720100920](https://user-images.githubusercontent.com/10737066/126252083-e7d28ea4-4a0e-4e25-b849-50aa09d61f8f.jpg)
> ![20210720101043](https://user-images.githubusercontent.com/10737066/126252088-583adc25-d6e8-4f4d-b2c6-b0c3c53c4139.jpg)
> 
> I can't reproduce the problem you describe, can you provide your way of introducing dependencies? This is the way I introduced it:
> 
> ```
> <dependency>
>     <groupId>org.aspectj</groupId>
>     <artifactId>aspectjweaver</artifactId>
>     <version>1.8.13</version>
> </dependency>
> ```
> 
> ![20210720102210](https://user-images.githubusercontent.com/10737066/126252435-ed4973c7-d005-4dca-b796-02478c8fd854.jpg)

You're right, it works now, I don't know the reason why, thanks again!
