### ISSUE TITLE
Popup windows not using selected font

### ISSUE THREAD

**Issue by balane** [YiiGuxing/TranslationPlugin#782]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [X ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details
Popup windows do not use selected font.

### Description

When a translation is shown in a popup window, the popup is not using the font selected in the Translation plugin settings. So, if I right-click an English word and select 'Translate', the popup will have the Hindi translation garbled. Same with the Translation dialog. But, if I right-click and select 'Translate and Replace', the text that is replaced is correct. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
Thank you for your feedback, I will find time to solve this problem.

**Comment by balane** [comment]
I should add that this used to work fine. Not sure when this started happening.

**Comment by YiiGuxing** [comment]
@balane Hi, 
I found that Hindi cannot be displayed on the input box of the IDE. This is probably a problem with the IDE.

**Comment by balane** [comment]
That's odd since it worked before.

**Comment by YiiGuxing** [comment]
It is likely that the underlying components of IDEA have been modified.

**Comment by YiiGuxing** [comment]
It is likely that the underlying components of IDEA have been modified.

**Comment by YiiGuxing** [comment]
@balane Hi,
I have reported this problem to JetBrains, if there is any progress, I will let you know.

**Comment by YiiGuxing** [comment]
@balane Hi,

My feedback was answered and they provided a solution: install the Hindi language pack for the system.
https://youtrack.jetbrains.com/issue/JBR-3608

Now I can display Hindi properly on the plugin:
![20210715144415](https://user-images.githubusercontent.com/10737066/125741656-95ea6e61-9411-4c6b-b26e-450f2b984ecb.jpg)
