### ISSUE TITLE
MacOS Big Sur上用AS最新预览版 插件出现乱码

### ISSUE THREAD

**Issue by Wangzihaooooo** [YiiGuxing/TranslationPlugin#784]
### 问题描述
插件出现乱码，系统默认是utf8。
<img width="169" alt="截屏2021-06-28 下午6 35 40" src="https://user-images.githubusercontent.com/31450515/123623688-54f85700-d840-11eb-9550-9a12e429870f.png">

### 环境 & 错误日志
- 插件版本: 最新版3.1.1
- IDE版本: Arctic Fox最新预览版
- 操作系统版本: MacOS Big Sur

**Comment by YiiGuxing** [comment]
https://github.com/YiiGuxing/TranslationPlugin#faq

**Comment by Petterpx** [comment]
![image](https://user-images.githubusercontent.com/41142188/124149730-761caa00-dac3-11eb-90d9-4e05742be178.png)
整个插件都乱码了，改字体并没有解决

**Comment by YiiGuxing** [comment]
可以尝试修改这里的字体：

<img width="611" alt="屏幕截图 2021-07-08 000238" src="https://user-images.githubusercontent.com/10737066/124792719-d908b800-df7f-11eb-81d1-68b68a9849f0.png">
