### ISSUE TITLE
DataGrip 中无法自动翻译文档

### ISSUE THREAD

**Issue by zjslqshqz** [YiiGuxing/TranslationPlugin#786]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
第一次安装插件后，在弹出文档中，打开翻译文档，能够自动翻译。
但是再次显示文档时，并没有自动翻译文档，但是翻译稳定的开关又是打开。
如果，手动去掉打勾，并再次打狗，又是能够正常翻译的。

### 如下
![2021-07-03 16 21 19](https://user-images.githubusercontent.com/6870067/124348139-d6722f80-dc1a-11eb-8ab0-2d16adcac935.gif)

**Comment by YiiGuxing** [comment]
这个问题是因为当前版本还没有支持SQL文档，我抽空看一下能不能支持吧。

**Comment by YiiGuxing** [comment]
问题不是不支持SQL文档，是因为写错了一个字符，`SQL`写成了`SQl`。。。
