### ISSUE TITLE
期望能增加阿里机器翻译api

### ISSUE THREAD

**Issue by Saukiya** [YiiGuxing/TranslationPlugin#787]
期望能增加阿里机器翻译api
Links:
通用版
https://www.aliyun.com/product/ai/base_alimt?spm=5176.19720258.J_8058803260.53.61ff2c4aw3DyR9
开发指引:
https://help.aliyun.com/document_detail/158244.html?spm=5176.14040699.J_9035878410.2.35293ec8DuevgR&accounttraceid=9ea3439178f843d3a41b5213cccbe5bazijf
代码示例:
https://next.api.aliyun.com/api/alimt/2018-10-12/TranslateGeneral?params={}

**Comment by YiiGuxing** [comment]
merged: #768

**Comment by Saukiya** [comment]
阿里云的api我正在自己添加，如果成功的话我试试合并？https协议的已经找到了，项目构建正常

**Comment by YiiGuxing** [comment]
> 阿里云的api我正在自己添加，如果成功的话我试试合并？https协议的已经找到了，项目构建正常

欢迎提交PR！

**Comment by Saukiya** [comment]
已发送至邮箱
来自saukiyaEX@Gmail.com
