### ISSUE TITLE
TRANSLATION_DIRECTORY 规范化

### ISSUE THREAD

**Issue by Hill-98** [YiiGuxing/TranslationPlugin#788]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
建议在 Linux 上将 `TRANSLATION_DIRECTORY` 目录设置为 `$XDG_CONFIG_HOME/.translation` 而不是现在的 `$HOME/.translation`。

这样可以使 $HOME 目录干净一些

### Proposed Solution
如果 `$HOME/.translation` 存在，则继续使用 `$HOME/.translation` (或者移动到新的位置)，否则使用 `$XDG_CONFIG_HOME/.translation`

**Comment by Hill-98** [comment]
使用 `$XDG_DATA_HOME 或许是更好的选择`

**Comment by YiiGuxing** [comment]
呃这个主要是我对桌面版Linux并不是很了解，你这么一提我才知道。那么如果按这个规范的话，`TRANSLATION_DIRECTORY` 放在 `$XDG_DATA_HOME` （即`$HOME/.local/share`）才是更好的。那么桌面版Linux是不是默认有这么一个目录？

**Comment by Hill-98** [comment]
默认都是有的，XDG 规范是应该读取 $XDG_DATA_HOME 变量，如果没有设置，应该默认为 $HOME/.local/share

**Comment by YiiGuxing** [comment]
OK，我去验证一下，再做调整。感谢你提出的建义！
