### ISSUE TITLE
卸载了还是报400

### ISSUE THREAD

**Issue by AceInAndroid** [YiiGuxing/TranslationPlugin#79]
Connection failed with HTTP code 400   卸载重装也是这样

**Comment by YiiGuxing** [comment]
请使用浏览器访问一下这个网址：https://openapi.youdao.com/api?appKey=19f08b1975c8c454&from=auto&to=auto&salt=1499223376205&sign=CFAD734CFB95F230416FEE002F828B7D&q=a
看看能不能访问到。

**Comment by AceInAndroid** [comment]
能访问到 我android studio也没设置代理  然后每次翻译还要输个密码 奇怪 以前都没有

**Comment by YiiGuxing** [comment]
[TranslationPlugin.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1123642/TranslationPlugin.zip)
那你使用这个包试一下，然后打开日志文件找到查询的URL，把URL贴出来我看一下。
日志文件：Help > Show Log in Finder > idea.log

至于密码。这个密码是保护你的翻译密钥的，这个密码打开程序后只输一次的啊，如果不想输入密码的话可能使用ide 2017以上的版本，或者在Settings->Appearance&Behavior->System Settings->Passwords里设置一下。

**Comment by AceInAndroid** [comment]
好~我试试

**Comment by AceInAndroid** [comment]
可以连上了，com.intellij.util.io.HttpRequests$HttpStatusException: Connection failed with HTTP code 400. Status=400, Url=https://openapi.youdao.com/api?appKey=21de4a59f70df888 &from=auto&to=auto&salt=1499256653941&sign=0EE79D4231BEA8D814832198C8A555F6&q=JSON+Object

**Comment by YiiGuxing** [comment]
你的应用ID后面多了一个空格。和#72问题是一样的。看来还得发个小版本。。。

**Comment by YiiGuxing** [comment]
#80
