### ISSUE TITLE
关于封锁本插件的 Exception 至其他展现形式的建议

### ISSUE THREAD

**Issue by RickoNoNo3** [YiiGuxing/TranslationPlugin#792]
### Preflight Checklist
* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

从原则上讲, IDE级的异常一般应出现于以下情景:
1. 无法预料的特殊运行时异常
2. 破坏项目内容完整性的异常
3. 造成IDE无法正常运转的异常

不论是自动翻译还是手动翻译, 有些异常是可预见的, 且对进一步的开发工作影响有限(甚至毫无影响), 在此以谷歌翻译的网络错误为例:

1. 具有明显的预见性和常见性
2. 未对项目内容造成任何破坏
3. 不会造成IDE运转问题

因此翻译错误不应在IDE级错误通知中出现, 它属于不同的级别. 此分析方法对其他一些可预见性错误也有指导作用.

### Proposed Solution

**进行异常捕获, 并于其他适当位置进行有效提示(如翻译弹窗中), 阻止异常进一步冒泡到全局**

### Additional Information

可从任意一层下手处理: 
```
TranslateException: Google 翻译 :: 翻译失败: 连接失败
NetworkException: translate.google.cn. host=translate.google.cn
java.net.UnknownHostException: translate.google.cn
```

**Comment by YiiGuxing** [comment]
好建议！文档翻译的Exception确实冒泡到了全局，体验非常糟糕，这是我的疏忽，这个必需改进。即时翻译对话框这部分的错误提示也应该还要优化一下，但目前还没有想好如何优化，窗口上找不到好的位置放置这个消息，这个再想想。
