### ISSUE TITLE
在更新最新android studio ，全部乱码了

### ISSUE THREAD

**Issue by panzhoutao** [YiiGuxing/TranslationPlugin#796]

**Comment by YiiGuxing** [comment]
![20210729173501](https://user-images.githubusercontent.com/10737066/127468939-36c8045f-3b9a-42bf-82c5-1d1952f0ec20.jpg)

> Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, cn.yiiguxing.plugin.translate

**Comment by YiiGuxing** [comment]
请检查字体配置：
![image](https://user-images.githubusercontent.com/10737066/127469085-381a62e1-f172-425a-afc3-bd33d4761633.png)
