### ISSUE TITLE
android studio升到最新版本出现乱码

### ISSUE THREAD

**Issue by YuWenHaoqq** [YiiGuxing/TranslationPlugin#797]
当我升到最新版本的android studio时，翻译的中文出现乱码，使用translate时会乱码，但使用translate and replace时是正常的

### 问题描述
  1. 重现问题的步骤。：选择目标，右键，点击translate
  2. 发生了什么。：翻译的中文出现了乱码
  3. 您认为正确的行为应该是什么。：应该出现中文
  4. 
![image](https://user-images.githubusercontent.com/49157135/127518077-052c199a-ca52-4878-9764-bbf7e17d528c.png)

环境：
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.ankit.mahadik.json.dart.class, leetcode-editor, Dart, com.localizely.flutter-intl, com.thoughtworks.gauge, org.jetbrains.kotlin, io.flutter, com.ruiyu.ruiyu, cn.yiiguxing.plugin.translate, org.intellij.plugins.markdown

**Comment by YiiGuxing** [comment]
#796
