### ISSUE TITLE
Android Studio 2020.3.1 for Mac，升级后到该版本后中文乱码

### ISSUE THREAD

**Issue by unicool** [YiiGuxing/TranslationPlugin#798]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
翻译到中文时出现乱码。

### 环境 & 问题描述
环境：Android Studio 2020.3.1 for Mac，最新版
翻译中文时乱码，拼音正常。AS升级之前是没问题的，其他IDEA正常。

**Comment by YiiGuxing** [comment]
#796
