### ISSUE TITLE
idea 14 版本并不能使用该插件

### ISSUE THREAD

**Issue by wallacefw1987** [YiiGuxing/TranslationPlugin#8]
我添加有道api key的name 和 value，并不能保存成功。
![qq 20160824155913](https://cloud.githubusercontent.com/assets/6769051/17922847/c22ffcb0-6a13-11e6-9da4-fb40a7b8a285.png)

**Comment by YiiGuxing** [comment]
@wallacefw1987 那使用默认的Key可以使用吗？

**Comment by YiiGuxing** [comment]
好吧，我使用了很多新版本的API，而idea 14并没有这些API...

**Comment by wallacefw1987** [comment]
所以idea14不支持吗？

**Comment by YiiGuxing** [comment]
@wallacefw1987 是的，我已经更新代码，不再支持idea14(本来就不支持，嘿嘿，只是现在idea14不能安装了)，增强了对idea15的支持。所以，抱歉了，请idea15或者更高的版本。见[**commit ba18851**](https://github.com/YiiGuxing/TranslationPlugin/commit/ba188513c1f18645677474bcaa4ada351f997880).
