### ISSUE TITLE
最新版的插件安装失败

### ISSUE THREAD

**Issue by 880634** [YiiGuxing/TranslationPlugin#803]
## 检查清单

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

* 插件安装失败，通过 release 下载的 3.1.1 最新版无法在 Android Studio 4.2.2 上面安装，会提示报错，我这边经过一轮测试，3.1-201 版本可以安装，但是后面的版本就不行了，望作者大大有空看一下，Android Studio 4.2.2 正式版下载：[Windows 版本](https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.2.2.0/android-studio-ide-202.7486908-windows.zip)，[MacOs 版本](https://redirector.gvt1.com/edgedl/android/studio/install/4.2.2.0/android-studio-ide-202.7486908-mac.dmg)。

### 问题描述

![](https://user-images.githubusercontent.com/24937241/128627986-00f4bd9b-b31c-4861-be84-86fa9d42e1b8.png)

![](https://user-images.githubusercontent.com/24937241/128627896-6d7ee78c-2f2c-4200-acb3-455bb50056ab.png)

![](https://user-images.githubusercontent.com/24937241/128627958-1a959755-377a-4d51-81ca-351129a5c9ee.png)

### 环境 & 错误日志

- 插件版本: 3.1.1

- IDE版本: 202.7660.26.42.7486908

- 操作系统版本: macOs 11.5.1

**Comment by YiiGuxing** [comment]
3.1.1版本插件最低仅支持到203以上的IDE版本，AS4.2和IDE版本为202，因此无法安装，只能安装3.1-201版本的插件。想要安装最新版本的插件，请升级AS版本到Arctic Fox | 2020.3.1版本。
