### ISSUE TITLE
【建议】建议添加打开类时自动翻译注释选项

### ISSUE THREAD

**Issue by pangdonghao** [YiiGuxing/TranslationPlugin#808]
如题

**Comment by YiiGuxing** [comment]
这操骚操作太耗翻译量了，在一些翻译引擎上还会有很多问题。而且这种操作并不是很有必要。

**Comment by noenif** [comment]
> 这种骚操作太耗翻译量了，在一些翻译引擎上还会有很多问题。而且这种操作并不是很有必要的嘛。

![image](https://user-images.githubusercontent.com/25174520/132471600-171da433-b253-455e-875a-71cb073e05bf.png)
如图,每次需要点击,translate,大佬,有没有快捷键,可以解决.

**Comment by YiiGuxing** [comment]
> ![image](https://user-images.githubusercontent.com/25174520/132471600-171da433-b253-455e-875a-71cb073e05bf.png)
> 如图,每次需要点击,translate,大佬,有没有快捷键,可以解决.

目前没有快捷键可以进行这部分的翻译（需求：#819），不过你可以暂时地使用Ctrl+Q查看快速文档，并在其上面打开快速文档的自动翻译。

**Comment by ldlPlus** [comment]
这个需求需要的人还是挺多的,感觉可以做个开关,我们自己控制嘛,而且百度阿里的翻译量也用不完

**Comment by pytkr** [comment]
@YiiGuxing Hello, maybe only all texts shown within the current screen by scrolling needs be translated automatically, simlilar to lazy loading, once scrolling to next page, new translatating begins for newer text.

**Comment by YiiGuxing** [comment]
> @YiiGuxing Hello, maybe only all texts shown within the current screen by scrolling needs be translated automatically.
Simlilar to lazy loading, once scrolling to the next page, new translatating begins for newer text.
Thus, the cost for requesting API will be largely reduced.

@pytkr  Hi, I had your idea before, it's a good idea, but there are many problems with the implementation, and the documentation system of the IDEA platform seems to be changing a lot at the moment, it will be much easier to implement this feature when the new documentation system is perfect and stable. Mostly I don't have any more energy at the moment, there are too many projects that need to be carried out, I have recorded this idea and it is in my plans, stay tuned, thanks for your support.
