### ISSUE TITLE
Android studio 插件中文乱码

### ISSUE THREAD

**Issue by zhouxiaocong** [YiiGuxing/TranslationPlugin#809]
升级版本:
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, io.flutter, cn.yiiguxing.plugin.translate

问题：
Preferences->Translation 描述全为 口口口 乱码
翻译后：中文为口口口 乱码 
英文都正常显示

**Comment by YiiGuxing** [comment]
duplicate: #796
