### ISSUE TITLE
突然间校验签名失败

### ISSUE THREAD

**Issue by nl101531** [YiiGuxing/TranslationPlugin#81]
之前用的还好好地,然后突然就校验签名失败了,使用有道的Java Demo正常翻译,但是配置到该插件后就提示校验失败.版本1.3.6

**Comment by nl101531** [comment]
对比了签名,发现确实有问题:
    //插件
https://openapi.youdao.com/api?appKey=631cfc513aa42c50&from=auto&to=auto&salt=1500209734348&sign=C8C6BAFC322043175ACADD6F614A43F2&q=%E4%BD%A0%E5%A5%BD
    //官方
https://openapi.youdao.com/api?appKey=631cfc513aa42c50&from=auto&to=auto&salt=1500209734348&sign=DC7BE6F673DDD61F7A60D7C80E9C3F79&q=%E4%BD%A0%E5%A5%BD

同样的参数,官方的签名与插件的签名不一致.

**Comment by YiiGuxing** [comment]
请确保输入的密钥是正确的，看看是不是多复制了其他的字符？

**Comment by nl101531** [comment]
这个试了很多遍,我怀疑是IDEA的bug,每次保存后再次打开设置,密码框就空掉了,我的是IDEA2017.1.5版本的/

**Comment by YiiGuxing** [comment]
这不大可能，你看看你是不是设置了不保存密码：
![1](https://user-images.githubusercontent.com/10737066/28248382-56a4d4c0-6a76-11e7-9c5d-9e16f2fe3d30.png)
如果是保存密码的就试一下清除掉以前的再重新设置一试密钥：
![2](https://user-images.githubusercontent.com/10737066/28248399-bd848ff0-6a76-11e7-8ade-0a501f7ed902.png)

**Comment by nl101531** [comment]
非常感谢,解决了,我的给我选择的是in native Keychain,手动改成in KeePass后解决问题.

![](http://oobu4m7ko.bkt.clouddn.com/1500215841.png?imageMogr2/thumbnail/!70p)

**Comment by YiiGuxing** [comment]
嗯，在mac下好像会用系统自己的，而且一但设置了在ide里好像改不了。。。

**Comment by privatez** [comment]
同样的问题
刚才按照作者的方法都试了个遍都无法解决

按照官方 Python demo 跑了下代码发现也是同样的202签名校验失败
进入有道后台 发现原来每个应用对应的秘钥和之前的不一样了
之前一直使用的是有道发我邮箱里的数字组成的应用秘钥且使用情况良好
但是后台显示却是字母组成的
使用后台显示的秘钥就能翻译成功了。。。

**Comment by YiiGuxing** [comment]
@privatez 你用老的API KEY当然不行啊

**Comment by privatez** [comment]
@YiiGuxing 之前一直都是 ok 的 QAQ

**Comment by YiiGuxing** [comment]
@privatez 那是你还没有更新插件
