### ISSUE TITLE
Plugin installs but immediatly uninstalls in ArcticFox Android Studio

### ISSUE THREAD

**Issue by promikhail** [YiiGuxing/TranslationPlugin#811]
Plugin installs but immediatly uninstalls in ArcticFox Android Studio

**Comment by xueziang** [comment]
yes,java too

**Comment by YiiGuxing** [comment]
Older versions of the plugin have fatal errors in Android Studio ArcticFox, please try to install the latest version of the plugin.

**Comment by promikhail** [comment]
> Older versions of the plugin have fatal errors in Android Studio ArcticFox, please try to install the latest version of the plugin.

I tried to install plugin latest version from built-in AndroidStudio Market. The problem is the same

**Comment by YiiGuxing** [comment]
Please describe the steps to reproduce the issue, I am unable to reproduce the issue.

![image](https://user-images.githubusercontent.com/10737066/131255434-bddb9551-d616-4e81-96af-d0dc845ecfb9.png)

**Comment by YiiGuxing** [comment]
Does the IDE have an error message? If so, please provide it, thanks!

**Comment by xueziang** [comment]
My fault. After installing the plug-in this time, the IDE is restarted directly, resulting in the disappearance of the plug-in after restart.
Finally, I waited for a while after installing the plug-in and found that a prompt of successful installation popped up in the lower right corner. Now it works.

**Comment by promikhail** [comment]
> My fault. After installing the plug-in this time, the IDE is restarted directly, resulting in the disappearance of the plug-in after restart.
> Finally, I waited for a while after installing the plug-in and found that a prompt of successful installation popped up in the lower right corner. Now it works.

I did the same too :) Now it's working!)

![image](https://user-images.githubusercontent.com/25414753/131305468-7690ea88-31b5-403c-ab60-94bb955e28c4.png)
