### ISSUE TITLE
不知道是我的电脑问题，未知错误

### ISSUE THREAD

**Issue by liujunjie00** [YiiGuxing/TranslationPlugin#825]
## 检查清单
![image](https://user-images.githubusercontent.com/68498178/133403358-e3478d80-bdb8-49da-9d21-fe9461ab13f6.png)

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by ChawLoo** [comment]
翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)

**Comment by YiiGuxing** [comment]
merged: #821

**Comment by liujunjie00** [comment]
好像是打开的，因为我的电脑是比较老的配置，我笔记本又可以用，还有我去导入其他gradle项目的时候老是出问题





你知道是什么原因吗？ 我是小白
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 不知道是我的电脑问题，未知错误 (#825)





 
翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
