### ISSUE TITLE
翻译连接超时

### ISSUE THREAD

**Issue by LaoTpanicl** [YiiGuxing/TranslationPlugin#829]
![image](https://user-images.githubusercontent.com/90834220/133587834-2626c591-86cd-4937-9a32-404ef51fd2e6.png)
![image](https://user-images.githubusercontent.com/90834220/133587871-81c91a2a-f09e-45e4-8bc1-003e4aa368ec.png)
找了解决方案都差不多，都没有效果

**Comment by LaoTpanicl** [comment]
@YiiGuxing

**Comment by LaoTpanicl** [comment]
我想了解一下大概什么原因，我的其他电脑也是有这样翻译失败的问题

**Comment by YiiGuxing** [comment]
连接超时真的不是插件的问题，很有可能是你网络环境的问题。实在不行建议先使用百度或者有道的吧，申请KEY又不是很难。

请另参阅：#454

**Comment by liveHub-ping** [comment]
`https://github.com/YiiGuxing/TranslationPlugin/issues/828`按照这里的设置可以正常使用

**Comment by YiiGuxing** [comment]
@LaoTpanicl 试试升级一下插件，可能是你的安装插件版本太老了。

**Comment by YiiGuxing** [comment]
@LaoTpanicl 你使用的插件的版本还是2.x的，太老旧了，3.x版本之前的 `translate.google.com` 是需要VPN才能访问的，请升级到3.x版本的插件。

**Comment by YiiGuxing** [comment]
@LaoTpanicl 如果还在使用2.x版本的话，升级至v2.9.3即可解决问题。
