### ISSUE TITLE
翻译失败: 未知错误

### ISSUE THREAD

**Issue by cc404360208** [YiiGuxing/TranslationPlugin#832]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
>Plugin v2.9.2  
>IntelliJ IDEA 2019.3.4  
>Build #IU-193.6911.18, built on March 17, 2020  
>Runtime version: 11.0.6+8-b520.43 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

**Comment by YiiGuxing** [comment]
duplicate: #827
