### ISSUE TITLE
更新 TKK 失败，请检查网络连接

### ISSUE THREAD

**Issue by yonglf** [YiiGuxing/TranslationPlugin#833]
上午10:21	TKK
					更新 TKK 失败，请检查网络连接
					复制到剪贴板

上午10:24	TKK
					更新 TKK 失败，请检查网络连接
					复制到剪贴板

上午10:29	TKK
					更新 TKK 失败，请检查网络连接
					复制到剪贴板

上午10:37	TKK
					更新 TKK 失败，请检查网络连接
					复制到剪贴板

**Comment by YiiGuxing** [comment]
是不是还在使用2.x的版本啊？升级一下吧。

**Comment by yonglf** [comment]
> 是不是还在使用2.x的版本啊？升级一下吧。
我通过在线安装  安装的版本是2.9.2，然后我卸载了在线安装的版本，通过手动安装TranslationPlugin-3.1.1.zip，提示Plugin 'Translation' is incompatible with this installation

**Comment by yonglf** [comment]
> 是不是还在使用2.x的版本啊？升级一下吧。

我通过在线安装 安装的版本是2.9.2，然后我卸载了在线安装的版本，通过手动安装TranslationPlugin-3.1.1.zip，提示Plugin 'Translation' is incompatible with this installation

**Comment by YiiGuxing** [comment]
> > 是不是还在使用2.x的版本啊？升级一下吧。
> 
> 我通过在线安装 安装的版本是2.9.2，然后我卸载了在线安装的版本，通过手动安装TranslationPlugin-3.1.1.zip，提示Plugin 'Translation' is incompatible with this installation

那就是IDE版本太低了，如果不想升级IDE的话，就只能用有道、百度的翻译了。

**Comment by YiiGuxing** [comment]
@yonglf 升级至v2.9.3即可解决问题。

**Comment by yonglf** [comment]
@YiiGuxing

> @yonglf 升级至v2.9.3即可解决问题。

nice

**Comment by zj4074305** [comment]
我IDEA 2020.3.1  插件3.1.1 还是报  更新 TKK 失败，请检查网络连接。
tool里面也勾选  translate.google.com/  浏览器可以正常访问
