### ISSUE TITLE
翻译失败: 未知错误

### ISSUE THREAD

**Issue by txf402066270** [YiiGuxing/TranslationPlugin#834]
windows  pycharm在使用此插件 提示：翻译失败: 未知错误

公司和家里都不能使用

**Comment by Chen-chuangheng** [comment]
![image](https://user-images.githubusercontent.com/61062052/133870799-c92e0e49-43e4-4cb3-9f72-64eddb44d8bc.png)
 这样搞一下就可以了，不过听说不是长久的办法

**Comment by eric521237** [comment]
> ![image](https://user-images.githubusercontent.com/61062052/133870799-c92e0e49-43e4-4cb3-9f72-64eddb44d8bc.png)
> 这样搞一下就可以了，不过听说不是长久的办法

这是idea的问题？

**Comment by shou-heng** [comment]
> > ![image](https://user-images.githubusercontent.com/61062052/133870799-c92e0e49-43e4-4cb3-9f72-64eddb44d8bc.png)
> > 这样搞一下就可以了，不过听说不是长久的办法
> 
> 这是idea的问题？

应该是谷歌翻译的问题

**Comment by eric521237** [comment]
> > > ![image](https://user-images.githubusercontent.com/61062052/133870799-c92e0e49-43e4-4cb3-9f72-64eddb44d8bc.png)
> > > 这样搞一下就可以了，不过听说不是长久的办法
> > 
> > 
> > 这是idea的问题？
> 
> 应该是谷歌翻译的问题

又快十月一号。。。。。

**Comment by antred** [comment]
还是不行,应该是被墙了吧,https://translate.google.cn倒是可用,但是不知道怎么替换到插件的配置里

**Comment by eric521237** [comment]
> 还是不行,应该是被墙了吧,[https://translate.google.cn倒是可用,但是不知道怎么替换到插件的配置里](https://translate.google.cn%E5%80%92%E6%98%AF%E5%8F%AF%E7%94%A8,%E4%BD%86%E6%98%AF%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E6%9B%BF%E6%8D%A2%E5%88%B0%E6%8F%92%E4%BB%B6%E7%9A%84%E9%85%8D%E7%BD%AE%E9%87%8C)

我的按照配置适配下是可以嘚。

**Comment by 2535688890** [comment]
- #835 我这里写了错误的具体原因

**Comment by lyprivate** [comment]
勾选上就可以了。挺好

**Comment by YiiGuxing** [comment]
> 还是不行,应该是被墙了吧,[https://translate.google.cn倒是可用,但是不知道怎么替换到插件的配置里](https://translate.google.cn%E5%80%92%E6%98%AF%E5%8F%AF%E7%94%A8,%E4%BD%86%E6%98%AF%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E6%9B%BF%E6%8D%A2%E5%88%B0%E6%8F%92%E4%BB%B6%E7%9A%84%E9%85%8D%E7%BD%AE%E9%87%8C)

@antred #827

**Comment by YiiGuxing** [comment]
duplicate: #821

**Comment by eric521237** [comment]
> > 还是不行,应该是被墙了吧,[https://translate.google.cn倒是可用,但是不知道怎么替换到插件的配置里](https://translate.google.cn%E5%80%92%E6%98%AF%E5%8F%AF%E7%94%A8,%E4%BD%86%E6%98%AF%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E6%9B%BF%E6%8D%A2%E5%88%B0%E6%8F%92%E4%BB%B6%E7%9A%84%E9%85%8D%E7%BD%AE%E9%87%8C)
> 
> @antred #827 (在2.x版本中需要VPN才能访问，而3.x版本不需要)

    那被墙的可能性就很大喽
