### ISSUE TITLE
之前用都没问题,最近换电脑重安了,不是未知错误就是请求次数过多

### ISSUE THREAD

**Issue by kundong520** [YiiGuxing/TranslationPlugin#836]
![image](https://user-images.githubusercontent.com/59166643/133883865-9d049c41-2b6b-4b94-9d69-2d36c1e131a7.png)

**Comment by boscher** [comment]
такая же фигня последнюю неделю...

**Comment by Rumyash** [comment]
I had the same problem. Setting the 'Use translate.google.com' option helped me (Settings -> Tools -> Translation).

![image](https://user-images.githubusercontent.com/29566240/134131643-aa6a147e-b2ce-4d7d-8b54-a55b22b1c86a.png)

**Comment by YiiGuxing** [comment]
merged: #821 

关于**请求次数过多的问题**：谷歌翻译使用的是公共的版本，有翻译频率的限制，翻译频率过高会被限制使用，被限制使用之后需要过24小时后才能再次使用。有高频率翻译需求的，请考虑使用百度、有道等其他翻译引擎，它们没有这方面的限制。
