### ISSUE TITLE
翻译报错

### ISSUE THREAD

**Issue by fzyjiangfeng** [YiiGuxing/TranslationPlugin#841]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

-选中英文词汇后点击翻译
-报错，翻译不出来，显示 翻译失败：未知错误

### 环境 & 错误日志
- 插件版本: V3.1.1
- IDE版本: IDEA 2021.1.2
- 操作系统版本: Windows 10

>

**Comment by YiiGuxing** [comment]
duplicate: #821
see also: #827
