### ISSUE TITLE
翻译遇到未知错误

### ISSUE THREAD

**Issue by Tiny-saltedfish** [YiiGuxing/TranslationPlugin#846]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by thatCbin** [comment]
Settings -> Tools -> Translation 
使用 translate.google.com

**Comment by YiiGuxing** [comment]
请按照 #827 上的方法处理。
