### ISSUE TITLE
插件报错，无法查询

### ISSUE THREAD

**Issue by YanHuiLi** [YiiGuxing/TranslationPlugin#85]
在android studio 2.3.3版本上
win10 系统

Connection closed at byte 35. Expected 53 bytes。

帮忙看下是什么问题。

**Comment by YanHuiLi** [comment]
无相关服务有效实例，

id 和key都配置了

**Comment by YanHuiLi** [comment]
我挂着xx-net的代理，应该是触发了某个bug，希望能帮我看下，是什么问题。
这个插件体验还是不错的。

**Comment by YiiGuxing** [comment]
应该是网络环境的问题，请换一个环境试试。

**Comment by YanHuiLi** [comment]
我觉得纳闷的很， 我倒是开着xx-net代理的。
andriod studio上只能单个单词画译
ideal上使用倒是没问题。

**Comment by YiiGuxing** [comment]
选词这个是可以设置的。在设置页面设置一下就可以的

**Comment by YanHuiLi** [comment]
@YiiGuxing  能详细一点吗 有点郁闷 一家的产品 一个好用一个不好用郁闷

**Comment by YiiGuxing** [comment]
设置页面有个自动造词方式设置项
