### ISSUE TITLE
9.23之后现实翻译失败，卸载后重装一直没成功。IntelliJ IDEA 2021.1.2,M1版本

### ISSUE THREAD

**Issue by XF-DD** [YiiGuxing/TranslationPlugin#850]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
麻烦提供一下错误信息，谢谢！

**Comment by XF-DD** [comment]
@YiiGuxing 谢谢大佬回复，我吃个饭回来它安装成功了。之前的问题是在插件页面显示安装成功(installed)，但是实际并没有。而且过一会儿去商店搜索又可以重新安装（install）。重启IDEA也没解决

**Comment by XF-DD** [comment]
> 麻烦提供一下错误信息，谢谢！
