### ISSUE TITLE
最近发现个翻译工具比较准确是否可以支持？

### ISSUE THREAD

**Issue by godcong** [YiiGuxing/TranslationPlugin#878]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

看了下好像有免费的api
https://www.deepl.com/zh/docs-api/
试用下来这个工具的翻译结果都比较接近人翻
不知道是否可以支持？

**Comment by YiiGuxing** [comment]
Merged: #472

@godcong 是有免费API，但是它需要高级账号。详细请另阅：#472
