### ISSUE TITLE
不能保存密钥

### ISSUE THREAD

**Issue by Garnerye** [YiiGuxing/TranslationPlugin#887]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
不能正常保存有道密钥,每次关闭IDE后重新打开都要重新配置
### 问题描述
不能正常保存有道密钥,每次关闭IDE后重新打开都要重新配置
![image](https://user-images.githubusercontent.com/52538385/140316440-f12a8a3a-4950-4401-a461-023d57ffc421.png)
 已经按照官网给出的设置设置了,还是不行
![image](https://user-images.githubusercontent.com/52538385/140316571-65299529-6f66-4602-9519-c51fdc0011a9.png)

### 环境 & 错误日志
- 插件版本: 3.1-201
- IDE版本: ![image](https://user-images.githubusercontent.com/52538385/140316787-aaa14b2f-b3e2-4855-bc42-e5528e7fbd92.png)
- 操作系统版本:

**Comment by YiiGuxing** [comment]
请更新插件到最新版本。
