### ISSUE TITLE
汉译英出现ZWSP字符

### ISSUE THREAD

**Issue by KuiYang2017** [YiiGuxing/TranslationPlugin#888]
## 问题详情
汉译英出现ZWSP字符
### 问题描述
当我尝试翻译 速度限制的时候
插件返回的结果是  speed​​limit 当我选定之后  呈现的文本
![image](https://user-images.githubusercontent.com/9023491/142716256-595e8a45-ecdf-42f5-bb84-ae17f9999015.png)

**Comment by YiiGuxing** [comment]
7330d5ae032ca073e5f801e5377eaf8b4a981e00
