### ISSUE TITLE
自动检测语言 希望能保持上次选择的结果

### ISSUE THREAD

**Issue by ggjess** [YiiGuxing/TranslationPlugin#889]
明明是英语,却认为是印度语法语啥的,希望固定被翻译的语言,
中国人的习惯,英语->中文

希望能固定自动检测那里的设置

**Comment by YiiGuxing** [comment]
这是翻译引擎给的结果，插件无法检测当前要翻译的语言。至于固定源语言设置，这是个伪需求。

**Comment by ggjess** [comment]
感谢回复，单是没有固定源语言，遇到好多jdk源码里的单词，不定时会翻译错误，每次都要点击手动修正，我觉得把设置开放给用户比较好，或者紧紧记住上次的修改

**Comment by YiiGuxing** [comment]
这个你可以使用有道的翻译引擎，翻译引擎更符合咱们国人的习惯。
