### ISSUE TITLE
校验签名失败

### ISSUE THREAD

**Issue by AceInAndroid** [YiiGuxing/TranslationPlugin#89]
最近莫名的校验签名失败  , android studio 2.3.3 ~ 我看了 #81 但我没有KeePass 这个选项

**Comment by YiiGuxing** [comment]
请问是什么系统的。可能是输入的key有误，可以用有道的Java demo确认一下签名。

**Comment by AceInAndroid** [comment]
Mac系统的10.12.5   , 好奇怪 上周五还可以~   Java demo在哪下载 我看只有sdk

**Comment by YiiGuxing** [comment]
http://ai.youdao.com/docs/api.s
是不是修改key后无效的？如果是的话，密码设置不要使用“in native Keychain”

**Comment by YiiGuxing** [comment]
密码设置请选择“Save on disk ...”
不行就清除一下密码试一试:
![qq20170814-165308](https://user-images.githubusercontent.com/10737066/29264818-1bf45ac4-8111-11e7-908c-f8a56de53cdd.png)
注意："Reset"以后private key和其他的密码（如git帐号和密码等）会被清除，其他的密码也会被清除。
另："Reset"以后如果你不设置一个新的密码的话，"Master Password"按钮后面的“Enable”会变成“Disable”，这时候就不需要输入密码就可以翻译了。

**Comment by AceInAndroid** [comment]
搞定了 重置密码 然后把有道的api删除了再添加一遍就好了
