### ISSUE TITLE
翻译历史是否能使用另外的文件保存，避免IDE同步配置时增加merge次数和失败概率

### ISSUE THREAD

**Issue by zoemak** [YiiGuxing/TranslationPlugin#891]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情

翻译历史是否能使用另外的文件保存，避免IDE同步配置时增加merge次数和失败概率

### 问题描述

如果使用gitlab或者github同步自己的IDE配置，经常要在两台电脑之间merge插件的配置文件，有时候会merge失败导致插件不可用。
languageScores好像也会经常变化。

![20211126140135](https://user-images.githubusercontent.com/16585243/143534619-1bc19ee5-4dab-4322-b882-3d36eb74ef16.png)

### 环境 & 错误日志

在此粘贴错误日志

**Comment by YiiGuxing** [comment]
不建议如此同步IDE配置，可以使用官方账号同步，或者将插件的配置文件忽略掉。
