### ISSUE TITLE
怎么把翻译后的弹框恢复成之前的样子？

### ISSUE THREAD

**Issue by LuoRuijin** [YiiGuxing/TranslationPlugin#892]
现在翻译的结果是这样显示的
![image](https://user-images.githubusercontent.com/40049700/143803249-63aa1954-e5cd-4baf-8f51-5259e07a4cd4.png)

希望可以设置恢复到之前那样
![image](https://user-images.githubusercontent.com/40049700/143803281-f70a2ce7-bfee-46df-be05-bba3606d2393.png)

**Comment by YiiGuxing** [comment]
操作使用错了，你那个是“翻译与替换”操作，使用“翻译”操作才是你想要的结果。

**Comment by LuoRuijin** [comment]
> 操作使用错了，你那个是“翻译与替换”操作，使用“翻译”操作才是你想要的结果。

哦哦，我傻了，谢谢答复！
