### ISSUE TITLE
使用idea插件翻译显示更新TKK失败,请检查网络连接

### ISSUE THREAD

**Issue by wangruqing723** [YiiGuxing/TranslationPlugin#893]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
请检查网络您的网络环境。

**Comment by wangruqing723** [comment]
> 
我的网络正常, 没任何问题, idea代理也没有开

**Comment by YiiGuxing** [comment]
这是一个网络问题，网络问题与插件无关，网络问题的原因众多，我无法一一帮你排查解决。

**Comment by YiiGuxing** [comment]
常见的网络问题排查我已经在README“常见问题”里说明清楚了的。

**Comment by wangruqing723** [comment]
好的, 谢谢

**Comment by YiiGuxing** [comment]
实现不行的话你就先使用“有道”或“百度”的吧。

**Comment by Xiaojiuc** [comment]
> 
使用有道和百度没有问题，但是下载音频无法下载

**Comment by Xiaojiuc** [comment]
当前遇到的跟楼主相同的问题

**Comment by Xiaojiuc** [comment]
经检查为自定义DNS解析无法解析谷歌的域名

**Comment by wangruqing723** [comment]
我今天又可以用了, 啥也没改😂😂😂
