### ISSUE TITLE
希望加个中文转英文 并替换功能

### ISSUE THREAD

**Issue by lovesL** [YiiGuxing/TranslationPlugin#897]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by YiiGuxing** [comment]
提问题之前请先看看使用说明文档，谢谢！
