### ISSUE TITLE
针对文档翻译的选择

### ISSUE THREAD

**Issue by 346673164** [YiiGuxing/TranslationPlugin#899]
* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
现在只能强制翻译文档或者不翻译文档，之前是可以通过快捷键在文档的pop中进行翻译切换的
### 问题描述
之前旧的版本可以在设置中设置默认是否翻译文档，而且可以在文档弹出的pop中使用快捷键进行翻译文档和原文档的状态切换。
这样对于想对比看中英文的情况下很方便。现在无法使用这个功能了，不确定是属于bug还是功能改进。
![image](https://user-images.githubusercontent.com/15109256/145177674-1419df19-c386-4fe4-b064-1160bc0d85d9.png)

### 环境 & 错误日志
- 插件版本: <-- 3.2.0.1 -->
- IDE版本: <-- IDEA 2021.3 -->
- 操作系统版本: <-- MacOS 10.15.7 -->

**Comment by YiiGuxing** [comment]
由于IDEA2021.3对文档子系统进行了完全地重构，新的文档子系统我目前还没有时间去适配，所以请耐心等待一些时日，谢谢！

另见：#883
