### ISSUE TITLE
Android Studio 每次查询都要输入密码

### ISSUE THREAD

**Issue by woetao** [YiiGuxing/TranslationPlugin#90]
每次查询都要输入密码，设置记住密码都没有用

**Comment by YiiGuxing** [comment]
每次？每打开一次程序应该只需输一次啊。

**Comment by YiiGuxing** [comment]
试一试清除一次密码：
![qq20170814-165308](https://user-images.githubusercontent.com/10737066/29264818-1bf45ac4-8111-11e7-908c-f8a56de53cdd.png)

**Comment by woetao** [comment]
能不能用第二个啊，记住密码，不用每次打开都要输入一次呢。

**Comment by YiiGuxing** [comment]
不行，用第二个项的话，每次启动你都得重新设置private key。reset一次密码，然后不要设置新密码，这样的话就不需要输密码了。
