### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by fengyue-bccsy** [YiiGuxing/TranslationPlugin#916]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
请详细描述问题，确保包括:
  1. Idea上面版本是3.2.1，Android studio上版本是2.9.3，两个界面不一样，能把Android studio上版本更新上来吗，非常感谢！

### 环境 & 错误日志
- 插件版本:3.2.1
- IDE版本: 2021.1
- 操作系统版本: Windows 11

**Comment by YiiGuxing** [comment]
这个是和IDE版本有关的，只有新版本的IDE才能安装版本的插件，因为它们并不都是相互兼容的。现在Android studio 2020.3版本的才能安装新版本的插件。
