### ISSUE TITLE
开放汉字拼音开关

### ISSUE THREAD

**Issue by ExcuseLme** [YiiGuxing/TranslationPlugin#917]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
(看到一个相同的issues, 但那条没有描述清楚问题, 而且没有说明关闭理由, 所以再提一遍做补充)
idea上最好用的翻译插件, 但唯一有瑕疵的是汉字拼音无法关闭, 英语单词却没有音标, 是不是搞反了?

### Proposed Solution
汉字拼音和 英语单词音标都可自选是否开启

### Additional Information
个人认为用这个插件的人更多的是对英语有需求, 更想看到的是英语单词的音标, 而不是汉字拼音, 翻译结果下面一长排拼音真的没什么用, 占空间, 显得臃肿, 翻译长串语句时, 拼音只会显示一排, 后面的就显示不了, 更凸显了这个功能并不重要

**Comment by ExcuseLme** [comment]
补充一下, 上面指的是"选中-右键"里的快捷翻译
![image](https://user-images.githubusercontent.com/43724060/147021780-9de4a288-17c2-45e5-9130-ffe01a531608.png)

**Comment by YiiGuxing** [comment]
这里并不区分英语音标和汉字拼音，这两者都是音标，单独关闭或者开放汉字拼音这样的需求并不合理。

关于英语单词却没有音标的问题，对于谷歌翻译而言，要显示音标，其输入是要满足一些条件的：
1. 必需是一个单词；
2. 单词的所有字母必需都是小写的。
而且并不是所有的单词都会有音标。这些条件都是谷歌翻译的规则，我无法改变。

**Comment by ExcuseLme** [comment]
那能否单独开放一下音标开关, 这个ui很简洁实用, 但音标放在这儿真的很突兀😂

**Comment by ExcuseLme** [comment]
> 这里并不区分英语音标和汉字拼音，这两者都是音标，单独关闭或者开放汉字拼音这样的需求并不合理。
> 
> 关于英语单词没有音标的问题，对于谷歌翻译而言，要显示音标，其输入是要满足一些条件的：
> 
> 1. 必需是一个单词；
> 2. 单词的所有字母必需都是小写的。
> 
> 而且并不是所有的单词都会有音标。这些条件都是谷歌翻译的规则，我无法改变。

那能否单独开放一下音标开关, 这个ui很简洁实用, 但音标放在这儿真的很突兀😂

**Comment by YiiGuxing** [comment]
> > 这里并不区分英语音标和汉字拼音，这两者都是音标，单独关闭或者开放汉字拼音这样的需求并不合理。
> > 关于英语单词没有音标的问题，对于谷歌翻译而言，要显示音标，其输入是要满足一些条件的：
> > 
> > 1. 必需是一个单词；
> > 2. 单词的所有字母必需都是小写的。
> > 
> > 而且并不是所有的单词都会有音标。这些条件都是谷歌翻译的规则，我无法改变。
> 
> 那能否单独开放一下音标开关, 这个ui很简洁实用, 但音标放在这儿真的很突兀😂

个人觉得并不突兀啊，而且这个需求并不很强烈，更重要的是，这个插件并不是只是针对中文和英文的互译的。

**Comment by ExcuseLme** [comment]
> > > 这里并不区分英语音标和汉字拼音，这两者都是音标，单独关闭或者开放汉字拼音这样的需求并不合理。
> > > 关于英语单词没有音标的问题，对于谷歌翻译而言，要显示音标，其输入是要满足一些条件的：
> > > 
> > > 1. 必需是一个单词；
> > > 2. 单词的所有字母必需都是小写的。
> > > 
> > > 而且并不是所有的单词都会有音标。这些条件都是谷歌翻译的规则，我无法改变。
> > 
> > 
> > 那能否单独开放一下音标开关, 这个ui很简洁实用, 但音标放在这儿真的很突兀😂
> 
> 个人觉得并不突兀啊，而且这个需求并不很强烈，更重要的是，这个插件并不是只是针对中文和英文的互译的。

好吧, 这也只是我个人的一点想法😂, 设计如此的话, 也就不强求了

**Comment by maoturing** [comment]
> 这里并不区分英语音标和汉字拼音，这两者都是音标，单独关闭或者开放汉字拼音这样的需求并不合理。
> 
> 关于英语单词没有音标的问题，对于谷歌翻译而言，要显示音标，其输入是要满足一些条件的：
> 
> 1. 必需是一个单词；
> 2. 单词的所有字母必需都是小写的。
> 
> 而且并不是所有的单词都会有音标。这些条件都是谷歌翻译的规则，我无法改变。



这个插件下载量最高，我一直没有使用的原因，就是汉字带拼音太难以接受了。
翻译插件的目标依然必然是用户的母语，无论什么语言都不应该带拼音（音标）啊。

还有就是分词后的英语没必要加粗和斜体啊。
