### ISSUE TITLE
@Override 和其他注解一并被折叠翻译

### ISSUE THREAD

**Issue by luoyangwei** [YiiGuxing/TranslationPlugin#919]
### 问题描述
不希望这里被自动翻译并且折叠，但是在插件的配置里也没有这项开关
![image](https://user-images.githubusercontent.com/31927848/147306513-67566d6b-f288-4b75-9018-56c23be3c298.png)

### 环境 & 错误日志
- 插件版本: 3.2.0.1
- IDE版本:  IntelliJ IDEA 2021.2 (Ultimate Edition)
- 操作系统版本: MacOS Monterey 12.1

**Comment by YiiGuxing** [comment]
。。。。这不是我干的，你别乱说🤣

不过这种翻译并且折叠的功能到是个好点子，我看看有没有应用的场景。。。

**Comment by luoyangwei** [comment]
> 。。。。这不是我干的，你别乱说🤣
> 
> 虽然这种翻译并且折叠的功能到是个好点子，我看看有没有应用的场景。。。

真的嘛？可是我装上插件就会自动翻译。。。。🤣

**Comment by luoyangwei** [comment]
> 。。。。这不是我干的，你别乱说🤣
> 
> 虽然这种翻译并且折叠的功能到是个好点子，我看看有没有应用的场景。。。

真的嘛？可是我装上插件就会自动翻译。。。。🤣

**Comment by YiiGuxing** [comment]
> > 。。。。这不是我干的，你别乱说🤣
> > 虽然这种翻译并且折叠的功能到是个好点子，我看看有没有应用的场景。。。
> 
> 真的嘛？可是我装上插件就会自动翻译。。。。🤣

你应该是安装了中文语言包，应该是它干的。。。

**Comment by luoyangwei** [comment]
> > > 。。。。这不是我干的，你别乱说🤣
> > > 虽然这种翻译并且折叠的功能到是个好点子，我看看有没有应用的场景。。。
> > 
> > 
> > 真的嘛？可是我装上插件就会自动翻译。。。。🤣
> 
> 你应该是安装了中文语言包，应该是它干的。。。

好像真的误会了🤣 8好意思
