### ISSUE TITLE
切换阿里引擎朗读源功能致灰无法使用

### ISSUE THREAD

**Issue by chenzhiwei-github** [YiiGuxing/TranslationPlugin#924]
朗读翻译可以，但是朗读源小喇叭致灰无法点击，还是说不支持朗读源，谷歌一切正常

**Comment by YiiGuxing** [comment]
这是因为你使用源语言你选择了“自动检测”了，阿里翻译的“自动检测”并不提供检测出的语言，没有指定语言的话是无法朗读的，所以如果你要在阿里引擎上朗读源的话需要指定源的语言才行。

**Comment by chenzhiwei-github** [comment]
> 这是你使用源语言时选择了“因为自动检测”了，阿里翻译的“自动检测”没有提供检测出的语言，没有指定语言的话是无法朗读的，所以如果你要在阿里引擎上朗读源话需要指定源的语言才行。



> 这是你使用源语言时选择了“因为自动检测”了，阿里翻译的“自动检测”没有提供检测出的语言，没有指定语言的话是无法朗读的，所以如果你要在阿里引擎上朗读源话需要指定源的语言才行。

非常感谢，解决了我的疑问，但发现指定源语言后，下次翻译没有记录上一次所选择的语言，是需要在哪里设置默认值吗

**Comment by YiiGuxing** [comment]
> > 这是因为你使用源语言时选择了“自动检测”了，阿里翻译的“自动检测”并不提供检测出的语言，没有指定语言的话是无法朗读的，所以如果你要在阿里引擎上朗读源的话需要指定源的语言才行。
> 
> 非常感谢，解决了我的疑问，但发现指定源语言后，下次翻译没有记录上一次所选择的语言，是需要在哪里设置默认值吗

这个并没有做记录，因为想着我们在翻译的时候有选择固定的语言的概率要远小于不固定的。
