### ISSUE TITLE
把符号¥自动翻译$

### ISSUE THREAD

**Issue by ctfang** [YiiGuxing/TranslationPlugin#925]
把符号¥自动翻译$

在phpstorm 这个¥还经常输入错误的

**Comment by YiiGuxing** [comment]
> 把符号¥自动翻译$

这个是翻译引擎的行为，如果您不想 `¥` 被翻译，请将其添加至内容忽略中。见：#470

**Comment by YiiGuxing** [comment]
> 在phpstorm 这个¥还经常输入错误的

不太明白“经常输入错误的”的意思，请提供详细的操作与预期行为和实际行为，谢谢！

**Comment by ctfang** [comment]
我表达错误，应该是需要把：符号¥自动翻译$；
写完中文注释，再写代码就是经常错误写入¥，PHP、Js、shell都有美元符号变量

**Comment by YiiGuxing** [comment]
> 我表达错误，应该是需要把：符号¥自动翻译$； 写完中文注释，再写代码就是经常错误写入¥，PHP、Js、shell都有美元符号变量

同样的，这个符号会不会被翻译，这是翻译引擎的行为，我插件不会做这样的干预。
