### ISSUE TITLE
建议增加翻译次数限制提示

### ISSUE THREAD

**Issue by nganh1** [YiiGuxing/TranslationPlugin#926]
比如阿里每月免费配额100万，在达到次数时增加提醒或自动切换到谷歌等其它翻译API

**Comment by YiiGuxing** [comment]
免费配额这个可不好写死，说不定服务商在什么时候就给改了，就像有道的，之前在一就修改了多次。免费配额用完后它自己有提示的，所以我们没有必要自己计数。后面会翻译失败会有切换翻译引擎的提示的。

**Comment by nganh1** [comment]
请用QQ邮箱发送邮件，下不为例，谢谢合作！
