### ISSUE TITLE
新版本不兼容

### ISSUE THREAD

**Issue by fenghuohuo** [YiiGuxing/TranslationPlugin#927]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description
![image](https://user-images.githubusercontent.com/20682637/148500149-5199e6cd-49ad-4bbe-aa9d-72250ffaaffc.png)

版本信息：
IntelliJ IDEA 2021.3.1 (Ultimate Edition)

能否兼容

**Comment by YiiGuxing** [comment]
2021.3版本的IDE请安装3.2.1-213版本的插件：https://github.com/YiiGuxing/TranslationPlugin/releases/tag/v3.2.1-213
