### ISSUE TITLE
申请的key用不了

### ISSUE THREAD

**Issue by mengzhidaren** [YiiGuxing/TranslationPlugin#93]
在有道申请的KEY，加到工具里 我自已测了半天一直提示 key不正确   能给个错误码 或者  test按键 能看到自已错在哪吗

**Comment by YiiGuxing** [comment]
- 请确认填写的KEY是否正确。申请程序请查看[使用说明](https://github.com/YiiGuxing/TranslationPlugin#使用)，或者看一下有道的文档。
- 可以在ide的日志看到翻译的日志信息：Help -> Show Log in ...

**Comment by mengzhidaren** [comment]
现在可以了   看了下日志 是版本太老升级了一下 就行了  谢谢
