### ISSUE TITLE
翻译与设置界面都是乱码，请问一下是什么原因？

### ISSUE THREAD

**Issue by CoreyInGuangzhou** [YiiGuxing/TranslationPlugin#930]
![image](https://user-images.githubusercontent.com/31690323/148744677-5ff93e2f-d87a-4e44-b8bf-51bc6aaa092d.png)

**Comment by YiiGuxing** [comment]
这里请使用支持中文的字体：

![image](https://user-images.githubusercontent.com/10737066/148744945-345f77b2-7094-49b8-b229-4be0d8a0fe0d.png)

**Comment by CoreyInGuangzhou** [comment]
> 这里请使用支持中文的字体：
> 
> ![image](https://user-images.githubusercontent.com/10737066/148744945-345f77b2-7094-49b8-b229-4be0d8a0fe0d.png)

已解决，感谢！
