### ISSUE TITLE
Incompatible with the current Android Studio version.

### ISSUE THREAD

**Issue by zzzgoda** [YiiGuxing/TranslationPlugin#931]
- 插件版本: 3.2.1(老哥，不是说此版本适用于2020.3至2021.2版本的IDE的吗？)
- IDE版本: 
![5FW3YW`)BGYG9PRNR3Q05)O](https://user-images.githubusercontent.com/64722247/149238820-e520f1e5-49af-4dae-bd44-6b5b43603249.png)
- 操作系统版本: Windows 10 21H1 19043.985

目前正在正常使用的2.9.3

**Comment by YiiGuxing** [comment]
你所用的AS版本还是2019.3的，要AI-203以上的才行。

**Comment by zzzgoda** [comment]
哦哦哦，原来这么看版本的
