### ISSUE TITLE
又报未知错误了，这次是把鼠标放在xml中自定义控件上的时候出来的

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [YiiGuxing/TranslationPlugin#933]
![image](https://user-images.githubusercontent.com/54784104/149262064-863d53a2-80c2-457d-b372-8886b9af4860.png)
[idea.log](https://github.com/YiiGuxing/TranslationPlugin/files/7859768/idea.log)

**Comment by YiiGuxing** [comment]
这和之前你提的问题是同一个问题（#929），已经被修复了，将在下一个版本发布，你可以点击“禁用文档翻译”暂时将文档的自动翻译关闭，就不会有这个提示了 ，需要翻译文档的时候手动翻译。

**Comment by SaltedFish-Extreme** [comment]
> 这和之前你提的问题是同一个问题（#929），已经被修复了，将在下一个版本发布，你可以点击“禁用文档翻译”暂时将文档的自动翻译关闭，就不会有这个提示了 ，需要翻译文档的时候手动翻译。

好的，麻烦了😂

**Comment by SaltedFish-Extreme** [comment]
> 这和之前你提的问题是同一个问题（#929），已经被修复了，将在下一个版本发布，你可以点击“禁用文档翻译”暂时将文档的自动翻译关闭，就不会有这个提示了 ，需要翻译文档的时候手动翻译。

话说老哥，我开了自动翻译，有的弹出来的介绍没有翻译，有的是代码中的方法有的是xml的属性的介绍，还是英文

**Comment by YiiGuxing** [comment]
> > 这和之前你提的问题是同一个问题（#929），已经被修复了，将在下一个版本发布，你可以点击“禁用文档翻译”暂时将文档的自动翻译关闭，就不会有这个提示了 ，需要翻译文档的时候手动翻译。
> 
> 话说老哥，我开了自动翻译，有的弹出来的介绍没有翻译，有的是代码中的方法有的是xml的属性的介绍，还是英文

这是因为AS上的XML文档翻译被Android插件拦截了，所以翻译不了，另见：https://github.com/YiiGuxing/TranslationPlugin/issues/883#issuecomment-1005331227

**Comment by SaltedFish-Extreme** [comment]
> 这是因为AS上的XML文档翻译被Android插件拦截了，所以翻译不了，另见：[#883 (comment)](https://github.com/YiiGuxing/TranslationPlugin/issues/883#issuecomment-1005331227)

好吧😢
