### ISSUE TITLE
快速预览（ctrl+q）中文也翻译了

### ISSUE THREAD

**Issue by Muceball** [YiiGuxing/TranslationPlugin#934]
![image](https://user-images.githubusercontent.com/51481074/149445706-67706aa6-60a2-4b85-a000-13c586345ee0.png)
![image](https://user-images.githubusercontent.com/51481074/149445715-9ea109c7-06d0-4b2c-979c-409c6ac30685.png)
![image](https://user-images.githubusercontent.com/51481074/149445722-2ea0f0bd-cd42-4613-9b78-6912c4ef4214.png)
![image](https://user-images.githubusercontent.com/51481074/149445730-d3392a2c-a5b5-4acd-99e0-ad8207da4034.png)

**Comment by YiiGuxing** [comment]
文档翻译不会检测语言的
