### ISSUE TITLE
老哥，不知道这个算不算bug，有的android包里的xml字符串属性会显示乱码😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [YiiGuxing/TranslationPlugin#936]
![image](https://user-images.githubusercontent.com/54784104/150127678-1799004a-b68c-480e-8c5c-3e1aced263c8.png)

**Comment by YiiGuxing** [comment]
这个不是翻译插件的问题，翻译插件无法对android xml 属性文档进行翻译。再说了，这个根本就不是什么问题，它就是因为你当前IDE所使用的字体无法显示那些字符罢了，你换一个字符全一点的字体就可以正常显示了。

**Comment by SaltedFish-Extreme** [comment]
> 这个不是翻译插件的问题，翻译插件无法对android xml 属性文档进行翻译。再说了，这个根本就不是什么问题，它就是因为你当前IDE所使用的字体无法显示那些字符罢了，你换一个字符全一点的字体就可以正常显示了。

好的，不好意思麻烦老哥了😂
