### ISSUE TITLE
单词语音播放时，前面读音会被跳过

### ISSUE THREAD

**Issue by huangzm0128** [YiiGuxing/TranslationPlugin#937]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

在点击单词小喇叭时，播放的读音会没有前半部分

![image](https://user-images.githubusercontent.com/18364150/150283892-3bc7d4b8-af2f-4746-9030-8fc899aa70d0.png)

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
其实是有的，只不过发音音量较小，时间较短而已。
