### ISSUE TITLE
哥们，问个idea插件开发的问题

### ISSUE THREAD

**Issue by wtjperi2003** [YiiGuxing/TranslationPlugin#94]
http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/language_and_filetype.html
在这个文档里的第2.5步骤 “&lt;fileTypeFactory implementation="com.simpleplugin.SimpleFileTypeFactory"/&gt;”，这个fileTypeFactory标签要填在哪里啊?死活找不到说明，望赐教

**Comment by YiiGuxing** [comment]
`fileTypeFactory`这个标签是放在`extensions`标签里的。例如：
```xml
<extensions defaultExtensionNs="com.intellij">
    <fileTypeFactory implementation="com.simpleplugin.SimpleFileTypeFactory"/>
</extensions>
```
具体请看[插件结构](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure.html)部分，详细的在[插件配置文件 - plugin.xml](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html)部分。
你可以使用IDEA来编辑，在Plugin类型的工程下，编辑plugin.xml是有标签自动完成提示的。
