### ISSUE TITLE
是否支持多选替换

### ISSUE THREAD

**Issue by SealinRepo** [YiiGuxing/TranslationPlugin#943]
大佬们好, 请问目前版本是否支持多选后翻译替换的场景, 我试过在分隔符添加空格, 换行好像也只能翻译选中的最后一个单词, 就像这样选中.
![image](https://user-images.githubusercontent.com/14067275/150926963-3a0bdbd6-05e7-4c71-8a16-31b835fb27bc.png)

**Comment by YiiGuxing** [comment]
并不支持哦
