### ISSUE TITLE
阿里翻译填写appkey和screct没有自动记住，重启idea后仍然提示输入

### ISSUE THREAD

**Issue by happut** [YiiGuxing/TranslationPlugin#949]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
改为阿里翻译后，重启idea时，appkey会自动记录，但是secret没有自动记住，需要从阿里网站中再次复制

### 环境 & 错误日志
- 插件版本: 3.2.2-213
- IDE版本: IDEA 2021.3.1
- 操作系统版本: macos12

**Comment by YiiGuxing** [comment]
请按照FAQ中的第3条处理后再尝试

**Comment by happut** [comment]
改成in native Keychain好用了，谢谢！！
