### ISSUE TITLE
IntelliJ IDEA 2021.3.1 (Ultimate Edition) mac m1版本无法安装插件

### ISSUE THREAD

**Issue by chuyaohua** [YiiGuxing/TranslationPlugin#951]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
在新款macbook pro上，使用的idea版本如标题，无法安装成功安装该插件。

### 问题描述
搜索translation--->install安装
  2. 发生了什么
  进度条显示安装完成后，在已安装的插件里面，搜索translation，无法找到。回到插件市场，搜索，此时仍然显示install。安装未成功。尝试使用手动安装方式，仍然失败。
  3. 您认为正确的行为应该是什么。
  成功安装使用。
  4. 如果可以，请添加屏幕截图以帮助解释您的问题。
  
![image](https://user-images.githubusercontent.com/57615098/151483963-92782a11-cb08-42ff-8127-d9172e98270d.png)
![image](https://user-images.githubusercontent.com/57615098/151484121-2be10734-15f0-4703-82b5-5f15fbe61ea0.png)
再次打开
又显示没有安装了
-->

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
安装完成之后，先不要重启IDE，点击apply，然后看看有没有提示要重启，没有的话就多等一几分钟再重启IDE。

**Comment by chuyaohua** [comment]
> 安装完成之后，先不要重启IDE，点击apply，然后看看有没有提示要重启，没有的话就多等一几分钟再重启IDE。
可以了。谢谢
