### ISSUE TITLE
翻译文档异常

### ISSUE THREAD

**Issue by zhaochongmink** [YiiGuxing/TranslationPlugin#961]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by zhaochongmink** [comment]
信息已经补充了，麻烦看一哈

**Comment by YiiGuxing** [comment]
请升级插件到最新版本。
