### ISSUE TITLE
请增加必应翻译，谷歌翻译，因为众所周知的原因，经常卡住，太难受了，请增加任意不需要id的翻译源

### ISSUE THREAD

**Issue by BraveHL** [YiiGuxing/TranslationPlugin#964]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
请增加必应翻译，谷歌翻译，因为众所周知的原因，经常卡住，太难受了，请增加任意不需要id的翻译源
### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
随意添加未受权的翻译源可能会面临未知的法律风险，所以我不能乱加的。。。。

**Comment by YiiGuxing** [comment]
使用百度、有道、阿里这些的，虽然申请ID的时候可能要麻烦一点，但是它是安全的。。。

**Comment by YiiGuxing** [comment]
我和必应，DeepL的联系申请过它们的免费公共API的使用权，人家不答应我。。。。
