### ISSUE TITLE
添加腾讯翻译君

### ISSUE THREAD

**Issue by xiaochen0517** [YiiGuxing/TranslationPlugin#970]
### Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. 

### Problem Description

能否添加腾讯翻译君的翻译，个人感觉这个翻译的效果要比其他的好点。

**Comment by YiiGuxing** [comment]
请关注 #768

**Comment by xiaochen0517** [comment]
好的
