### ISSUE TITLE
为什么查询单词的时候,很多时候音标出不来

### ISSUE THREAD

**Issue by 2629743986** [YiiGuxing/TranslationPlugin#98]
IDEA:2017.2.5  插件下载是目前最新的这个版本

**Comment by YiiGuxing** [comment]
这可以是有道API返回的本身就是没有音标，请问你查的是那些单词没有音标？我确认一下问题，我这里很少遇到这样的情况。

**Comment by 2629743986** [comment]
嗯,我不知道是不是我配置错了,但是我就是把插件下载下来,然后重启,然后重启.查单词的时候,可以显示应标,但是像.[这种样子](http://blog.csdn.net/qq_34272046/article/details/78143738)

**Comment by YiiGuxing** [comment]
原来是乱码。。。可以看这个： #50

**Comment by 2629743986** [comment]
谢谢哈
