### ISSUE TITLE
IDEA 2021.3.2  只有翻译，没有翻译替换的功能，快捷键  Ctrl + Shift + X 也没用

### ISSUE THREAD

**Issue by zhouxiaofu** [YiiGuxing/TranslationPlugin#981]
Windows10 
IDEA 2021.3.2 
只有翻译，没有翻译替换的功能，快捷键  Ctrl + Shift + X 也没用

![image](https://user-images.githubusercontent.com/34471928/158317599-cdbb6096-be39-469c-9bec-82ea3c67ac5d.png)

**Comment by YiiGuxing** [comment]
右键菜单上的需要要开启才有：
![image](https://user-images.githubusercontent.com/10737066/158317918-5743bb71-8db0-4296-880b-2cbbe1b711ee.png)

快捷键不能用很有可能是快捷键冲突了，你先试试开启右键菜单选项看看。
